### ISSUE TITLE
Page reloaded on popup after signin (not closing)

### ISSUE THREAD

**Issue by abegines** [AzureAD/microsoft-authentication-library-for-js#1005]
I've reproduced/workaround the problem by simply changing the execution scope of `new Msal.UserAgentApplication`...

In the code above, if the line `init()` is executed on page load (i think in the window scope) all works fine (show login popup, and back to app windows). But if I comment this line and execute `init()` inside of click event of a button, then it fails (show login popup, and reload app in popup window).

Tested in Chrome and Safari.

```html
<!DOCTYPE html>
<html>
  <head>
    <title>LOGIN MICROSOFT TEST</title>
    <meta charset='utf-8' />
    <script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.1.2/js/msal.js"></script>
    <script type="text/javascript">

      let __msalInstance = undefined;
      const __msalConfig = {
        auth: { clientId: "f7d9d4ca-f66c-42b9-9181-xxxxx" }
      };

      const __loginRequest = {
        scopes: ["user.read"] ,
        prompt: 'select_account',
      }

      init(); // << this makes it work!

      function init()
      {
        __msalInstance = new Msal.UserAgentApplication(__msalConfig);
        console.log(__msalInstance);
      }

      function login()
      {
        __msalInstance.loginPopup(__loginRequest).then(logged);
      }

      function logged(loginResponse)  {
        console.log('onLoged=', loginResponse)
      }
    </script>

  </head>

  <body>
    <button onclick="init();">INIT</button><br>
    <button onclick="login();">LOGIN</button><br>
  </body>
</html>
```

_Originally posted by @abegines in https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/152#issuecomment-533834503_

**Comment by sameerag** [comment]
@abegines #939 should prevent this from happening. @jasonnutter Can you also confirm this?

**Comment by jasonnutter** [comment]
@abegines The reason why the popup will not close is because the current version of `msal` relies on `msal` running in the popup to communicate with the parent page to pass the result of the login action, and if your code waits until a user clicks a button to instantiate `UserAgentApplication`, that will never occur, which results in the behavior you are seeing. #939 I believe should fix this, but regardless, I would not recommend waiting until a button is clicked to instantiate `UserAgentApplication`, as that could result in unexpected behavior like this scenario. It may also prevent you writing business logic in your application to control your app's behavior based on whether or not the user is logged in, etc.

**Comment by abegines** [comment]
@jasonnutter our application is open to many users who can log in with Microsoft, Google, twitter, username / password, etc. and we want to create instances only of the objects necessary for the authentication desired by the user. That is why he tried to create, as far as possible, the necessary objects when necessary. Knowing the current MSAL limitation, we will do it at the time it works.

I'll try the #939 PR soon. Thanks.
