### ISSUE TITLE
Add AADSTS50199 to list of expected errors

### ISSUE THREAD

**Issue by jasonnutter** [AzureAD/microsoft-authentication-library-for-js#1007]
STS will return `AADSTS50199` when an application is using a non-https redirect uri, such as `chrome-extension://`. This error is not documented, which causes confusion for developers when it is return unexpectedly.

AC:
1. `AADSTS50199` errors are documented on docs.microsoft.com under the list of known errors: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-handling-exceptions

Related: #941

**Comment by jasonnutter** [comment]
@hpsin Where is the place to document this error? Is this something your team can take care of? Thanks!

**Comment by hpsin** [comment]
This is an interaction required error, which should be handled as an interaction required error and not special cased.  It is triggered because a client used a system webview to request a code for a native application.  This is a known attack vector, so the identity platform requires the user to "check my sign in" (CMSI) and validate that this is the app that needs to be requested. 

No app that uses a system webview should be silently requesting a code.

**Comment by jasonnutter** [comment]
@hpsin Thanks! Closing.
