### ISSUE TITLE
AuthError: Unexpected error in authentication.: Hash does not contain state. 

### ISSUE THREAD

**Issue by tangudu1808** [AzureAD/microsoft-authentication-library-for-js#1052]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X ] Chrome version XX
- [ ] Firefox version XX
- [X ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version 
Version 1.1.1
<pre><code>
Library version: 1.1.1

</code></pre>

## Current behavior

We have created separate policy for invitation (which is same as Sign up) functionality. But if user is trying to sign up using invitation its throwing the error saying "AuthError: Unexpected error in authentication.: Hash does not contain state. " . But if user is trying to use Sign up its working as expected. I saw both the URL's after authentication , State parameter was not there if user comes thru invitation in the URL. Please help us to fix this issue. Same functionality is working in v0.2.4 but this version is not working for IE. Hence we migrated to v1.1.1 to resolve IE issue then this functionality broken. Please help us asap.

**Comment by jasonnutter** [comment]
@tangudu1808 Apologies for the delay, this slipped through the cracks.

Our understanding is that this is happening when the URL is too long, and IE truncates query parameters, which ends up removing the `state` parameter, as it is added at the end of the url. This often happens when the library tries to retrieve an ID token and an access token in the same call.

To mitigate this, you should ensure that you have acquired an ID token (e.g. by calling `loginPopup` or `loginRedirect`, or `acquireTokenSilent` with your `clientId` as the only scope) and then acquire an access token.

We're adding mitigations in the library for this scenario. In the mean time, please try this and let us know if it addresses your issue.

**Comment by sameerag** [comment]
@tangudu1808 Closing this issue as the above stated mitigation is what we are generally advising for IE users. Please watch our space for #1172 to be merged; until then this is the only recommendation we can make.

Closing this issue.
