### ISSUE TITLE
Optimize /openid-endpoint call for token requests

### ISSUE THREAD

**Issue by sameerag** [AzureAD/microsoft-authentication-library-for-js#1123]
### Address customer feedback on optimizing token request turnaround times:

/openid-configuration endpoint: Per guidance from the AAD/STS server team, we will continue making this network call everytime a network call for a token is needed (and rely on cache headers to have the browser cache this call accordingly).

### **Use cases:** 

1. **SSO with another client library:** Ask from SPO to improve their performance. For SSO cases similar to them can we  provide an option for them to skip this and have them pass `msal js` the needed info (authority and logout URL etc.,) 

2. **Standalone `msal js`**:

**Customer feedback:**

- This adds somewhere between 70ms and 200ms to the token fetch time based on some profiles I just made. This is especially important when users to return to our app for the first time in a while and the 24 hour TTL on this file has expired. It ends up adding a significant delay to our first (and most important) token fetch. I'll leave the specifics up to the area experts, but here are some thoughts from an outside observer:

    - Is this file coming from a CDN? The network times are quite slow.
    - Can we have a longer TTL on this file? 
    - If you fetch multiple tokens at the same time, each fires an openid-configuration call rather than sharing the first call. Can we make them share the same request?
    - Can we make this request early in the MSAL instantiation flow rather than waiting for the first token fetch?

- Caching openid-configuration in local storage: it has to do with the fact that it is already cacheable for 24 hours. Caching it in local storage is useful because it removes asynchronicity and this is key to make things execute faster in high CPU contention scenario. Basically the ultimate goal is to get to /authorize call as quickly as possible in synchronous manner. Usual approach for something like is still to make network call but make it non-blocking and use only to update local cache so new value is used for next token fetch. Maybe I am over-simplifying things but it seems to me that there is an opportunity here for optimization.

**Comment by jasonnutter** [comment]
Before we think about shipping our own caching mechanism for this call, we should do some in depth performance tests to compare local storage versus built-in browser caching. I'm not convinced yet that it will be worth the work, given it may only meaningfully benefit a relatively small percentage of users. I would hypothesize that the better approach would make it so we don't make that call at all, then to reinvent the wheel for how its cached.

**Comment by AndreiZe** [comment]
Note that currently config response is being cached for limited amount of time so depending on how frequently app is being used you might end up taking a hit more often than you think. Even when response being cached by browser you end up taking a hit due to the fact that XHR is being used to fetch config and that results in queueing separate task to handle response which can result in significant delays in case of CPU contention which is common during app boot sequence.

The frustrating thing is that the config response is usually exactly the same. For instance in our case we use default authority (https://login.microsoftonline.com/common) and config request (https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration) always returns the following three pieces of info:
"issuer": https://login.microsoftonline.com/{tenantid}/v2.0
"authorization_endpoint": https://login.microsoftonline.com/common/oauth2/v2.0/authorize
"end_session_endpoint": https://login.microsoftonline.com/common/oauth2/v2.0/logout

This info **may** change but in practice it does not happen too often hence the suggestion to cache it locally. Local cache is almost guaranteed to be faster than hitting browser cache but most importantly it is synchronous which allows token fetching code to hit /authorize endpoint as quickly as possible. 

I realize that library has to worry about many scenarios and understand the reluctance to support elaborate caching mechanism. 

When do you expect to provide support for the case when client app is responsible for supplying authority configuration? At the very least this would open an opportunity for apps that really care about optimizing this flow to do their own caching implementation.

**Comment by sameerag** [comment]
@AndreiZe Thanks for the feedback. Since we released `msal@1.2.0` today, this is the next task we are focused on. I would like to get a nod from the service team before finalizing our approach. 

CC @hpsin. (I also added you in an email)

**Comment by keystroke** [comment]
@sameerag please consider that openid configuration objects must be fetched / cached for each distinct authority URI. Also, please consider exposing these resulting openid configuration objects to end-user code in some way, as I didn't see a way to get at it from my code, and my application has to redundantly fetch the same openid configuration object.

Perhaps you could imagine some approach where the application can pass an object (dictionary) of openid configuration objects to the MSAL constructor. That way, target applications can opt-in when necessary to cache openid configuration objects as necessary, and when omitted, you get the default behavior. I would request that MSAL then expose these openid configuration objects in some kind of method like msal.getOpenIdConfigurations() which returns an object (dictionary) of tenantId -> config, and perhaps the method can accept a specific tenantId input and only return that openid configuration object if it exists.

Let me know your thoughts.

**Comment by tnorling** [comment]
#1578 will allow you to provide your configuration object to skip this call. This will be included in the next release.
