### ISSUE TITLE
MSAL for Angular 0.1.4 is not recognizing SSO

### ISSUE THREAD

**Issue by pasanenl** [AzureAD/microsoft-authentication-library-for-js#1152]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x ] Chrome Version 78.0.3904.108 (Official Build) (64-bit)
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: MSAL for Angular 0.1.4

</code></pre>

## Current behavior

Our application (app1) using MSAL for Angular doesn’t recognize the SSO from our other application (app2 non MSAL) when it should.  Our app2 application sign in has set the x-ms-cpim-sso cookie but the SSO is not successful. Our B2C configuration is correct. So from app2 (non MSAL) to app1(MSAL) SSO does not work. But from app1(MSAL) to app2(non MSAL) the SSO is recognized.

I tried setting the login_hint. Put this didn’t work and it is unclear in the documentation on how to do this on the MSAL for Angular API's. It should detect the SSO and authorize the signed in user.

## Expected behavior

The request should not have the prompt=select_account and MSAL is setting this. It should detect the SSO and authorize the signed in user.

**Comment by jasonnutter** [comment]
@pasanenl This is a known shortcoming of MSAL Angular, but will be addressed soon, as we are currently working to upgrade MSAL Angular to use MSAL 1.x, where this works as expected. I'll post an update here when there is a version you can try.

We'll also make sure to make it more clear in the documentation how to do this.

**Comment by Atlas361** [comment]
Normally, you would add the **extraQueryParameters = prompt=auto** to avoid the user being prompted to choose their user account but the MSAL Angular library is always setting this parameter to **prompt=select_account** in the login URL. This issue has been annoying to our users because they always have to click their user account to get into the app even though they’re already logged into the Microsoft cloud, thus it’s not a true Single Sign-On (SSO) experience. 

Can you please let us know if this fix has been added to the next release and if so when can we expect that release?

**Comment by jasonnutter** [comment]
This should now be possible with the pre-release version of MSAL Angular. First, install the new version:

`npm install msal@beta @azure/msal-angular@alpha`

Complete changes can be found here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev-angular-1.0/lib/msal-angular/changelog.md#100-alpha1

Then call `msalService.acquireTokenSilent` with your clientId as the only scope, along with `loginHint`:

```js
msalService.acquireTokenSilent({ 
  scopes: [ "your_client_id" ],
  loginHint: "name@email.com"
})
```

This will attempt to SSO to the existing AAD session. If there is an existing, the promise will resolve successfully. If not, it will throw, and you will need call one of the interactive methods.

**Comment by csinfo-cps** [comment]
I am also experiencing this problem.  I am surprised that there is a parameter for this that completely ignores what the developer is sending.  If I wanted a pop-up I would set that param value.  If I need SSO, I should be able to put in AUTO.  Please fix asap.

**Comment by pasanenl** [comment]
I've tried the latest alpha.1 version because we need SSO working and got the error below from acquireTokenSilent(). Is this a bug? Is there a way around this timeout error?:
 
msal client logging: Mon, 20 Jan 2020 20:07:44 GMT:1234-1.2.0-Verbose Loading frame has timed out after: 30 seconds for scope xxxx
app.component.ts:181 acquire token failure {"errorCode":"token_renewal_error","errorMessage":"URL navigated to is https://xxxx/xxxx/oauth2/v2.0/authorize?response_type=id_token&scope=openid...
app.module.ts:79 msal client logging: Mon, 20 Jan 2020 20:07:44 GMT:1234-1.2.0-Error Error when acquiring token for scopes: xxxx ClientAuthError: URL navigated to is https://xxxx/oauth2/v2.0/authorize?response_type=id_token&scope=openid..., Token renewal operation failed due to timeout.

**Comment by Atlas361** [comment]
Thank you **[jasonnutter](https://github.com/jasonnutter)** for the quick reply, I appreciate it! However, I don't understand how using the 1.0.0-alpha.1 along with your suggestion below will solve my problem:   

**Then call msalService.acquireTokenSilent with your clientId as the only scope, along with loginHint:**

**msalService.acquireTokenSilent({** 
  **scopes: [ "your_client_id" ],**
  **loginHint: "name@email.com"**
**})**

In my previous post I stated that the MSAL Angular's library 0.1.4 doesn't allow me to set the **extraQueryParameters** to **prompt=auto** to avoid prompting the user to select their account. I cannot call **msalService.acquireTokenSilent( )** with the **loginHint: "name@email.com"** parameter because my Angular app doesn't know the User's Email until after their initial login to the Angular app. Meaning that even if my user's identity is already known because they're logged into the Microsoft Cloud (such as https://account.activedirectory.windowsazure.com/r#/applications) that they will still be prompted to select their user account which of course is what Single Sign-On (SSO) is suppose to eliminate. 

Also, the referenced documentation at https://www.npmjs.com/package/@azure/msal-angular/v/1.0.0-alpha.1#msal-angular-public-api specifically states that I should not call the acquireTokenSilent( ) function but instead only use the API's exposed by the MSAL Angular Wrapper.

**The documentation states:**
"Note: Since MSAL Angular wrapper is inheriting from UserAgentApplication of msal-core, all the public APIs of msal-core are still accessible from msal-angular. But it is recommended not to use any of the msal-core APIs like acquireTokenSilent(), acquireTokenPopup(), acquireTokenRedirect() etc from Angular application and use only the APIs which are exposed directly from the msal-angular wrapper itself."

**Comment by jasonnutter** [comment]
@Atlas361 `loginHint` (or `sid` (session id))  is required in order to properly disambiguate in case the user has multiple AAD sessions in their browser (e.g. a work account and personal account).

That documentation is somewhat dated, so we'll make sure it gets updated, as the guidance provided isn't really accurate, especially for advanced scenarios.
