### ISSUE TITLE
WindowUtils.isInPopup() returns wrong result which leads to the bug that the callback is not handled

### ISSUE THREAD

**Issue by Nasicus** [AzureAD/microsoft-authentication-library-for-js#1207]
## Library
 `msal@1.2.0`

## Problem

I found out that sometimes the callback from `loginRedirect` or  `acquireTokenRedirect` is not handled.

After I while I found out that the problem is this code block:
```
        if (!this.config.framework.isAngular && urlContainsHash && !WindowUtils.isInIframe() && !WindowUtils.isInPopup()) {
            this.handleAuthenticationResponse(urlHash);
        }
```

It turned out that `WindowUtils.isInPopup()` returns `true` even though my browser window is not a popup.
Actually I accessed my app via a link I received in an email client (gmx.net), see.
Apparently the code you use for detecting a popup...
```
    static isInPopup(): boolean {
        return !!(window.opener && window.opener !== window);
    }
```
....  is not always accurate, see:
https://stackoverflow.com/questions/10240398/check-whether-a-window-is-popup-or-not#comment96666402_30873964

It took me quite a while to figure out what the problem is. Would be nice if you would also add some (verbose) log message at this point in the code (i.e. why it will not handle the popup or something like that).

Maybe there is another (better) way to do this detection - or maybe you know of a workaround for me.
Btw: I'm using only the `acquireTokenRedirect` and `loginRedirect` methods, I don't care about the popups at all. Maybe one solution would be to simply set the ` window.opener` to `null` in my case?

**Comment by sameerag** [comment]
@Nasicus Thanks for bringing this to our notice. Will check what we can do, appreciate the feedback.

**Comment by Nasicus** [comment]
@sameerag this just seems to have gotten much worse (or maybed it also was).
Now this happens for every link which is pointing to our application an doesn't include the `rel="noopener"` attribute ,e.g. `<a href="http://our-app" target="_blank">Go to our app</a>`.

So if anyone now access our app via this link, you will not be able to login (you will be able to go through the login flow, but the callback will not be handled).

I'm surprised I'm the only one who reported this so far.

For me this has quite a high priority now.

As a workaround I will try to set `window.opener` to `null` in our app.

**Comment by sameerag** [comment]
@Nasicus I will try to prioritize this next week/ or have someone from my team follow up.

**Comment by Nasicus** [comment]
Thanks.

For people who have the same problem:

Setting `window.opener = null;` right before creating the `UserAgentApplications` works for me as a workaround.
=> In my site I never care about the opener anyway, so for now this seems to be an okay fix.

**Comment by wvanderdeijl** [comment]
We are also running into this issue after upgrading MSAL from v1.1.3 to v1.2.0.
This change in behaviour seems to have been introduced in ff2b0e3164278004c9f3d2a36a1f49484ddaabc1

As stated above, this can break the login flow whenever a link is used to access the application. To make things worse, our users use the application links from https://myapps.microsoft.com to access the application and those no longer work.
Here is what I see in my logging:
- user clicks link at myapps.microsoft.com to access our application
- our SPA detects there is no valid session and uses `msal.loginRedirect`
- azure AD detects there is already a valid session and immediately redirects the user back to our app with an idtoken in the url fragment
- our SPA uses msal again and UserAgentApplication ignores the idtoken in the url since it sees window.opener not being null. 
- this means our callback that is registered with `msal.handleRedirectCallback` is not invoked and our application again tries to trigger the login flow. This throws:
```json
{
    "errorCode": "login_progress_error",
    "message": "Login_In_Progress: Error during login call - login is already in progress.",
    "errorMessage": "Login_In_Progress: Error during login call - login is already in progress."
}
```

We have also hacked `window.opener = null` into our bootstrapping code since we know we are not using popups for MSAL login flow.

It's rather ironic that these changes have broken the login flow from https://myapps.microsoft.com

**Comment by wvanderdeijl** [comment]
This is probably related to #1095 and #1198

**Comment by s2ramana** [comment]
I am also having this issue and our work-around was to set window.opener to null. We still see intermittent failures where the redirect is not processed.

**Comment by tnorling** [comment]
@Nasicus This should be fixed in ```msal@1.3.0-beta.1``` Could you try it out and let us know if this can be closed? Thanks

**Comment by Nasicus** [comment]
Looks like it's fixed 👍

**Comment by sameerag** [comment]
Great! Thanks, closing the issue.
