### ISSUE TITLE
Remove static query parameters

### ISSUE THREAD

**Issue by schurlinga** [AzureAD/microsoft-authentication-library-for-js#130]
It is not possible to change the query parameter "prompt" to for example "prompt=none".

I think the static query parameters in loginRedirect and loginPopup should be removed or at least the extraQueryParameters parameter should overwrite the "prompt" and "response_mode" parameters if defined.

**Comment by rohitnarula7176** [comment]
@schurlinga "prompt=none" is used to silently authenticate the user when he is already logged in via SSO. Allowing prompt=none for loginRedirect and loginPopup would prevent the UI to be shown to the user for entering credentials and would assume that the user is already logged in via SSO. We have this behavior in the library by design.

**Comment by schurlinga** [comment]
Yeah, thx for the response. Actually i was using the library wrong, i didn't check if the user is already logged in by using UserAgentApplication.getUser().
