### ISSUE TITLE
Background token renewal

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#1303]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [X] `msal@1.2.1` or `@azure/msal@1.2.1`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Currently there is no background token renewal, the client code has to call acquireTokenSilent whenever it needs tokens and if the cached token has expired, MSAL will refresh it

However, this creates an experience where if a user is inactive long enough for the cached token to expire, and then starts using the app, making api calls, the first call is blocked until the token renewal happens.

This token renewal could have been done in the background without the user knowing

Is there a reason why this library does not do this? We are thinking of rolling our own background token renewal using setInterval and checking the token expiry time but it would be great if this feature was built in

Thanks!

**Comment by jasonnutter** [comment]
@thoo1 The library does not work this way in part because of the load that would put on Microsoft's services if every application was silently renewing tokens on some sort of schedule (as you describe). Furthermore, silent requests/renewals are not guaranteed to succeed, and so it could create a poor UX in your application if not handled correctly.

Please also note that if the same user makes too many requests in a short period of time, our services will return [Invalid Grant errors (`AADSTS50196`)](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-breaking-changes#march-2019). While the threshold for this is pretty high, automatically renewing tokens increases the likelihood of this happening, especially for apps that need a non-trivial number of access tokens.

All that said, we have no plans to include this in the library, and do not recommend client applications implement this logic themselves.

**Comment by jasonnutter** [comment]
Closing, as no further action at this time. Feel free to let us know if you have further questions.
