### ISSUE TITLE
Authentication issue when URL is opened from window.open in Edge Chromium

### ISSUE THREAD

**Issue by riteshbhoi** [AzureAD/microsoft-authentication-library-for-js#1391]
We have a scenario where in we use window.open to redirect user from another website to our website. But we run into login issue while doing so in Edge Chromium and Edge Chromium In Private. I am using Edge Chromium Version 80.0.361.66 (Official build) (64-bit) and MSAL package version 1.2.0. Same code works perfects fine in Chrome and Chrome In Private. 

sample code -
window.open("https://ourWebUrl");

![image](https://user-images.githubusercontent.com/27738317/76909517-a60d5300-6868-11ea-97a2-3085e5038fdb.png)

**Comment by enniob** [comment]
I'm having a similar issue. If the user is logged out from the site and they click on a link from another site to my site the authentication never happens. When I look at the Session Storage I can see that the `msal.interaction_status` shows inProgress. I also noticed that all the session variables are duplicate.

This only happens if the user is not logged in to our site and if the hyperlink to my site has the target="_blank".

I'm using the MSAL package version 1.2.0 too and using Angular 8. We developed our own auth service for Angular 8 so I thought the issue was there. But I removed all of our custom code and installed angular MSAL beta and I still get the same issue. 

I followed the instructions here (https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev-angular-1.0-protectedresources/lib/msal-angular/docs/0.x-1.x-upgrade-guide.md).

I also noticed that when the URL to the site has the `target="_blank"` it adds the login.request in the session and I have the option to `navigateToLoginRequestUrl: false` so that should be there right?

**Comment by jasonnutter** [comment]
@enniob It is a known issue that sites opened in a new tab/window have problems acquiring tokens, and we are working on a fix. 

@riteshbhoi Do you have a Fiddler trace you can share that demonstrates the issue you are seeing?

**Comment by enniob** [comment]
@jasonnutter thanks for the reply.

**Comment by riteshbhoi** [comment]
@jasonnutter it is just an issue with Edge and Edge Chromium, as this works fine in Chrome and Chrome In Private

**Comment by jasonnutter** [comment]
@riteshbhoi Can you share a Fiddler trace? Email in my profile, thanks!

**Comment by riteshbhoi** [comment]
As per discussion with @jasonnutter this appears to be a known issues with loginRedirect when an app is opened in a new tab. Here is a link to the issue https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1301

**Comment by jasonnutter** [comment]
Closing as a duplicate, as we have a few issues about this open already.
