### ISSUE TITLE
Auto logout after period of inactivity

### ISSUE THREAD

**Issue by kchlapinski** [AzureAD/microsoft-authentication-library-for-js#1407]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I would like to add in my app auto logout after period of inactivity.

Calling function authService.logout() (authService: MsalService) showing a dialog 'Pick an account - Which account do you want to sign out of?'. 

How to skip it, enforce logout?
How to logout a user without any interaction, from code?

**Comment by derisen** [comment]
Hmm, you could simply wipe clean your storage/session/cookies using an idle timeout function, but without an interaction, Azure AD won't know that your user is signed out, which means they might be able to re-authenticate automatically (since they'll still have a valid session/cookie for AAD).

Perhaps you should take a look at [conditional access](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-session-lifetime). You can configure how long they could stay signed-in with that.

**Comment by mvrak** [comment]
@kchlapinski can you describe your scenario more?  What kind of users are we talking about?
If they user could theoretically get single sign on from another app, then would we be signing them out of those apps as well?  

We have a number of scenarios where "logout" isn't that intuitive.  Therefore we highly recommend using conditional access to manage this.

**Comment by tnorling** [comment]
Closing as this has been answered.
