### ISSUE TITLE
MsalInterceptor drops request when "login_required" error is thrown, even after doing a login via popup

### ISSUE THREAD

**Issue by tschmidt01** [AzureAD/microsoft-authentication-library-for-js#1420]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [X] `@azure/msal-angular@1.0.0-beta.4`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
My requirement:
1. User opens application in two tabs
2. User signs out in one tab
3. User switches back to the other tab
4. User interacts with the application causing an API call
5. Popup opens, user signs in again

Result: The API request, which triggered the retrievement of the token and thus the "login_required" error gets dropped

Expected: The request gets executed as soon as the user logged back in

Configuration:
```
{
  provide: HTTP_INTERCEPTORS,
  useClass: MsalInterceptor,
  multi: true
},
```

```
this.broadcastService.subscribe("msal:acquireTokenFailure", (payload: AuthError) => {
  this.msalService.loginPopup({scopes: [environment.api.scope]});
});
```
Is this an expected behaviour?

**Comment by jasonnutter** [comment]
@tschmidt01 Apologies for the delay. Yes, this does look like expected behavior. I am looking into providing built in error handling (to invoke interactive methods) for the Interceptor to help with situations like this. 

For now, you could add error handling at the place where you make the API request, and then when interaction in completed, make the API request again. I realize this isn't optimal, but should be a workaround for now.

**Comment by jasonnutter** [comment]
This is now available in MSAL Angular v2: https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/msal-angular-v2.0.0-alpha.0

Closing.
