### ISSUE TITLE
Uncaught AuthError: Unexpected error in authentication.: Hash does not contain state.

### ISSUE THREAD

**Issue by chris-gunawardena** [AzureAD/microsoft-authentication-library-for-js#1484]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.2.2` 
**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
If you are using a framework, please provide the framework and version (React v16 but auth code is vanilla js).

## Description
After resetting the password and redirecting back to application, get a blank page wit the following in the console: 

AuthError.ts:26 Uncaught AuthError: Unexpected error in authentication.: Hash does not contain state.

## Security
Is this issue security related? No

## Regression
Did this behavior work before? Not sure

## Configuration
Please provide your MSAL configuration options.

```js
const myMSALObj = new Msal.UserAgentApplication({
  auth: {
    clientId: "a2306b5f-e6b8-421e-8e0d-8be6e8761f5b",
    authority:
      "https://skyfintest.b2clogin.com/skyfintest.onmicrosoft.com/B2C_1_signup",
    redirectUri: window.location.origin,
    validateAuthority: false
  }
});
const scopes = {
  scopes: [
    "openid",
    "profile",
    "https://skyfintest.onmicrosoft.com/scopes-app-id-url/test"
  ]
};
```

## Reproduction steps
1.  Click on forgot password and enter email.
2.  Receive validation code via email and enter it.
3. Enter new password and click on.

## Expected behavior
Should redirect to app and login automatically.

## Browsers
Chrome 80

**Comment by tnorling** [comment]
@chris-gunawardena There is a known issue with the forgot password flow in a sign-up/sign-in policy due to the fact that the library does not currently support multiple policies. We apologize for the inconvenience. 

You can follow these issues [1245](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1245), [9](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/issues/9) for updates and potential workarounds in the interim.
