### ISSUE TITLE
iframe usage in MSAL Angular 9+

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-authentication-library-for-js#1500]
Is there a goal to not have to use iframe in MSAL.js?  Specifically MSAL Angular 9+ path?

If yes,  is that something being worked on already?

Thanks

**Comment by jasonnutter** [comment]
MSAL v1 (which is used in MSAL Angular v1) implements the Implicit Flow, which uses iframes to acquire tokens. We are currently working on MSAL v2, which switches to the Auth Code Flow w/ PKCE. The Auth Code Flow uses fetch requests instead of iframes as the primary mechanism for acquiring tokens, however, there are still situation where iframes will be used. MSAL Angular will be updated to use MSAL v2 at some point in the future, although that work has not yet been planned.

Do you have any specific concerns with iframes?

**Comment by jrmcdona** [comment]
Thanks @jasonnutter .  I once saw the entire app loading with an iframe and it felt very heavy.  I was just always curious and thought I had heard with an non-iframe version might be a little more elegant.  But I understand there are challenges.  Greatly look for to MSAL v2.   I am using MSAL Angular 9 and MSAL.NET for a first party app here at Microsoft.  So it is great to see all the progress you guys are doing!

**Comment by jasonnutter** [comment]
@jrmcdona It is possible to use a dedicated redirect page (with no content), which alleviates the concern of reloading your entire application in the iframe/popup. As noted, there will still be iframes in v2, they will just be used less often.

Thanks for the feedback. Closing, as no further action at this time.
