### ISSUE TITLE
acquireTokenPopup does not save access token in local cache

### ISSUE THREAD

**Issue by barisbikmaz** [AzureAD/microsoft-authentication-library-for-js#1509]
#607  Library
- `msal@1.2.2` 

## Framework
-  `React v16`

## Description
Seems like UserAgentApplication.acquireTokenPopup does not save the accessToken in local cache. Is this desired behaviour?

When I call acquireTokenPopup and call directly afterwards acquireTokenSilent with the same scopes a network call happens.

## Regression
Did this behavior work before? Don't know

## Configuration
```js
{
	auth: {
		clientId,
		authority: 'https://login.microsoftonline.com/organizations',
		redirectUri,
	},
};
```

## Reproduction steps
1.  call acquireTokenPopup with some scopes which were not granted
2.  call after success acquireTokenSilent with the same scopes
3.  Observe network call to the auth endpoint

## Expected behavior
acquireTokenPopup should save the acquired access token in the local cache.

**Comment by riccardos77** [comment]
I have encountered the same problem. From a first analysis the problem seems to be in the updateCacheEntries method when invoked with the loginStartPage argument. In this case, setAccountCache is not invoked and, without putting the account in the cacheStorage, the saveTokenFromHash method does not persist the new token.
By moving the invocation of the setAccountCache method out of the else I get the correct behavior

**Comment by tnorling** [comment]
@barisbikmaz @riccardos77 Thanks for bringing this to our attention. I was able to recreate this on my end. I will discuss with the team and see if we can get a fix out soon.
