### ISSUE TITLE
Issues when trying to login directly without a login button flow

### ISSUE THREAD

**Issue by joanjane** [AzureAD/microsoft-authentication-library-for-js#151]
Hi! I've tested dev branch and made a few changes related to #144 and my issue is that the app redirects back to B2C after log in on IE.

My flow tries to authenticate directly on my app without using any login button like some examples I've seen, but maybe is having some issues maybe because of a [setTimeout](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/c5aef89abff79539529818c5a2a60eec1b6b9759/lib/UserAgentApplication.ts#L253) on the constructor of msal.

I'm calling acquireTokenSilent at startup, but it seems is not working without wrapping it in a setTimeout.

I have an [example](https://gist.github.com/joanjane/61cbed87ba19ad01c923078704f66f8f) that shows this behavior.

Thank you!

**Comment by rohitnarula7176** [comment]
@joanjane The constructor of msal is written in an asynchronous manner. The code inside setTimeout (handleAuthenticationResponse) calls the callback defined by the user and hence the code flow switches control from the library to the app developer. If we do not put this code inside the setTimeout, then you will not have the instance of msal available inside the callback method. In your example, you call the   constructor function of msal on line 32 and since it is asynchronous, the call to acquireToken also goes out in parallel on line 48 which causes issues since login has not completed yet. If you remove the call to acquireToken on line 48 and run your sample. it should work as expected. You should only have a single call to acquireToken in your sample which is on line no 42 inside the callback.

**Comment by joanjane** [comment]
@rohitnarula7176 The library don't execute the callback method when you're authenticated and you refresh the page, so removing line 48 on [my initial sample](https://gist.github.com/joanjane/61cbed87ba19ad01c923078704f66f8f/b683ad1012525970ac7706712bbe7ea83540af31) implies that flow is not triggered in this case. Also, a login button is not what I need, I just simply want a redirection to login if the user is not authenticated, and stay on the website otherwise (which is a very common practice).

Finally, I've [read a sample](https://docs.microsoft.com/en-us/azure/active-directory/develop/guidedsetups/active-directory-javascriptspa) that uses msal isCallback method that fixes this case. 

I've updated [my gist](https://gist.github.com/joanjane/61cbed87ba19ad01c923078704f66f8f) and this seems to solve the issue.
