### ISSUE TITLE
Multiple instances of MSAL with redirect flow

### ISSUE THREAD

**Issue by oneillsp96** [AzureAD/microsoft-authentication-library-for-js#1534]
## Library
"msal": "^1.3.0-beta.1",

## Framework
React 16.9

## Description
I have a page that requires authenticating and granting consent to two different Azure AD apps, each having a different client ID.  I am using the redirect flow having had a lot of issues with the popup flow.  I am making a call to my app's server to get the two client IDs, and then passing the ID to a function that returns a new UserAgentApplication with the client ID populated.  With just one usage of this function, everything works fine. When I use the function again (instantiating a new UserAgentApplication with a different client id), msalApp.handleRedirectCallback fails silently once the redirect is complete.

## Security
No

## Regression
No

## Configuration

two functions are identical except for client id passed in

```js
export async function getTeamsMsalApp() {
    const clientIdFromApi = await getMicrosoftTeamsClientId();

    return new UserAgentApplication({
        auth: {
            clientId: clientIdFromApi,
            authority: "https://login.microsoftonline.com/common",
            validateAuthority: true,
            postLogoutRedirectUri: "http://localhost:8080/settings/integrations",
            navigateToLoginRequestUrl: false,
            redirectUri: redirectUrl
        },
        cache: {
            cacheLocation: "localStorage",
            storeAuthStateInCookie: false
        },
        system: {
            navigateFrameWait: 0,
        },
    });

}
```

in my componentDidMount, I then call:
```js
const msalAppTeams = await getTeamsMsalApp();
this.handleMsalRedirect(msalAppTeams);
```
handleMsalRedirect uses the instance of msalApp to register the handleRedirect callback.
As soon as I add this line to get the new instance of UserAgentApplication, it breaks

```js
const msalAppAzureAd = await getAzureAdMsalApp();
const msalAppTeams = await getTeamsMsalApp();
this.handleMsalRedirect(msalAppTeams);
```

## Reproduction steps
1.  Add another instance of user agent application
2. Import new instance into relevant file
3. Original flow breaks, handleRedirectCallback fails silently

## Expected behavior
I should be able to add multiple instances of UserAgentApplication and register unique handleRedirectCallbacks for each one without issue

## Browsers
Chrome, assuming it affects all browsers

**Comment by tnorling** [comment]
@oneillsp96 Can you explain a little more about your use case? Why do you need 2 separate instances of msal? Do you just need to access resources from 2 different apps? If so, the correct way to do this would be to create a single instance of msal and make separate acquireToken requests for the scopes associated with each of your resources.

**Comment by oneillsp96** [comment]
@tnorling I just need to acquire access tokens from two different azure AD apps, to be stored off for later use. The scopes I need are identical for each app, just by coincidence.

**Comment by tnorling** [comment]
@oneillsp96 In order to do this you should create a new app registration in the azure portal and use the client_id for this app, give this new app permissions to the APIs you need access to, and then request each of these scopes in a single msal instance. I'll see if I can find some documentation to help you set this up.

**Comment by tnorling** [comment]
[Access Web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-access-web-apis) - Should be done on the app that will need access
[Expose Web APIs](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-expose-web-apis) - Should be done on the apps you need access to

Also important to note: Once you are logged in, you will need to make 2 separate acquireToken calls to obtain the access token, one for each resource. You can pre-consent to both during the login call if that is desired, meaning you can acquire the access tokens silently without needing to redirect or use popups twice.

**Comment by oneillsp96** [comment]
Not sure of all the implications for that setup, as I am not the one who created the AAD apps.  I think the idea was to use seperate AAD apps to keep them logically separated. For example what if I wanted different redirect URLs for each? Sure I can just pile them all in one app, it just seems unnecessary. I was also very confused that there was a PR to fix this issue but it seemed to either not work or only work for the popup flow

[](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/296)

**Comment by oneillsp96** [comment]
[](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/296/commits/01d811661dc248fdb5bf5c9164cfe0fb98bf98c2)

**Comment by oneillsp96** [comment]
[someone msft described the issue as being fixed here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/974)

I bailed on the redirect flow and am back to popup flow, which seems to be less buggy in the 1.3.0-beta versions versus some of the older versions. Just something to look out for, it's an inconsistency between the flows that should probably be documented.

**Comment by tnorling** [comment]
@oneillsp96 This is not the recommended way of handling this scenario because it introduces more complexities. However, this is technically possible as long as you are not trying to use multiple accounts; that is unfortunately not supported. You need to be careful that you do not run multiple concurrent interactive flows, silent flows should be fine. If using the popup flow, a second popup will not open if you haven't finished the first. 

Redirect is more complicated. The easiest way to handle this is to have each instance redirect to separate pages that are not aware of the other instance. If your use case requires that both return to the same page you will need to have some mechanism to determine which instance should handle the response. Otherwise, whichever is instantiated first on the page will strip the response hash and attempt to process it and the 2nd instance will never be aware that a response was sent. Not totally sure if this would work but you could potentially include a custom ```state``` in your request which on redirect you would need to read from the hash and determine which msal instance to instantiate first.

**Comment by oneillsp96** [comment]
Ok, I think I'm all set with the popup flow for now. Thanks for the quick response.
