### ISSUE TITLE
How to do incremental consent with /.default scopes?

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#1574]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [X] `@azure/msal@1.2.1`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
We have an existing application that is requesting scopes: ["https://management.azure.com/.default"]. Everything works well

We have a new requirement to access Azure storage apis and thus we need a new scope for resource https://storage.azure.com. We decide to request the /.default scope again on this resource so our new scopes look like this: ["https://management.azure.com/.default", "https://storage.azure.com/.default"].

I've tried to request these scopes on `loginRedirect` and I got an error:
![image](https://user-images.githubusercontent.com/55852795/80743531-fa475c00-8ad1-11ea-833f-acfa3e527693.png)

So I tried to remove this new scope from `loginRedirect` and put it in `acquireTokenSilent` and I get a similar error (an exception gets thrown in code and a similar error message is contained in the error)

My question is
1. Am I requesting these scopes improperly?
2. [The documentation has suggested to use incremental consent](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/api-scopes#request-dynamic-scopes-for-incremental-consent) but there aren't instructions on how to do so

Let me know if you need any more details from me. Thank you.

**Comment by tnorling** [comment]
@thoo1 When you call `acquireTokenSilent` are you including both scopes in that call or making separate calls for each?

**Comment by thoo1** [comment]
@tnorling including both scopes in one call

**Comment by thoo1** [comment]
I think I just found another issue that might clarify it for me: https://github.com/Azure/azure-sdk-for-net/issues/9076

The resolution seems to be that AAD will return this error if I am requesting multiple scopes (using /.default) for multiple resources

Is that correct? In that case do I need to maintain two separate tokens?

**Comment by tnorling** [comment]
@thoo1 AcquireToken calls are per resource, regardless of if you are using ./default or not. So you should be making separate calls for each. Try that and see if it works.

**Comment by thoo1** [comment]
that worked, thank you @tnorling

**Comment by zanlikealobster** [comment]
Hi! Sorry to ask, but how did you manage to solve this issue? I'm having the same problems trying to access "https://management.azure.com/" and "https://api.loganalytics.io/" resources within the same app using @azure/msal-browser@2.x.x. 
Even making two separate AcquireToken calls (each one with its own object with the relative scope), i get a 401 error for the second request.
Reversing the order of the requests will simply result in the reverse situation, but the second call will always fail. 
Appreciate your suggestions! Thanks!

**Comment by tnorling** [comment]
@zanlikealobster Which version of msal-browser are you using? There was a bug in `2.0.0-beta.0` causing exactly what you describe when trying to get tokens for multiple resources. This should be fixed in `2.0.0-beta.1` which was released yesterday. We know that there are still some outstanding issues we need to resolve in msal-browser before GA and appreciate your patience while we we work on those!

**Comment by zanlikealobster** [comment]
@tnorling thank you so much! that was the case indeed! I was using `2.0.0-beta.0` and everything is working fine after upgrading to `2.0.0-beta.1.` 
I installed beta.0 two days ago, but didn't check for a possible newer release in the meantime, my bad. Sorry for such an easy-to-fix question.
I'm just playing around with it and it looks really promising! It was just driving me crazy because i thought I got my authentication flow wrong. 
Thank you again for your precious help, I really appreciate it!
