### ISSUE TITLE
Default scopes in @azure/msal-browser

### ISSUE THREAD

**Issue by ktikku** [AzureAD/microsoft-authentication-library-for-js#1671]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@ 2.0.0-beta.2
`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
When are you planning to remove the 5 default scopes that are added by default in @azure/msal-browser?
I have an org wide scope that is not supported with the microsoft graph apis scopes.
0: "email"
1: "openid"
2: "profile"
3: "user.read"
4: "offline_access"

**Comment by ktikku** [comment]
the `tokenResponse ` has all the scopes I had requested for while creating the client
I added `Calendars.Read` and I'm getting that as well even though while creating the scopes for loginRedirect I'm providing only `openid` and `profile`.

**Comment by ktikku** [comment]
Also, I had deleted `User.Read` and `Calendars.Read` but I'm still getting them in my tokenResponse.

**Comment by pkanher617** [comment]
@ktikku The default scopes are only added for login calls. If you use the acquireToken APIs, you can make requests without those scopes.

> the tokenResponse has all the scopes I had requested for while creating the client
> I added Calendars.Read and I'm getting that as well even though while creating the scopes for loginRedirect I'm providing only openid and profile.

I'm a bit confused by this statement. When you say you added Calendars.Read, what do you mean?

> Also, I had deleted User.Read and Calendars.Read from the client but I'm still getting them in my tokenResponse.

An access token response will have all consented scopes, not just the ones you requested. If you are removing consent from these scopes, and then still seeing them returned in the response from the auth server, then that is a different issue. Deleting them only in your JS application will not change what the server returns, since you are still technically consented to those scopes.

**Comment by ktikku** [comment]
I was under the impression we can get an access token with selected scopes provider while calling `loginRedirect` method.
Let's say I have 'openid', 'profile' and 'User.Read' configured in my Azure AD client, I was hoping I can get a token having openid' and 'profile' scopes only if I provide them as a param inside while calling `loginRedirect`. 
Thanks for the clarification!

**Comment by pkanher617** [comment]
The `openid` and `profile` scopes are passed when you want additional information about the user  and access to the user_info endpoint. (see [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent)). So as a side effect of sending those scopes, we provide the `id_token` back to you. The `User.Read` scope is a graph scope, same with `Calendars.Read`. So the access token will provide you access to the graph user information, as well as the OpenID user_info endpoint. You can also send a scope for another resource during the login call, but you will not receive a token for this scope - you will only consent to it. You must make a silent request with ONLY that scope in order to retrieve the access token for it.
