### ISSUE TITLE
How to force users to log in after they have logged in for a long time in a single-page app?

### ISSUE THREAD

**Issue by flytiny** [AzureAD/microsoft-authentication-library-for-js#1729]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
  When the user logs in for a long time, for example, one day or two days, and he/she refreshes the page, we will want the user to log in again, but currently it will not trigger the re-login.
  So is there any way to force users to log in again? Or what configuration do we need to modify to shorten the effective time of the login state?
    

Examples: 
> "How do I use MSAL with Vue.js"
> "How do I SSO between tabs?"
> "How do I use MSAL to protect my custom Web API?"
> "How can my app support multiple AAD tenants?"
> "When will my scenario be supported?"
> "When will this framework be supported"

**Comment by flytiny** [comment]
Sorry to bother you.

**Comment by flytiny** [comment]
Sorry, After read the [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes) and created Azure AD conditional access, it seems that the life of refresh token was not successfully modified. And the page prompts this sign-in frequency control only works with supported apps, and third-party applications cannot use this control.
<img width="237" alt="chrome_4OJAQKpIiO" src="https://user-images.githubusercontent.com/6790396/83502320-f86b2100-a4f3-11ea-8e1d-bafdf7ab5883.png">

So, still the previous questions, how to force users to log in again after they have logged in for a long time.

**Comment by tnorling** [comment]
@flytiny Token lifetimes are 1 hour and the session lifetime is 24 hours. This means that if no requests have been made in 24 hours, you will need to login again before requesting a new token. Refreshing the page will not trigger this on it's own, you will likely receive an `InteractionRequiredError` the next time you try to call an `acquireToken` method and need to call `loginRedirect` or `loginPopup`.

The document you referenced is in preview and not recommended for production use. But you will still need to invoke a login function in order to prompt the user after the session has expired regardless of what you set the lifetime to.
