### ISSUE TITLE
msal-electron-poc npm package is missing dist folder

### ISSUE THREAD

**Issue by kurkle** [AzureAD/microsoft-authentication-library-for-js#1754]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal-electron-poc@0.1.0"

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Electron

## Description

The NPM package has `"main": "dist/index.js"` in it, but the package does not contain `dist` folder.

## Error Message

Unable to resolve path to module 'msal-electron-poc'.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior

The package should contain the built distribution files.

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by technical-boy** [comment]
Hi @kurkle! Have you tried running `npm build` on the msal-electron-proof-of-concept directory?

Since `msal-electron-proof-of-concept` is not officially supported (it is just a proof of concept and we don't recommend using it in production), we haven't actually deployed it to npm. For that reason, you need to build and use the local version of the library (as shown in [the msal-electron-poc sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-electron-sample-app).

Please keep in mind that `msal-electron-proof-of-concept` hasn't been updated in over a year, so some updating may be necessary.

Let me know if this helps so we can close the issue!

**Comment by kurkle** [comment]
Thanks, I did not realize https://www.npmjs.com/package/msal-electron-poc was published by someone else.
That one did build, but it did not work linked to another project. I'll try the sample, if it works.

You can close this, because the package is not released by you.

**Comment by technical-boy** [comment]
@kurkle so looking at the published package, it seems the person who published the package on npm didn't run the build command, which is why the dist directory isn't present when you npm install it. Closing the issue since we didn't publish that package.
