### ISSUE TITLE
specifying common authority in acquireTokenSilent results in cache miss

### ISSUE THREAD

**Issue by onlyann** [AzureAD/microsoft-authentication-library-for-js#1761]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.3.1` 

## Description
Specifying an authority of _https://login.microsoftonline.com/common/_ to `acquireTokenSilent` will result in a access token cache miss every time.

## Error Message

No error message.
However, the access token will be fetched from Azure AD every single time the token is silently acquired.

## MSAL Configuration

It doesn't seem to have an impact. Example of configuration:

```js
auth: {
        clientId: config.clientId,
        postLogoutRedirectUri: window.location.origin,
        redirectUri: window.location.origin
      },
cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: true
      }
```

## Reproduction steps
```js
acquireTokenSilent({
  scopes,
  authority: "https://login.microsoftonline.com/common/"
})
```
## Expected behavior

I would expect that the library either warns that _https://login.microsoftonline.com/common/_ is not a valid authority value when calling `acquireTokenSilent` or that it would ignore such authority.

When logging in with _https://login.microsoftonline.com/common/_ authority, the retrieved access token gets cached using the `tid` value of the id token. 
Whenever an authority is passed to `acquireTokenSilent`, it gets used as is to find an access token from the cache, which explains the cache miss.

## Browsers/Environment
Any

**Comment by jmckennon** [comment]
If you don't include the authority as `https://login.microsoftonline.com/common/`, do you still see the same functionality? The common endpoint is the default authority. This should be a workaround for now.

We've been able to reproduce the bug when that default authority is provided and we always get a cache miss. Will move it over to be fixed.

**Comment by onlyann** [comment]
Yes, I am currently working around it by not providing the authority.

**Comment by lidermanrony** [comment]
Hi. Any ETA for a fix?

**Comment by jmckennon** [comment]
@lidermanrony It's in our backlog but we have not dove deeper into this yet, as the workaround seems to be fairly simple, making this low-priority.

Are you seeing other problems or unable to use the workaround for now?

**Comment by lidermanrony** [comment]
I had no problem working around it, but the issue is very common (no pun intended :-)) and on the other hand is not very easy to notice (since it mostly effects performance). It took us a while to understand that our customers are experiencing double the amount of wait time when we moved from ADAL to MSAL

**Comment by lidermanrony** [comment]
actually, I'm seeing the following error. could leaving the authority blank be the cause of this?
![image](https://user-images.githubusercontent.com/199509/85664907-a723fc80-b66f-11ea-9518-553978b643a3.png)

**Comment by jmckennon** [comment]
>I had no problem working around it, but the issue is very common (no pun intended :-)) and on the other hand is not very easy to notice (since it mostly effects performance). It took us a while to understand that our customers are experiencing double the amount of wait time when we moved from ADAL to MSAL

Noted. Will bring this up with the team to try and get things prioritized.

>Seems like leaving the authority blank can be the cause of this when we have a user that's logged into 2 tenants (and thus has 2 separate access tokens).
Any advice on how to work around this?

I see, this makes sense. That error is definitely intended. In the meantime, you can clear access tokens from the cache like you mentioned or fallback to setting `forceRefresh` to true, [which will skip the cache and go directly to the server](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-pass-custom-state-authentication-request). Note that there's a loss in performance here. Again, will try to expedite seeing that this issue is larger than excluding a string.

>Is there a an API to clear all access tokens? adal.js had one but i cannot seem to locate such a thing in msal.js

[There is](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/UserAgentApplication.ts#L1104), `UserAgentApplication.clearCache()`.

**Comment by lidermanrony** [comment]
thanks! looks like the typescript d.ts files do not provide it (i have to cast to any for it to work)
