### ISSUE TITLE
Use redirect flow to acquiretokensilent,not stable!

### ISSUE THREAD

**Issue by element8763** [AzureAD/microsoft-authentication-library-for-js#1781]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`

## Description
I'm using a redirect flow to perform authentication in the mobile browser,It works well in localhost,but after I deploy to the server,sometimes,when acquireTokenSilent ,the authorize will happen twice at the time,I put some details in this link
https://stackoverflow.com/questions/62339746/acquiretokensilent-failed-when-using-msal-js

Examples: 
> "Why authorize happen twice?"

**Comment by element8763** [comment]
this error code returns:token_renewal_error

**Comment by jmckennon** [comment]
Can you provide the rest of your msal-related code, like where `getTokenRedirect` is being called?

**Comment by element8763** [comment]
@jmckennon 
I called my function in componentDidMount,and regarding to the call  `this.props.onFetchTemplate();`
and define it in my saga file   `  const res = yield call(repository.findAll, "inputhere");`
and here is my call
```
export class TemplateRepository implements IRepository<ITemplate> {
    constructor() {
    }
    public findAll = async (queryOptions: string): Promise<ITemplate[]> => {
        let token;
        var storage = window.sessionStorage;
        if (isMobile) {
            storage.setItem('getTemplate', '2');
            token = await getTokenRedirect();//TODO lOAD TWICE
        } else {
            token = await getTokenMsal();
        }
        console.log("token when findall templates" + token);
        const reqHeaders = new Headers();
        const bearer = "Bearer " + token;
        reqHeaders.append("Authorization", bearer);
        reqHeaders.append("Access-Control-Allow-Origin", "*");
        reqHeaders.append("Content-Type", "application/x-www-form-urlencoded");
        const options = {
            headers: reqHeaders,
            method: "GET"
        };

        return new Promise<ITemplate[]>((resolve, reject) => {
            fetch(GRAPH_ENDPOINTS.SITETEMPLATE, options)
                .then(response => {
                    // This is where you deal with your API response. In this case, we
                    // interpret the response as JSON
                    if (response.status === 200) {
                        response.json().then((responseJson: any) => {
                            storage.setItem('getTemplate', '1');
                            const result = responseJson;
                            const mapObject = (result as any[]).map<ITemplate>(res => {
                                const createdTemplate = this.mapITemplateFromServiceResult(res);
                                return createdTemplate;
                            });
                            return resolve(mapObject);
                        });

                    } else {
                        console.log("res:" + response.text())
                        const err = new Error("401")
                        reject(err);
                    }
                })
                .catch(error => {
                    reject(error);
                });
        });
    };`
```
and when first loading the page and tried to get token,such error code will returned.
Thanks!

**Comment by jmckennon** [comment]
You shouldn't try to call one of the login APIs when your app is loaded inside an iframe. 

You can also try using a blank page as a redirectUri as of `msal@1.2.0`. It is recommended to set the redirectUri for the silent calls to a blank page, say https://yourhost/auth.html instead of the SPA's homepage. 

Could you also implement the msal Logger and send us the logs? That will help us see what's going on in this use case. You can [read about this on the Microsoft docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging?tabs=javascript).

**Comment by ryandegruyter** [comment]
@jmckennon how would you load the app, if after each login you redirect to a blank page?

**Comment by jmckennon** [comment]
@ryandegruyter when you call acquireTokenSilent, it sends off a request to the server. The original call still sits monitoring the iframe for the response, even if you redirect to a different page. A blank page works well because it avoids reloading any application-level or msal code that may unknowingly interfere with the original call. Once you get the response back, you can reload the page or do whatever your app needs to do. This strategy works with silent and pop calls.

Additionally, you can have more than one redirectUri, and also set them per request. This allows you to set the blank page as the redirectUri only for silent calls and not for redirect calls where this strategy wouldn't work.

**Comment by ryandegruyter** [comment]
Ok, we don't use acquireTokenSilent. only loginRedirect and the MSALGuard for Angular

**Comment by element8763** [comment]
@jmckennon Yes,I used to use a blank page for Popup login,It works well.But if I use blank page It will redirect the application to a blank page.How can I load the application after login? And do you mean I can only use it in popup and silent calls,if so how can I have more than one redirect uri?Does it means I have to maintain different auth variable when call login redirect and silent call? Thanks!

**Comment by jmckennon** [comment]
>Yes,I used to use a blank page for Popup login,It works well.But if I use blank page It will redirect the application to a blank page.How can I load the application after login?

If you are using the redirect flow, setting the `redirectUri` as a blank page will not work. This will only work in popup and silent flows. 

>how can I have more than one redirect uri? Does it means I have to maintain different auth variable when call login redirect and silent call?

You can register multiple `redirectUri` in the Azure portal, in your app registration. You can then pass in `redirectUri` to your `msal` config as a means of using the registered ones, so that a particular request will go to that specific uri. From [this documentation page](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-initializing-client-applications): 

> redirectUri: Optional. The redirect URI of your app, where authentication responses can be sent and received by your app. It must exactly match one of the redirect URIs you registered in the portal. Defaults to window.location.href.

The idea is that you can make this different for each request type. So only when doing `acquireTokenSilent`, you may give the request a `redirectUri` of a blank page.

**Comment by tnorling** [comment]
Closing as the question has been answered and there has been no further activity. Let us know if you're still having issues.
