### ISSUE TITLE
IE and Edge: Issue with token renewal 

### ISSUE THREAD

**Issue by harishKandikatla** [AzureAD/microsoft-authentication-library-for-js#1820]
## Library
- [x] `msal@1.3.2` or `@azure/msal@1.0.0`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
Angular

## Description
- I'm able to renew token silently in all browsers except IE and edge. 
- Able to get token silently for the first time when user logins but can't renew it later in IE(I have only option to redirect in this case which makes user changes lost)
- Able to get token silently for the first time when user logins but can't renew it later in edge(infinite loop)

## Error Message
Interaction required 
<img width="337" alt="Screenshot 2020-06-24 at 11 01 29 AM" src="https://user-images.githubusercontent.com/36755848/85505401-d9037780-b60b-11ea-89b0-865911c6a5cb.png">

## Security
- [ ] Is this issue security related?
No
## Regression
- [ ] Did this behavior work before?  
Not sure
Version:

## MSAL Configuration
<img width="884" alt="Screenshot 2020-06-24 at 11 15 50 AM" src="https://user-images.githubusercontent.com/36755848/85505562-3a2b4b00-b60c-11ea-8c73-fdd04857ba6e.png">

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
1 Log in to the app
2 Get token silently
3 Renew token silently on getting 401 error
4 Always getting interaction required error only in IE

On getting these errors as per my code it is navigating to the home screen and all user changes(for example form details entered in some screen) are lost

```js
export class RefreshTokenInterceptor implements HttpInterceptor {
  private isRefreshing = false;
  private refreshTokenSubject: BehaviorSubject<any> = new BehaviorSubject<any>(
    null
  );
  constructor(
    public authService: MsalService,
    private broadcastService: BroadcastService
  ) { }

  intercept(
    request: HttpRequest<any>,
    next: HttpHandler
  ): Observable<HttpEvent<any>> {
    if (this.authService.getAccount()) {
      const idToken = window.localStorage.getItem("idToken") || "";
      request = this.addToken(request, idToken);
    }

    return next.handle(request).pipe(
      catchError((error) => {
        if (error instanceof HttpErrorResponse && error.status === 401) {
          return this.handle401Error1(request, next);
        } else {
          return throwError(error);
        }
      })
    );
  }

  private async handle401Error1(request: HttpRequest<any>, next: HttpHandler) {
    if (!this.isRefreshing) {
      this.isRefreshing = true;
      this.refreshTokenSubject.next(null);
      try {
        const response = await this.authService.acquireTokenSilent(
          GRAPH_REQUESTS.LOGIN
        );
        console.log(response);
        this.saveAccessToken(response.idToken.rawIdToken);
        this.isRefreshing = false;
        this.refreshTokenSubject.next(response.idToken.rawIdToken);
        return next
          .handle(this.addToken(request, response.idToken.rawIdToken))
          .toPromise();
      } catch (error) {
        window.alert(error); 

        debugger;
        const isIE = window.navigator.userAgent.indexOf('MSIE ') > -1 || window.navigator.userAgent.indexOf('Trident/') > -1;
        window.alert(isIE); 
        if(isIE) {
          window.alert("redirect"); 
            this.authService.acquireTokenRedirect(GRAPH_REQUESTS.LOGIN);
            let error;
            this.isRefreshing = false;
            return throwError(error).toPromise();
          } else {
            try {
              const payload = await this.authService.acquireTokenPopup(
                GRAPH_REQUESTS.LOGIN
              );
              console.log("Token---Fetch");
              this.saveAccessToken(payload.idToken.rawIdToken);
              this.refreshTokenSubject.next(payload.idToken.rawIdToken);
              this.isRefreshing = false;

              return next
                .handle(this.addToken(request, payload.idToken.rawIdToken))
                .toPromise();
            } catch (error) {
              this.isRefreshing = false;
              window.alert("Something went wrong, make sure popups are allowed and refresh page");
              return throwError(error).toPromise();
            }  
          }
      }
    } else {

      return this.refreshTokenSubject
      .pipe(
        filter((token) => token != null),
        take(1),
        switchMap((jwt) => {
          return next.handle(this.addToken(request, jwt));
        })
      )
      .toPromise();
    }
  }
```

## Expected behavior
Should able to renew the token silently
## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [x] IE
- [ ] Other (Please add browser name here)

**Comment by jmckennon** [comment]
>Able to get token silently for the first time when user logins but can't renew it later in edge(infinite loop)

This is usually due to some iframe shenanigans. You can read extensively on this subject [on our wiki](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/FAQs#how-to-avoid-page-reloads-when-acquiring-and-renewing-tokens-silently), along with potential fixes. You can try setting your `redirectUri` to a blank HTML page. Note that this will not work in a redirect flow, only in silent and popup flows. You can provide a separate redirectUri in the request config to manage this.

> Able to get token silently for the first time when user logins but can't renew it later in IE(I have only option to redirect in this which makes user changes lost)

The token you obtain initially from `acquireTokenSilent` only lasts for an hour, and if called again within an hour (assuming a valid AAD session still exists), will renew that token. If it's been over an hour, you will need to use an interactive flow like `acquireTokenRedirect`. 

If you're seeing these errors before that 1-hour has elapsed, can you provide the scopes you're passing into the call?

**Comment by harishKandikatla** [comment]
@jmckennon thanks for getting back!

I kept the token expiration time to 10 mins. I waited for 10 mins and made an API call, I got 401 and redirected to the home page (only in IE) 

I passed below Login scope

export const GRAPH_REQUESTS = {
  LOGIN: {
    scopes: ["xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"],
  },
};

**Comment by harishKandikatla** [comment]
Also, I have a request. Most of the developers are confused with MSAL implementation. We need a sample app. I don't think you handled all these cases in the sample app you provided

Why don't you provide a sample app which handles all(login, refresh token with interceptor) cases?

**Comment by jmckennon** [comment]
Having a more comprehensive/robust set of samples is on our radar. There's been a lot of improvement over the past few months, but we still have a long ways to go and appreciate the feedback.

>I kept the token expiration time to 10 mins. I waited for 10 mins and made an API call, I got 401 and redirected to the home page (only in IE)

Sorry, I think I need clarification--if you are trying to renew after expiration, that should error out by design. Please correct me if I'm misunderstanding the use case here.

If the expiry time is set to 10 minutes, and we wait until after 10 minutes to try to renew, we should definitely be getting an error. At this point you will need to call `loginRedirect` or `loginPopup` again (in order to retrieve another `idToken`). If you make this API call BEFORE the expiration, you should be able to call `acquireTokenSilent` with only the `clientId` as a scope in order to refresh the `idToken`. 

You can default to trying to renew after initial login, but if you see a 401, you should fall back to one of the login APIs.

**Comment by harishKandikatla** [comment]
@jmckennon 

I would like you to understand my current flow and correct me If I'm wrong
Below is the flow which I followed

I'm using redirect API to login into the app. Immediately after successful login and getting the token silently and storing id token in local storage. For the API calls, I'm reading token from local storage and passing it in headers

Below is the REST API call flow(using interceptor)
       1. Fetch id token from local storage
       2. Set it for Authorization header and make API call

Response Handling:        
If I get 401 error I'm calling Aquiretokensilent(clientid), if its success I'm storing updated token locally and calling my REST API again. 

Else I'm calling AquireTokenRedirect(clientid) for IE, AquireTokenPopup(clientid) for other browsers. On success, I'm storing updated token locally and calling my REST API again else logging out the user from the app

```
//401
// gettokensilent
//       - Success(resume the rest api)
//       - Fail
//          Call AquireTokenRedirect for IE, AquireTokenPopup for other browsers 

private async handle401Error(request: HttpRequest<any>, next: HttpHandler) {
      try {
        const response = await this.authService.acquireTokenSilent(
          GRAPH_REQUESTS.LOGIN
        );
        this.saveAccessToken(response.idToken.rawIdToken);
        return next
          .handle(this.addToken(request, response.idToken.rawIdToken))
          .toPromise();
      } catch (error) {
        const isIE = window.navigator.userAgent.indexOf('MSIE ') > -1 || window.navigator.userAgent.indexOf('Trident/') > -1;
        if(isIE) {
            this.authService.acquireTokenRedirect(GRAPH_REQUESTS.LOGIN);
            let error;
            return throwError(error).toPromise();
          } else {
            try {
              const payload = await this.authService.acquireTokenPopup(
                GRAPH_REQUESTS.LOGIN
              );
              this.saveAccessToken(payload.idToken.rawIdToken);
                .handle(this.addToken(request, payload.idToken.rawIdToken))
                .toPromise();
            } catch (error) { //logout
                 this.authService.logout();
                return throwError(error).toPromise();
            }  
          }
      }
    } 
```

Question for you
     
1. Sometimes I observed I'm getting access token as null while refreshing token. But I'm able to get Id token every time, so id token is used in REST API calls. Is this fine?
2. Is IE supports acquire token popup?
3. Is the above flow recommended? Else let me know the flow which needs to be followed

**Comment by jmckennon** [comment]
> Sometimes I observed I'm getting access token as null while refreshing token, not sure the reason behind this. But I'm able to get Id token every time, so id token is used in REST API calls. Is this fine?

The reason is that in certain situations when requesting an idToken (which you are doing when `clientId` is the only scope), idToken and accessToken fields on the response are both populated with an idToken. If you are using idTokens to protect your backend APIs, then yes you can use the idToken value; however, we recommend using accessTokens with custom scopes to protect backend APIs instead of idTokens. 

> Is IE supports acquire token popup?

Yes, there are known issues with popups in IE, so we recommend using the redirect flow in IE.

> Should I always refresh the token before expiration?

The library handles this, and should call `acquireTokenSilent` when you need a token. The library handles renewals. Whenever you call `acquireTokenSilent`, you should always have a fallback to one of the interactive flows.

> Is the above flow recommended? Else let me know the flow which needs to be followed

Can you clarify what your `saveAccessToken` function is doing? The library will save tokens in local/session storage for you, so you likely don't need to write that code yourself.

Additionally, in regards to your original question about the intranet error; can you verify that your application domain, `login.microsoft.com`, and other sites associated are in the same security zone in IE? You can read about these problems [on our wiki](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issues-on-IE-and-Edge-Browser).

**Comment by harishKandikatla** [comment]
Now I'm got some idea with your response!

Can you please answer below queries too

1. I understand the `acquireTokenPopup`  issue in IE. User context(for example form data) will be lost if I use `acquireTokenRedirect`, is there any way this can be handled?
2. I will try to implement the flow which you suggested.  I will call the silent token method every time before an API is called. But what if the user is reading some data for a long time and not making any updates to data. So no API will be called in this time and so `acquireTokenSilent` method also will **not** be called for a long time.  Assume after an hour if there is an API got called, obviously, the `acquireTokenSilent` method fails.  In this case, I need to use a `popup/redirect` flow. Should I add a timer keep on calling some API so that silent token always succeeds?
3. I am using `MSAL guard` for routes. In this case also if the user is not making any updates no API will be called. After some long time If I click on some other tab which is protected with MSAL guard, I observed it is navigating to home screen. Is there any way this can be handled? I do not want the user to navigate to the home screen if the token expires

**Comment by jmckennon** [comment]
> I understand the acquireTokenPopup issue in IE. User context(for example form data) will be lost if I use acquireTokenRedirect, is there any way this can be handled?

Yes, you will lose context here. It's up to you how to handle this, but you can leave some sort of hint to yourself to repopulate or reload information, for example by passing in information to the `state` field, which will return whatever is passed in on the redirect response.

> I will try to implement the flow which you suggested. I will call the silent token method every time before an API is called. But what if the user is reading some data for a long time and not making any updates to data. So no API will be called in this time and so acquireTokenSilent method also will not be called for a long time. Assume after an hour if there is an API got called, obviously, the acquireTokenSilent method fails. In this case, I need to use a popup/redirect flow. Should I add a timer keep on calling some API so that silent token always succeeds?

Some apps do call `acquireTokenSilent` periodically to keep their tokens fresh, but this is not directly supported by the library, so you will need to write that logic on your own.

>I am using MSAL guard for routes. In this case also if the user is not making any updates no API will be called. After some long time If I click on some other tab which is protected with MSAL guard, I observed it is navigating to the home screen. Is there any way this can be handled? I do not want the user to navigate to the home screen if the token expires

Can you try setting `navigateToLoginRequestUrl: false` in your msal config?

**Comment by jmckennon** [comment]
Closing this as we're assuming the problem is solved due to inactivity. Please open a new issue if you have further questions. Thanks!
