### ISSUE TITLE
[Angular] Version 1.0.0 is not working

### ISSUE THREAD

**Issue by anth-git** [AzureAD/microsoft-authentication-library-for-js#1839]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.0.0`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
After upgrading from v0.1.4 to v1.0.0 I constantly get those errors when trying to log in:

```
Token calls are blocked in hidden iframes

Token renewal operation failed due to timeout
```

I'm able to log in maybe 1 time in 10, after clearing the cache or hitting ctrl+f5 several times. This was not an issue in the old version.

## Expected behavior

It should just work, especially that development of the library supporting Angular 6+ took like 2 years…

I tried a work-around described in https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-avoid-page-reloads without success. Besides, what do I care about some implementation detail that MSAL uses iframe? And apparently this error shouldn't prevent acquiring the token, so why is it even logged to console, let alone as en error?

Regarding "Token renewal operation failed due to timeout" there are several issues about this, all closed due to inactivity or because _"this is not a problem in MSAL"_. No solution provied.

Last time I checked I pay for the Azure, so I would expect to have working solution. And it's not like this library is developed by volunteers, right?

Sorry for the rant, but I lost 2 days trying to make it working, so I'm a bit annoyed with this.

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jmckennon** [comment]
Sorry for the inconvenience. Auth is hard and we understand the frustration.

>Token calls are blocked in hidden iframes

You may have already tried this based on the information in your provided link, but you can set your `redirectUri` to a blank page (when using silent and popup flows) in order to generally avoid the "Token calls are blocked in hidden iframes" output. This is caused when your app tries to make a token call with the hash in the URL inside an iframe. We recommend not calling an `acquireToken` API on page load, or at the very least not on page load when there is a hash and when in an iframe. You are correct in that it is not blocking, we just print that to note the library is being used incorrectly and perf is being wasted. #1156 is a whole thread about this problem.

>Token renewal operation failed due to timeout

This is potentially a larger problem for some of our users, tracked by #1592. A few potential fixes that have worked for some are:
* Try setting `navigateToLoginRequestUrl` to false
* Try setting `loadFrameTimeout` to a large number, like `30000`. You may need to monitor this to see if your app just spins forever, or if something actually was causing it to need a few extra seconds.

Additionally, if you are getting the renewal error on a silent call, make sure that your app falls back to something like `acquireTokenPopup` if the silent flow does not work, along with potentially logging any errors.

**Comment by tnorling** [comment]
Just to piggy-back off what @jmckennon said and provide some additional context, the timeout error happens when the top frame of your application cannot retrieve the hash from the url of the hidden iframe. There are a number of reasons this might happen, the 2 most common of which are:
1. The IDP is trying to display an error or interaction prompt and never redirected back to your application, in this case the error message might include a url. If you open this in a new tab this may provide some additional clues as to what's happening and how to resolve it.
2. The page that is used as the redirectUri is clearing the hash or redirecting away before the top frame of your application can extract it. This could be solved by setting the redirectUri for your silent call to a blank page as suggested above. 

It's possible that solving the first error will resolve the 2nd.

**Comment by anth-git** [comment]
I managed to get rid off "Token calls are blocked in hidden iframes" error by checking if I'm in the iframe.

But I still have problem with the "Token renewal operation failed due to timeout" error.
loadFrameTimeout has no effect whatsoever. If I set it to 30s, it just fails after 30s instead of 6s.

Overall, in my app I need to redirect user to login screen automatically (without Login button)
In order to do this I'm using this snippet. Login() method is called on the page load:
```
  login(): Observable<LoggedOnUser> {
    const cfg = environment.loginConfig;
    return from(this.msalService.acquireTokenSilent({ scopes: cfg.angular.consentScopes, authority: cfg.msal.auth.authority, prompt: 'select_account' })).pipe(
      switchMap(() => this.fetchLoggedOnUser()),
      catchError(err => {
        this.msalService.loginRedirect({ prompt: 'select_account' });
        return of(undefined);
      })
    );
  }
```

This is how 
1. App is loaded, acquireTokenSilent() fails with *"ClientAuthError: User login is required. For silent calls, request must contain either sid or login_hint"* error, and user is redirected to the login page
2. User types in username & password, page is redirected back to the app, acquireTokenSilent() fails with *"ClientAuthError: Token renewal operation failed due to timeout."* error, and user is redirected to the login page again
3. User types in username & password again, and only now it works as expected

Strangely enough it seems to be working if app is hosted from Angular CLI (ng serve -aot), but once it is production build (ng build --prod --aot) it's not working (configuration is the same in both cases).

**Comment by jmckennon** [comment]
@anth-git we're currently testing a potential fix for the token renewal problem with an internal customer, if it works we'll get it out ASAP for `1.3.3`. I'm going to close this issue as the renewal problem is being tracked by #1592. Please open a new issue if you have further questions. Thanks!
