### ISSUE TITLE
ReactJS frontend with Azure AD B2C error UnsupportedAuthorityValidation

### ISSUE THREAD

**Issue by ariffadhillah** [AzureAD/microsoft-authentication-library-for-js#1869]
I have a problem with this, I use ReactJS frontend with Azure AD B2C, but when I run react displays this error "Uncaught (in promise) UnsupportedAuthorityValidation" I still don't understand why

import b2cauth from 'react-azure-adb2c';

b2cauth.initialize({
  instance: 'https://FunSuitDev.onmicrosoft.com/tfp/', 
  tenant: 'FunSuitDev.onmicrosoft.com',
  signInPolicy: 'B2C_1_ADB2C_API',
  applicationId: 'ae82c7fe-a82b-448d-905f-6a63827e92a4',
  cacheLocation: 'sessionStorage',
  
  scopes: ['https://FunSuitDev.onmicrosoft.com/teastAPI/user_impersonation'],
  redirectUri: 'http://localhost:3000/',
  postLogoutRedirectUri: window.location.origin,
});

b2cauth.run(() => {
  ReactDOM.render(<App />, document.getElementById('root'));
  serviceWorker.unregister();
});`

![Untitled](https://user-images.githubusercontent.com/31968096/86289565-c86d7700-bba0-11ea-868d-75a2677a397d.png)

> ``

**Comment by jmckennon** [comment]
You need to provide both `authority` and the `validateAuthority` values in the [msal config when using AAD B2C](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-initializing-client-applications). 

From the docs:
>In Azure AD B2C, [the authority] is of the form 'https://instance/tfp/tenant/policyName/', where instance is the Azure AD B2C domain i.e. {your-tenant-name}.b2clogin.com, tenant is the name of the Azure AD B2C tenant i.e. {your-tenant-name}.onmicrosoft.com, policyName is the name of the B2C policy to apply.

>validateAuthority: Optional. Validate the issuer of tokens. Default is true. For B2C applications, since the authority value is known and can be different per policy, the authority validation will not work and has to be set to false.

**Comment by ariffadhillah** [comment]
```
b2cauth.initialize({
  instance: 'https://FunSuitDev.onmicrosoft.com/tfp/', 
  tenant: 'FunSuitDev.onmicrosoft.com',
  signInPolicy: 'B2C_1_ADB2C_API',
  applicationId: 'ae82c7fe-a82b-448d-905f-6a63827e92a4',
  cacheLocation: 'sessionStorage',
  scopes:'https://FunSuitDev.onmicrosoft.com/teastAPI/user_impersonation'],
  redirectUri: 'http://localhost:3000',
  validateAuthority: false,
  postLogoutRedirectUri: window.location.origin,
});
```

is this what you mean?

**Comment by jmckennon** [comment]
That setup should theoretically work if you are requesting tokens from the `common` endpoint. The default `authority` value is  `https://login.microsoftonline.com/common`, so that's what you'll have if you don't provide it, like in your setup above. If you want to to use a different authority you'll need to specify in that config. You can see another example of this in our [B2C sample](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/blob/aff0ad7ce528561f7dfe211edfd8ec9842bbe44d/JavaScriptSPA/authConfig.js#L7).

**Comment by ariffadhillah** [comment]
but I see from this tutorial that 
https://medium.com/@fiqriismail/how-to-secure-your-reactjs-frontend-with-azure-ad-b2c-8fd165f602e8
he does not use "validateAuthority" and there is no error "UnsupportedAuthorityValidation" and if I try to use the code in the tutorial everything works fine, but when I use the Azure id mine
"instance: 'https://login.microsoftonline.com/tfp/', tenant:,
  signInPolicy:,
  applicationId:,
  cacheLocation: 'sessionStorage',
  scopes :,
  redirectUri: 'http: // localhost: 3000', "
everything becomes an error "UnsupportedAuthorityValidation"

**Comment by jmckennon** [comment]
That tutorial is from 1.5 years ago and is written by a third party, so I can't necessarily comment on it. It's most likely working because his policies will utilize the common authority, which is what `validateAuthority: true` (the default if not provided) will work for. We recommend defaulting to our samples and the Microsoft docs for usage. Is the setup not working even if you include `validateAuthority: false`? This is generally going to be required for B2C apps, as explained in the docs, and shown in the sample I linked. There's also some more information on #606 about this.

**Comment by jmckennon** [comment]
Closing this as we're assuming this has been solved due to inactivity. Please open a new issue if you have further questions. Thanks!

**Comment by ariffadhillah** [comment]
ok, thanks for the information, i forgot to tell you, because i just checked it yesterday,
