### ISSUE TITLE
Our Angular App with token "https://oursite.com/#access_token=eyJ0eXAi..." in a frame is refused because it set 'X-Frame-Options' to 'deny' in "web.config"

### ISSUE THREAD

**Issue by eastjie** [AzureAD/microsoft-authentication-library-for-js#1985]
## Library
-  `msal@1.3.2` 
-  `@azure/msal-angular@1.0.0`

## Description
Our web application is hosted on IIS runs without problem with Azure AD, but now, we have a requirement, that the web app should be prevented from "Clickjacking", so the following item is added in our app.

```
     <customHeaders>
         <add name="X-Frame-Options" value="deny" />
     </customHeaders>

```
Then the error will be displayed after login by user.

> Refused to display 'https://oursite.com/#access_token=eyJ0eXAiOiJKV...' in a frame because it set 'X-Frame-Options' to 'deny'.
> app.component.ts:71 MSAL Logging:  Fri, 17 Jul 2020 08:48:59 GMT:3a12e170-643b-4106-9e5c-dcccfa41ac1c-1.3.2-Error monitorWindowForHash unable to find hash in url, timing out

I have searched some similar problem about 'X-Frame-Options' to 'deny'. 
From "[FAQ](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/FAQs)" , it is suggested to change the bootstrap module. On the other [issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/494), the 'X-Frame-Opitons' has only denied Microsoft "login" URL of Azure.  It is not our case. 

I have two questions, 

1. Why our original page is blocked after we change the header "X-Frame-Options" to "deny" in callback instead of Microsoft Azure AD login page? I have thought, the first refused frame should be login page, the same as the other issue.
2. How can we solve this problem, because we can't remove this configuration. It must be required for the other Clickjacking?

Thanks very much for the help.

**Comment by jo-arroyo** [comment]
@eastjie MSAL.js v.1 implements the implicit flow which uses hidden iframes to silently acquire tokens. If your application cannot be loaded in an iframe, MSAL will be unable to silently acquire tokens. One possible mitigation in your scenario is to create a dedicated page to use as your redirect uri for silent operations (and that page can be a blank HTML page) and allow that page to be rendered in an iframe (e.g. set x-frame-options to SAMEORIGIN). Otherwise you will be unable to silently acquire tokens and you will have to use `acquireTokenPopup` or `acquireTokenRedirect`.

**Comment by eastjie** [comment]
Thanks very much for your support. We have set  "x-frame-options" to SAMEORIGIN to solve our problem.
