### ISSUE TITLE
Cached token not matching login hint for AAD third-party auth providers

### ISSUE THREAD

**Issue by jerryjili** [AzureAD/microsoft-authentication-library-for-js#2010]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.3.2` or `@azure/msal@1.x.x` => v1.3.2
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
typescript (SharePoint WebPart)

## Description

I was building a SharePoint Web Part, which needs to make Rest API calls to AAD guarded APIs. To authenticate user, I'm calling ssoSilent() method to acquire an id token with the current logged-in user's email id fetched from Graph API (/me). When the user is an external user on AAD, the principal name was in the format like "xxx_gmail_com#EXT#tenant@contoso.com" (for email id xxx@gmail.com). When I'm passing either original gmail id or principal user id, I get error AADSTS50058, indicating that the login hint does not match any logged-in user in cached tokens. However, for a internal email id, since principal name and email id is consistent with each other, there is no issue.

Another issue I had was, when I ever logged in with my internal account (yyy@contoso.com) on a domain joined device, even if I log out and switch to the external account xxx@gmail.com, it will sometimes accidentally pick up the internal account from the cache and shows the login hint not matching issue.

I'm wondering if this is an issue with MSAL library, or I missed anything in my configuration? Thanks!

## Error Message
1. In ssoSilent request, AADSTS50058 - Login user from cached token does not match login hint.
2. In pop up window: You can't sign in here with a personal account. Use your work or school account instead. 

## Security
- [ ] Is this issue security related?
No

## Regression
- [ ] Did this behavior work before? 
Version:
Did not try on previous versions yet

## MSAL Configuration

```js
// Provide configuration values here.
auth:{
    clientId: 'client-to-authenticate',
    authority: 'https://login.microsoftonline.com/common',
    redirectUri: 'url-of-this-page',
    navigateToLoginRequestUrl: true,
    cacheLocation: 'sessionStorage'
  }
```

## Reproduction steps
```js
// Provide relevant code snippets here.
this.context.msGraphClientFactory
          .getClient()
          .then((client: MSGraphClient): Promise<string> => {
            return client
                .api('/me')
                .get((error, userProfile: MicrosoftGraph.User, rawResponse?: any) => {
                  var userPrincipalName = userProfile.userPrincipalName;

                  var ssoRequest = { 
                    loginHint: userPrincipalName 
                  };
                  
                  msalInstance.ssoSilent(ssoRequest)
                  .then((authResponse: Msal.AuthResponse) => {
                    // Extract id token or access token and do something else
                  })
                  .catch(graphError => {
                    alert("Access token error: " + graphError);
                    msalInstance.loginPopup(ssoRequest);
                  });
          });
```

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jerryjili** [comment]
@shwetashukla @deachyut could you please add details if necessary?

**Comment by jo-arroyo** [comment]
@jerryjili Unfortunately there are known issues with guest users and login hints. Please try enabling the sid claim and passing that in your requests. [Here are the instructions to enable sid](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims).

Expressly providing sid in the request may also help with your second issue, so that the account on your domain joined device is not used. If the problem persists, please provide logs so we can further assess this issue.

**Comment by liupeirong** [comment]
We have the same issue with B2B gmail users. Both our own apps and the javascript and react samples in this repo were working fine last month. We haven't changed our code. One app is using 1.3.1, the other, 1.3.2. They all stopped working recently.

Enabling `sid` didn't work for us. According to [this documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso#automatically-select-account-on-azure-ad), `sid` can only be used in `acquireTokenSilent`, but it's actually the following call `acquireTokenRedirect` that has the incorrect `loginHint` for guest users. For now I'm working around by setting the `loginHint` to the email in the `idTokenClaims` if email is not null, which is the case for guest users. Otherwise, set it to upn, as shown [here](https://github.com/liupeirong/react-aspnetcore-graph-b2b-or-b2c/blob/master/react-sample-app/src/withAuth.js#L28). This workaround seems to only work for msal 1.x though.

**Comment by shwetashukla** [comment]
@jo-arroyo is there any timeline when it would be fixed?

**Comment by jasonnutter** [comment]
@shwetashukla @jerryjili As noted, for silent requests you can pass `sid` to resolve errors with mismatched login hint values.

For interactive requests, can you try passing `prompt: 'select_account'` to loginPopup? I would also recommend setting your authority to use your tenant ID instead of `/common`, e.g. `https://login.microsoftonline.com/<tenant-id>`. Let us know if that helps resolve your issue.
