### ISSUE TITLE
login error 'state_mismatch: State mismatch error' with msal-browser

### ISSUE THREAD

**Issue by flytiny** [AzureAD/microsoft-authentication-library-for-js#2019]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
@azure/msal-browser:2.0.0
## Description
We are a first-party app (I don't know if this information is important). After the user logs in and jumps back to the page, the AuthenticationResult that msalObj gets is empty, then the page will automatically refresh again soon, and this error appears in the console.
I saw [this issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1846) reported by others, but it seems to be fixed already.

## Error Message
![image](https://user-images.githubusercontent.com/6790396/88282512-4ba36800-cd1c-11ea-88bb-a0260a7a7212.png)

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
const msalConfig: Configuration = {
  auth: {
    clientId: "****",
    authority: "https://login.microsoftonline.com/common",
    redirectUri: "****",
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: true,
  },
};
```
other code

```js
const myMSALObj = new PublicClientApplication(msalConfig);
let account: any = null;

const loginRedirectRequest = {
  scopes: config.authConfig.loginRequestScopes,
  redirectStartPage: window.location.href
};

myMSALObj.handleRedirectPromise().then((resp: AuthenticationResult | null) => {
  handleResponse(resp);
}).catch(console.error);


function handleResponse(response: AuthenticationResult | null) {
  if (response !== null) {
    account = response.account;
  } else {
    account = getAccount();
  }
}

function getAccount(): AccountInfo | null {
  const currentAccounts = myMSALObj.getAllAccounts();
  if (currentAccounts === null) {
    console.log("No accounts detected");
    return null;
  }
  if (currentAccounts.length > 1) {
    // Add choose account code here
    console.log("Multiple accounts detected, need to add choose account code.");
    return currentAccounts[0];
  } else if (currentAccounts.length === 1) {
    return currentAccounts[0];
  } else {
    return null;
  }
}

export async function signIn() {
  await myMSALObj.loginRedirect(loginRedirectRequest);
  console.log(account);
}
```
```js
await signIn();
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
After the user logs in and jumps back to the page, we can get the AuthenticationResult, and the page will not refresh again quickly, and the error will not appear

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jo-arroyo** [comment]
@flytiny Is this issue intermittent or easily reproduced? Can you please share with us a fiddler trace of this behavior? Please feel free to share over email or Teams.

**Comment by ronaldh46** [comment]
@jo-arroyo Just wondering whether this issue has been resolved?
I'm currently using the latest version @azure/msal-browser 2.0.2 and have also been receiving this error.
`ClientAuthError: state_mismatch: State mismatch error. Please check your network. Continued requests may cause cache overflow.`

I have essentially the same code as above.
Cache Options:`      "cache": {
        "cacheLocation": "localStorage",
        "storeAuthStateInCookie": true
      }`
Turning on logging does not yield much more info to help.
Any direction would be great! Thanks

**Comment by van-dung-mulodo** [comment]
@ronaldh46 I met the same issue that morning.
The version is @azure/msal-browser 2.0.2 too.
Hope to see any working around...

**Comment by ronaldh46** [comment]
@van-dung-mulodo I did some more troubleshooting.
It turns the error wasn't due to the double encoding in my case, but rather the instantiation of the `handleRedirectPromise()` method.

As a bit of background, I'm using this in React and have the MSAL client as a wrapper using Context.
Previously had this instantiated within the the Context provider - and this was causing the error. I have since moved it into the a useEffect hook, set to trigger only on initialisation. This fixed the problem. I assume it must have to due with the MSAL client generating the GUID for the state parameter again, possibly after the redirect - unsure.

Would be curious to find out and also hear from the team the ideal way to use the auth code flow with a React SPA.

**Comment by van-dung-mulodo** [comment]
@ronaldh46 I see. So my issue is not the same at you.
I installed @azure/msal-browser 2.0.1. My code ran normally.
But when I update to @azure/msal-browser 2.0.2. The error log was thrown `ClientAuthError: state_mismatch: State mismatch error. Please check your network. Continued requests may cause cache overflow.`
Because of the deadline, so I rollbacked the old version for attempting.
I'll be back to research later.

**Comment by jo-arroyo** [comment]
@ronaldh46 We are in the early stages of design for msal-react, which will demonstrate how to use the auth code flow with react.

@van-dung-mulodo Please open a new issue if you need further assistance.
