### ISSUE TITLE
Using msal-browser with B2C

### ISSUE THREAD

**Issue by vaughanh1** [AzureAD/microsoft-authentication-library-for-js#2037]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Hi,

I am trying to understand how to use msal-browser (released version 2.0.0).

Having read through a lot of the help files and viewed lots of samples, I am still unable to get things to work as expected.

Here is my scenario:
1/ I have configured a B2C tenant and registered an SPA application to run on http://localhost:3000 using Auth. flow with PKCE.
2/ Downloaded the samples and attempted running the sample, "samples\msal-browser-samples\TypescriptTestApp2.0"
3/ I assume configured correctly, as I am able to signup and signin successfully using a local account, (username and password, **NOT** social login). This is using the loginRedirect methods on Chrome (with CORS disabled, more details here: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1795)
4/ I wish to use the token of the logged in user in order to make a call to an API, in this case we will use what is in the sample (Graph API). Please note, I am not expecting the API to work, but at least be able to see the setup of the call to the API created successfully, (with the correct token added to the header).

Here is where my knowledge is a little thin, and I need some guidance please:

1/
After logging in, the AuthenticationResult response object passed to the handleResponse method, contains an AccountInfo object. The username of this object is **always** undefined. Upon investigation, it appears this is a known issue with B2C, as it is looking for the "preferred_username" claim, that is never supplied by the B2C tenant.

Further research, found here: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-aad-b2c-considerations
informed me that I should add the displayName claim (which comes through as "name" in the claims). The response object does now contain this claim, and I am able to access it and display this to the user.

If I attempt refresh the page, the AuthenticationResult response object is null, and the returned account (currentAccounts[0]) is correct, however, the username of this object is **always** undefined. As the response object is null, I am unable to determine the logged in user. This is where the documentation stops.

Some thoughts were to perhaps persist the username or the entire token in a cookie to access on subsequent refreshes / new tabs? Can somebody point me to some documentation or some examples of what I should do please? 

2/
Once logged in, I clicked the button, "See Profile". This attempts to get the token for the logged in user by using the same AccountInfo object (with username as undefined) but fails with the following error:
ClientAuthError: no_tokens_found: No tokens were found for the given scopes, and no authorization code was passed to acquireToken. You must retrieve an authorization code before making a call to acquireToken().

I assume Msal should have stored the token for the logged in user and retrieved it for me by using the acquireTokenSilent method. I am currently configured as follows:

cache: {
        cacheLocation: "localStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: true, // Set this to "true" if you are having issues on IE11 or Edge
    },

Changing the cache settings made no difference.

Some thoughts:
It cannot get the token because of this whole issue surrounding the username being undefined?
Perhaps I should be passing in a loginHint to the SilentRequest, but not sure why that would work either.

Again, if someone can point me in the right direction, it would be most appreciated.

Warm regards,

Vaughan

**Comment by tnorling** [comment]
@vaughanh1 To answer your first question regarding the `username` in the `AccountInfo` object, this is a known issue which we are actively looking into. If you just need to get the account object you can call `getAllAccounts()` and then find the account you need from the returned array. If you are only signing in one user at a time this should only contain a single element. 

If you need access to the `name` claim you mentioned you can pull that from the idToken which is cached in local or session storage, depending on how you've configured msal. It is expected that `AuthenticationResult` would be null when refreshing the page as this is populated directly from the response of attempting to acquire a token, when you refresh this value is lost.

As for the 2nd issue, since MS Graph scopes cannot be used in B2C scenarios, it's not surprising that this would not work. For testing purposes I would suggest creating a custom scope on your app registration which you can request from your app. Also please keep in mind that for B2C currently you will also need to request the `offline_access` scope in order to obtain a refresh token. This differs a little bit from AAD scenarios and the samples we currently have up but we're working on getting B2C aligned in the near future.

Apologies for the lack of documentation, we have some docs and B2C specific samples pending and will be sure to get those up as soon as the major blockers to getting B2C working are resolved. Thanks for your patience and as always we'll be happy to answer any additional questions you have in the meantime.

**Comment by ammar-mop** [comment]
When you mention that B2C is getting aligned in the near future, how soon is that? Just a rough ETA would work (1 month, 3 months, in one year etc.) I am currently working on a product for a client, and I am facing many issues with MSAL B2C.

**Comment by tnorling** [comment]
@ammar-mop I unfortunately can't share any sort of ETA but getting B2C working with msal-browser v2.0 is one of our highest priorities right now and we're working with the service teams to get that work done as quickly as possible. If you need an immediate solution we recommend using `Msal@1.x` for the time being and upgrading to 2.0 when the issues are resolved. My sincerest apologies for the inconveniences this may cause.

**Comment by jasonnutter** [comment]
For the getAccount question, this was resolved by #2114.

`offline_access` is already tracked in #1999.

Closing, as the first issue has been addressed, and the second issue is already tracked.
