### ISSUE TITLE
(MFA) Outlook add-in. userAgentApplication.loginPopup works in OWA, but not in Outlook

### ISSUE THREAD

**Issue by oyvindo** [AzureAD/microsoft-authentication-library-for-js#2039]
## Library
- [x] `@azure/msal@1.3.3`

## Description
I am authentication an outlook add-in with msal (MFA)
Using @eirikb 's replacement hack for userAgentApplication.openPopup, everything worked fine calling userAgentApplication.loginPopup(tokenRequest), both in outlook and OWA.
After the latest fixes from the msal team, this hack is no longer required in OWA as long as pop-ups are enabled in the browser.
In Outlook however, this still does not work. The behavior and error messages are the same in Outlook as when pop-ups are not enabled in the browser.

How can I make the msal loginPopup() work in Outlook as well?
Is there a way to enable pop-ups for addins in Outlook?
------------------------------------------------------------

## Code
Some code, including commented lines and the no longer uses openPopUp() hack.
(please don't mind the console.logs)
The only lines changed is the assignment : "userAgentApplication.openPopup = openPopup;" which is commented out.
login() is the main login.
mvaPopup() is used when token is expired.
```
const openPopup = () => {
  console.log('openPopup');
  const popupWindow = {
    close() {
    },
    location: {
      assign(url) {
        window.Office.context.ui.displayDialogAsync(
          url, {
            width: 25,
            height: 50,
          }, res => {
            popupWindow.close = res.value.close;
            res.value.addEventHandler(
              window.Office.EventType.DialogMessageReceived,
              ({ message }) => {
                popupWindow.location.href = message;
                popupWindow.location.hash = message;
              },
            );
          },
        );
      },
    },
  };
  return popupWindow;
};

const loginPopup = () => {
  // userAgentApplication.openPopup = openPopup;
  // logging in
  return userAgentApplication.loginPopup(tokenRequest)
    .then(token => {
      console.log('loginPopup token', token);
      appInsights.trackTrace({ message: 'loginPopup' });
      return Promise.resolve(token);
    })
    .catch(err => {
      console.log('loginPopup err', err);
      appInsights.trackTrace({ message: `error in loginPopup: ${err.message}` });
      Promise.resolve(err);
    });
};

const login = async () => {
  await loginPopup();

  return userAgentApplication.acquireTokenSilent(tokenRequest)
    .then(tokenResult => Promise.resolve(tokenResult.accessToken))
    .catch(err => {
      appInsights.trackTrace({ message: `error ${err instanceof InteractionRequiredAuthError} in login: ${err.message}` });
      if (err instanceof InteractionRequiredAuthError) {
        return userAgentApplication.acquireTokenPopup(tokenRequest)
          .then(token => Promise.resolve(token.accessToken))
          .catch(e => Promise.reject(e));
      }
      return Promise.reject(err);
    });
};

const mvaPopup = async () => {
  console.log('mvaPopup');
  // userAgentApplication.openPopup = openPopup;

  return userAgentApplication.acquireTokenPopup(tokenRequest)
    .then(popupTokenResult => Promise.resolve(popupTokenResult))
    .catch(e => Promise.reject(e));
};
```

**Comment by jasonnutter** [comment]
@oyvindo Unfortunately, we have not had a chance to prioritize fixing the experience when MSAL.js is used in Outlook desktop. To clarify, the `openPopup` method posted above does work in both environments?

We'll take this under consideration, and follow up if we need more information, thanks!

**Comment by eirikb** [comment]
@jasonnutter Hi. 
Why #1072 was closed (as fixed), when this is still not fixed?  
Should the original issue be either still open, or closed as won't-fix?

Anyway, I believe it could be possible to implement my previous hack in `@azure/msal-browser`, but only if [`PopupHandler`](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/interaction_handler/PopupHandler.ts) is exported (so it can be altered from outside) - or some other way to re-implement popup behavior is introduced.

**Comment by jasonnutter** [comment]
Sorry for the delay. You can find a working sample for how to use MSAL.js v1 in an Office Addin here: https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/auth/Office-Add-in-Microsoft-Graph-React

I have put together a fork/PR for how this can be updated to use MSAL.js v2: https://github.com/jasonnutter/PnP-OfficeAddins/tree/upgrade-msal/Samples/auth/Office-Add-in-Microsoft-Graph-React

Please follow the directions in the sample, and be sure to use the Office.js APIs for opening dialogs and communicating back to your addin from the dialog.

**Comment by jasonnutter** [comment]
Closing, as the samples above demonstrate how to properly open popups in Office addins to perform auth via MSAL.js. If you are using MSAL.js v1 and encounter issues related to a missing state value in the hash (#2726), please upgrade to MSAL.js v2, where this is no longer an issue.

**Comment by eirikb** [comment]
@jasonnutter Thank you :heart:!
I have now tested the repos you linked to and here is my result:

1. MSAL 1
    1. Excel Native: :heavy_check_mark: 
    1. Outlook Native: :heavy_check_mark: 
    1. Outlook Web: :heavy_check_mark: 
1. Your version with MSAL 2 and SPA 
    1. Outlook Native: :heavy_check_mark: 
    1. Outlook Web: :heavy_check_mark: 

I have tried to understand the code, am I correct about:

1. Add-in: Show login button
1. User click login: login.html is opened in a Office dialog using `Office.context.ui.displayDialogAsync`
1. Login window: Use `msal` with `loginRedirect`
1. Microsoft login endpoint: Let user login and redirect back to Login window
1. Login window: Use `msal` to call `acquireTokenRedirect`
1. Token endpoint: Redirect back to Login window with token
1. Login window: Pass token to parent window (Add-in) using `Office.context.ui.messageParent`

Also; what happens if the user leaves the Add-in open for say one hour, come back and then click on a button (resulting in the token being used)?

**Comment by jasonnutter** [comment]
@eirikb For MSAL v1, this is correct. As you can see in my MSAL v2 PR branch, the code can be simplified to just call `loginRedirect`. 

> Also; what happens if the user leaves the Add-in open for say one hour, come back and then click on a button (resulting in the token being used)?

When the token expires, you can invoke the auth popup again to get a new token.

**Comment by eirikb** [comment]
@jasonnutter Thank you for your answer :smiley: 
Sorry to bother you again, but what is your view on a mechanism for providing a custom popup handler to MSAL as an alternative?

- Beside an initial setup for a handler the MSAL API would work as usual. 
- Examples of MSAL online would be accurate.
- No special handling of token expiration since `acquireTokenSilent` would work as expected.
- No need to setup a custom build for `login.html`.
- Less feeling of "workaround".

**Comment by jasonnutter** [comment]
> Sorry to bother you again, but what is your view on a mechanism for providing a custom popup handler to MSAL as an alternative?

@eirikb I would not be in favor of that approach. We design our library APIs such that they can be composed together in any scenario, instead of providing specific APIs or configuration options for specific scenarios. In this case, the restriction that Office addin dialogs must be initially opened to a url on the same domain as the addin itself is set in the `displayDialogAsync` API, not MSAL, so I would argue that augmenting the `loginPopup` API to instead open your `/login` page is more of a workaround/hack then going through the steps demonstrated in the sample.
