### ISSUE TITLE
Unexpected # symbol in the URL after logging in

### ISSUE THREAD

**Issue by devfservant** [AzureAD/microsoft-authentication-library-for-js#2086]
## Library

**`msal@1.3.3`**

## Framework

*  JavaScript
*  `react@16.13.1`
*  `react-aad-msal@2.3.5`

## Description

After logging in, I do not expect to have an additional `#` symbol at the end of the URL.  
I get this new behaviour when upgrading `msal` from `1.2.2` to `1.3.3`.  
In the [Release notes](https://github.com/AzureAD/microsoft-authentication-library-for-js/releases), I did not notice any _breaking change_ regarding that point.  
Maybe I don't use `msal` in the right way, in that case feel free to add the `question` label.

```javascript
// Before (i.e.: msal@1.2.2)
https://mywonderfulapp.com

// After (i.e.: msal@1.3.3)
https://mywonderfulapp.com/#
```

Note that the `#` symbol then disappears when navigating to another page of the application.

## Error Message

None

## Security
- Is this issue security related? → No

## Regression
- Did this behavior work before? → Yes, it worked with `msal@1.2.2`

## MSAL Configuration

```js
// auth-provider.js
import { LoginType, MsalAuthProvider } from 'react-aad-msal'

export default () => {
  const msalConfig = {
    auth: {
      clientId: 'abcdefgh-1234-5665-4321-ijklmnopqrst',
      authority: 'https://login.microsoftonline.com/zyxwwxyz-1234-5665-4321-ijklmnopqrst/',
      validateAuthority: true,
      redirectUri: 'https://mywonderfulapp.com',
      postLogoutRedirectUri: 'https://mywonderfulapp.com',
      navigateToLoginRequestUrl: true
    },
    cache: {
      cacheLocation: 'sessionStorage',
      storeAuthStateInCookie: false
    },
    system: {
      loadFrameTimeout: 6000,
      tokenRenewalOffsetSeconds: 300,
      navigateFrameWait: 500
    }
  }
  const authenticationParameters = {
    scopes: [...]
  }
  const options = {
    loginType: LoginType.Redirect,
    tokenRefreshUri: 'https://mywonderfulapp.com/auth'
  }

  return new MsalAuthProvider(
    msalConfig,
    authenticationParameters,
    options
  )
}
```

```js
// app.js
ReactDOM.render(
  <BrowserRouter>
    <AzureAD provider={authProvider()} forceLogin={true} reduxStore={store}>
      {...}
    </AzureAD>
  </BrowserRouter>,
  document.getElementById('root')
)
```

## Reproduction steps

*  Open a fresh session in a private window
*  Log in to the application
*  Observe the difference in URL after redirection between versions `1.2.2` and `1.3.3`

## Expected behavior

I expect not to have an additional `#` symbol at the end of the URL after logging in.

## Browsers/Environment

Tested in Chrome 84.0 & Firefox 79.0 with Windows 10, in both normal & private modes.

**Comment by technical-boy** [comment]
Hi @devfservant. This is a known side effect of the redirect handling process and should not cause any breaking behavior. Can you please clarify if this is causing a bug in your application? If so, please provide more context on how your application is affected.

**Comment by devfservant** [comment]
Hello @technical-boy.

Actually, except the unexpected `#` symbol, it does not really _affect_ the application: the additional `#` symbol _would be_ the "bug".  
Is there a way to prevent this "side-effect"? Do you know why we have not that behaviour with `msal@1.2.2`?  
Maybe there should be a mention of that in the [Release notes](https://github.com/AzureAD/microsoft-authentication-library-for-js/releases)?

Thank you very much

**Comment by technical-boy** [comment]
Hey @devfservant . If you're interested in clearing the URL hash entirely after the redirect (including the anchor tag ('#')), you can use the following workaround:

1. Implement `handleRedirectCallback` and inside that callback, **make sure you get a valid response object**. 
2. **If you do have a valid response object**, check that the URL hash has been cleared (basically, that it looks like 'https://mywonderfulapp.com/#' with nothing after the anchor tag). This step is important because otherwise, you may interrupt the redirect logic before the hash has been properly processed.
3. At this point, you can access the `window.location.href` value and change it to whatever you want (setting it to an empty string should clear the # tag and leave the user at the redirect URI.)

The reason why `msal@1.3.3` doesn't remove the "#" tag is that, as mentioned in the last point, doing so would force a page refresh.

Thanks again for raising the issue and please let me know if the workaround above produces the desired behavior so we can close the issue.

**Comment by devfservant** [comment]
Hello @technical-boy,

Thank you for your help. I used `handleRedirectCallback` as follows:

```javascript
// auth-provider.js
export default () => {
  ... // Defining `msalConfig`, `authenticationParameters`, `options`

  const res = new MsalAuthProvider(
    msalConfig,
    authenticationParameters,
    options
  )

  const { UserAgentApplication } = res
  UserAgentApplication.handleRedirectCallback((authErr, response) => {
    if (authErr) {
      throw authErr
    }
    window.history.pushState({}, '', '/') // Remove anchor tag ('#')
  })

  return res
}
```

and it works fine. Closing the issue,

Thanks
