### ISSUE TITLE
Request entity Too Large

### ISSUE THREAD

**Issue by GerwinFleurop** [AzureAD/microsoft-authentication-library-for-js#2134]
## Library
MSAL Browser @1.3.4

## Error Message
'The page was not displayed because the request entity is too large.'

## Reproduction steps
Login through MSAL to website & check localstorage

## Expected behavior
No error after login - MSAL seems to be creating a lot of really big local storage items.

## Browsers/Environment
- [x ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

This was supposedly fixed in release 1.3.3 or 1.3.4 - but the issue only seems to have gotten worse after upgrading from 1.1.3 to 1.3.4

See for example: #1316 and #1188

**Comment by technical-boy** [comment]
Hi @GerwinFleurop . Could you please provide your MSAL configuration object? Also, could you clarify if you think this caused by too many cookies being sent to the server? Could you determine how many MSAL-specific cookies are being set? Thanks.

**Comment by GerwinFleurop** [comment]
Heey,

The error occurs whenever a call occurs to the database,
~11 or 22 cookies, sometimes it appears that MSAL sets the cookies twice? (Different GUIDS though)
& it also sets a lot of local storage records (20+ from time to time)

Object:

var config= {
        auth: {
            clientId: "<GUID from azureAD>",
            authority: "https://login.microsoftonline.com/<GUID From AzureAD>",
            redirectUri: "<ReturnURL>"
        },
        cache: {
            cacheLocation: "localStorage",
            storeAuthStateInCookie: true
        }
    };

**Comment by technical-boy** [comment]
@GerwinFleurop could you provide the MSAL cookies that are being sent?

**Comment by ImantsSkultans** [comment]
Still happening, sometimes. Noticed in previous Edge (non Chromium) and FF (version prior v68.12 (just recently got update)). Current assumption, that this happening when network is lagging - Azure authentication tries to store MSAL cookies, but authentication fails, then it goes in infinite loop tries to store cookies again and so on... and moment later there are a lot of cookies, which are added to requests and server prevents such request as header is too large.

**Comment by jmckennon** [comment]
@ImantsSkultans What version of the library are you using?

**Comment by ImantsSkultans** [comment]
@jmckennon - using "react-microsoft-login": "1.10.1" and "react-aad-msal": "2.3.5" which under the hood uses "msal": "1.2.1".

**Comment by jmckennon** [comment]
@ImantsSkultans @ppisarski Is it possible to upgrade your versions to `1.3.3`? There were some fixes in that release for problems like this one.

**Comment by ppisarski** [comment]
I tried with msal@1.3.3 and 1.4.0, which didn't help. Eventually, I changed the App Service Plan to run on Windows as opposed to Linux which I was using. Now I am not getting 431 errors anymore. However, after authentication instead of being redirected to the app, I am redirected to /auth.html#id_token=...&client_info=...&session_state=...

**Comment by jakehockey10** [comment]
I'm using @azure/msal-angular ^1.1.1 and msal ^1.4.0 and I'm still seeing this issue on Microsoft Edge and Mozilla Firefox.  During development, the hot-reload feature of the angular framework might be authenticating quite frequently, which could be causing this.  But I'm not sure how to get rid of it without deliberately slowing down my development changes...

**Comment by ImantsSkultans** [comment]
Its happened again in Chrome (Version 84.0.4147.89 (Official Build) (64-bit)), incognito mode in localhost (development)
![msal_list_cookies_edit](https://user-images.githubusercontent.com/10184995/93356130-7d7e0a00-f847-11ea-9ece-049004d68fc7.jpg)

**Comment by jakehockey10** [comment]
This is happening for me on all the browsers I have installed on this computer (the big 3) and each of them just put me in an endless login/logout loop until I get the "too large" error.  Each time it happens, I see this error in the console: Refused to display 'https://teamincb2c.b2clogin.com/<my-companies-b2c>.onmicrosoft.com/oauth2/authresp' in a frame because it set 'X-Frame-Options' to 'deny'.

**Comment by jmckennon** [comment]
@jakehockey10 @ppisarski These sounds like separate problems at this point, can you open a new issue with your configs, versions, and code so we can track separately?

Additionally, has anyone been able to consistently reproduce this, or is it intermittent? I have not been able to repro the "Request Entity too large" or the lots of entries in local storage. I would take a look at network traces to see what exactly is happening on the network. You can send fiddler traces to the email on my profile if you find anything suspicious.

**Comment by ppisarski** [comment]
My problem was related to react-aad-msal@2.3.5 implementation - it works but with msal@1.2.1.
If anyone is interested in the code, here it is https://github.com/ppisarski/reactapp-with-msal

**Comment by jakehockey10** [comment]
@jmckennon I've been struggling to find time to package everything up for you.  This is an issue for the devs and qa, but hasn't really bubbled up onto our board, but I'm campaigning for it to be.  In the meantime, I've been looking into it further.  I believe this has several causes in our case.  The devs and qa members are jumping from DEV, TEST, STAGING, and PRODUCTION quite a bit and we had similar issues when we were working with OKTA and using a lot of different environments throughout the day.  Another issue I've found inside our code is that on login failure, we call the libraries logout method and then attempt a loginRedirect immediately.  This causes the loop, not the library, which was my mistake for suggesting otherwise.  However, upon looking at the reason for failure in these cases, a familiar issue that we had correspondence in this issue tracker with a timeout error.  In attempting to retrieve the token, it times out and fails to login.  

I've been playing with fiddler and I'm just not familiar with it enough to understand what I'm looking for.  I don't see any indication of an issue, yet I experience the issue.  Right now, one of our QA members can't not login on any browser even after removing all cookies, local storage, etc. for our domains, our b2c endpoints, etc.

Another factor, since the timeout seems to be the root cause, is that some of our team members are in India with a significantly lower connection speed.  Could this be causing the issue?

**Comment by jmckennon** [comment]
@jakehockey10 

> Another factor, since the timeout seems to be the root cause, is that some of our team members are in India with a significantly lower connection speed. Could this be causing the issue?

You can try increasing the timeout by adjusting `loadFrameTimeout` to see if that helps and if these requests are truly timing out.

Unfortunately, there are many causes of timeouts, but the most common solution is to set your `redirectUri` to a blank html page. This prevents the app from reloading and instantiating new auth processes that can mess with the original one. Again, if you can find the time to open a new issue with full version/usage/config coverage, it will be much easier to provide insight.
