### ISSUE TITLE
secret is contained in localStorage MSAL-browser

### ISSUE THREAD

**Issue by garridio85** [AzureAD/microsoft-authentication-library-for-js#2135]
---
name: Question
about: Generals question about one of our libraries or related services.
title: 'secret is contained in localStorage MSAL-browser'
labels: question

---

Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
This may seem like a dumb question but... I see that our Azure App secret is returned after auth.

I am guessing this doesn't really matter as its protected by PKCE though? Am I correct in this thinking or do I need to do anything with it?

Thank you

--- EDIT:

Just noticed that secret is actually just the Access Token. why is it named secret?

![image](https://user-images.githubusercontent.com/36960065/90062975-9a5a7700-dcb6-11ea-81d1-806674bae9da.png)

**Comment by technical-boy** [comment]
Hi @garridio85 ! Could you please update your issue to comply with our [Issue Template](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/.github/ISSUE_TEMPLATE) so we can have enough information to adequately address your question? Thanks!

**Comment by technical-boy** [comment]
@garridio85 thanks for the update! The token you are seeing under "secret" is actually a short-lived refresh token. This refresh token comes with the access token requested and is later used by MSAL to "refresh" that access token (acquire a new access token) around the time the original access token expires. It's called "secret" because that's the way the authorization server expects it to be called.

**Comment by technical-boy** [comment]
Close since this is expected behavior, please let us know if there are any other questions.
