### ISSUE TITLE
Supporting subdomains with one central redirect url

### ISSUE THREAD

**Issue by JonDReese** [AzureAD/microsoft-authentication-library-for-js#2139]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

I need to make an application support subdomains per client, when I tried this I get the following logs:
- Navigated to https://clientname.appname.com/... 
- Navigated to https://b2cdirectoryname.b2clogin.com/...
- Navigated to https://appname.com/redirect
- MSAL Error: “Unable to get valid login request url from cache, redirecting to home page”

I think I understand this error. The cache isn't shared between clientname.appname.com and appname.com. Right?

In response I set https://clientname.appname.com/redirect as an approved redirect URL and updated the redirect URL in the MSAL configuration and it worked! Unfortunately this isn't going to work long-term because of the 256 limit on redirect URLs.

I found this documentation which seems to describe a solution for my exact problem:
https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url#use-a-state-parameter

Are there any examples of this solution using the MSAL library? 

It makes sense to me in theory, but I'm unsure how to configure MSAL to support it.

Thank you,

Jon

**Comment by technical-boy** [comment]
Hi @JonDReese . Unfortunately there are no samples that demonstrate the use of state for this use case, but you could do something like the following:

```js
  msalInstance.acquireTokenRedirect({
    scopes: [...],
    state: "appname.com" // the subdomain you want to redirect back to after login
});

msalInstance.handleRedirectCallback((authError, response) => {
  // response.accountState should be "appname.com", you can use this URL to redirect your application to the right subdomain.
});
```

**Comment by JonDReese** [comment]
Thank you for the quick response @technical-boy 

In order to get handleRedirectCallback to be triggered, I set navigateToLoginRequestUrl: false

I think my MSAL is configured slightly differently, instead of adding state to the .acquireTokenRedirect() I added it to .loginRedirect()

I then used response.accountState in the handleRedirectCallback to add this line:

window.location.replace('http://clientname.appname.com/redirect');

Here are my new logs:
Navigated to http://clientname.appname.com/
Navigated to https://b2cdirectoryname.b2clogin.com/...
Navigated to http://appname.com/redirect
styles.scss?1f7e:6 Fri, 14 Aug 2020 19:44:29 GMT:1234-1.3.4-Info Returned from redirect url
styles.scss?1f7e:6 Fri, 14 Aug 2020 19:44:29 GMT:1234-1.3.4-Info ProcessCallBack has been called. Processing callback from redirect response
styles.scss?1f7e:6 Fri, 14 Aug 2020 19:44:29 GMT:1234-1.3.4-Info State status: false; Request type: undefined
styles.scss?1f7e:6 Fri, 14 Aug 2020 19:44:29 GMT:1234-1.3.4-Error State Mismatch. Expected State: null, Actual State: eyJpZCI6IjM5N2FkMjVkLTA2MWEtNDUyNi1hMzY0LTc3MzY2ZmY4NDdlYiIsInRzIjoxNTk3NDM0MjYyLCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0=|clientname
Navigated to http://clientname.appname.com/redirect

Nothing happens after getting back to the correct subdomain's redirect. Is there a proper way to redirect back to the subdomain?

I think the state error is expected, since the cache isn't shared for the same reason I was getting the other error.

**Comment by jaslloyd** [comment]
Hi @technical-boy, I have a similar question to @JonDReese which you also commented about and you said about adding redirect_uri automatically but a question I have about the state approach, would this work if all of the subdomains also of an instance of msal running on them? When I tried this before it really didn't like the request coming from a subdomain e.g:

- User loads subdomain sub1.mycompany.example.com, msal checks on page load to check if user is authenticated, if not it does a redirect or a popup with the redirect_url pointed to the parent domain? I think it needs to be the parent domain because if we don't specify a redirect_uri MS will try to redirect where we came from and it will error because that url is not in the reply urls (because there are probably 100s of them). We would also add to the state to tell where we came from originally

- User signs in and is redirected back to parent domain, parent domain has msal so it takes the id_token etc out of the URL and signs us in, if i redirect the user back to sub1.mycompany.example.com that instance of msal doesn't have the token so it goes through the whole process again...ending in an endless loop.

I have tried to get in before msal and basically redirect to the subdomain myself with id_token attached but that seems to work.

Am I doing this wrong? or is there something i am missing.

**Comment by tnorling** [comment]
@JonDReese @jaslloyd 

A possible solution is:
1. Call `loginRedirect` on subdomain with subdomain url in state param
2. Redirect to AAD sign-in page
3. Redirect back to parent-domain with token/code response in hash
4. Detect that url has a response hash, strip the hash from the url, parse out the state param and retrieve the url from step 1
5. Redirect to the url retrieved from step 4 + append the full hash onto that url
6. Call `handleRedirectCallback` on your subdomain to process the response and cache the tokens

The issue lies in the fact that MSAL drops cache entries for itself before step 2 that it expects to be there on step 3. Because you're redirecting to a different domain the cache entries are not available. If you call `handleRedirectCallback` on this page you will get the invalid state error you were seeing so you'll need to trigger the redirect yourself and make sure you include the response hash in that redirect. If the parent domain is also running MSAL you'll need to be extra careful to check if the response is meant for this page or if redirection is needed **BEFORE** calling `handleRedirectCallback`  on this page. You only want to call `handleRedirectCallback` if you are certain the cache entries are available (i.e. the original request originated from the same domain)

Let me know if any of that doesn't make sense or if you're having trouble implementing it. It's important to note that I'm not aware that we've tested this use case but this is how it should work in theory...

**Comment by jaslloyd** [comment]
@tnorling Thanks for the detailed reply, it is good to know what exactly what is going on at each of these steps. I think when I tried this before I might have been missing some of the steps or calling handleRedirectCallback too early.

I will see if I can give this go over the next few weeks, if I can get it working I might submit a PR to add it to the docs/examples as I think it would be a common enough case what do you think?

**Comment by JonDReese** [comment]
@jaslloyd in order for handleredirectcallback to get called for me I had to set navigateToLoginRequestUrl to false. I'm going to try to have that toggled to false only when there isn't a subdomain.

I won't be able to attempt this until later next week. I'm hoping the one thing I need to do is step 5 from @tnorling 's comment

This might be a dumb question, but I'm not exactly sure what that code will look like. I will try in one week and report back.

Thank you!

**Comment by JonDReese** [comment]
Commenting to avoid this being closed as inactive, will look into more in the next few days.

**Comment by JonDReese** [comment]
@jaslloyd @tnorling @technical-boy 

Had a bit of a breakthrough :)

First I changed the redirect URL from https://appname.com/redirect to https://appname.com/central-redirect

Then I added **state: 'subdomain' + window.location.host.split('.')[0]** to loginRedirect(...) and acquireTokenSilent(...)

Then I added this javascript to my main.js:

if (window.location.pathname.includes('central-redirect')) {
    window.location.replace('https://' + window.location.hash.split('subdomain')[1].split('&')[0] + '.appname.com/redirect' + window.location.hash)
} else {
    //the rest of my application.
}

My logs now look like this

Navigated to https://clientname.appname.com/specific-page
Navigated to https://b2cdirectoryname.b2clogin.com/...
Navigated to https://appname.com/central-redirect
Navigated to https://clientname.appname.com/redirect
Navigated to https://clientname.appname.com/specific-page

The code I wrote is not pretty. I can do a better job setting and retrieving the state parameter. Any idea of the best way? 

I also need a better way to check for "central-redirect" without just throwing it at the top level of my SPA. Maybe it should be a separate endpoint.

I think I'm good to go from here. Still, I feel like I'm doing something wrong. It would be nice to have an example or an MSAL configuration to support this scenario.

**Comment by JonDReese** [comment]
There is a new problem that this caused. When my token expires and an API request fails, it automatically tries to acquire a new token silently, but that attempt doesn't have state attached to it, so it fails. I'm guessing there is some way for me to override that process to include state as well? I will look into it soon.
