### ISSUE TITLE
MSAL: Logout and when Login immediately not asking for User Credentials

### ISSUE THREAD

**Issue by veera-raghavagupta** [AzureAD/microsoft-authentication-library-for-js#2162]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.3.4`

## Framework
-[] `Angular 8`

## Description
We are using Front End as Angular 8 and Back End .Net Core 3.1 with MSAL 1.3.4. When we logout of the application and without closing the window try to login not asking for user credentials. 

Also seen when we logout the localStorage is cleared.

Please help

## Expected behavior

When user tried to relogin to application after logout. Should be asking for credentials.

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge

**Comment by technical-boy** [comment]
@veera-raghavagupta are you using an AAD or B2C application? Could you please provide your MSAL configuration? In the future, please complete all sections of the issue template so we can better investigate and address your issues.

**Comment by veera-raghavagupta** [comment]
Going forward will make sure will fill all the details.

Front end - Angular 8 
Back end - .Net Core 3.1
MSAL- 1.3.4
We are using **Azure B2C** 

Initially when we click on login redirects to login page for user to credentials, after successful login will be redirected to dashboard. And on click of logout will be redirected to login page as expected. When user clicks on login again should be asked for user credentials instead getting redirected dashboard.
[msal-angular-custom.zip](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/5104004/msal-angular-custom.zip)

**Comment by tnorling** [comment]
Can you confirm if you are using B2C local accounts or Social IDP logins? This is expected behavior when using Social logins with B2C. When you logout you are clearing local/session storage of your tokens for your app and closing the session with B2C, you are **not** logging out of your federated IDP (Google, Facebook, etc). This is because your app and the B2C service should not make any assumptions about whether or not a user wants to be signed out of your social account everywhere or just for that app. What this translates to in practice is that when you try to login again, the B2C service should present you with a screen to select the IDP you'd like to use (this suggests the B2C session was closed previously). Once you select your IDP you will be redirected to the IDP's login page, which if you are already signed in, will automatically redirect you back to B2C and then back to your app without asking for credentials.

**Comment by devalshilu** [comment]
did anyone get any solution for the same? what if the user wants to log in with a different account, not with the current login user? did the user need to wait till the session got expire in IDP?

**Comment by veera-raghavagupta** [comment]
> This issue has not seen activity in 14 days. It will be closed in 7 days if it remains stale.

We are still waiting for the fix as we are still facing the issue. Team, please help me with turn around solution.

**Comment by carlosrc** [comment]
I am in the same situation. Any help will be appreciated. Thanks.

**Comment by tnorling** [comment]
@veera-raghavagupta @carlosrc As explained above this is expected behavior for Social IDPs. There's a great answer on [Stack Overflow](https://stackoverflow.com/questions/12909332/how-to-logout-of-an-application-where-i-used-oauth2-to-login-with-google) explaining why it works this way.

I've also added an entry to our FAQ [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#i-logged-out-of-my-application-why-am-i-not-asked-for-credentials-when-i-try-to-log-back-in) if you still have questions.

**Comment by veera-raghavagupta** [comment]
@tnorling We are not using Social IDPs for logging in

**Comment by tnorling** [comment]
@veera-raghavagupta Can you send me a network trace including the login, logout and the 2nd login? Email is on my profile. Thanks!
