### ISSUE TITLE
Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by sanishmbod** [AzureAD/microsoft-authentication-library-for-js#2182]
## Library
- [X] `@azure/msal-browser@2.0.2`

## Framework
N/A
## Description
When logging in for the first time, and then pressing back button, the `handleRedirectPromise` method throws the error 
'Cannot read property 'replace' of null'

## Error Message
'Cannot read property 'replace' of null'

## MSAL Configuration

I am using the sample code with only the client id changed.

## Reproduction steps 

Steps using the sample app :

* Ensure you are logged out of all Microsoft accounts (or use incognito mode)
* Click 'Sign in using redirect' 
* Once signed in click the browser back button.

Video : 

https://streamable.com/9nc45o

## Expected behavior

The login to work as expected

## Browsers/Environment
- [X] Chrome - tested in chrome only, not sure about others.

**Comment by tnorling** [comment]
@sanishmbod Thanks for pointing this out. This happens because `loginRedirect` and `acquireTokenRedirect` drop some temporary cache items before redirecting to the IDP which MSAL expects to be there when it returns. Once you return from the initial login MSAL will process the response and clear these temporary cache items. Now when you hit the back button the IDP redirects back to your app again with a new response in the hash but MSAL no longer has those cache items it expects. 

I've linked a PR that should fix this bug by not throwing an error in this scenario, however, MSAL will not process the 2nd response. There should be a 1:1 relationship between MSAL token request and token response.
