### ISSUE TITLE
Force login for user

### ISSUE THREAD

**Issue by Shyam268** [AzureAD/microsoft-authentication-library-for-js#2220]
i want Always ask for enter credentials when open a base url even the user already previously.
tried 
 export const loginRequest = {
   scopes: ["user.read"],
   prompt: 'login',
 }
 this.authService.loginPopup(loginRequest);

this is not working for me

**Comment by jmckennon** [comment]
Have you tried `prompt: 'select_account'`? 

Additionally, in the future, please fill out the provided template, as it helps us diagnose issues better.

**Comment by Saxy** [comment]
@jmckennon also with 
`this.msalService.loginRedirect({
      prompt: 'select_account'
    });`
it does not work, the prompt seems to be ignored

**Comment by jmckennon** [comment]
@Shyam268 @Saxy We've been unable to reproduce this issue, can you both provide your msal configurations and versions?

**Comment by Shyam268** [comment]
msal version is 1.3.4

msal configuration 

```
export function MSALConfigFactory(config: AppConfigService): Configuration {
  const appSettings = config.getConfig(config.APP_SETTINGS);
  const authentication = appSettings.authentication;
  const auth = {
      auth: {
          clientId: authentication.clientId,
          authority: authentication.b2cPolicies.signUpSignIn.authority,
          redirectUri: appSettings.redirectUri,
          postLogoutRedirectUri: appSettings.postLogoutRedirectUri,
          navigateToLoginRequestUrl: false,
          validateAuthority: false,
      },
      cache: {
          cacheLocation: authentication.cacheLocation
      }
  };
  return (auth as Configuration);
}
```

**Comment by jmckennon** [comment]
Since you're using B2C, I would recommend also filing a ticket with the [B2C service team](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options). 

Are you using a social/third party IDP or a local login? Sometimes social IDPs (i.e. Google) can automatically redirect without our given parameters, which is my guess to what is happening here. I would recommend taking a look at network traces to see which params are getting sent, and you can send a fiddler trace to the email on my profile if you'd like help diagnosing.

**Comment by jmckennon** [comment]
Closing this as we're assuming the original problem has been solved due to inactivity, please open a new issue if you have further questions. Thanks!
