### ISSUE TITLE
How to write unit testing / e2e for the services using access token in Angular Project?

### ISSUE THREAD

**Issue by VijayakannanRaju** [AzureAD/microsoft-authentication-library-for-js#2221]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
How to write unit testing for the services using access token in Angular Project?

**Comment by jmckennon** [comment]
Can you provide more details about the unit tests that you're trying to write and the things that don't make sense?

**Comment by VijayakannanRaju** [comment]
I have implemented MSAL Module in app.module.ts

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule} from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

import { MsalInterceptor, MsalModule } from "@azure/msal-angular";
import { HTTP_INTERCEPTORS, HttpClientModule } from "@angular/common/http";
import { SharedModule } from './shared/shared.module';

const isIE = window.navigator.userAgent.indexOf('MSIE ') > -1 || window.navigator.userAgent.indexOf('Trident/') > -1;

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
    SharedModule,
    MsalModule.forRoot({
      auth: {
        clientId: '<client ID>', // This is your client ID
        authority: 'https://login.microsoftonline.com/<tenant id>', // This is your tenant id
        redirectUri: 'http://localhost:4200/'// This is your redirect URI
      },
      cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: isIE, // set to true for IE 11
      },
    }, {
      popUp: !isIE,
      consentScopes: [
        'user.read',
        'openid',
        'api://<clientid>/test'
      ],
      unprotectedResources: [],
      protectedResourceMap: [
        ['https://graph.microsoft.com/v1.0/me', ['user.read']],
        ['https://graph.microsoft.com/v1.0/me/drives', ['user.read']],
        ['http://localhost:3000/test', ['api://<clientid>/test']],
      ],
      extraQueryParameters: {}
    }),


  ],
  providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
  }
  ],
  bootstrap: [AppComponent],
  
})
export class AppModule { }
```

I have hosted an express webservice in localhost:3000 ( one of the protectedResourceMap that I mentioned in the MSAL configuration in the app.module.ts). The webservice uses Azure AD passport to validate the Bearer token.

Is there a way to write a unit test case in angular where I can call the azure protected service (http://localhost:3000/test) and check the response ?

**Comment by jmckennon** [comment]
Yes, there are many ways to do something like this. I would recommend either of the following:

1. Unit test the msal functionality by mocking the response using a library like [Sinon](https://sinonjs.org/).
2. E2E/Integration test the entire app using a library like [Puppeteer](https://github.com/puppeteer/puppeteer).

Since everytime you make a request to the server to get a new access token, the actual contents of some of the fields that come back are totally unpredictable by nature. If unit testing, you'll need to account for those fields based on the written test and either mock them or not check against them. Certain things will stay consistent and you will be able to check some of those by looking in `localStorage`. You can see some examples of mocking out certain function calls in our [angular sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-samples/angular8-sample-app/src/app/app.component.spec.ts).
