### ISSUE TITLE
msal don't work if B2C susi policy initiated manually

### ISSUE THREAD

**Issue by ed-ilyin** [AzureAD/microsoft-authentication-library-for-js#229]
Steps to reproduce:
1. Open b2c susi policy manually by going in browser to url like the following: `https://login.microsoftonline.com/te/mytenant.onmicrosoft.com/b2c_1a_signup_signin/oauth2/v2.0/authorize?response_type=id_token&scope=https%3A%2F%2Fmytenant.onmicrosoft.com%2Fapi%2Fread%20openid%20profile&client_id=client-guid&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&state=8bf581a4-a581-4347-8e20-f8dcb532a6e6&nonce=f0b68acb-35f8-4cc6-9bf5-1554c91ed623&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=0.1.3&brand=mybrand&client-request-id=12e14a79-5261-43e0-a7c5-3642ef0a3ec1&prompt=select_account&response_mode=fragment`
2. sign in
3. browser is redirected to SPA: `http://localhost:8080/#state=8bf581a4-a581-4347-8e20-f8dcb532a6e6&client_info=eyJ1aWQiOiI1MDk2MWQzMi0wY2FkLTQyOTMtYmYwNS1mNTI5MjY3M2NjZGMtYjJjXzFhX3NpZ251cF9zaWduaW4iLCJ1dGlkIjoiNjJhMGM5MzItMTgyMC00YzM4LTg3YTQtOWE5YWIyYzRjMmZhIn0&id_token=eyJ0eXAic...`
4. msal redirects browser to `http://localhost:8080/`
5. `msalApp.getUser()` **unexpectedly** returns **null** :(

I expect to `msalApp.getUser()` return signed in user object.

If I use `msalApp.loginRedirect`, then `msalApp.getUser()` return correct user object

**Comment by rohitnarula7176** [comment]
@ed-ilyin This is by design. Msal saves parameters like state and nonce when you call loginRedirect in the browser storage and it then matches the parameters in the response with the ones saved in the storage. If you make the authorization request manually, no such parameters will be saved and Msal must not process the response for security reasons. In this case , user object will be returned as null.
