### ISSUE TITLE
Error handling and retry policies for silent calls.

### ISSUE THREAD

**Issue by rhnsharma999** [AzureAD/microsoft-authentication-library-for-js#2324]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Sorry if this has been asked earlier. 

So i wanted to know what all errors fall into the case of a retry-able error (500s or any similar ones) or an error which can be retried after some time (eg. 429s) for silent calls such `acquireTokenSilent` or `ssoSilent`. 
Is there a recommended way of dealing with these errors such as 429s which may require a back-off time. 
I am assuming these are not already retried by default. 

Is there a specific documentation for error handling in general? I could see some error handling [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-handling-exceptions?tabs=javascript) but not a lot of details were present on the scenarios other than `InteractionRequiredAuthError`.

**Comment by jmckennon** [comment]
We have some [documentation in the repo on this topic](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Throttling.md).

The cases that cause a back-off are:
* 429 and 5xx statuses
* Response contains Retry-After header _without_ a 2xx status
* `InteractionRequiredError` on the response

The default is that a call will be locked out for 60 seconds, but the server can specify various amounts of time. Interactive calls will bypass this and also alleviate the lockout if successful. They are also not retried by default. The idea is that you should always be able to alleviate the problem rather than just wait for the timeout to end.

The error and timing information is stored in a [ThrottlingEntity object](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/cache/entities/ThrottlingEntity.ts) as a value in local storage.

The error currently gets exposed as a `ServerError`, though there was some discussion about making a `ThrottlingError` type that exposes this more explicitly with the time the call is locked out.

This is pretty deep information, so let me know if things aren't clear or you have more questions.

**Comment by rhnsharma999** [comment]
Thanks Jake for the info.

 So if I understand correctly (feel free to correct me otherwise)
- For 5xx or 429, we'll get `ServerError` thrown when making a silent call. 
- This can be fixed (or rather retried) using an interactive call for the same request?
- Are there any specific error codes with respect to the `ServerError` object received in the error block for which an interactive call should be made? 
- I believe `ServerError` is currently not exported from `@azure/msal-browser`. I am assuming that might be because `ServerError` acts as a base class for other errors that we see.

**Comment by jmckennon** [comment]
> For 5xx or 429, we'll get ServerError thrown when making a silent call.

5xx will be `ServerError`, 429 is just a generic backoff request that the library respects. There could be any errors associated with it as well.

>This can be fixed (or rather retried) using an interactive call for the same request?

Yes, if you make an interactive call it bypasses any throttles set--and a successful interactive call will alleviate that throttle.

> Are there any specific error codes with respect to the ServerError object received in the error block for which an interactive call should be made?

The main one is `InteractionRequiredAuthError` (different from `ServerError`, to be clear). It's up the the app developer to decide how they handle particular errors, but the most common cases are to always fall back to an interactive call if a silent calls fails, or to fall back to an interactive call if a silent call fails with `InteractionRequiredAuthError`.

>I believe ServerError is currently not exported from @azure/msal-browser. I am assuming that might be because ServerError acts as a base class for other errors that we see.

Yes, exactly, it is exported from `msal-common` which `msal-browser` consumes.
