### ISSUE TITLE
Does MSAL.js 2.0 require third party cookies to be enabled?

### ISSUE THREAD

**Issue by m-mattu** [AzureAD/microsoft-authentication-library-for-js#2334]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.3.4`
- [ ] `@azure/msal-browser@2.2.2`

## Description
We are currently using msal@1.3.4 library in a production app and it requires third party cookies to be enabled to work on all the various devices. We plan to migrate to @azure/msal-browser, since PKCE is a much better option. However the one question we have is whether we will still require third party cookies to be enabled in the browser when we migrate to @azure/msal-browser?

**Comment by jmckennon** [comment]
Taken from the [Microsoft docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas):
> Many browsers today are blocking third-party cookies - cookies on requests to domains that are not the same as the one showing in the browser bar. This breaks the implicit flow and requires new authentication patterns to successfully sign in users. **In the Microsoft identity platform, we use the authorization flow with PKCE and refresh tokens to keep users signed in when third-party cookies are blocked.**

`msal-browser@2.x` uses the auth-code flow with PKCE, so no, it does not require third-party cookies to be enabled.

**Comment by pkanher617** [comment]
@m-mattu To be more clear, third party cookies are required in order to complete silent authentication. Because @azure/msal-browser uses the auth code flow, it can use the refresh token instead of cookies to perform this, with the caveat that the refresh token is limited to a 24 hour lifetime. You can read more about it [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md).
