### ISSUE TITLE
How to clear an access token?

### ISSUE THREAD

**Issue by jeremyc11** [AzureAD/microsoft-authentication-library-for-js#2447]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `@azure/msal-angular@1.x.x`

## Description
I'm using MSAL Angular. When a user is logging out, it is redirect to a logout page. I don't want to use the logOut function because it causes to log out the user from other sites that are using the Microsoft login. So, when redirecting the user to the logout page, I want to clear the access token in order to not been used after that.
So my question is how to clear an access token or how to invalidate it?

**Comment by sameerag** [comment]
@jeremyc11 We do not invalidate `access tokens`. The only work around for you is to clear your cache accessing`window.localStorage() or window.sessionStorage()`. Please note that doing this would mean, if you call `acquireTokenSilent()` after the cache clearance, you would get a new token since the AAD session is still active.

**Comment by jeremyc11** [comment]
Thanks it worked me.
