### ISSUE TITLE
sample react-sample-app problem in EDGE

### ISSUE THREAD

**Issue by francescodelorenzi** [AzureAD/microsoft-authentication-library-for-js#2465]
When I try to run the example in Edge and click on "sign in"

It shows the error message:

> "Error: Error opening popup window. This can happen if you are using IE or if popups are blocked in the browser."

even if the pop up blocker is deactivated. 
And of course the flow doesn't work and it redirects to the login page 
Any suggestion?

**Comment by francescodelorenzi** [comment]
Adding the version of Edge on Windows 10

Microsoft Edge 44.17763.831.0
Microsoft EdgeHTML 18.17763

**Comment by jasonnutter** [comment]
@francescodelorenzi Sorry for the delay in responding. 

This is not expected, as popups that are opened as the direct result of user interaction should be blocked by default, especially if popups are explicitly enabled. Does this happen in other browsers? 

> And of course the flow doesn't work and it redirects to the login page

The react-sample-app won't automatically call redirect if there is an error (it should display the error message), can you clarify what is triggering this?

Regardless, your users can block popups, which would prevent loginPopup or acquireTokenPopup from working, so it is recommend to invoked loginRedirect/acquireTokenRedirect if the popup methods throw an error due to popups being blocked.
