### ISSUE TITLE
PublicClientApplication->getAllAccounts() not considering config.auth.authority

### ISSUE THREAD

**Issue by daniel-seitz** [AzureAD/microsoft-authentication-library-for-js#2509]
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x ] `@azure/msal-browser@2.4.0` and  `@azure/msal-common@1.6.2`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
We create our authApp-instance and provide the tenant (config.auth.authority) 
Upon browser refresh we use getAllAccounts() and then aquireTokenSilent() in order to figure out whether the user is already logged in.
An issue come up because **we have different Azure Active Directories** and users sometimes are logged into more than one (i.e. when working with different apps). 

Then getAllAccounts() **returns more than one account** because it doesn't consider the tentant.

Short sample implementation:

```
const config = {
    ....
    auth: {
        ....
        authority: TENANT1_ID,
    }
};

const authApp = new PublicClientApplication(config);

authApp.handleRedirectPromise().then(result => {
    if(!result) {
        const accounts = this.authApp.getAllAccounts();

        if(accounts.length === 0) {
            // not logged in
            return;
        } else if (accounts.length > 1) {
            // TOO MANY, THE ERROR HAPPENS HERE
            return; // :(
        }

        // there is an account -> try to get a token
        const account = accounts[0];
        const scopes = []; // could be something else..

        const authResult = await authApp.acquireTokenSilent({ scopes, account });

        // etc.
    }
})
```

## Expected
getAllAccounts() should just return the accounts that the PublicClientApplication is configured with, and not unrelated ones as well.

Please let me know if you need more info or if I can help with anything else.

Regards, 
Daniel

**Comment by sameerag** [comment]
@daniel-seitz The definition of an `account` is tied up as much as with the `tenantId` as with the `user`. `msal` should treat a user logged in two different directories as two different `accounts`. In your case, since you know the `tenantId`s in advance and get all the accounts with `getAllAccounts()`, can you try filtering based on the `tenantId`?

We are working on a feature that adds `getAccountsByTenantId()` (cc @pkanher617) and that would be a better suited API. Currently it is work in progress though.

**Comment by daniel-seitz** [comment]
@sameerag thank you for your quick and to the point answer. 

This is what I thought of as well, at the same time I would argue that when I new up the object with a certain config, I would expect that this object adheres to the config and wouldn't get things from outside of that boundary.

I don't know if there is a use-case to really get All accounts, from my perspective - yes - getAllAccounts seems to be intended to get ALL accounts and changing this part might bring unwanted sideeffects. 

At the same time I think it would be a more suitable design to just retrieve the one that's given in the config (I assume the clientId indeed is being respected). That would feel cleaner and more what I'd expect from an object oriented perspective.

For now, I will implement the filter as you mentioned. Please let me know if you decide to change the behaviour.
This issue can be closed afterwards.

Regards,
Daniel

**Comment by sameerag** [comment]
@daniel-seitz `getAllAccounts()` is intended to serve the purpose of literally getting all the accounts in the cache at a given point of time.`msal-node` and `msal-browser` currently support multiple accounts to be logged in, hence we do not intend to change this behavior. What you are asking seems to be rather `getCurrentAccount()` which is the application context of the `msal-browser` at the time of execution, and may be that can be implemented but I am not clear if it can be done simply. I will update on this thread once I understand the implementation cost.

cc @pkanher617

**Comment by daniel-seitz** [comment]
@sameerag no worries.

I am implementing the workaround - if I may call it like that - since this already serves the purpose.
Hence, it would be a welcomed feature, at the same time: no hurry in implementing this.

Thank you.

**Comment by sameerag** [comment]
@daniel-seitz The tenant profiles feature will be able to help you to `getAccountByTenantId` and that is in progress. Since you can always track what your current account is, `getAccountByHomeId` or `getAccountByLocalId` may also serve your purpose. 

Since an `Account` is tied up with `IdToken` and not configuration and we do not manage a `currentAccount`, and we do not plan to at this point.

Closing this issue as tenant profiles is already tracked as a feature. Do let me know if you have any concerns and we can revisit as needed.
