### ISSUE TITLE
MSAL double redirect

### ISSUE THREAD

**Issue by zhangxAmtrak** [AzureAD/microsoft-authentication-library-for-js#2514]
We are implementing company web site to integrate with Azure B2C. The site (SPA application) has over 100 pages and potentially grows.  User can login from every page from a header link.  This makes impossible to configure all redirect URIs in B2C.  We are using following config for MSAL config but this setting potential causes double redirects when B2C sends token back after successful authentication.  How can we dynamically set redirect uri when page is loaded and MSAL config is initialized?

redirectUri: "http://abc.com/home",
navigateToLoginRequestUrl: true

**Comment by sameerag** [comment]
@zhangxAmtrak Can you please fill the issue template, especially the library version details?

**Comment by zhangxAmtrak** [comment]
Sorry, where is the template?  We include https://alcdn.msauth.net/lib/1.3.2/js/msal.js.  So I assume it's v1.3.2

**Comment by pierreh-korbicom** [comment]
@zhangxAmtrak The MSAL library can issue a redirect when it is loaded by the browser. If `navigateToLoginRequestUrl` is set to `true`, there will be a redirect to the same path as when `loginRedirect` was called. That is, if you configure AD with a redirect URI of `http://abc.com` (although it's recommended to limit it to https) and a user is on `http://abc.com/home` when `loginRedirect` is called with `navigateToLoginRequestUrl` set to `true`, the user will be redirected by MSAL to `http://abc.com/home` as part of the MSAL boot up process.

Note that a new field was added to the `AuthenticationParameters` class around MSAL v1.3.1 - if specified, `redirectStartPage` will redirect the user to the specified URL rather than the URL from where `loginRedirect` was called.

The same is true for any path on `http://abc.com`. So, your AD configuration only needs 1 URI - `http://abc.com`

**Comment by zhangxAmtrak** [comment]
Does it mean double redirect can't be avoided?  B2C redirects to http://abc.com, then browser further redirect to http://abc.com/home?

**Comment by pierreh-korbicom** [comment]
@zhangxAmtrak Effectively it cannot be avoided, because the Azure B2C (or whichever auth provider you're using) needs to redirect the user's browser to your SPA (first redirect) and then the SPA (either directly or via MSAL as described above) needs to redirect the user to the correct route within the SPA (second redirect).

This, however, is not an MSAL/Azure AD restriction, but a restriction in OAuth for security purposes. See here https://techcommunity.microsoft.com/t5/azure-active-directory-identity/azure-ad-app-with-wild-card-reply-urls/m-p/171236

**Comment by DEEPTI-18** [comment]
When we are trying to do enroll/Signup in one of the scenario in our application, we are getting jwt token correctly. And then we need to call api so for that we are calling below function to get the access token but somehow getting unsual errors in console due to which it failed to renew the token and redirected back to b2c-url.

 function getTokenRedirect(request) {
        return myMSALObj.acquireTokenSilent(request)
            .then((response) => {
                if (response.accessToken) {
                    accessToken = response.accessToken;
                    // logMessage("Request made to Web API:");

                    console.log("accessToken = " + accessToken);
                    if (accessToken) {
                        try {
                            apiCall(myMSALObj, response);
                        } catch (err) {
                            console.log(err);
                        }
                    }
                }
            }).catch(error => {
                console.log("Silent token acquisition fails. Acquiring token using redirect");
                console.log(error);
                // fallback to interaction when silent call fails
                return myMSALObj.acquireTokenRedirect(request);
            });
    }


Cdn url  is included in our application for this functionality - https://alcdn.msauth.net/lib/1.3.2/js/msal.js

We are getting below error is console.
**Error1** - Refused to display 'https://tenant.com/policy-name/oauth2/v2.0/authorize?response_type=token&scope=https%3A%2F%2Ftenant.com%2Fapi%2Fdemo.read%20openid%20profile&client_id=xyz&redirect_uri=https%3A%2F%2Fxyz.com%2Fprogress.html&state=xyz&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=xyz&client-request-id=xyz&prompt=none&response_mode=fragment' in a frame because it set 'X-Frame-Options' to 'deny'.

**Error2** - Silent token acquisition fails. Acquiring token using redirect

**Error3**- ClientAuthError: Token renewal operation failed due to timeout.
    at ClientAuthError.AuthError [as constructor] (https://alcdn.msauth.net/lib/1.3.2/js/msal.js:1529:28)
    at new ClientAuthError (https://alcdn.msauth.net/lib/1.3.2/js/msal.js:1414:28)
    at Function.ClientAuthError.createTokenRenewalTimeoutError (https://alcdn.msauth.net/lib/1.3.2/js/msal.js:1440:16)
    at https://alcdn.msauth.net/lib/1.3.2/js/msal.js:4676:62

Can someone please suggest what is going wrong here ?

**Comment by tnorling** [comment]
Closing as the question has been answered. As stated above, any url that the B2C service redirects to needs to be registered in the portal. If you want a single redirect you should ensure that all your redirectUris are registered and set `navigateToLoginRequestUrl: false`. If you want the user to end on a page that is **not** registered in the portal, 2 redirects are required.
