### ISSUE TITLE
Client Credentials Flow for SPA?

### ISSUE THREAD

**Issue by sam-wheat** [AzureAD/microsoft-authentication-library-for-js#2534]
I have an API I would like to secure and also allow my SPA to call.  

I want to call this API regardless of if the user is logged in or not.  I want my app to be the user.  This is pretty much like machine-to-machine auth.  Is this possible? If so, can you point me to an example showing a SPA where there is no user to input credentials?

I have seen the documentation for [Authorization Code Flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow) however I believe this requires a user to input credentials (perhaps I am reading it wrong?).

**Comment by jasonnutter** [comment]
@sam-wheat This scenario is not supported by MSAL.js, as the Implicit Flow and the Auth Code Flow require user consent and context. There are confidential client flows supported in MSAL Node, however, confidential client flows require secrets such as client secrets or certificates, but those will not work in SPAs because browsers cannot securely keep client secrets.
