### ISSUE TITLE
B2C Redirect URI

### ISSUE THREAD

**Issue by zhangxAmtrak** [AzureAD/microsoft-authentication-library-for-js#2544]
#2113 
 Library
- [ ] `msal@1.3.2` 

## Description
Please provide your question here, including as much relevant details as possible.

"How do I resolve double redirect?"

We are implementing Azure B2C for company consumer site.  The site is implemented as SPA angular application and has header "SIGN IN" button.  The header is on every page that makes impossible to configure redirect uri from B2C portal.  We had to use code below to redirect page to destination where the login is triggered.  But that caused double redirect on client browser.  Is there anyway we can avoid double redirect?  Any suggestion? 

redirectUri: "http://localhost:6420/",
navigateToLoginRequestUrl: true

**Comment by jasonnutter** [comment]
Can you please clarify what you mean by "double redirect"? By design, when `navigateToLoginRequestUrl` is enabled, the browser will be redirected from B2C to your redirect URI (`http://localhost:6420/`), and then again from your redirect URI to the page the user was originally on when they triggered login.

Also, please update to the latest version of msal (1.4.3), and let us know if this is still an issue.
