### ISSUE TITLE
acquireTokenSilent is not working , specifically for IE 11.1518.17763.0

### ISSUE THREAD

**Issue by rohitsharma91** [AzureAD/microsoft-authentication-library-for-js#2580]
### Library
- [ ] "@azure/msal-angular": "^1.0.0"
- [ ] "msal": "^1.3.0"
.

### Framework
Angular 9

## Description
Implemented MSAL login in Angular application and it's working fine with chrome browser but creating problem for IE 11.1518, when I try to login using IE then it gives 'ClientAuthError: Token calls are blocked in hidden iframes'error.

By going through other posts , I am clear about the cause and also tried some of the solution , like 'Provide redirect url as some blank HTML page' , but nothing seems to work.

## Error Message
![error_msal](https://user-images.githubusercontent.com/74247439/98679524-2cd9e780-2386-11eb-94af-8d40a134143e.png)

the above error message appears all the time.

## Security
Yes

## Regression
It works in Chrome but never worked for IE 11.1518

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
Open IE browser and try Azure login

## Expected behavior
Login functionality should work with IE browser too.

## Browsers/Environment
- [ ] IE 11.1518.17763.0

**Comment by jasonnutter** [comment]
@rohitsharma91 This error happens when your app is loaded in iframe, the url contains a hash response from AAD, and the apps tries to invoke acquireTokenSilent (usually this error is thrown when the page used for the redirect URI calls acquireTokenSilent on page load). In an app using MSAL Angular, this can happen if on page load the redirect page makes an http request to a url that requires an access token (resulting in the MSAL Interceptor invoking acquireTokenSilent). If this is the case, your app should not make said http request when the page is loaded in an iframe.

Also, can you please include your configuration for MSAL Angular?

**Comment by kthimmai** [comment]
@jasonnutter - we tried redirecting to a blank html page only for acquireTokenSilent call but it is not working in IE and we see the redirect call still goes to app page loading.

Below is the MSAL configuration -

MsalModule.forRoot({
     auth: {
       clientId: environment.azClient,
       authority: environment.azAuthority,
       redirectUri: http://localhost:4200
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
  },
  {
    popUp: !isIE,
    consentScopes: [
      'user.read',
      'openid',
      'profile',
    ],
    unprotectedResources: [],
    protectedResourceMap: [
      [environment.azGraphEndpoint, ['user.read']]
    ],
    extraQueryParameters: {}
  })

**Comment by jasonnutter** [comment]
@rohitsharma91 What is triggering acquireTokenSilent to be called when your app is in an iframe? Whatever it is, can you disable it when your app is in an iframe? That should mitigate this error.

**Comment by kthimmai** [comment]
@jasonnutter - we are calling acquireTokenSilent on app page initial load so we can get hold of access token and pass this token to downstream service. What I understand is whenever acruireTokenSilect is called Azure is redirecting back to the app home page and that redirect is handled in iframe(is my understanding correct?). We are somehow not able to block this call in iframe in angular app(though tried redirecting to blank page)

Additionally we are seeing below MSAL logs, can you tell us what these errors meant for

MSAL Logging:  Fri, 13 Nov 2020 07:05:25 GMT:6e57faac-19fd-483d-971e-1b511f7799f2-1.3.2-**Error monitorWindowForHash unable to find hash in url, timing out**
MSAL Logging:  Fri, 13 Nov 2020 07:05:26 GMT:6e57faac-19fd-483d-971e-1b511f7799f2-1.3.2-**Error Error when acquiring token for scopes: api://XXXXXXXXXXXX/AccessTokenRead ClientAuthError: Token renewal operation failed due to timeout.**

**Comment by kthimmai** [comment]
@jasonnutter - we implemented a solution as suggested in below issue thread and now app is working fine in IE

https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1728

**Comment by jasonnutter** [comment]
@kthimmai Glad to hear, thanks for the update.
