### ISSUE TITLE
Feature Request: Simple Auth Status API

### ISSUE THREAD

**Issue by MarkHerhold** [AzureAD/microsoft-authentication-library-for-js#263]
Hi MSAL team,
I'm requesting features for two functions to make MSAL users' lives easer.

### `isUserAuthenticated(): Promise<boolean>`

This function would return a promise that resolves to a single boolean value if the following conditions are met:
* user is logged in
* MSAL has an access token available (`acquireTokenSilent()` will succeed)
* access token is not expired
* we have user information (`getUser()` will return a non-null value)

### `authComplete(): Promise<void>`

This function would return a promise that resolves when MSAL is done initializing, meaning that the above conditions for `isUserAuthenticated()` are met. The concept behind this is that developers would have a **single** function to rely on to determine when MSAL is done acquiring tokens, token refreshes, etc...

Conceptually, I would use this function in my login component/page to check to see if MSAL is is completely ready. Ideally, this would be called after a login redirect flow and after page refreshes, making the user sit at a loading screen until the promise resolves. This would potentially solve issue  #257.

**Comment by rohitnarula7176** [comment]
@MarkHerhold Due to the nature of the implicit flow, it is not possible to return a promise for the login scenario. We receive all responses via a redirect response which forces a browser reload. In a case where we initialize a promise before redirecting the user, the promise will lose its state when page reloads. The current way to achieve this is to use loginRedirect but use loginPopup instead which returns a promise.
