### ISSUE TITLE
MSAL library state mismatch issue

### ISSUE THREAD

**Issue by zhangxAmtrak** [AzureAD/microsoft-authentication-library-for-js#2689]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

We are using below  version of msal library
https://alcdn.msauth.net/browser/2.6.1/js/msal-browser.js

## Description:

We are using msal OAuth2.0 + PKCE implementation for B2C integration with Angular SPA.  Our company has UI/UX design which you can see from here **https://beta-aemtest.amtrak.com/home.html**

On B2C login/enroll page, we want to allow user be able to flip between signin and signup. The problem is: if flip, the token that is sending back to our page is rejected due to state mismatch issue.

We want to know the options to resolve this issue.  Is there any way to catch state mismatch error?  What's the function we need to invoke if we have to implicitly re-send the request without prompting user to enter username/password

## Error Message:

state mismatched error is received 

## Security
- [ ] Is this issue security related?  Maybe

## Regression
- [ ] Did this behavior work before? No, this is our first implementation
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps

1. Go to https://beta-aemtest.amtrak.com/home.html
2. Click on "Join"
3. On B2C page, click on "Sign In" blue button
4. Login with test account 
5. On Amtrak home page, you will see user is not login and state mismatch error when inspect the browser error

## Browsers/Environment
 Chrome

**Comment by tnorling** [comment]
@zhangxAmtrak This is happening because we do not support switching policies mid-stream. We recommend you resolve this in one of 2 ways: 
1. Use a single policy for both sign up and sign in
2. When a user changes the policy, first redirect back to your app and have your app call `loginRedirect` again with the new policy

**Comment by kalyansury** [comment]
@tnorling After the user lands on the home page with the state mismatch error, a subsequent user action for login, is handled by the msal plugin and it logs the user in. What is the expected behavior for msal here? If this the current flow of msal to login the user on the user action is acceptable, then I assume handling the state_mismatch error to retry the msal login action is good too and a future fix from msal to allow retry in this case can be expected too?

**Comment by tnorling** [comment]
@kalyansury Not sure I understand what you're asking. The issue here is that msal makes a request out to policy "signin" and receives a response from policy "sign-up", resulting in a mismatch. To clarify, it's fine to catch the state mismatch error and make a new login call to the other policy but you should not try to process the response from the first login call. A cleaner solution would be: app calls policy "signin" -> user selects policy "sign-up" -> custom policy returns to app with a meaningful error -> app catches this error and calls policy "sign-up".

As long as the policy that msal calls is the same as the policy that issues the token there should not be an issue.
