### ISSUE TITLE
 error TS2307: Cannot find module 'msal-electron-poc' #1217 

### ISSUE THREAD

**Issue by Ladvace** [AzureAD/microsoft-authentication-library-for-js#2701]
I tried running `msal-electron-sample-app sample` but I got the same error of this issue: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1217.

As suggested in the issue above, I run npm install in the root folder, but I still get the error.

**Comment by hectormmg** [comment]
@Ladvace hi! The `msal-electron-sample-app` is a little outdated. As mentioned in the sample's README, `msal-electron-poc` is just a proof of concept and isn't really supported. For now, we suggest using our `msal-node` library, which is in public preview, for Electron apps. Here's an up-to-date sample using `msal-node with Electron which I hope will help you!

https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/standalone-samples/ElectronTestApp

**Comment by Ladvace** [comment]
thanks, what is the difference between `msal `and `msal-node`?

**Comment by hectormmg** [comment]
@Ladvace so, `msal` (1.x), or `msal-core` as the package is called is our v1 MSAL for JavaScript. This first implementation uses the OAuth 2.0 Implicit Grant flow to acquire tokens. That library is optimized for Single Page Applications that use JavaScript on the browser.

However, since OAuth 2.0 suggested moving SPAs from the Implicit Grant to the Auth Code grant, and JavaScript is also available server-side with environments like Node.js, we created a new set of libraries to cover both browser-based single-page apps (`msal-browser`) as well as backend web and CLI applications (`msal-node`). 
You can read more about the different libraries we have in our base [README](https://github.com/AzureAD/microsoft-authentication-library-for-js).

Here's the link to [MSAL for Node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node) in case you need more information.

**Comment by Ladvace** [comment]
I will give it a look, I was using "msal" but i have some problem going on
