### ISSUE TITLE
Authenticate with XBL using msal-node

### ISSUE THREAD

**Issue by Ladvace** [AzureAD/microsoft-authentication-library-for-js#2767]
I don't know if it's OT, If it is i'm going to close the issue, I'm using msal-node and i'm trying to authenticate in xboxlive following [this](https://wiki.vg/Microsoft_Authentication_Scheme#Microsoft_OAuth_Flow).  the problem is that when I try to authenticate I get the **error 400** (Bad Request) and I don't understand why.

I'm using your electro [sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/standalone-samples/ElectronTestApp) and to get the token I'm using the `.getProfileToken()` method. I thought it should be the wrong token but actually I'm not sure.

## Library
- [x] `@azure/msal-node@1.x.x`

` 
await axios
        .post(
            "https://user.auth.xboxlive.com/user/authenticate",
            {
                Properties: {
                    AuthMethod: "RPS",
                    SiteName: "user.auth.xboxlive.com",
                    RpsTicket: token, // the token i get from msal
                },
                RelyingParty: "http://auth.xboxlive.com",
                TokenType: "JWT",
            },
            {
                headers: {
                    "Content-Type": "application/json",
                    Accept: "application/json",
                },
            }
        )
        .then((x) => console.log("success", x))
        .catch((e) => console.error("error", e));
`

**Comment by tnorling** [comment]
@Ladvace Can you clarify, are you getting the 400 error when you try to obtain an access token with msal or is it when you try to make the request to the XBL endpoint with the access token?

**Comment by Ladvace** [comment]
when i try to make the request to XBL (with the token I got from msal)

**Comment by tnorling** [comment]
@Ladvace In that case, this is outside the scope of msal. I did find some [official documentation](https://docs.microsoft.com/en-us/gaming/xbox-live/api-ref/xbox-live-rest/additional/httpstandardheaders) on the XBL REST API. Looks like they expect a `x-xbl-contract-version` header which I do not see in your request so that might be worth a shot. It also looks like there's a couple samples linked at the bottom of the wiki you shared in the original post, that may also provide some insight. Not being familiar with the xbox live API myself, unfortunately that's the best I can offer.

**Comment by Ladvace** [comment]
Thanks anyway, i didn't find so much information too but I Will give a Better look

**Comment by tnorling** [comment]
Closing as this is not an issue with msal. Feel free to open a new issue if you have additional questions about msal
