### ISSUE TITLE
Possible bug with msal 1.4.4 not seen in msal 1.3.1

### ISSUE THREAD

**Issue by JeffFisher-sitekit** [AzureAD/microsoft-authentication-library-for-js#2787]
Update to issue 2618 (closed) - we see this issue with msal 1.4.4, and there is no issue when using msal 1.3.1. In both cases running angular-msal 1.1.2.

It's possibly a bug with msal 1.4.4.

[https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2618](url)

**Comment by tnorling** [comment]
@JeffFisher-sitekit As stated in the other thread, this is potentially a bug on the B2C service. Can you please open a ticket with them to understand why the `uid` parameter does not contain a userId? A change was made in 1.4.0 to remove the policy name from the `uid` in order to support multiple policies, so this is why it **appears** to work for you in 1.3.1 but this is coincidental and not how it's intended to work. [Here's](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options) the link to B2C support once again.
