### ISSUE TITLE
Handling multiple accounts

### ISSUE THREAD

**Issue by dfibuch** [AzureAD/microsoft-authentication-library-for-js#2805]
## Library

- [x] `@azure/msal-browser@2.5.1`

## Description
I'm trying to track down an issue some of my users are having where I can see an error is thrown during `acquireTokenSilent` but all it gives me is `TypeError: Failed to fetch`.

The user journey seems to be:

- Hit site and refresh token is expired (over 24hrs since last visit) so `acquireTokenSilent` fails with `AADB2C90077` error and this is handled with a `acquireTokenRedirect`
- User signs in and goes back to the site where `acquireTokenSilent` is called again to get a token for an API request but this time it fails with the `Failed to fetch` error.

Now the interesting part is I can see that the code responsible for getting the account to use in these requests has detected that there are multiple accounts when `msalApp.getAllAccounts()` is called, in which case I return the first one from the array (not sure this is OK to do...).

My problem however is that I do not know you even go about having multiple accounts in the `msalApp` so I'm struggling to recreate the issue.

## Question

How do you get the `PublicClientApplication` to have multiple accounts stored in it and is there some example of how to actually handle this scenario properly? All code samples I've seen just have a comment `Add code to handle multiple accounts`.

**Comment by tnorling** [comment]
@dfibuch In order to have multiple accounts returned from `getAllAccounts` a user would need to choose a different account than the one they had originally signed in when you call one of the interactive methods, likely when your app calls `acquireTokenRedirect`. If you're having trouble getting to the account selection screen you can include `prompt: "login"` or `prompt: "select_account"` in your request object passed to `acquireTokenRedirect`

As for handling multiple account scenarios, that's really up to the app developer. There's no single right way to handle it and it just depends on what you want your app to support and how you want to make that happen, which is why we don't provide an example in our samples. Some people opt to support only a single account in which case they keep track of the account info and use `getAccountByHomeId` or `getAccountByLocalId` instead of `getAllAccounts`, others do need to support multiple accounts and have their own requirements around that.

**Comment by dfibuch** [comment]
@tnorling Thanks for that, this has made a bit more sense now. I'll keep investigating. It's probably not related but thought worth exploring as I can't really explain why we get this `Failed to fetch` error.
