### ISSUE TITLE
How to retrieve B2C users and update them?

### ISSUE THREAD

**Issue by varghesep** [AzureAD/microsoft-authentication-library-for-js#2817]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [X] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

How to retrieve the B2C users and update them?

I'm currently using **msal-angular** to login and logout from a B2C directory which is working fine. I also have 25 users in the directory. I want to retrieve the users and update their information in the angular application.

My questions are:

1. Can I retrieve the B2C users other than the user that I logged in and update using **msal-angular**?
2. If I can't, should I follow the instructions on this page [Get access without a user](https://docs.microsoft.com/en-us/graph/auth-v2-service) to retrieve the users? This will force me to use **msal-angular** to login and **JavaScript SDK** to retrieve the users and update them.
3. What configuration that I need to have if I want to have 5 groups and 25 users in each group, so the Group Administrator can login and update the users under his group?

## Source

- [ ] Internal (Microsoft)
- [X] Customer request

**Comment by jo-arroyo** [comment]
@nickgmicrosoft Can you please address this?

**Comment by nickgmicrosoft** [comment]
Hi varghesep,

Microsoft Graph does not recognize tokens issued by Azure AD B2C, so at this time it's not possible for a user to update other users using delegated Graph permissions. Instead, you can use client credentials so that the application can perform the Graph operations to update users itself. [This](https://docs.microsoft.com/en-us/azure/active-directory-b2c/manage-user-accounts-graph-api) documentation may be useful.

@jmprieur on implications for ms-angular vs JS SDK.

**Comment by jmprieur** [comment]
@derisen @hamiltonha

**Comment by derisen** [comment]
@varghesep this corresponds to user management scenarios outlined [here](https://docs.microsoft.com/azure/active-directory-b2c/manage-user-accounts-graph-api). In short you'd have to use application permissions instead of delegated permissions (i.e. [client credentials grant flow](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow)). Since that requires a confidential client application, you won't be able to do it via msal-angular.

We had it in backlog to create a sample doing that using [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node) but it's not out yet. We'll hasten the effort to put it out soon. For reference, there is a [sample](https://github.com/Azure-Samples/ms-identity-dotnetcore-b2c-account-management) in .NET Core framework.

**Comment by derisen** [comment]
> @varghesep this corresponds to user management scenarios outlined [here](https://docs.microsoft.com/azure/active-directory-b2c/manage-user-accounts-graph-api). In short you'd have to use application permissions instead of delegated permissions (i.e. [client credentials grant flow](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow)). Since that requires a confidential client application, you won't be able to do it via msal-angular.
> 
> We had it in backlog to create a sample doing that using [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node) but it's not out yet. We'll hasten the effort to put it out soon. For reference, there is a similar [sample](https://github.com/Azure-Samples/ms-identity-dotnetcore-b2c-account-management) in .NET Core framework.

@varghesep apologies, this guidance is misleading. You **can** manage your B2C users with `msal-angular`. Here's how:

**Requirements:**
- An admin account (global admin, application admin or user admin). You will sing-in with this account. (Graph API will not allow access to less privileged accounts)
- Delegated permissions for `User.ReadWrite.All` (possibly others depending on the user operation).
- Familiarity with [this](https://docs.microsoft.com/azure/active-directory-b2c/microsoft-graph-get-started?tabs=app-reg-ga) and [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/working-with-b2c.md) document.

**1st approach:**
If you would like to use your existing B2C app registration, simply replace the B2C `authority` string (that looks like this: `https://<your_tenant_name>.b2clogin.com/<your_tenant_name>.onmicrosoft.com/<policy-name>`) with AAD `authority` string in your `msal-angular` configuration. This will be `https://login.microsoftonline.com/common`. You can see this string via the **Endpoints** tab in your B2C **App Registration** -> **Overview** blade.

Because this is normally a B2C app that signs in users with **user-flows** , you cannot define delegated Graph permissions via the **Permissions** blade on App registration portal. Instead, you will use dynamic scopes i.e. you will define in the application what scopes to request. See below for a sample config.

```typescript

// in app.module.ts

export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: 'YOUR_CLIENT_ID',
      authority: https://login.microsoftonline.com/common', 
      redirectUri: 'http://localhost:4200',
      postLogoutRedirectUri: 'http://localhost:4200',
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set('https://graph.microsoft.com/v1.0/users', ['User.ReadWrite.All']);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap,
  };
}
```

**2nd approach:**

Simply create a new B2C application. However, instead of choosing **Accounts in any identity provider or organizational directory (for authenticating users with user flows)** for **supported user accounts**, choose **accounts in this organization only** (first option). This app registration is only for signing-in your admin users. This way, you can define the required scopes via the **Permissions** blade in your app registration. Then, grant **admin consent** to these scopes. Your angular configuration will look like this: 

```typescript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: 'YOUR_CLIENT_ID',
      authority: https://login.microsoftonline.com/<Your_Tenant_ID>,
      redirectUri: 'http://localhost:4200',
      postLogoutRedirectUri: 'http://localhost:4200',
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set('https://graph.microsoft.com/v1.0/users', ['https://graph.microsoft.com/.default']);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap,
  };
}
```

Let me know if this helps. The samples illustrating these approaches and the previously mentioned **client credentials** approach will be out shortly. I'll share the link then.

**Comment by varghesep** [comment]
The first approach with ```authority: 'https://login.microsoftonline.com/common'``` does not work.

I get the following error:

```ERROR Error: Uncaught (in promise): ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.
ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.
```

**Comment by derisen** [comment]
@varghesep that's strange, it looks like you are still using B2C authority -can you confirm that your browser cache is clean?

The sample is in review still, but you can take a look at it [here](https://github.com/Azure-Samples/ms-identity-b2c-javascript-nodejs-management/tree/derisen);
