### ISSUE TITLE
Securing API without triggering login redirect/popup

### ISSUE THREAD

**Issue by danich93** [AzureAD/microsoft-authentication-library-for-js#2920]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.9.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.0.0-alpha.3`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

I am new to MSAL and I have been playing with it a for a bit. I noticed that making an http request to a protected API prompts a login redirect/popup. From what I understand after looking at docs MsalInterceptor tries to acquire a token and then adds it to the http request. Is there a way to alter this behavior (without creating a custom interceptor) so that the http request to API will not trigger login prompt, but at the same time would still attach auth token along with the request (if the token has already been acquired)? Thanks.

**Comment by Ohmu93** [comment]
So I ended up just writing a custom interceptor based off the original MsalInterceptor. But it would have been nice if, as an option, it was possible to set interaction type for MsalInterceptorConfig to InteractionType.Silent so that it would just try to acquire a token silently and if it can't, either throw an error or pass the request without token to the api. But I guess its more of a feature request at this point.

**Comment by jo-arroyo** [comment]
@Ohmu93 At this point, the MsalInterceptor only triggers interaction if there is an error silently acquiring the token. We believe that this logic works best for most scenarios, but if it doesn't work for you, writing your own interceptor would be our recommendation for this use case.
