### ISSUE TITLE
MSAL Browser: ssoSilent should leverage cached auth state if possible

### ISSUE THREAD

**Issue by jasonnutter** [AzureAD/microsoft-authentication-library-for-js#2925]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Source

- [x] Internal (Microsoft)
- [ ] Customer request

## Description

Today, the `ssoSilent` API will always attempt to invoke a network request, regardless of current cache state. This means that a network request may be made when it is not necessary, which results in a needless perf penalty.

## Priority

Medium

## Acceptance Criteria

1. If the application has valid auth state in the cache (valid id token, refresh token), invoking ssoSilent should not result in a network request, by default.
2. Setting `forceRefresh` to `true` should result in a network request, like with `acquireTokenSilent`.

**Comment by zzzachzzz** [comment]
This may or may not be rooted in the same issue, but I've noticed the same behavior when using `acquireTokenSilent` with a B2C authority. In localStorage, there is no entry for a `credentialType` of `AccessToken`, only `IdToken`, resulting in a cache miss.

**Comment by tnorling** [comment]
@zzzachzzz What you describe is due to a known limitation of B2C currently. There's a work item in to change this behavior service-side but in the meantime please see our [FAQ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#why-is-there-no-access-token-returned-from-acquiretokensilent) for the suggested workaround and you can track issue #2315 for updates on the more permanent fix.

>Additionally, the returned AuthenticationResult contains an idToken, but the accessToken is an empty string. Are these two tokens functionally the same?

These tokens are not the same. You should use the idToken if you need to verify a user is logged in or who is logged in and an accessToken if you need to protect a resource such as a backend API.

**Comment by jasonnutter** [comment]
Closing, as we decided that if apps want caching when using `ssoSilent`, they should invoke `acquireTokenSilent`, and then invoke `ssoSilent` only if they get the `no_tokens_found` error.
