### ISSUE TITLE
Using Axios interceptors to fetch access tokens

### ISSUE THREAD

**Issue by KBLux** [AzureAD/microsoft-authentication-library-for-js#3034]
Hi
I'm new to React/JS and trying to to fetch my access tokens using axios interceptors. The question is basically just how to handle tokes using msal-react with axios. Right now my all my API calls look like this.

```
function SomeComponent() {
  const { instance, accounts, inProgress } = useMsal();
  const account = useAccount(accounts[0] || {});

  useEffect(() => {
    if (account && inProgress === "none") {
      instance.acquireTokenSilent({
          ...loginRequest,
          account: account,
        }).then((response) => { "use response.accessToken for API call" })
    }
  }, [account, inProgress, instance]);

  return (
    <>
    </>
  );
}
```

I want this to be handled using axios, something like this:

```
import axios from "axios";
import { loginRequest } from "./authConfig";

const axiosInstance = axios.create({
  baseURL: process.env.REACT_APP_BASE_URL,
});

function fetchAccessToken() {
const { instance, accounts, inProgress } = useMsal();
const account = useAccount(accounts[0] || {});

 return new Promise((resolve) => {
 instance.acquireTokenSilent({...loginRequest, account: account})
           .then((response) => { resolve(response.accessToken)})
    });
}

function fetchToken() {}

// Add a request interceptor
axiosInstance.interceptors.request.use(
  (config) => {
    const accessToken = await fetchAccessToken;
    if (accessToken) {
      config.headers["Authorization"] = "Bearer " + accessToken;
    }
    config.headers["Content-Type"] = "application/json";
    return config;
  },
  (error) => {
    Promise.reject(error);
  }
);

export default axiosInstance;
```
Obviously this code doesn't work, ass I can't use hooks in normal JS functions. How do I get the instance, accounts, inProgress without using hooks?

Thanks!

**Comment by tnorling** [comment]
@KBLux You can use the same `PublicClientApplication` instance you pass into the `MsalProvider`. Just export it from the file where you initialize it and import it here. To get the accounts you can call `instance.getAllAccounts()`. You can't access the `inProgress` value outside of a component or outside of context, but since you're just using `acquireTokenSilent` you won't need it.

This scenario will be added to the docs in #3002 and I'll make sure we add this to one of our samples as well.

Also in the future, please fill out the issue template when opening issues as it helps us organize the information and answer your question quicker. Thanks!
