### ISSUE TITLE
Should the contents of MsalAuthenticationTemplate tag be assured that there is a valid user session?

### ISSUE THREAD

**Issue by timtucker** [AzureAD/microsoft-authentication-library-for-js#3087]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [x] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

Our expectation was that the content of MsalAuthenticationTemplate would only ever be rendered if a user was actually logged in and that they would be prompted to sign in again if their login had expired.

We've seen both errors that we're unable to get a token silently because the token is at its refresh limit and I've seen occasional errors that a token can't be acquired silently because no user is logged in.

In both cases, I would have expected the outer MsalAuthenticationTemplate to have redirected to login again.

Note that these errors are occurring on a fresh page load of the app, not after extended use with it open.

Are we missing something?

```
const AppContent: React.FunctionComponent<{}> = () => {
  const { accounts, instance, inProgress } = useMsal();
  const [token, setToken] = useState('');

  useEffect(() => {
    if (inProgress !== 'none') {
      return;
    }

    const username = accounts[0]?.username;
    if (!username) {
      return;
    }

    const account = instance.getAccountByUsername(username);
    if (!account) {
      return;
    }

    const tokenRequest: SilentRequest = {
      scopes: ['openid'],
      account: account,
    };
    instance
      .acquireTokenSilent(tokenRequest)
      .then((response) => {
        setToken(response.idToken || '');
      })
      .catch((e) => {
        // Something went wrong
        console.error(e);
      });
  }, [accounts, inProgress, instance]);
  
  if (!token) {
    return <span>Not signed in yet</span>;
  }
  
  return <span>Signed in!</span>;
};

export const loginRequest = {
  scopes: ['openid'],
  extraQueryParameters: { domain_hint: 'example.com' },
};
interface Props {
  msalInstance: PublicClientApplication;
}
export const App: React.FunctionComponent<Props> = (props: Props) => {
    return (
        <MsalProvider instance={props.msalInstance}>
          <MsalAuthenticationTemplate interactionType={InteractionType.Redirect} authenticationRequest={loginRequest}>
            <EmployeeAppContent />
          </MsalAuthenticationTemplate>
        </MsalProvider>
    );
}

```

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by timtucker** [comment]
To note, our desired end state would be able to use as few tags and as little code as possible to render content for an authenticated user with a token retrieved with as little user interaction as possible.

i.e.:
- Authenticate and get the token via a single operation / tag
- Start with a silent attempt, but automatically fall back on redirect if needed

**Comment by tnorling** [comment]
@timtucker Msal does not track user sessions on the server. Once a user is logged in msal will create an account object for the user which persists until you explicitly logout or clear the cache. The presence or absence of this account object is what determines whether children of `MsalAuthenticationTemplate` are rendered. If you are running into issues with `acquireTokenSilent` failing when the token is expired your code should fallback to an interactive method such as `acquireTokenRedirect` in order to renew the session.

**Comment by timtucker** [comment]
Which sounds like pretty much the same behavior as I observed from <AuthenticatedTemplate>, which is next to useless.

If MsalAuthenticationTemplate can't guarantee that it has an authenticated user in context, it doesn't sound like it offers much more.

I guess I'm looking for a higher level of abstraction than is provided.

Would really love something as simple as a single tag or hook that handles any fallbacks automatically and gives some indication of whether or not a request is currently in progress:
```
const [account, validToken, inProgress] = useMsalTokenProvider(siteConfig);
```

Have tried various attempts at getting the fallback logic to work consistently, but it's nearly impossible to troubleshoot when I can only get the errors I see to occur once every 24 hours.

**Comment by tnorling** [comment]
> I guess I'm looking for a higher level of abstraction than is provided.

Generally speaking, if the provided components don't meet your needs you are more than welcome to copy the source code and make the necessary adjustments to create a custom component that works for you. All of our provided components use public APIs, hooks and components. With that said, this is a reasonable use case and we'll take it under consideration for future enhancements.

> Would really love something as simple as a single tag or hook that handles any fallbacks automatically and gives some indication of whether or not a request is currently in progress:

This is likely not something we will pick up since the `inProgress` value is available on the `useMsal` hook and given that the APIs to fallback to interaction already exist. It's really as simple as: 

```javascript
instance.acquireTokenSilent(request).catch(e => {
    instance.acquireTokenRedirect(request);
});
```

> Have tried various attempts at getting the fallback logic to work consistently, but it's nearly impossible to troubleshoot when I can only get the errors I see to occur once every 24 hours.

You can try to fake the behavior for debugging purposes by editing or removing your refresh token value in local/session storage, setting the `forceRefresh` value to `true` on your silent request to skip the cache and disabling 3rd party cookies in your browser to force the hidden iframe renewal to fail. If you'd like to share the specific problems you're facing I would be more than happy to help you solve them.

**Comment by georgejdli** [comment]
> With that said, this is a reasonable use case and we'll take it under consideration for future enhancements.
For my use case at least I would like to show the user a login prompt (with a message telling them popup blockers should be disabled) if they aren't signed in or of their token (or refresh token) has expired
