### ISSUE TITLE
Request for documentation/samples to handle multiple accounts and account switching

### ISSUE THREAD

**Issue by amrutha95** [AzureAD/microsoft-authentication-library-for-js#3189]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location

- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [ ] README file
- [ ] Other (please fill in)
- [x] Documentation does not exist

## Description
It would be extremely helpful to have a sample/documentation that demonstrates how to switch between multiple logged in accounts.

**Comment by jasonnutter** [comment]
@amrutha95 Thanks, we'll make sure to get this documentation added.

**Comment by mojanas** [comment]
Is there any update on when this documentation will be available?

**Comment by jasonnutter** [comment]
@mojanas Not yet, unfortunately.

**Comment by olafwrieden** [comment]
+1 I am also waiting for this. When multiple users are signed in and one isn’t able to refresh the token, then it still shows as “authenticated” even if the second user has no relation to my application whatsoever.

In this case, my app may try to fetch profile info from my API to re-hydrate the user context, thinks a valid user is authenticated, yet may actually return `undefined` because the user was signed into the browser (therefore appears in the list of accounts) but never actually registered with my application and therefore doesn’t exist as far as my backend is concerned. More samples on this would be much appreciated!

**Comment by olafwrieden** [comment]
Any progress on this logic? Commenting to keep open.

**Comment by anton-marchenko** [comment]
@jasonnutter 

Is there any update?

**Comment by derisen** [comment]
@anton-marchenko @olafwrieden @mojanas @amrutha95 See the updated [document on accounts](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/accounts.md) and the [react-router sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/react-router-sample) which has this logic now.

**Comment by jasonnutter** [comment]
Thanks @derisen, closing.
