### ISSUE TITLE
isAngular option, what does that do?

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#326]
I was just browsing the source and I see there's a new option [`isAngular`](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/src/UserAgentApplication.ts#L237) but I don't see that documented in the [releases](https://github.com/AzureAD/microsoft-authentication-library-for-js/releases).

What is it?  What does it do?  When was that introduced?  Thanks 🙏

**Comment by asnow003** [comment]
It is a property you can set if you are using the library in an Angular application.  So if this is set to true instead of when events happen like redirects when popups close and so on it will "broadcast" events instead that your app can handle in the "angular" way.

It looks like it was added a couple months ago due.  We are coming out with Angular support very soon with samples so you can easily integrate login in your Angular apps.  There is a branch you can see starting with na/ that has these samples already if you are more curious.

**Comment by spottedmahn** [comment]
hmm.. interesting!  thanks 🙏 for the response @asnow003!

**Comment by spottedmahn** [comment]
>We are coming out with Angular support very soon with samples so you can easily integrate login in your Angular apps

We use Angular and MSAL **today**.  I assume this means there will be better first-class citizen support for Angular?

**Comment by bh3605** [comment]
As of today, I noticed setting isAngular to true is only applicable to when you aren't using loginRedirect() and instead calling loginPopup(). It broadcasts whenever the hash changes and the pop up closes

**Comment by AndrewCraswell** [comment]
@asnow003, is it possible to get this option added to the documentation? [The wiki](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-basics#configuration-options) that describes the optional parameters for MSAL.js seems to be out of date, and I'm not sure of the best way to describe the `isAngular` option.

**Comment by Danieliverant** [comment]
using Angular 7  (vanilla JS package because the Angular wrapper compatible just up to version 5) and loginPopup(), when I set "isAngular" to true the popup opens and closes itself without doing anything (really weird behavior because I can't catch the error, not in the 'then' block nor in the 'catch').

When not using "isAngular", and using Angular Router to redirect to the main page of the app after I get the accessToken a blank pop-up remains on the screen.

@asnow003 @bh3605 what version are you using? 

some help?

**Comment by bh3605** [comment]
@Danieliverant Our Angular application(s) use full page redirection and don't utilize any popups. I've also switched to using OidcClient.js from msal.js. It has a higher level of granularity (IMO), also uses events, the code is very well abstracted out, and there are more configuration options in OidcClient.js. OidcClient.js also operates differently from the "automatic" nature msal.js uses. Primarily, msal.js will automatically validate a jwt token that exists in the url while you have to call a certain method in OidcClient.js to validate your jwt. I was also able to overcome the IE/Edge issues using OidcClient.js and wrote a fun service class to interface with the wrapper it already provides for easier use. Been working like a charm. Msal.js has since overcame these IE/Edge issues (which is good!)

I haven't looked at this code base in a while. When I was still using this, I was reading all of the code to see what it would do, including any event propagation. That may help you find why the pop up doesn't stay open. You could also turn the isAngular setting back on and subscribe to all of the events. I would use an event to determine when the application routes to a new page. I'd also turn on any logging msal may have added and crank the verbosity up to 10.

**Comment by spottedmahn** [comment]
@bh3605 - I assume you mean [IdentityModel/oidc-client-js](https://github.com/IdentityModel/oidc-client-js)?

**Comment by bh3605** [comment]
@spottedmahn Yep, that's the one.
