### ISSUE TITLE
Strategy.prototype.jwtVerify: cannot verify token. When using AzureAD v2.0

### ISSUE THREAD

**Issue by OttoChamo** [AzureAD/microsoft-authentication-library-for-js#3260]
We are migrating our application from the AzureAD v1.0 endpoint to AzureAD v2.0, but after doing the proper changes I receive that response which you see in the title.

This is my configuration:

identityMetadata: OAUTH2_CONFIG.identityMetadata,
clientID: OAUTH2_CONFIG.clientID,
audience: OAUTH2_CONFIG.clientID,
validateIssuer: OAUTH2_CONFIG.validateIssuer, //true
passReqToCallback: OAUTH2_CONFIG.passReqToCallback, // true
loggingLevel: OAUTH2_CONFIG.loggingLevel

Following the documentation the default value for audience is clientID, anyways I set it. But It can't validate the Access Token.

Also I am sending the token in the Authorization header like this `Bearer $thetokenIrecieve`

**Comment by pkanher617** [comment]
We are working on an update for the passport library that will encompass this ask, you can track the progress [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9).

**Comment by collaorodrigo7** [comment]
Thank you to everyone that share in this issue!. I also waster a couple of hours on this!
I just want to add something I noticed, from your client you must pass the `api://app-id/read` scope (after you added it on azure, I put a screenshot at the end in case it helps anyone having problems setting it up), and make sure you do NOT pass the `user.read` from graph or any other scope from graph because that will make the token be a v1.0 again.

Now I was wondering, is it safe to just receive the JWT token on the API, and then just parse it using JWT libs and actually query GraphAPI to get current user data and use that as the verification that the token is valid. I was able to do this by making this request:

```
curl --location --request GET 'https://graph.microsoft.com/v1.0/users/USER-ID-0000-aaaa-bbbbbbbb' \
--header 'Authorization: bearer YOUR_V1_GRAPH_TOKEN_HERE'
```
And this will return some user information like this:
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
    "businessPhones": [
        "000-000-0000"
    ],
    "displayName": "User name",
    "givenName": "Given Name",
    "jobTitle": "something",
    "mail": "email@thanks.azuread.for.the.great.documentation.and.not.making.us.waste.time.com",
    "mobilePhone": null,
    "officeLocation": null,
    "preferredLanguage": null,
    "surname": "Surname",
    "id": "USER-ID-0000-aaaa-bbbbbbbb"
}
```

Then just to be safe you could double check the reply info, email, and user id with the data encoded on the token, and if it's all good take as a valid token??



In case it helps anyone, here is how you expose the api and add a scope:
![image](https://user-images.githubusercontent.com/24518083/112585373-ad463580-8dc7-11eb-9eb9-bb3f2771600d.png)

**Comment by talgat-saribayev** [comment]
Following @benc-uk and removing "audience" helped.

**Comment by ndhambie** [comment]
I am trying to validate my access token on the Nodejs server using passport-azure-ad but I keep getting this error:

{"name":"AzureAD: Bearer Strategy","hostname":"testPC","pid":20016,"level":30,"msg":"authentication failed due to: Error: unable to get local issuer certificate","time":"2021-10-27T22:10:39.323Z","v":0}

What certificate and how do I solve this

**Comment by Efrony** [comment]
@collaorodrigo7, Thanks for the screenshot, it was not very clearly written at the top =) 
I'll add some too

Client
![image](https://user-images.githubusercontent.com/45768389/143609094-75e95492-61e8-4225-84e3-967aae1448c5.png)

Server
![image](https://user-images.githubusercontent.com/45768389/143609248-2f19b514-7966-44e5-aa43-d5ac035d567e.png)

Delete  User.read

It remains to figure out how to pull out the necessary account data

**Comment by ShamiliSingidi** [comment]
I want to access my node API through Angular App. Both are registered under same AD. I am getting jwt cannot verify. Anyone please help me

**Comment by CelestialMusa** [comment]
If you're still toiling on this after having tried everything suggested, you might want to follow this approach:
Include your Client ID as part of the identityMetadata url as a query param named "appid" like so:

**V1 Tokens:**
`https://login.microsoftonline.com/<tenant_id>/.well-known/openid-configuration?appid=<client_id>`

**V2 Tokens:**
`https://login.microsoftonline.com/<tenant_id>/v2.0/.well-known/openid-configuration?appid=<client_id>`

This should narrow down the search for the KID pointing to your public key.

**Comment by rocketraman** [comment]
Coming back to this after a long time... after having just updated to MSAL 2.x, I can offer some additional guidance which I'm not sure anyone has mentioned above.

The main thing to note is that with MSAL you can pass one set of scopes (graph scopes like `openid`, `profile`, and `user.read`) to the login call e.g. `loginRedirect`, and a *different* set of scopes when retrieving an id token e.g. `acquireTokenSilent` which can be verified by a backend like passport-azure-ad.

The first set of scopes are Graph scopes, and as many people have noted, the token generated with those scopes is not meant to be validated by any system other than Graph. So, when generating the token that is needed for your backend API, pass only a custom scope (see https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-app-registration#expose-an-api). This custom scope can be pre-approved by the user at login time by adding it to `extraScopesToConsent` in the `loginRedirect`/`loginPopup` call options.

NOTE: The custom scope recommended in those docs didn't actually work for me -- what did work is to pass an empty scope list to the `acquireTokenSilent` call, which works fine when all you need is an id token to pass to your backend, and not an access token that your frontend code needs to access some resource directly.

See this comment for more info: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1040#issuecomment-540810355.

I don't know why this is so poorly documented...

**Comment by joshuablanco** [comment]
In my case, I got this error because when I requested the token with the wrong scopes, I mean scopes not defined in the API exposed by one APP registration previously defined by me.

**Comment by rrakso** [comment]
> @Afdz1020 No, you should send the accessToken.

My `accessToken` contains `nonce` in it's header, so I can't decode it with `passport-azure-ad` ([reference](https://stackoverflow.com/a/45318464/)) - but validating `idToken` works perfectly.

This [blog post](https://tonesandtones.github.io/azure-ad-and-the-unvalidatable-access-token/#:~:text=related%20Github%20issue-,tl%3Bdr,-To%20get%20the) written by @tonesandtones may be helpful.

**Comment by michaelosbornegit** [comment]
This thread was a goldmine and got me 95% of the way there. In case this helps anyone. I'm using the Authorization Code flow as referenced here https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas

In my SPA I am using the scope `api://{app-guid}/myscope` so I was trying to use the scope `api://{app-guid}/myscope` on my web API to verify the bearer token. Turns out on the web API side the scope just needs to be `myscope` and it starting working.

**Comment by Kuro091** [comment]
So for anyone still having issues with this, aside from matching scopes, putting

`TenantId: "9188040d-6c67-4c5b-b112-36a304b66dad" in my server code ` works for a client using

`Authority: "https://login.microsoftonline.com/common"`

I honestly don't know why it is that specific value.
For the future, I'll just avoid anything Microsoft to save me the headaches.

**Comment by sumitcodedata** [comment]
I have already tried every solution which in mention on google but it is not working for me. 
i am generating token by postman:
 
https://login.microsoftonline.com/74a5ee4e-7fed-4113-97b7-912ea693de9f/oauth2/v2.0/token
post {
client_id:b90bd881-24d4-417d-914c-534d36a92b22
client_secret:WVh8Q~s6N9YxH0R5cd-KAr6llIK1KCsG.vu1uaAc~x
scope:https://graph.microsoft.com/.default
grant_type:client_credentials
}

IN Node i am validating bt Bearer Strategy :

const options = {
    identityMetadata: `https://login.microsoftonline.com/74a5ee4ce-7fed-4ll113-97b7-912ea693de9f/v2.0/.well-known/openid-configuration`,
    clientID: config.credentials.clientID,
    audience: config.credentials.clientID,
    loggingLevel: 'info',
     passReqToCallback: true,
        policyName: config.policies.policyName,
     validateIssuer: false,
    issuer : "https://login.microsoftonline.com/74a5ee4e-7fed-41c13-97b7-912ea693de9f/v2.0",
     scope: ['User.Read' ]
}
const bearerStrategy = new BearerStrategy(options, (token, done) => {
        // Send user info using the second argument
        console.log("token strategy:::")
        done(null, { }, token);
    }
);

Can anybody help me about this. Its going to be headache  foe me.

**Comment by smartworld-dm** [comment]
I resolved it by using the `id_token` instead of using `access_token`.
I think `access_token` is for v1, `id_token`(or idToken) is for v2.
