### ISSUE TITLE
msal-browser: interaction_in_progress error when user closes AAD page and then attempts to revisit

### ISSUE THREAD

**Issue by bt-88** [AzureAD/microsoft-authentication-library-for-js#3280]
## Library
- [x] `@azure/msal-browser@2.12.0`

## Framework
- [x] React 17

## Description
Our problem is _identical_ to issue #2149 (which was solved in `2.0.2`).

**Reproduction steps**
- The user goes to our page.
- He is not signed in, so the `msal` redirects him.
- The AAD page is shown (Signing in...).
- The user closes the tab prematurely.
- The user opens a new page and attempts to go to our page again.
- He receives an error message `interaction_in_progress` from `msal-browser` in his browser console window.

**Interaction status not cleared**
It seems that the state in localStorage is not cleaned properly when the user cancels the ADD page and that `msal..interaction.status: interaction_in_progress` remains.

**Possible regression?**
Possible regression following [this commit](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/2935/commits/ea382c2986ee4d44571d5e672bcfecf81162ec27) (?).

## Error Message
See issue [#2149](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2149).

## MSAL Configuration
See issue [#2149](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2149).

## Reproduction steps
See issue [#2149](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2149).

## Identity Provider

- [x] Azure AD

## Browsers/Environment

- [x] Chrome
- [x] Firefox
- [x] Edge

**Comment by tnorling** [comment]
@bt-88 Can you try upgrading to version 2.12.1? This includes a patch affecting clearing of cookies that can result in this behavior.

**Comment by bt-88** [comment]
> @bt-88 Can you try upgrading to version 2.12.1? This includes a patch affecting clearing of cookies that can result in this behavior.

@tnorling Which patch exactly?
In the meantime we will try this, but I'm not hopefull since the [history](https://github.com/AzureAD/microsoft-authentication-library-for-js/commits/ea382c2986ee4d44571d5e672bcfecf81162ec27/lib/msal-browser/src/app/ClientApplication.ts) shows that nothing has changed since that last commit (which might've caused regression). I will report back.

**Comment by tnorling** [comment]
@bt-88 PR #3129 fixed an issue that prevented cookies from being cleared in the scenario you describe. It was included in version 2.12.1

**Comment by idri** [comment]
Hi,
I confirm I experience the same problem starting with version: 2.12.0. It works fine in 2.11.2
After doing some debugging in the msal-browser 2.13.0 I found out that the problem might be that in the `BrowserCacheManager.prototype.cleanRequestByInteractionType`. There is a call to `this.resetRequestCache(stateValue)` that uses the `stateValue` (a base64 encoded string of an object that contains `id` and `meta.interactionType`), when in fact I think it should have used the decoded state id instead of the encoded state value. The thing is that this decoded state id should have probably been obtained by the previous call to `var parsedState = BrowserProtocolUtils.extractBrowserRequestState(_this.cryptoImpl, stateValue);` but this only returns the decoded state meta after parsing the encoded state.

**Comment by tnorling** [comment]
@idri I looked into this but `cleanRequestByInteractionType` is implemented correctly. The state value is decoded inside each of the key generation functions, right before the individual cache entries are retrieved: [for example](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/cache/BrowserCacheManager.ts#L631)

Can you please confirm that you are getting this error when loading a fresh instance of the application in a new tab or browser? Are you calling and awaiting `handleRedirectPromise` on this page before attempting to login? 

Unfortunately, this error is one of the more common errors people run into and most of the time it is expected due to some misconfiguration or incorrect implementation, the root cause in your case may not be the same as the original poster's. Given that everyone's implementations are different I would suggest you open a new issue with code snippets and log messages so that we can focus on your particular problem and help you resolve it. I would also start by reading through [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md#interaction_in_progress) and double checking your app is following the guidance laid out in there.
