### ISSUE TITLE
localAccountId seems to be only required on JS's account structure

### ISSUE THREAD

**Issue by sadasant** [AzureAD/microsoft-authentication-library-for-js#3336]
## Library
- [x] `@azure/msal-node-extensions@1.0.0-alpha.6`

## Description

As we're working across languages on using MSAL for the Azure SDKs, we noticed that `localAccountId` is only a required value the account structure for JS. Other languages can get away without sending this parameter. I've talked with some of the MSAL team about this and I've been told that this property is required in some authentication cases. Does that mean that this property can be set to another value (like an empty value or like `homeAccountId`) in most cases? Moreover, which cases require these values to be set?

## Source

- [x] Internal (Microsoft)
- [ ] Customer request

**Comment by sameerag** [comment]
@sadasant `localAccountId` is needed for ADFS use cases where there is no tenantId (hence they cannot generate `homeAccountId`). We introduced this to support our customer use cases and a few of the reference issues are:  #2500 #2507 #2553.

For your use case, you can safely ignore this since all AAD calls which generate a `homeAccountId` if there is an account. This can be a blank value which is not consumed by your application. Hope this clarifies.

**Comment by sadasant** [comment]
@sameerag you helped me clarify this over chat, but just for the record: to recover an account from the cache, only the homeAccountId matters. Is that correct? If that's the case, since that's what's being used on other languages too, we can close this issue.

Thank you for your time!

**Comment by sameerag** [comment]
@sadasant Yes. Your understanding is correct. Closing this issue.
