### ISSUE TITLE
Redirect URI should end with /

### ISSUE THREAD

**Issue by MarkHerhold** [AzureAD/microsoft-authentication-library-for-js#335]
Per [this issue](https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/451), ADAL should probably help users out by adding a trailing `/` or error out when one is not provided in the redirect URI.

**Comment by nehaagrawal** [comment]
@MarkHerhold  The issue that you pointed out is for ADAL. Are you seeing the same issue in MSAL?

**Comment by MarkHerhold** [comment]
@nehaagrawal The issue exists will both ADAL and MSAL.

**Comment by nehaagrawal** [comment]
@MarkHerhold  The issue that you reference was for safari browser where cookie was disabled and our library can't work if cookie is disabled. That issue was closed. I saw your comment and it seems your issue is related to reply url not ending with slash.
Can you please send me the exact error that you are getting. Also if it's related to slash, it should be reproducible in all browsers. I am not clear why it's reproducible only in safari.

**Comment by asnow003** [comment]
@MarkHerhold I just did a generic test on my mac using the latest Safari in Sierra.  I used our VanillaJSTestApp in the repo.  Have you tried that also...just wondering if there is a specific setup I can do to repro this.

**Comment by MarkHerhold** [comment]
See comment in referenced issue. Closing.
