### ISSUE TITLE
Redirect URI for Electron based app?

### ISSUE THREAD

**Issue by willwull** [AzureAD/microsoft-authentication-library-for-js#357]
Hi,

I'm currently developing a desktop application using Electron. However, since Electron (in a simplified sense) simply opens an HTML file using the `file://` protocol, I'm not sure what I should use as redirect URI in our Azure application.

Many OAuth tutorials online mention using `localhost`, but that's unsuitable for production IMO.

One approach I tried which almost works is adding native as a platform in our app, which let's us use `https://login.microsoftonline.com/common/oauth2/nativeclient` as redirect. I then listened to url changes in the Electron window for when the user is redirected to the above url. Lastly, I took the hash (which contains `#id_token` among other things) and manually redirected to our HTML page with the hash included.

This sort of worked, except `userAgentApplication.acquireTokenSilent(graphAPIScopes)` doesn't work. Perhaps because of the absence of some Azure cookie? If I use `acquireTokenRedirect`, and _then_ `acquireTokenSilent`, that works, but that requires the user to log in twice...

Do you have any suggestions for this situation?

**Comment by justinwilaby** [comment]
Take a look at [this pr for the Botframework Emulator](https://github.com/Microsoft/BotFramework-Emulator/pull/709)
The jist of it is that we had to run an http server in the main process to retrieve the `id_token`. If you need to, you can spin up your server when AAD auth is in play and tear it down when not needed.

**Comment by justinwilaby** [comment]
I should add that the `[AzureAuthWorkflowService.ts](https://github.com/Microsoft/BotFramework-Emulator/pull/709/files#diff-045e2bff07614acfc0f4293237565250)` and `[registerRoutes.ts](https://github.com/Microsoft/BotFramework-Emulator/pull/709/files#diff-461caac44362e4ae664c5f3c490f091d)` are the meat of the solution.

**Comment by willwull** [comment]
@justinwilaby Thanks for your answer. I looked at your linked code briefly, and I want to see if I understand your flow correctly:

* When a user is going to log in, `enterAuthWorkflow` is called from somewhere.
* This opens a new window with the MS sign in page.
* At this point, you have a server running on `localhost:5000`(Looked at [this](https://github.com/Microsoft/BotFramework-Emulator/blob/c423c0ca99e9ed642ea8ec783fde78b8f5323644/packages/emulator/cli/src/index.ts), not sure if that's the correct place).
* The user is redirected to the blank page that is generated in `registerRoutes.ts` and the `id_token` is extracted from the url.

My questions are:
* I don't see any usage of `msal.js`, is this correct?
* If indeed you are using port 5000, how can you guarantee that it's available when the user is using your app? I'm assuming you have `http://localhost:5000` registered as the redirect URL in the Azure app portal.
* After getting the `id_token`, what happens then? Do you use it to fetch an `access_token` somewhere?

**Comment by justinwilaby** [comment]
@willwull  -

Yes that is correct. I did not use the msal library for 2 reasons: 
1. I wanted to use a WebView and not an iframe
2. Taking on anther dependency for essentially building a url and registering callbacks seemed unnecessary in my case

In the case of the Botframework Emulator, we run an HTTP server as part of the [startup sequence](https://github.com/Microsoft/BotFramework-Emulator/blob/v4/packages/app/main/src/main.ts#L262) for, well, emulation. This server also used to deliver the empty page as the `redirect_uri` registered in Azure. Since the WebView is closed as soon as this page is loaded, the user never sees this page.

In your case, using a [simple http server](https://nodejs.org/dist/latest-v10.x/docs/api/http.html#http_class_http_server) using native node APIs and spinning up this server when the user begins the Auth flow and terminating it when the flow completes would be the lightest and fastest implementation. Generator functions are an exquisite way to define multi-step asynchronous  workflows so I'd recommend looking into this to determine if they are appropriate for your particular case.

If you need to get an access token in addition to an id_token, update the response type to `response_type=id_token+code`. the url will look like this:
```js
https://login.microsoftonline.com/common/oauth2/authorize?response_type=id_token+code
```
I'll be implementing JWT validation and Azure web service access using the access token this week on the `jwilaby/AAD-token-validation` and the `jwilaby/azure-service-access` branches. Feel free to follow along, comment and contribute!

**Comment by navyasric** [comment]
MSAL.js is designed to handle authentication using OpenID Connect flows in JS web applications. It does not support the code flow required by native applications. 
@willwull Closing this issue as the approach mentioned in above comment maybe more suitable for your scenario and it is not related to MSAL.js.
