### ISSUE TITLE
Infinite loop with out Login button

### ISSUE THREAD

**Issue by lakshmipuli** [AzureAD/microsoft-authentication-library-for-js#3667]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.0

### Description

I am trying to login user seamlessly, with out having a login button as it will be hosted on Azure. But ending in infinite loop with error:

interaction_in_progress: Interaction is currently in progress. 
Please ensure that this interaction has been completed before calling an interactive API.  
For more visit: **aka.ms/msaljs/browser-errors.**

### Relevant Code Snippets

```javascript
Sample Pagelayout code modified Typescript sample from https://github.com/AzureAD/microsoft-authentication-library-for-js:

export const PageLayout = (props: any) => {
    const { instance,accounts,inProgress } = useMsal();
    if(instance.getActiveAccount() == null)
    {
        console.log('account =' + instance.getActiveAccount());
        instance.loginRedirect(loginRequest);
    }
    console.log('count =' + instance.getAllAccounts().length);
    console.log('active =' + instance.getAllAccounts());
    return (
        <>
            <Navbar bg="primary" variant="dark">
                <a className="navbar-brand" href="/">MS Identity Platform</a>
                {/* <SignInSignOutButton/> */}
            </Navbar>
            <h5 className="sample-header">Welcome to the Microsoft Authentication Library For Typescript - React Quickstart</h5>
            <br/>
            <br/>
            {props.children}
        </>
    );
};
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
@lakshmipuli This code example will call `instance.loginRedirect` on every render. You need to make sure you check `inProgress === InteractionStatus.None` before calling `loginRedirect` as documented [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/errors.md#interaction_in_progress).

Alternatively, instead of calling `loginRedirect` yourself you can use the [useMsalAuthentication hook](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/hooks.md#usemsalauthentication-hook) or [MsalAuthenticationTemplate component](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/getting-started.md#msalauthenticationtemplate-component) to achieve auto login on page load. This is demonstrated on the `/profile` route in the [TypeScript sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-react-samples/typescript-sample/src/pages/Profile.tsx)

**Comment by lakshmipuli** [comment]
Hi @tnorling,

Sorry for the delay in responding and Thank you so much for the response.  I did try it in my POC and it worked. I am going to integrate with my code and update you if I have any further issue.

Thanks,
Lakshmi.

**Comment by tnorling** [comment]
Thanks for letting us know! I'll close this but feel free to open a new issue if you run into any other issues. Thanks!
