### ISSUE TITLE
Token calls are blocked in hidden iframes

### ISSUE THREAD

**Issue by yvoneee** [AzureAD/microsoft-authentication-library-for-js#3674]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.4

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

1.1.2

### Description

I'm getting error "Token calls are blocked in hidden iframes" during acquireTokenSilent in MsalInterceptor. It happend all the time when I'm trying log in to app. Clearing localStorage and cache doesn't work for me. I tried fixed it using this solutions:

1.` intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
  if (!isIframe){ 
  return super.intercept(req,next);
  }
 }`

2. catch Error from acguireTokenSilent
3. `    this.isIframe = window !== window.parent && !window.opener;
 and     <router-outlet *ngIf="!isIframe"></router-outlet>
` 
4. navigate to empty page after login

and nothing works for me

### Error Message

Token calls are blocked in hidden iframes and Token renewal failed due to timeout

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
  auth: {
    clientId: environment.msalModule.clientID,
    authority: environment.msalModule.authority,
    redirectUri: environment.msalModule.redirectUri,
    validateAuthority: true,
    postLogoutRedirectUri: environment.msalModule.redirectUri,
    navigateToLoginRequestUrl: true
  },
  cache:
  {
    cacheLocation: 'localStorage',
  }
}

export const angularConfig: MsalAngularConfiguration = {
  popUp: false,
  consentScopes: [
    'user.read',
    environment.msalModule.appScope
  ],
  protectedResourceMap: protectedResourceMap
}
```

### Relevant Code Snippets

```javascript
CoreModule configuration

export function init(injector: Injector) {
  return () => injector.get(AuthService).startListening();
}

@NgModule({
  declarations: [
  ],
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    HttpClientModule,
    MaterialModule,
    SharedModule,
    MsalModule.forRoot(msalConfig, angularConfig),
    StoreModule.forRoot(appReducer, { metaReducers }),
    EffectsModule.forRoot([effects_array]),
    StoreRouterConnectingModule.forRoot(),
  ],
  exports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
  ],
  providers: [
    MsalGuard
  ]
})
export class CoreModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: CoreModule,
      providers: [
        {
          provide: APP_INITIALIZER,
          useFactory: init,
          deps: [Injector],
          multi: true
        },
        {
          provide: HTTP_INTERCEPTORS,
          useClass: MsalInterceptor,
          multi: true
        },
        { provide: API_BASE_URL, useValue: environment.baseApiUrl },
        AuthService,
      ]
    }
  }
}
```

### Reproduction Steps

Any form of calling MsalIntercept acquireTokenSilent

### Expected Behavior

User can log in without lack of token renewal.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by pkanher617** [comment]
I'm working on trying to reproduce this issue, will get back as soon as I can.

**Comment by pkanher617** [comment]
@yvoneee This is probably happening because the page rendering the iframe is calling acquireTokenSilent again. Make sure that the page on the redirect URI you use for the silent requests does not invoke acquireTokenSilent. You can also try setting initialNavigation to `disabled` when the app is rendered inside an iframe: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/21123e62ed0c9e99bfe6ed248f2f789a3ee6239a/samples/msal-angular-v2-samples/angular10-sample-app/src/app/app-routing.module.ts#L36

**Comment by yvoneee** [comment]
> Make sure that the page on the redirect URI you use for the silent requests does not invoke acquireTokenSilent.

Would you like to tell me what is the proper way to do this? Right now I'm navigate user to the page where in  routing config is canActivate flag managing by MsalGuard. If I understood correctly that I should navigate user to page with empty component or something like that?

> You can also try setting initialNavigation to disabled when the app is rendered inside an iframe:

I will also try this solution and reply to you If it's work. Despite that I would be glad If you answer me for previous question.

**Comment by mehdiibrahim** [comment]
i think this issue was introduced with the latest release of Chrome (v91). i'm running into the same problem. works with prior version of Chrome.

**Comment by jbockle** [comment]
I'm having the same issue with edgium/chrome v91 with an aurelia app.  Confirmed that users upgrading to v91 are now running into the issue as well.  I can't find a specific release notes from v91 that would cause this.  In some edge browsers, users are also seeing this error `Refused to display 'https://login.microsoftonline.com/' in a frame because it set 'X-Frame-Options' to 'deny'.`.  @pkanher617 were you able to reproduce the problem?

**Comment by jbockle** [comment]
I fixed it in my case, I changed `redirectUri` for `acquireTokenSilent` to be an blank page without any msal initialization/backend authorization requirement per the FAQ https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/FAQ.md#when-using-a-popup-or-silent-api

**Comment by gvheertum** [comment]
> 
> 
> I'm having the same issue with edgium/chrome v91 with an aurelia app. Confirmed that users upgrading to v91 are now running into the issue as well. I can't find a specific release notes from v91 that would cause this. In some edge browsers, users are also seeing this error `Refused to display 'https://login.microsoftonline.com/' in a frame because it set 'X-Frame-Options' to 'deny'.`. @pkanher617 were you able to reproduce the problem?

I can confirm that version >= 91 Chrome/Edge are causing issues. Although Chrome does not seem to yield the error message edge is giving us, both Chrome and Edge are no longer working.

Firefox and Chrome <= 90 seem to keep functioning without any issues.

**Comment by samuelkubai** [comment]
> I fixed it in my case, I changed `redirectUri` for `acquireTokenSilent` to be a blank page without any msal initialization/backend authorization requirement per the FAQ https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/FAQ.md#when-using-a-popup-or-silent-api

@gvheertum @jbockle @mehdiibrahim @yvoneee did implementing the solution above, resolve your problems for Chrome and Edge with versions >= 91?

**Comment by gvheertum** [comment]
> 
> 
> > I fixed it in my case, I changed `redirectUri` for `acquireTokenSilent` to be a blank page without any msal initialization/backend authorization requirement per the FAQ https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/FAQ.md#when-using-a-popup-or-silent-api
> 
> @gvheertum @jbockle @mehdiibrahim @yvoneee did implementing the solution above, resolve your problems for Chrome and Edge with versions >= 91?

We are trying to get that one to work, but changing the redirectUri to a blank page causes other issues since this means that after the login we also go the the blank page. We might need to have some changes in other consumed packages. So for now no success yet :(

**Comment by jbockle** [comment]
Its fixed for me.  Specifying the blank page redirectUri for `acquireTokenSilent`/`acquireTokenPopup` shouldn't cause any undesired redirect issues, don't set it to the blank page for `loginRedirect`, set it to your desired redirect page.

**Comment by mehdiibrahim** [comment]
A redirectUri in itself didn't work for me. But after upgrading our project to .NET core 3.1 and the front end libraries, it resolved itself. I need to dig in a little deeper to isolate the cause and fix and will post back once I have more clarity.

**Comment by gvheertum** [comment]
> 
> 
> Its fixed for me. Specifying the blank page redirectUri for `acquireTokenSilent`/`acquireTokenPopup` shouldn't cause any undesired redirect issues, don't set it to the blank page for `loginRedirect`, set it to your desired redirect page.

It appears to be wrapped by some other code in our situation, which only allowed us to set a single redirectUri which is used for all possible actions. So I'll have to dig deeper into the wrapping code to make a distinction somewhere.

What I am also afraid of is that I might need to also add the blank page to the B2C application allowed Reply and redirect Uri's which is something we rather not do since the blank page is not a "real" page. Do you know whether we need to also put it there?

**Comment by gvheertum** [comment]
I did some changes to only use a blank page for the acquireTokenSilent and using the regular for the loginRedirect, *but* it did not yield the correct results. After the token was acquired the user is redirected to the blank page with the status information in the url part (after the #). I am not sure why this is happening, but it looks like the solution is not working for us (yet).

**Comment by gvheertum** [comment]
Update: I also saw that the blank page solution resulted in the X-Frame error. Digging a bit deeper it seems that the login provider (IdentityServer in our case) kept adding the X-Frame header to all responses served, meaning that serving _any_ page via that server will result in the X-Frame header and a non-working saml plugin.

We tried removing the header from the response of the server to see if we could make Chrome/Chromium accept the data but we did not manage to remove the header from the responses (this part is embedded quite deep in IdentityServer) and the responses are flushed before the OnSessionEnd in the global.asax is executed meaning we cannot intercept the messages and remove the header (only solution we did not try would be inserting a proxy to remove the headers).

So unless the working of the library is changed to no longer rely on frames (or Chromium reverts the change, which I certainly don't expect) the combination with some (older) versions of IdentityServer and the saml < 2 libraries seems to be broken for Chromium (>= 91) browsers. Since 1.4 of the saml library is no longer supported and the package page suggests upgrading to 2.0 we decided to do a migration to either version 2 or another library (also because our desires regarding auth are changed over time).

I do understand it if there won't be coming a patch for 1.4 since the component is end-of-life. On our end we stopped chasing this bug and will move out to a newer version or other component.

Regardless of that, thank you for thinking with us in this ticket! 😄

**Comment by gvheertum** [comment]
Another update: I worked together with a colleague to make a custom rolled IdentityServer3 package that suppressed the X-Frame headers. Web issues wouldn't be web issues if after clearing one another will arise, so after the X-Frame we had to battle the SameOrigin flag on the cookies, apparently this is also more strictly enforced by Chromium (although in the past the SameOrigin stuff already gave problems to some extend). So we also had to fix that part (meaning updates to Owin to be able to do so (since intercepting the requests in the wrapping application did not yield the correct results).

After finally satisfying Chromium and getting all the errors out of the way we noticed that somehow Chrome encounters timeout issues when retrieving the silent token. The request takes to long and will yield an error from the msal library stating that the renewal timed-out.

So the last change we had to make was getting around that problem. Luckily the msal popup method _did_ work for Chrome (not sure if our other changes helped in this, but when trying with the new code it worked and I did not feel like going back 😉 ). We first try the silent, and upon failing we try the popup method which now results in a site working for both Chromium and non-Chromium browsers.

So our final solution was to change IdentityServer to no longer make Chromium angry and have an ultimate failback in the form of the popup method for the token.

I shared my fork and changes of IdentityFramework3: https://github.com/gvheertum/IdentityServer3 . Although the exact problem might not be really resolved we found a working workaround which perhaps can be of help to somebody else.

**Comment by yvoneee** [comment]
> I can confirm that version >= 91 Chrome/Edge are causing issues. Although Chrome does not seem to yield the error message edge is giving us, both Chrome and Edge are no longer working.
> 
> Firefox and Chrome <= 90 seem to keep functioning without any issues.

This part is confusing for me because part of users using Chrome >= 91 and everything works fine. Other user use exactly the same version of Chrome and they have problems during login to app. We had one case when user couldn't log in from his Chrome account but could log in from his account on other computer.

@gvheertum we are not using IdentityServer so it isn't solve our problem :( I have errors only on angular side of project.

**Comment by gvheertum** [comment]
> This part is confusing for me because part of users using Chrome >= 91 and everything works fine. Other user use exactly the same version of Chrome and they have problems during login to app. We had one case when user couldn't log in from his Chrome account but could log in from his account on other computer.

It wouldn't be the first time that Chromium rolls out some kind of A/B test to production. They did the same with the SameSite cookie policy a while back, where a part of the install base had a different setting on how to handle the samesite flag on the cookies. I believe they eventually reverted that change, but that also puzzled us at the moment why not 100% of the Chrome users had issues.

We eventually had to work around 3 issues in with the SAML library (and the underlying identity provider/Azure B2C):
- Remove the X-Frame-Options (required a custom build of the identity provider)
- Update the cookies to have the correct SameSite setting (None from the top of my mind)
- Use the popup as fallback (somehow Chrome now timesout on the requests for the tokens through the iFrame)

We now see that Chrome always goes for the popup. Having that als fallback prevents the site from an endless loop (due to the token request failing in the frame option). Somehow Chromium got very picky with regards to the token requests and first disregards the requests due to the xfame and cookie settings, but even after clearing those Chromium will just timeout, so for now it looks like the popup is the only working solution for Chromium and SAML.

**Comment by tnorling** [comment]
@yvoneee Did you try setting the `redirectUri` to a blank page as suggested above and in the docs?

@gvheertum 
> We now see that Chrome always goes for the popup

This is likely because you didn't actually solve the underlying problem but suppressed the error instead. The issue is that when you call `acquireTokenSilent` it opens a hidden iframe to your identity provider requesting a token. When the identity provider redirects to your redirectUri, your app is attempting to acquire a token now from inside the iframe resulting in nested requests. To solve this you need to prevent the nested application from attempting to request a token. You can do this either by setting the redirectUri to a blank page or by adding some checks on your redirectUri page to make sure it's not in an iframe before attempting to request a token.

To make this a little more reliable I also suggest upgrading to `msal-angular` v2 as soon as you're able to as it does not rely on hidden iframes in **most** scenarios.

**Comment by gvheertum** [comment]
> @yvoneee Did you try setting the `redirectUri` to a blank page as suggested above and in the docs?
> 
> @gvheertum
> 
> > We now see that Chrome always goes for the popup
> 
> This is likely because you didn't actually solve the underlying problem but suppressed the error instead. 

Come to think of it, that sounds fair and possibly correct indeed. We did not succeed in redirecting to the blank-page at first since somehow the underlying identity provider or wiring logic on our side either refused doing what was asked or also redirected us to the blank page _after_ successful authentication, but even that part we didn't get to work in Chrome at first (as far as I recall Chrome just kept giving errors regarding the frames). So I guess in our situation the version of our IdentityProvider was also to blame, since even with the blank page Chrome just simply refused on our side.

Maybe a combination of the updates to the identity provider and the blank page could have worked, but as you suggest we are aiming for an upgrade to a newer version of the library (and possibly also another Identity Provider) so once we got something working we parked the issue for now.
