### ISSUE TITLE
PKCE code flow and React  SPA?

### ISSUE THREAD

**Issue by vpopescu** [AzureAD/microsoft-authentication-library-for-js#3691]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.0

### Description

What is the guidance for implementing PKCE flow in a react SPA (multitenant) app? I see a number of confusing answers around, including some that seem more like hacks than solutions. 

Here's my problem. I have a service and an app registered in azure.  

- If I log in with an admin user, I get the prompt to consent to the usage, and once I agree I end up with "_AADSTS9002325: Proof Key for Code Exchange is required for cross-origin authorization code redemption._". This repeats (including the consent prompt, on every login)

- If I log in with a non-admin user, I get another exception "_AADSTS650052: The app needs access to a service ('api://XXX') that your organization 'ca7981a2-....etc' has not subscribed to or enabled. Contact your IT Admin to review the configuration of your service subscriptions._"

I am using a fairly barebone client downloaded from the azure Quickstart blade. I also added my app to the service as a known client, on the AAD side. I granted admin consent for the default directory (I'm logging in to the same domain where the client and APIs are registered)

So question is, how do I get this set up properly, using best security practices, including not storing secrets in plain text?

I did follow [this guide](https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-react), but I must be missing something.

### MSAL Configuration

```javascript
auth: {
        clientId: "dcbf047b-<REMOVED>",
        authority: "https://login.microsoftonline.com/common",
        redirectUri: "http://localhost:3000/redirect"

    },
    cache: {
        cacheLocation: "sessionStorage", 
        storeAuthStateInCookie: false, Edge
    }
```

### Relevant Code Snippets

```javascript
{
	"id": "d3fa084d-<REMOVED>",
	"acceptMappedClaims": null,
	"accessTokenAcceptedVersion": null,
	"addIns": [],
	"allowPublicClient": null,
	"appId": "dcbf047b-<REMOVED>",
	"appRoles": [],
	"oauth2AllowUrlPathMatching": false,
	"createdDateTime": "2021-05-27T20:17:42Z",
	"disabledByMicrosoftStatus": null,
	"groupMembershipClaims": "DirectoryRole",
	"identifierUris": [],
	"informationalUrls": {
		"termsOfService": null,
		"support": null,
		"privacy": null,
		"marketing": null
	},
	"keyCredentials": [],
	"knownClientApplications": [],
	"logoUrl": null,
	"logoutUrl": null,
	"name": "Test Client App",
	"oauth2AllowIdTokenImplicitFlow": false,
	"oauth2AllowImplicitFlow": false,
	"oauth2Permissions": [],
	"oauth2RequirePostResponse": false,
	"optionalClaims": {
		"idToken": [
			{
				"name": "groups",
				"source": null,
				"essential": false,
				"additionalProperties": []
			}
		],
		"accessToken": [
			{
				"name": "groups",
				"source": null,
				"essential": false,
				"additionalProperties": []
			}
		],
		"saml2Token": [
			{
				"name": "groups",
				"source": null,
				"essential": false,
				"additionalProperties": []
			}
		]
	},
	"orgRestrictions": [],
	"parentalControlSettings": {
		"countriesBlockedForMinors": [],
		"legalAgeGroupRule": "Allow"
	},
	"passwordCredentials": [
		{
			"customKeyIdentifier": null,
			"endDate": "2021-11-27T21:24:59.409Z",
			"keyId": "f78dc345-c7fe-4233-a9c4-10947afca177",
			"startDate": "2021-05-27T20:24:59.409Z",
			"value": null,
			"createdOn": "2021-05-27T20:25:03.4717029Z",
			"hint": ".oY",
			"displayName": "Default App Secret"
		}
	],
	"preAuthorizedApplications": [],
	"publisherDomain": "<REMOVED>.com",
	"replyUrlsWithType": [
		{
			"url": "http://localhost:3000/redirect",
			"type": "Spa"
		}
	],
	"requiredResourceAccess": [
		{
			"resourceAppId": "600d1c38-<REMOVED>",
			"resourceAccess": [
				{
					"id": "f14dd9fb-<REMOVED>",
					"type": "Scope"
				}
			]
		},
		{
			"resourceAppId": "00000003-0000-0000-c000-000000000000",
			"resourceAccess": [
				{
					"id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
					"type": "Scope"
				}
			]
		}
	],
	"samlMetadataUrl": null,
	"signInUrl": null,
	"signInAudience": "AzureADMultipleOrgs",
	"tags": [],
	"tokenEncryptionKeyId": null
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by derisen** [comment]
@vpopescu the first error usually occurs when you select "Web" instead of "Single-page application" on the **Authentication** blade on Azure portal. But I see from your manifest that you have already selected "Single-page application" (i.e. `replyUrlsWithType`). It might be that the changes require some time to take effect, if you have recently switched from web to spa (also a good idea to check if this `clientId` you use in the react app is the right one).

The second error is a consent issue, basically until the admin user consents to your spa + web API, the user from tenants other than the home tenant cannot access the web API, as the service principles are not provisioned yet. So once the first error is resolved and admin user can sign-in and consent, this second error should not occur.

See this sample for a [React SPA calling a web API](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/3-Authorization-II/1-call-api). I see that you are using security groups, so this sample can also come in handy: [React SPA using security groups for access control](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/5-AccessControl/2-call-api-groups)

For not storing client secrets in your code, you can use [Azure Key Vault](https://docs.microsoft.com/en-us/azure/key-vault/general/basic-concepts). I don't know what's your language/framework for the backend (React app will not have any client secret), but if it's Node.js you can check the [documentation here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/key-vault-managed-identity.md) (this is for certificates instead of client secrets, but the approach is the same) and see an [example here](https://github.com/Azure-Samples/ms-identity-javascript-nodejs-tutorial/tree/main/3-Deployment#enable-your-web-app-to-get-secrets-from-key-vault-using-managed-identity).

**Comment by vpopescu** [comment]
Thank you. That was after a few hours of trying, so any changes should've taken effect. However I just deleted the app and recreated it, making sure it's set to SPA and never Web, and I still see the same issue.

I also see the following in the audit log, if it helps any:

```
ACTIVITY TYPE
Add app role assignment grant to user
STATUS
Failure
STATUS REASON
Microsoft.Online.DirectoryServices.UniqueKeyPropertyException
```
Unfortunately I don't know what it is referring to?

I will hack around a bit more, thank you.

**Comment by derisen** [comment]
@vpopescu no worries : ) What would help here is the logs generated by msal-react (which will appear in your browser's console). Can you share them?

Also, you have set your `redirectUri` to `http://localhost:3000/redirect` -is that page actually running msal-react? (the tutorial suggests to set it to `http://localhost:3000/`)

**Comment by vpopescu** [comment]
I somehow got part of it to work, but I don't know how just yet, still looking into it. Could it have something to do with the fact that I was using a Global Admin that was external to the directory? For example, me_live.com#EXT#@mydomain.onmicrosoft.com?

I created a global admin in the domain (me@mydnsname.com), and it still got the PKCE error, but it managed to grant admin consent somehow.

I am sure I am going to run into this again, and I will capture the console log. Thank you!
