### ISSUE TITLE
How do I get an authorization code from the library?

### ISSUE THREAD

**Issue by gaut7** [AzureAD/microsoft-authentication-library-for-js#3702]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

I did all the configuration as mentioned in the instruction but why after calling "loginpopup' or "loginredirect" method I am getting an **access token** instead of **auth code**. In my use case, I want to create auth code 1st and then will send this auth code to the backend server to generate other tokens(access, refresh).

One more confusing point is that even after authentication why I am getting only "access token" instead of "access token" and "refresh token" token both. I can see these values in cache though.

### Source

External (Customer)

**Comment by pkanher617** [comment]
@gaut7 The msal-browser library is meant for browser-based authentication for Single-Page applications, which is why all AuthNZ is done inside the browser. For a server-side flow, you can use the [msal-node library](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node).

**Comment by pkanher617** [comment]
> One more confusing point is that even after authentication why I am getting only "access token" instead of "access token" and "refresh token" token both. I can see these values in cache though.

The library takes care of token renewal, so the refresh token is not returned. This is something done in most MSAL libraries.

**Comment by cwardcode** [comment]
@pkanher617 My use case involves taking the refresh token, access token, and identity token and shipping it somewhere else so that it can be used to re-authenticate outside of the web app. Something like using device code flow doesn't work in my case, because the initial configuration must be made from the SPA. In this case, being able to retrieve the refresh token is essential so that I do not have to re-implement the authentication flow myself. It seems really interesting to me that the refresh token isn't exposed even though it's returned from the token endpoint. I don't believe "the library takes care of it, which is why we expose it" is an acceptable answer.
