### ISSUE TITLE
silent_sso_error after changing to new policy

### ISSUE THREAD

**Issue by code-by-gijs** [AzureAD/microsoft-authentication-library-for-js#3709]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.11.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Description

Last week we have changed our adb2c login policy to a new policy and we are now facing a problem with users unable to login. The `acquireTokenSilent` function throws an error: `silent_sso_error`. Users are not able to login again without logging out first. Unfortenently the `silent_sso_error` is quite generic. If I check the api call that `aquireTokenSilent` made, I can see that it has a specific error:
```
{
	"error": "invalid_grant",
	"error_description": "AADB2C90088: The provided grant has not been issued for this endpoint. Actual Value : B2C_1_signin_v2 and Expected Value : B2C_1_signin_v3\r\nCorrelation ID: ##HIDDEN##\r\nTimestamp: 2021-06-03 08:40:51Z\r\n"
}
```

Is there a way to get access to the `error_description`, containing the real error code (AADB2C90088) in the `aquireTokenSilent` exception? At this point it seems impossible to aquire the original error code. I know that it is possible in the `handleRedirectPromise`, that exception does throw the original error code.

Any thoughts? Thanks!

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
@code-by-gijs It looks like there's a couple things going on here. First, it looks like you're trying to use the refresh token for policy `B2C_1_signin_v2` to acquire a new access token for policy `B2C_1_signin_v3`. This is not supported and what the AADB2C90088 server error is trying to tell you. Second, when this fails `acquireTokenSilent` will fallback to calling `ssoSilent` to attempt an iframe renewal. This is throwing the `silent_sso_error` because either you haven't provided a `loginHint` or the account you are trying to use does not have a username property (this description should be returned in the error description, is it not?)

To resolve the main issue you should make an interactive login call when you try to switch to the new policy for the first time. You cannot use the account object for your `v2` policy to acquire tokens for your `v3` policy. You can inspect `account.idTokenClaims.acr` or `account.idTokenClaims.tfp` to determine which policy the account object belongs to.

To resolve the `silent_sso_error` you should enable your policy to return the username claim on idTokens, you can find instructions for that [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#why-is-getaccountbyusername-returning-null-even-though-im-signed-in)

**Comment by code-by-gijs** [comment]
Thank you for your response. I didn't know it was falling back to `ssoSilent`. But I think that call fails because the browser doesn't support third party cookies.

I'm now using `account.idTokenClaims.tfp` to determine if the policy is correct. Thanks for the help!

**Comment by tnorling** [comment]
> Thank you for your response. I didn't know it was falling back to `ssoSilent`. But I think that call fails because the browser doesn't support third party cookies.

The error you were getting was a configuration error and was thrown before it even tried to open an iframe. But yes this step would be expected to fail if 3rd party cookies are blocked.

> PS: wouldn't it be nice to actually have the AADB2CXXXX codes available in `acquireTokenSilent`? Just like it is in `handleRedirectPromise`?

In most cases `acquireTokenSilent` actually will return the server error. However, invalid_grant errors can be resolved by acquiring a new auth code and exchanging for new tokens so `acquireTokenSilent` will quietly try to resolve this error using `ssoSilent`. Usually if `ssoSilent` fails (due to 3rd party cookies or other) it should throw an `interaction_required` error which is your cue to call an interactive method. In your case there was another issue that caused this step to fail prematurely so you didnt get the `interaction_required` error.
