### ISSUE TITLE
Fragment redirect

### ISSUE THREAD

**Issue by semihucari** [AzureAD/microsoft-authentication-library-for-js#3767]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.0

### Description

Hi, I created the exact flow @jasonnutter described here https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2531#issuecomment-770110059. Since I am using react-router and azure portal doesn't allow redirect uris with fragments, we created a redirect api to land on the desired pages after redirect. The problem is, since the redirect url has fragments instead of queries (in the form #code=....), the server can't read the part with #code=....., and it can't pass it back to the UI. As a result, handleRedirectPromise() is called with a null result value, and I can't set the msal active account from this value. Am I missing something or can you suggest me a workaround for this?

### MSAL Configuration

```javascript
auth: {
        clientId: "97d488cd-0129-418e-a928-714f227d7ba2",
        authority: "https://login.microsoftonline.com/common",
        redirectUri: `${window.location.origin}/somewhere/manager/azure_oauth_sso_callback`,
        postLogoutRedirectUri: "/"
    },
    cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: false
    }
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@semihucari 

>  The problem is, since the redirect url has fragments instead of queries (in the form #code=....), the server can't read the part with #code=....., and it can't pass it back to the UI.

The response being passed back in the fragment instead of a the query parameter (and thus not being readable by the server) is by design. MSAL.js will understand how to parse the response (when `handleRedirectPromise` is invoked), validate it, and then trade the auth code for tokens (or throw an error). 

Your page used as the redirect should invoke `handleRedirectPromise` and not attempt to clear the hash from the url (MSAL will do that once it has been processed).

**Comment by semihucari** [comment]
The redirecturl is set to somewhere in the server since I couldn't put fragments in the azure portal redirect urls (fragments for react-router library). Are you saying that the server can pass the fragment part (fragment for msal auth) back to the client side? Sorry I didn't know its possible, I will try thanks.

**Comment by jasonnutter** [comment]
@semihucari 

> The redirecturl is set to somewhere in the server since I couldn't put fragments in the azure portal redirect urls (fragments for react-router library). 

The reason why fragments aren't support in redirect uris is because AAD needs to send back the response in the fragment.

> Are you saying that the server can pass the fragment part (fragment for msal auth) back to the client side? Sorry I didn't know its possible, I will try thanks.

And no, the url fragment is not send to the server, so this is not possible. Why do you want the response sent to your server?

If you require that the redirect response be sent to your server, as opposed to being processed client-side by MSAL.js, you will need to use a library such as MSAL Node which supports initiating and processing requests server-side.

For scenarios like yours where you are using hash-based routing, we recommend using a redirect URI that does not have a hash (such as your home page, or a dedicated html page), and then enabling `navigateLoginRequestUrl` which will tell MSAL to navigate back to the page that initiated the login request.

**Comment by semihucari** [comment]
Thanks for the fast replies and thanks your time, that helped a lot.
