### ISSUE TITLE
How do I connect my app to Active Directory using Msal? 

### ISSUE THREAD

**Issue by md56n** [AzureAD/microsoft-authentication-library-for-js#3795]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

I've followed the documentation but I'm still having trouble setting up a user sign in. What am I missing?

### MSAL Configuration

```javascript
in app.module.ts:

export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: '[Application (client) ID]',
      redirectUri: '[Application ID URI]'
    }
  })
}

providers: [
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory
    },
    MsalService
  ]
```

### Relevant Code Snippets

```javascript
in app.component.ts:

 login() {
    this.msalService.loginPopup().subscribe( (response: AuthenticationResult) => {
      this.msalService.instance.setActiveAccount(response.account)
    });
  }

  logout() {
    this.msalService.logout();
  }

  isLoggedIn() : boolean {
    return this.msalService.instance.getActiveAccount() != null;
  }
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by md56n** [comment]
The console doesn't get any msal logs.
Right now I'm getting this error:

Sorry, but we’re having trouble signing you in.
AADSTS700016: Application with identifier '[correct id]' was not found in the directory '[wrong directory id]'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

**Comment by derisen** [comment]
@md56n to get the msal logs you'll need to set the [logger](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md) to `verbose` mode, like:

```typescript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: '[Application (client) ID]',
      redirectUri: '[Application ID URI]'
    },
    system: {
        loggerOptions: {
            loggerCallback(logLevel: LogLevel, message: string) {
                console.log(message);
            },
            logLevel: LogLevel.Verbose,
            piiLoggingEnabled: false
        }
    }
  })
}
```

Regardless, the error you're getting is telling you that this application (client/app id) has not been [added/provisioned](https://docs.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals) to this tenant (directory id). This happens if the user that is trying to login does not have permissions to add this application into their tenant. A tenant admin needs to do that before non-admin users will be able to sign-in.

So the first thing to check the Azure AD App registration portal to see if the client Id and tenant (directory) Id you have is correct. You've mentioned that the directory Id in the error is wrong. But you didn't specify a tenanted authority in your app configuration, so msal is defaulting to the `/common` endpoint (indicates that the app is [multi-tenant](https://docs.microsoft.com/en-us/azure/active-directory/develop/single-and-multi-tenant-apps)). Is your application configured to be multi-tenant on Azure AD app registration portal? If you didn't mean it to be, you can specify a tenanted authority endpoint as shown below:

```typescript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: '[Application (client) ID]',
      authority: "https://login.microsoftonline.com/ENTER_TENANT_ID_HERE"
      redirectUri: '[Application ID URI]'
    }
  })
}
```


I would recommend following the tutorial [here](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial) for getting comfortable with the basics. See [this section](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/6-Multitenancy/1-call-api-mt) in particular for multi-tenant use case.

**Comment by md56n** [comment]
I changed all of that but now I'm getting this error:
AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '[client id]'.

I directly copied the redirectUri from under the authentication tab so I'm not sure why it says they don't match.

**Comment by derisen** [comment]
@md56n might be a good idea to restart the app and clear browser cache for the app. Occasionally, changes on App registration portal might take a few minutes to take effect.

**Comment by md56n** [comment]
I did that but I'm still having the same issue. Is there some setting in Azure that could be changing that?

**Comment by derisen** [comment]
@md56n there's really not much chance of this happening other than a mismatch between what's on App registration portal (Authentication blade) and what's on your msal app configuration (redirectUri).

![sdf](https://user-images.githubusercontent.com/13197548/123474961-98886200-d5af-11eb-9595-ce61541f6325.png)

If the issue persists, can you capture the network traffic with [Fiddler](https://www.telerik.com/fiddler) and send me a trace? You can find my email on my GitHub profile page.

**Comment by md56n** [comment]
The only time I get a different result is when both urls are /.auth/login/aad/callback which causes this:
The page cannot be displayed because an internal server error has occurred.

Do you know why this could be happening?

**Comment by derisen** [comment]
@md56n are you using Azure App Service? Is the app deployed there? If so, make sure to disable the authentication service on App Service portal:

![disable_easy_auth](https://user-images.githubusercontent.com/13197548/123486021-266c4900-d5c0-11eb-826b-af6d250fef56.png)

Otherwise please send us a Fiddler trace and a link to public repository if you can.

**Comment by md56n** [comment]
I do have it deployed. Unfortunately, I don't have the option to turn that off. The page just says "This app is configured using the new authentication experience". The closest option I can find is toggling between "require authentication" and "allow unauthenticated access"

**Comment by derisen** [comment]
That explains! So I wonder why you needed the msal in the first place. The authentication service on the App Service is a no-code alternative to msal -so they shouldn't be used together. You need to decide between the two. If you like to keep using msal, just check the "allow unauthenticated access".

Can you mention the documentation you initially followed? Sounds like its misleading.
