### ISSUE TITLE
Clicking back button in browser after login throws an error

### ISSUE THREAD

**Issue by a2441918** [AzureAD/microsoft-authentication-library-for-js#3813]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

I have a login screen which has a button. I click the button and it calls loginRedirect with the config. I enter my credentials and I am successfully authenticated and I enter the app. However, when I click the back button on the browser, I get an error.

![image](https://user-images.githubusercontent.com/4927454/123823490-3f7c3f00-d8cb-11eb-945e-51a0ff5ae448.png)

What should be the ideal way of handling this?

Please advice.

### Error Message

AADSTS90014: The required field 'request' is missing from the credential. Ensure that you have all the necessary parameters for the login request.

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
  auth: {
    clientId: CLIENT_ID,
    authority: AUTHORITY,
    redirectUri: REDIRECT_URI,
    postLogoutRedirectUri: REDIRECT_URI,
  },
  cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage,
    storeAuthStateInCookie: false,
  },
};
```

### Relevant Code Snippets

```javascript
<AuthenticatedTemplate>
        {componentToRender}
      </AuthenticatedTemplate>
      <UnauthenticatedTemplate>
        <Login />
      </UnauthenticatedTemplate>
```

### Reproduction Steps

1. Login to app
2. Click browser back button

### Expected Behavior

Logout user and show login screen??

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by tnorling** [comment]
@hpsin Any ideas? Have you seen this before?

**Comment by hpsin** [comment]
The login flow is a path-dependent flow, so going back takes you to the same page via the wrong path, leading to errors like this.  There are two options I think:
1. We (Azure AD) make a change to edit the back stack while navigating through so that hitting back takes you to the original sign in page, rather than an intermediate step. 
2. The app manipulates the back stack, so that hitting back doesn't take you to AAD. 

What is the user goal here when hitting the back button? Do they want to sign in with a different user account?

**Comment by a2441918** [comment]
@tnorling @hpsin Apparently, it looks like we are experiencing the same behavior in portal.azure.com as well as office.com

Is this expected or should we do something about it?

https://www.loom.com/share/f790f454d5864e478876892c3376e3f4

**Comment by tnorling** [comment]
@hpsin 
> The app manipulates the back stack, so that hitting back doesn't take you to AAD.

Correct me if I'm wrong, but this wouldn't be a viable solution as the app has already fully redirected to AAD before AAD starts its own redirects. We can prevent the first page (e.g. https://login.microsoftonline.com/common) from being added to the browser history but after that it's in AAD's hands.

It sounds to me like option 1 is the solution here: change server-side behavior to essentially start over from the sign-in page when the back button is clicked mid sign-in

**Comment by tnorling** [comment]
@a2441918 We've opened a ticket on the AAD service to change the behavior when a user clicks the back button so that they're not presented with a confusing error. It should be noted that clicking the back button in the middle of the auth flow is unsupported, and even after this change may not result in a successful sign-in. 

If the desire is to change the account you're signing in with, the guidance is to let the in progress sign-in complete and then initiate a new sign in with `prompt: "select_account"` or `prompt: "login"` to be presented with the account selection screen again.

As this issue is about server behavior and does not require changes on MSAL.js I'm going to close this. Please feel free to open a new issue with any further questions regarding MSAL.js. Thanks!
