### ISSUE TITLE
Next Login No authentication required after the user logs out

### ISSUE THREAD

**Issue by blackmo18** [AzureAD/microsoft-authentication-library-for-js#3815]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

User Automatically Logins after the user Tries to logout

### MSAL Configuration

```javascript
{
    auth: {
        authority: signInAuthority,
        clientId: applicationID,
        redirectUri: reactRedirectUri,
        postLogoutRedirectUri: reactRedirectUri,
        validateAuthority: false,
        navigateToLoginRequestUrl: true,
    },
    cache: {
        cacheLocation: 'sessionStorage',
        storeAuthStateInCookie: true
    }
}
```

### Relevant Code Snippets

```javascript
{
// Authentication Parameters
    scopes: [
        `${applicationID}`
    ]
}
```

### Reproduction Steps

1. setup react project using next js in sample
2. replace authConfig with the msal configuration stated above
3. login an account
4. logout an account
5. login the same account

// at step 5 the user is no longer asked by email and password authentication

### Expected Behavior

The User Should be prompt with Input Email/Password

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Regression

@azure/msal-browser 2.14.0

### Source

External (Customer)

**Comment by tnorling** [comment]
@blackmo18 Are you signing in with a "local" account or a federated account through an external identity provider (Google, Facebook, etc)? This is expected behavior for federated accounts as documented [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/working-with-b2c.md#b2c-and-sign-out-experience) and [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#i-logged-out-of-my-application-why-am-i-not-asked-for-credentials-when-i-try-to-log-back-in)

**Comment by blackmo18** [comment]
@tnorling we are using our Identity Provider, do we have already a solutions for this?

I tried upgrading the msal to 14.2 but I got issues with known authorities.

**Comment by tnorling** [comment]
@blackmo18 The reason this doesn't work as you expect is that when you sign out of app A it doesn't mean you also want to sign out of App B, C and D that use the same account. When you call logout B2C will clear it's own session cookies but your downstream Identity Provider will not, in order to allow other applications to remain signed in. Now when you try to log back in, your Identity Provider will tell B2C you are signed in and B2C will re-establish the session without asking you for credentials again. If you do wish to completely logout of your Identity Provider you'll need to edit your custom policy to call the Identity Provider's logout endpoint. This is something [B2C Support](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options) can help you with if you choose to go that route.

> I tried upgrading the msal to 14.2 but I got issues with known authorities.

knownAuthorities has always been a requirement to use B2C, I would be surprised if upgrading caused this. Please see the example configuration in the [working with B2C doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/working-with-b2c.md#b2c-app-configuration) for details on how to properly configure MSAL to use B2C.

**Comment by blackmo18** [comment]
I gonna close this issue, since the behavior is expected. Nonetheless thank you for the response.

**Comment by blackmo18** [comment]
@tnorling this might not be related, but the thing is once i logout i can see the session is cleared, but when ever i got redirected after i rel ogin (no authentication anymore) it goes to `<UnauthenticatedTemplate>....</UnauthenticatedTemplate>`

i use this for login
```typescript
    if (!login && inProgress == 'none') {
      instance.loginRedirect(authenticationParameters)
    }
```

any ideas, since its working fine if not used with identity provider

**Comment by tnorling** [comment]
@blackmo18 You're right this is likely a different issue but I would need more information to understand what is happening. Can you first try to reproduce this with our [b2c sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/b2c-sample) and if you're seeing the same issue there or if you need help understanding what you're doing differently please open a new issue and we would be happy to help you figure it out.

**Comment by blackmo18** [comment]
Right now I am using `const isAuthenticated = useIsAuthenticated()` to check whether i am really have correct token
and clear all token info cached on the app side before relogin, and whenever i am in unauthenticated template redirect back to login.

it works for now, ill post another issue if i have another unusual behavior related to this

```
    if (!isAuthenticated && inProgress == 'none') {
      setShow(true)
      instance.loginRedirect(authenticationParameters)
    }
```
```<UnauthenticatedTemplate><Login/></UnauthenticatedTemplate>```

thanks
