### ISSUE TITLE
setting navigateToLoginRequestUrl  true, the redirect url flicker

### ISSUE THREAD

**Issue by rash09** [AzureAD/microsoft-authentication-library-for-js#3818]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

4.4.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

I am redirecting the user to MSAL Edit profile page, upon editing the page and redirecting back to my application, i want the user to redirect back to Edit profile page in my application for which i have set navigateToLoginRequestUrl:true. But while redirecting back to my application the page starts flicker ! If navigateToLoginRequestUrl is set to false the flicker does not happen.

### Error Message

Unhandled Rejection (ChunkLoadError): Loading chunk 13 failed.

### MSAL Configuration

```javascript
auth: {
    clientId: "9ef81a41-e128-4e84-aa7e-60f010762c27",
    authority:
      "<ul>",
    knownAuthorities: [<tenant name>],
    redirectUri: "http://localhost:3000/",
    postLogoutRedirectUri: "http://localhost:3000/",
    validateAuthority: false,
    navigateToLoginRequestUrl:true
  }
```

### Relevant Code Snippets

```javascript
import { useMsal} from "@azure/msal-react";

export default function Profile() {
 const { instance, accounts } = useMsal();
 const name = accounts[0] && accounts[0].name;

const editProfile = () => {
        instance.loginRedirect(editProfileRequest)
    };

return(....)
}


export const editProfileRequest = {
  authority: "<Tenant-name >/B2C_1_editProfile"
}



```

### Reproduction Steps

1. Login to application
2. Go to profile page
3. click on edit profile
4. User redirected to B2C edit profile page
5. Edit user profile
6. Click on "continue" button
7. User redirected to application
8. The page will start to flicker 

### Expected Behavior

The user should be redirected to the same page not to the homepage.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
@rash09 Can you please share a video/gif of this flickering? Could you also please send me a fiddler trace of the network activity when this happens? You can reach out to me over Teams or email it to me. Thanks!

**Comment by tnorling** [comment]
@rash09 Thanks for emailing me the video. It looks like you're getting stuck in a loop between the homepage and `/profile`. Since you're setting `navigateToLoginRequestUrl: true` your flow should look something like this:

`http://localhost/profile` -> B2C edit profile page -> `http://localhost/` -> http://localhost/profile`

Something seems to be causing you to be auto redirected back to `/` the moment you hit the `/profile` page causing you to get stuck in a loop between those 2 pages. Do you happen to have logic in your app that may be unexpectedly sending you back to the homepage? I don't think there's a scenario where MSAL would do this but if you can turn on verbose logging and paste those logs here I can verify.

**Comment by rash09** [comment]
@tnorling , below is my logic for reactjs based SPA 
**Router file:**
```
let isAuthenticated = useIsAuthenticated();

 <Route exact path="/profile">
          {isAuthenticated ? <Profile /> : <Redirect to="/" />}
        </Route>

```

**Expected flow:**
http://localhost/profile -> B2C edit profile page -> http://localhost/profile`


So i am basically checking the isAuthenticated for each route path. 
I guess the isAuthenticated is failing or there is a delay in authenticating the user due to which the condition is switching back and forth. 

- Is there a scenario where we can expect a delay in authentication?

- Shouldn't the user be redirected to http://localhost/profile page from B2C edit profile page when the navigateToLoginRequestUrl is set to **_true_**

**Comment by tnorling** [comment]
@rash09

> So i am basically checking the isAuthenticated for each route path.
> I guess the isAuthenticated is failing or there is a delay in authenticating the user due to which the condition is switching back and forth.
> 
> * Is there a scenario where we can expect a delay in authentication?

This is why you're getting stuck in a loop. `useIsAuthenticated` will always return `false` on the first render. This is because MSAL needs to perform a few initialization steps, and in the case of coming back from a redirect, process the response from the server. In order to fix this you should not redirect to the homepage if the `inProgress` value from the `useMsal` hook is not equal to `InteractionStatus.None`.

Rough example of logic that may fix your issue: 

```javascript
const isAuthenticated = useIsAuthenticated();
const { inProgress } = useMsal();

if (isAuthenticated) {
  return <Profile />
} else if (inProgress === InteractionStatus.None) {
  return <Redirect to="/" />;
} else {
  return null;
}
```

> * Shouldn't the user be redirected to http://localhost/profile page from B2C edit profile page when the navigateToLoginRequestUrl is set to **_true_**

The server will always redirect back to whatever you set as your `redirectUri`. `navigateToLoginRequestUrl` only tells MSAL if it should perform an **additional** redirect back to the page that initiated the request. If you wish to be returned back to the `/profile` page directly from the server, without first going through the homepage, you should set your `redirectUri` to `http://localhost/profile` (which you also would need to register on your app registration in the portal). In this case `navigateToLoginRequestUrl` would be irrelevant as the `redirectUri` and the initial page would be one and the same.

**Comment by rash09** [comment]
@tnorling , The above solution seems to be working after adding the **_inProgress_** router login and **_navigateToLoginRequestUrl_** set to **true**, but i am facing different issue now with this logic in place. 
http://localhost/profile -> B2C edit profile page
When i click on edit profile link, 

1. The component gets re-rendered before redirecting to B2C edit profile page
2. Once returned back to profile page, i get the token error (400 error)

Note: If i set navigateToLoginRequestUrl to false, i dont get the above issues.


_Also if MSAL can provide a detailed documentation(what methods are called in background, architecture of authorization) on the token and the user flow would be helpful, as currently at times we are clueless what is happening. A detailed documentation is required._

**Comment by tnorling** [comment]
@rash09 

> The component gets re-rendered before redirecting to B2C edit profile page

This is expected as the `inProgress` value will change when you invoke interaction. I would not expect `navigateToLoginRequestUrl` to affect this as this flag is used **after** authentication. Can you clarify why the re-render is an issue?

> Once returned back to profile page, i get the token error (400 error)

Can you provide more detail around this error? You can email me a fiddler trace.

> Also if MSAL can provide a detailed documentation(what methods are called in background, architecture of authorization) on the token and the user flow would be helpful, as currently at times we are clueless what is happening. A detailed documentation is required.

I'm not sure what you mean by "methods called in the background" but is [this](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow) helpful?
