### ISSUE TITLE
How to configure scopes for an app which hosts both the api and front end on a single app service

### ISSUE THREAD

**Issue by Raffledoocious** [AzureAD/microsoft-authentication-library-for-js#3845]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

I have a .Net Core hosted Web API which also serves the Angular front end. This app is deployed on a single app service in production. Before upgrading to the 2.x version of the MSAL library, we have been able to request scopes and get valid tokens back to validate users.

After upgrading and keeping the same protected resource maps, the tokens I am getting back instead have an 'aud' of the Graph endpoint - "00000003-0000-0000-c000-000000000000". The issuer is also "iss": "https://sts.windows.net/3f9cd7a0-127a-4ed4-bf06-2f830d5616b7/".  Before we changed libraries, the token looked to be correctly set as shown below.

// previous bit of token returned
{
  "typ": "JWT",
  "alg": "RS256",
  "kid": "nOo3ZDrODXEK1jKWhXslHR_KXEg"
}.{
  "aud": "bac1edeb-ec0c-4759-b086-a5e5acf8e3c8",
  "iss": "https://login.microsoftonline.com/3f9cd7a0-127a-4ed4-bf06-2f830d5616b7/v2.0",
  "iat": 1625711125,
  "nbf": 1625711125,
  "exp": 1625715025,
  "aio": 

What is the proper way to configure an AAD application if the application is hosting both the API and front end in the same service? I have been unable to find documentation around this exact scenario. Am I setting up my Angular app correctly? 

This is the 'Expose an API' portion of the Azure AD app.

![image](https://user-images.githubusercontent.com/1238728/124853328-8963c580-df5a-11eb-8acb-5a475c133c3c.png)

I've confirmed I'm getting back a valid ID token. Originally we were using the 'roles' portion of this ID token to let users access certain routes in the API backend.

Let me know if you need any other screenshots or more information.

### MSAL Configuration

```javascript
MsalModule.forRoot( new PublicClientApplication({ // MSAL Configuration
      auth: {
        clientId: environment.azureActiveDirectory.clientId,
        authority: environment.azureActiveDirectory.authority,
        redirectUri: environment.azureActiveDirectory.redirectUrl,
        navigateToLoginRequestUrl: true
      },
      cache: {
        cacheLocation : BrowserCacheLocation.LocalStorage,
      },
      system: {
        loggerOptions: {
          piiLoggingEnabled: false
        }
      }
    }), {
      interactionType: InteractionType.Redirect, // MSAL Guard Configuration
    }, {
      interactionType: InteractionType.Redirect, // MSAL Interceptor Configuration
      protectedResourceMap: new Map([
        [ environment.apiBase, ['openid'] ],
        [ environment.odataBase, ['openid'] ]
      ]) 
    })
  ],
```

### Relevant Code Snippets

```javascript
// environment.ts
export const environment = {
  azureActiveDirectory: {
    authority: 'https://login.microsoftonline.com/3f9cd7a0-127a-4ed4-bf06-2f830d5616b7',
    clientId: 'bac1edeb-ec0c-4759-b086-a5e5acf8e3c8',
    redirectUrl: 'http://localhost:4200',
  },
  production: false,
  apiBase: 'http://localhost:52547/api',
  odataBase: 'http://localhost:52547/odata'
};
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by derisen** [comment]
@Raffledoocious in your `protectedResourceMap`, the scope you are requesting for the resource `environment.apiBase` is openid, which gets you an ID token and an Access Token for [graph user_info endpoint](https://docs.microsoft.com/en-us/azure/active-directory/develop/userinfo). Can you replace it with the scope you exposed during app registration (the first screenshot) and give it a try again?

**Comment by Raffledoocious** [comment]
I've tried this but then I get an error from requesting the token to the line of 

ERROR ServerError: invalid_client: AADSTS650053: The application 'Backup iFrame 2.0' asked for scope 'user_impersonation' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'. Contact the app vendor.
Trace ID: bd31efd3-be8c-48a4-9bb4-4f11b6cf8500

I feel I am missing something to protect this resource. The MSAL 1.0 library was behaving where we'd get a token but then it seemed like the identity_token was being pushed on every request to our API. We could get our AAD group info right from it.

This is how my app was configured previously with MSAL Angluar 1.0. Am I missing a configuration step?  The configuration in environment.ts remains unchanged.

```
function MSALConfigFactory(): Configuration {
  return {
    auth: {
      clientId: environment.azureActiveDirectory.clientId,
      authority: environment.azureActiveDirectory.authority,
      validateAuthority: true,
      redirectUri: environment.azureActiveDirectory.redirectUrl,
      navigateToLoginRequestUrl: true
    },
    cache: {
      cacheLocation: 'localStorage'
    },
    system: {
      logger: new Logger(loggerCallback, {
        level: LogLevel.Verbose,
        piiLoggingEnabled: false,
      })
    }
  };
}

function MSALAngularConfigFactory(): MsalAngularConfiguration {
  return {
    popUp: false,
    protectedResourceMap: [
      [ environment.apiBase, ['openid'] ],
      [ environment.odataBase, ['openid'] ],
    ]
  };
}
```

**Comment by derisen** [comment]
> I've tried this but then I get an error from requesting the token to the line of
> 
> ERROR ServerError: invalid_client: AADSTS650053: The application 'Backup iFrame 2.0' asked for scope 'user_impersonation' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'. Contact the app vendor.
> Trace ID: bd31efd3-be8c-48a4-9bb4-4f11b6cf8500

Is your scope named `user_impersonation`? The app ID URI before the scope is also needed. Can you try setting your `protectedResourceMap` like: 

`[ environment.apiBase, ['https://xxxxx/xxxxxxxxxxxxxx/user_impersonation'] ],`

Also, your app ID URI suggests that your app is multi-tenant (in single tenant apps the form is usually like `api://<app_id>/<scope_name>`), however your configuration looks like the app signs in users using the tenanted authority (`https://login.microsoftonline.com/3f9cd7a0-127a-4ed4-bf06-2f830d5616b7` instead of `https://login.microsoftonline.com/common`). This is why the issuer is `https://sts.windows.net` instead of `https://login.microsoftonline.com`  i.e. you are getting a [v1 access token](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#v10-and-v20).

> To expound on my use case more. I am receiving the ID token I expect back and it has the group information I need. Is the right thing to do to change where my API validates the token to match Graph issuer, aud etc? 

Definitely not. Something is wrong here. If the suggestion above does not work either, can you send me a network trace using [Fiddler](https://www.telerik.com/fiddler). You can find my email on my [GitHub profile](https://github.com/derisen)? If you have a public repository that hosts your code, that would also be helpful.

> Or pass in the ID token to my API since they are on the same server?

I wouldn't recommend this. The Id token is meant for the client app and shouldn't be used for accessing resources. Access token is the way to go. You can have all the roles and groups information in an access token just like in an ID token.

**Comment by snebjorn** [comment]
I believe I'm having a similar issue.

I updated from msal-angular v1 to v2 and now I'm getting access tokens (v1 tokens) instead of id tokens (v2 tokens) for the protected resource urls that define the openid scope.

```js
protectedResourceMap: [
  ['my-url', ['openid']],
]
```

There's even a comment in the source code suggesting that when the `openid` scope is included it'll get an idToken
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/b154798bdd7b4e2ee0b80d8f6a4292b48ebef873/lib/msal-angular/src/msal.interceptor.ts#L67

If this is not the intended way to control whether a resource should receive a v1 or v2 token, then please advice :)

**Comment by Raffledoocious** [comment]
@derisen oh AWESOME. Changing the scope to include the full URI did fix it for me and I get a valid token back. Thank you for the very thorough explanation. I'll take a look at the documentation and see if it is something I missed and I'll respond here if I think there could be changes. I completely missed the requirement to use the full URI.

**Comment by derisen** [comment]
@Raffledoocious sounds great! Yeah please let us know if the docs are misleading, the full app Id URI + scope name should be used when requesting a token.

@snebjorn to control whether a resource should receive a v1 or v2 access tokens, you should set the `accessTokenAcceptedVersion` property in the application manifest on Azure portal (i.e.  **Azure portal** > **App Registration** > **Your app** > **Manifest**). As you recognized, `openid` scope will get you an ID token (meant for your client app) and an access token (meant for calling MS GRAPH user_info endpoint). For getting an access token for a protected resource like your web API, you shouldn't use `openid` at all. See how @Raffledoocious resolved the issue.
