### ISSUE TITLE
Make config adjustable after initialization

### ISSUE THREAD

**Issue by negberts** [AzureAD/microsoft-authentication-library-for-js#385]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Library version

<pre><code>
Library version: 0.1.0

## Current behavior
The MSAL config is initialized directly with the module and clientId of the API needs to be supplied directly in consentScopes and protectedResourceMap. However, we have a multi-tenant app where the API clientId for each tenant is stored in azure table storage. Based on the URL the tenant parameters are first retrieved, before a call to MSAL will be made. In ADAL this was no problem, because the context could be initialized at a later point, but with MSAL we have to import the module in the app.module. Then there is no chance to update the config parameters anymore before the first login call is made. 

## Expected behavior
It would be nice if the parameters for all the config items, or the config itself would be adjustable after initialization of the module. Then we can adjust things like protectedResourceMap, consentScopes with the specific tenant parameters

</code></pre>

**Comment by nehaagrawal** [comment]
@negberts  I just wanted to clarify that the only mandatory parameter that you need to pass at the time of initialization is clientId. You can pass the consentScope directly to login api . I agree that there is no way you can set the protectedResourceMap later.

**Comment by negberts** [comment]
@nehaagrawal correct! But if I want to use the authentication guard, I will not call the login method directly… So consentscopes would be nice to expose as well :-) And I was talking about the clientId of the API thats is being called, not the clientId of the application.

**Comment by sameerag** [comment]
@negberts Does API here means the resource you want to access? I am little unclear about what you meant. The clientId of the application cannot be changed post MSAL JS initialization as of today. But for any accessToken() call, I believe you can call them separately as long as the service can give the token.

Can you send some sample code on what you mean? May be that will help for us to analyze if this is a feasible requirement.

**Comment by negberts** [comment]
@sameerag I want to be able to adjust consentscopes and protectedresourcemap after initialization of the module, because at the time of module initialization I do not know these parameters yet.

**Comment by sameerag** [comment]
@negberts You should be able to. 

**Consentscopes:**

- module initialization is only for the scopes you need consent to at login, but each acquireToken() call that follows can be send newer scopes. There is a dynamic consent screen that will be displayed if you are unable to consent it prior.

- Only in the case where you do not want interaction, you have an option to pre-decide all the scopes you want the tokens for and send them in login request instead of the following accessToken requests.

- more details on how scopes work is listed in our [scopes-readme](https://github.com/AzureAD/microsoft-authentication-library-for-js#2-login-the-user)

**protectedresourcemaps:**
Did you get a chance to try out our new msal 1.0.0 release? This is not yet supported for angular (which is planned for this summer - [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap), but we have a 'response' object today supported in the core, which has the scopes that are consented until up the accessToken request you make: more details at [msal apichanges](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL.js-1.0.0-api-release)

If you want a specific behavior for "protectedresourcemaps" we can consider including it as we are gathering the requirements while writing the angular wrapper since this is very angular specific. Please let us know.

**Comment by negberts** [comment]
No, I did not know about a 1.0.0 release until now :) But as I am using Angular it means I have to wait until summer right? I will give it a try then. Can we keep this one open until then?

**Comment by sameerag** [comment]
@negberts Okay. We are tracking all angular issues with a tag and will close them as and when the release is made with the ask in the corresponding tickets.

**Comment by sameerag** [comment]
Tagging this with #786.
