### ISSUE TITLE
Handling authentication for multiple applications on localhost

### ISSUE THREAD

**Issue by graphicsxp** [AzureAD/microsoft-authentication-library-for-js#3884]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

1.4.11

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

I have multiple Angular applications that can be run locally on localhost:4200 (not simultaneously though).

Authentication using msal-angular 2.0  works fine for the first app when launching the `ng serve my-first-app` command. 

Then I stop `ng  serve` and I start it again for another app `ng serve my-second-app`.

This time, authentication fails with the error : `ClientAuthError: token_refresh_required: Cannot return token from cache because it must be refreshed.`

At application startup I run the following code (see snippet below). For the first app, getAllAccounts() returned nothing so I was redirected to the login page and all was fine.
When I run the second app though, getAllAccounts() return the account that was created after successful login when I ran the first app.
However this is inccorect because they are two different app, and the audience of the first one is different from the audience of the second one.

I'm not sure how this should be handled ? Is there a way to filter what getAllAccounts returns ?  What is the correct way to do this ? 

### Relevant Code Snippets

```javascript
this._authService.msalService.instance.handleRedirectPromise().then(res => {
                if (this._authService.msalService.instance.getAllAccounts().length > 0) {
                    resolve(true);

                } else {
                    this._authService.msalService.loginRedirect({ scopes: [], redirectStartPage: window.location.href });
                    reject('User is not signed in. Redirecting to login page.');
                }
            });
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @graphicsxp . This behavior is expected from `getAllAccounts` in MSAL Browser. The `getAllAccounts` API does not filter based on an application's `clientId`, but instead relies on the browser's own storage restrictions to filter by domain (localhost:4200 in this case).

In this case, since both of your angular apps are running on `localhost:4200`, the browser believes it is the same application and therefore allows App "B" access to App "A"'s cache items.

The important thing is that as long as both apps have different domains in production, this should not be a concern, since this will only happen in localhost.

For a workaround during local testing, you have two options:

1. Make sure you logout from each app before running the other app so this doesn't happen
2. Run your apps on different ports to avoid the cache "collision"

Please let us know if you have any further questions or if we can close this issue. Thanks!

**Comment by graphicsxp** [comment]
Hello @hectormmg 

In the end I chose to run each of my local apps on a different port. This solves the problem. And indeed onc deployed to different domains, there is no such issue.

thank you for the answer.
