### ISSUE TITLE
How to get the emails claim into the id token with custom policies

### ISSUE THREAD

**Issue by devbrains-com** [AzureAD/microsoft-authentication-library-for-js#3898]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

According to this code line here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/04b6bd4fd2b4a643505b525ed3d44271bcc3b654/lib/msal-common/src/cache/entities/AccountEntity.ts#L173

The username for the acquireTokenSilent request is filled by the id token "emails" claim. There is also an FAQ Section (https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#why-is-getaccountbyusername-returning-null-even-though-im-signed-in), that explains how to enable that on the B2C Configuration. But we use custom policies and I didn't find a way, how to get this claim into the id token. We have an "email" claim but not "emails".

Thank you very much for your help :)

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by derisen** [comment]
@devbrains-com would you mind raising this question at the [b2c-samples](https://github.com/azure-ad-b2c/samples) repo? This repo contains custom policy samples and can help with custom policy related issues.

**Comment by devbrains-com** [comment]
Yes sure. But why do you only read the emails claim and not the email claim? Because the email claim is set in the id token by using the default custom policies.

**Comment by derisen** [comment]
I believe this is because the [standard user-flows](https://docs.microsoft.com/azure/active-directory-b2c/user-flow-overview) return only emails claim in the id token (you can see that if you try to create a new one), so the library is basing the assumption on that (i.e. it is not necessary for developers to make use of a custom policy).

![ss](https://user-images.githubusercontent.com/13197548/127052936-0bf77232-33b7-405e-b813-1468a7ccdf6b.png)
