### ISSUE TITLE
Log in on multiple tabs

### ISSUE THREAD

**Issue by sadiomanhne** [AzureAD/microsoft-authentication-library-for-js#3966]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

When I opened my web app on two tabs, I logged out tab 1, trigger event logout on tab 2 also. 
Both of the tabs redirect to the login page: https://abc.b2clogin.com/abc.onmicrosoft.com/....
I input username/pass on tab 1 and login => success
But on tab 2 => Bad Request (400)

Is it an intended behavior?
![400_b2c](https://user-images.githubusercontent.com/20012116/129170157-26463381-23e5-4c51-bc57-6f7e8f6a97bd.png)

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by pkanher617** [comment]
Are there any details you can provide around the Bad Request error? or do you only see the 400 error code? And is the error coming from the B2C page or does tab 2 redirect back to your application before throwing the error?

**Comment by sadiomanhne** [comment]
> Are there any details you can provide around the Bad Request error? or do you only see the 400 error code? 
=> only see the 400, no additional information
> And is the error coming from the B2C page or does tab 2 redirect back to your application before throwing the error?
=> The error coming from the B2C page
I think maybe the authentication status is stored on B2C page cookies, I logged in on Tab 1, the cookies set to authenticated or something like that, then I logged in on Tab 2, request will send the cookies that changed on Tab 1 to server. Server verify it is invalid and response a Bad request

**Comment by tnorling** [comment]
@sadiomanhne Please open a ticket with [B2C Support](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options) as server side issues are out of scope for this library. Thanks!

**Comment by Dima11235813** [comment]
@sadiomanhne 
I've always implemented cross tab auth event tracking in my own code as MSAL doesn't implement that.

You can use local or session storage events to indicate if you are authenticated or not.

That way when you have multiple tabs open. You can trigger msal's logout redirect and also set some state in browser storage.

Then have an browser state event listener for that change and trigger msal logout there as well. The thing to remember is that you'll need to check auth state before logging out as the original tab you clicked log out in, should ignore the browser storage that it itself triggered.

You want to apply this same logic to the log in flow, so that if you log in on one tab, all other tabs automatically redirect to a page that invokes the auth flow (aquire token silent with the usual fallbacks to login redirect. 

Hope that helps.
