### ISSUE TITLE
acquireTokenSilent MSAL Client Auth Error - Vue + nuxt implementation

### ISSUE THREAD

**Issue by RajGanguly** [AzureAD/microsoft-authentication-library-for-js#4033]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.12

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

vue:  2.16.14
nuxt: 2.15.8
msal: 1.4.12

Trying to implement Azure login + getting refresh token + calling graph api.
To achieve this I have tried 3 APIs till now (as provided in the code snippet below):

1.  `acquireTokenSilent` (This is the API I require, I dont want to have UI interaction for every refresh token request)
   On doing this it always goes to the error block and the error it throws:
   
![Screenshot from 2021-09-05 12-42-12](https://user-images.githubusercontent.com/5802104/132118705-f84e2d75-cbec-480d-a94b-3fd8881dac3f.png)

2.  `acquireTokenRedirect`
   I see a request to `https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token`  which gives me an access token but I dont know how to receive the token in the callback function as the page reload takes place ignoring the callback
   
3. `acquireTokenPopup`
  On doing this, this is the only api that returns me an `accessToken` in the callback, but as I mentioned before, my essential requirement is to get the `refreshToken` silently (without any UI intervention).
  
  Am I on the right track on doing this? Any nuxt example that I can refer to?
  Is there any issue with `acquireTokenSilent` in `msal`? How can I acquire the access Token Silently without any UI interaction.
    
  

### MSAL Configuration

```javascript
// components/MicrosoftAuthConnection.js

function MicrosoftAuthConnection () {
  let Msal = require('msal')
  this.connection = new Msal.UserAgentApplication({
    auth: {
      clientId: process.env.aadClientId
    },
    cache: {
      cacheLocation: 'sessionStorage'
    }
  })
}

MicrosoftAuthConnection.prototype.login = function (callBack) {
  let loginRequest = {
    scopes: ['user.read'] // optional Array<string>
  }
  this.connection.loginPopup(loginRequest).then(
    response => {
      console.log('Login window opened', response)
      callBack(response)
    },
    error => {
      return error
    }
  )
}

MicrosoftAuthConnection.prototype.getToken = function (callBack) {
  console.log('Inside get Token')

  console.log('Checking account', this.connection.getAccount())
  if (this.connection.getAccount()) {
    const account = this.connection.getAllAccounts()[0]
    let loginRequest = {
      scopes: ['user.read', 'mail.send'],
      account: account,
      navigateToLoginRequestUrl: false,
      tenantId: process.env.aadTenantId
    }
    // try {
    //   this.connection.acquireTokenPopup(loginRequest).then(
    //     response => {
    //       callBack(response)
    //     },
    //     error => {
    //       console.log('error ', error)
    //     }
    //   )
    // } catch (e) {

    // }
    this.connection.acquireTokenRedirect(loginRequest).then(
      response => {
        // callBack(response)
        console.log('Inside token redirect', response)
      },
      err => {
        console.error('Checking token error', err)
      }
    )
  }
}

export default MicrosoftAuthConnection
```

### Relevant Code Snippets

```javascript
// pages/app/index.vue

<template lang="pug">
  .calendar-container
    button(@click="msAccountLogin")
      img.calendar(src="~assets/images/outlook.png")
        label Outlook
</template>
<script>
  import MSAuth from  '~/components/MicrosoftAuthConnection'
  export default {
     components: { MSAuth },
     methods: {
       async msAccountLogin () {
         let authConnection = new MSAuth()
         try {
           const loginResponse = await authConnection.login(this.msLoginCallback)
         } catch(e) {
         }     
       },

    async msLoginCallback (payload) {
      console.log("Checking payload", payload)
      
      let authConnection = new MSAuth()
      if (!payload.accessToken){
        let response = await authConnection.getToken(this.msTokenCallback)
        console.log("response", response)
      }      
    },

    msTokenCallback (payload) {
      console.log("Token Payload :", payload)
    }

   }
  }
</script>
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @RajGanguly. My first recommendation would be that you try MSAL Browser (MSAL v2) instead of MSAL v1. Other than that, I have a few of questions.

1. Are you using AzureAD B2C by any chance? I ask because you seem to be doing a login with Google.
2. The usual calling pattern we recommend is that you call acquireTokenSilent first and then you fall back to either acquireTokenRedirect or acquireTokenPopup if you get an Interaction Required error. You may want to look at our existing samples in the sample folder to see how this pattern is implemented.
3. The `acquireTokenRedirect` API does not return a promise, so using `.then` will not work. The way to handle the result of that function is to configure `handleRedirectCallback` like so:

```js
    msalInstance.handleRedirectCallback((error, response) => {
        // handle redirect response or error
    });
   ```
   
   You can see the [MSAL v1 docs] (https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-core) or the [msal-core-samples](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-core-samples) for more information. However, I would still recommend you move to [MSAL Browser](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser) instead.

**Comment by RajOfficeTroops** [comment]
@hectormmg Thanks for your generous reply, will check and let you know

**Comment by RajGanguly** [comment]
@hectormmg 
Currently this is the implementation that I've come up with after upgrading to ```msal-browser```
```
// components/MicrosoftAuthConnection.js

import * as Msal from '@azure/msal-browser'
export default class MicrosoftAuthConnection {
  constructor () {
    this.connection = new Msal.PublicClientApplication({
      auth: {
        clientId: process.env.aadClientId
      },
      cache: {
        cacheLocation: 'sessionStorage'
      }
    })
    this.requestParams = {
      scopes: ['user.read', 'mail.send'],
      navigateToLoginRequestUrl: false,
      tenantId: process.env.aadTenantId,
      resource: 'https://graph.microsoft.com/'
    }
  }
  getTokenResponse () {
    console.log('Inside get Token')
    const account = this.connection.getAllAccounts()[0]
    console.log('Checking account ', account)
    if (account) {
      console.log('Inside if account ')
      this.requestParams.account = account
      return this.connection.acquireTokenSilent(this.requestParams).then(
        response => {
          // callBack(response)
          console.log('Inside token redirect')
          console.log(response)
          return response
        },
        err => {
          if (err) {
            // fallback to interaction when silent call fails
            console.log('fallback to interaction when silent call fails')
            this.connection.acquireTokenPopup(this.requestParams).then(
              result => {
                console.log('Inside acquireTokenPopup 1111111', result)
                return result
              },
              err => {
                console.log('Error 1111111', err)
                console.log('error ', err)
              }
            )
          }
        }
      )
    } else {
      console.log('No account found')
      return this.connection.acquireTokenPopup(this.requestParams).then(
        result => {
          console.log('Inside acquireTokenPopup ', result)
          return result
        },
        err => {
          console.log('error 222222', err)
        }
      )
    }
  }
}
 ```

The Graph API implementation
```
// components/MicrosoftGraphApi.js
function MicrosoftGraphApi (tokenValue) {
  this.graphUrl = 'https://graph.microsoft.com/v1.0/'
  this.token = tokenValue
  console.log('Token Value ', this.token)
}

MicrosoftGraphApi.prototype.getCalendar = function () {
  const headers = new Headers({ Authorization: 'Bearer ' + this.token })
  const options = { headers }
  return fetch(`${this.graphUrl}/me/calendars`, options)
    .then(response => { return response.json() })
    .catch(response => {
      throw new Error(response.text())
    })
}

export default MicrosoftGraphApi
```
Now here's how my API invocation looks like

```
 this.accessToken = this.getRefreshToken()
 let msGraph = new MSGraph(this.accessToken)
 let userCalendarList = await msGraph.getCalendar()
 
     async getRefreshToken() {
      let msAuth = new MSAuth()  
      return await msAuth.getTokenResponse().then(
        result => { console.log('Inside result', result) 
          return result.accessToken
        },
        _error => {
          return msAuth.loginRequestNoInteraction().then(
            response => { 
             return response.accessToken },
            err => { console.log('Checking err ', err) }
          )
        }
      )
    },
  ```
  So everything works fine when the cache holds the value for azure accounts:
  ```const account = this.connection.getAllAccounts()[0]``` doesn't give ```null```
  
  When the account returns null I've check ```acquireTokenSilently``` also fails with error ```No account object provided to acquireTokenSilent and no active account has been set. Please call setActiveAccount or provide an account on the request graph api```, therefore I've invoked the  ```acquireTokenPopup```. 
 So in any case a UI interaction is always required when ```acquireTokenSilent``` should fail, and it will when the cache expires?
 Isn't there any way to silently keep on receiving accessToken without UI interaction?
 
 Also the  ```acquireTokenPopup``` is also failing in this regard because the page where this integration is required has a dynamic url:
 URL: ```localhost:3000/app/products/<product-slug>/entity/<entity-slug>```
 Which I have checked cannot be registered in redirect URIs as it doesn't support wildcard urls
 Therefore ```acquireTokenPopup``` is giving me ```AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application``` which makes sense as I don't have the url registered as its not possible to do so.
 
 I don't understand how to get around this problem.

**Comment by hectormmg** [comment]
Hey, @RajGanguly .

1. Since MSAL supports multiple account, `acquireTokenSilent` requires an account object so MSAL knows which account's tokens to return from the cache. If there is no account in the cache, then your user is not authenticated (i.e. logged in) and you need to authenticate them through either an interaction (popup or redirect login), or through MSAL's `ssoSilent` API (please check our docs for more info on `ssoSilent`.
2. When you call `acquireTokenSilent` with an account and the access token is expired, MSAL tries to get you a new access token (silently, i.e. with no interaction by the user) by using the cached refresh token. Auth Code grant refresh tokens (which MSAL uses) have a 24 hour lifetime, which means you should be able to silently get access tokens for that time, without interaction, as long as you don't log your user out.
3. When it comes to redirect URIs, you should register a single redirect URI that you use in your application for authentication. If you start authentication from `https://yourdomain.com/app/products/<product-slug>/entity/<entity-slug>` and want to redirect there after authentication is done, you can leverage the `state` parameter in the authentication request. The `state` is returned with the `AuthenticationResult` so your app can retrieve it and redirect to that page once the token is acquired from the network.

**Comment by RajGanguly** [comment]
@hectormmg 
1.  As per your comment I have tried implementing `ssoSilent` when the cache clears the account details (when `const account = this.connection.getAllAccounts()[0]` returns null). I have checked the docs for the necessary request options for `ssoSilent`.
This is how `ssoSilent` is implemented on fallback if account is null on `acquireTokenSilent`

```
      this.requestParams.loginHint = userName
      this.redirectUri = process.env.appUrl + 'empty'
      return this.connection.ssoSilent(this.requestParams).then(
        result => {
          console.log('Inside ssoSilent 2222222', result)
          return result
        },
        err => {
          console.log('error 222222', err)
        }
      )
```
And I get
![Screenshot from 2021-09-17 16-56-39](https://user-images.githubusercontent.com/5802104/133776068-9ea89065-8a8f-4cc0-95ee-c821c8cdc860.png)

I created an empty html page and assigned it to as `redirectUri` but still no change.

Previously I was getting [this issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1199), however it got resolved by adding:
``` 
system : {
        navigateFrameWait: 500,
        iframeHashTimeout: 10000
    }
 ```
 This was the API I was looking for but unfortunately it doesn't work
 I have also tried exposing `http://localhost:3000` to `https` but it still doesn't work

**Comment by RajGanguly** [comment]
@hectormmg 
As per your second point I'm receiving the `accessToken` from `loginPopup` and then for every graph api call I'm calling `acquireTokenSilent` to get the token to call respective APIs. It works well for 24 hours after which on calling `acquireTokenSilent` gives error because the account information is removed from the cache. I'm trying to handle that scenario without any interaction hence trying to get the token via `ssoSilent`

**Comment by RajGanguly** [comment]
@hectormmg Any advice on this?

**Comment by hectormmg** [comment]
Hey, @RajGanguly.

1.  MSAL trying to navigate to "https://login.microsoftonline.com/common/oauth2/v2.0/undefined" is unexpected. Given that navigating to /undefined will result in a 404, the server will not receive/process the request and MSAL times out waiting for a response. This can happen if the authority object in the request is corrupted. Is there any place in the code where you modify or set the authority for the request?
2. You're able to get access tokens silently for 24 hours because that is how long auth code flow refresh tokens last. Once `acquireTokenSilent` fails you need to either do interactive authentication (login or popup) or leverage SSO (through `ssoSilent`). However, SSO depends on there being an active session with the server (i.e. the user having previously logged in, not logging out and the session not having expired). This means that you eventually do need to fall back to interactive authentication as well.
3. You have to set `redirecUri` in your MSAL config and request parameters to a valid redirect URL that is registered in your app registration.

You can set `navigateToLoginRequestUrl` to true in the request so that after the server redirects back to the redirect URI, MSAL redirects your app back to the page where the login request was made from. Alternatively, you can set the `state` in the request to the page the request was made from (from `window.location`) and then get the `state` from the authentication result and redirect to the page yourself.
