### ISSUE TITLE
Why I can't get "signed in" account in v.2 despite in v.1.2 I could?

### ISSUE THREAD

**Issue by anton-marchenko** [AzureAD/microsoft-authentication-library-for-js#4053]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.2

### Description

I am reading [migration documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/v1-v2-upgrade-guide.md):

> When getting accounts, we recommend using getAccountByHomeId() and getAccountByLocalId(), available on the MSAL instance. getAccount() is now getAccountByUsername(), but should be a secondary choice, as it may be less reliable and is for convenience only.

I just want to get my current "signed in" account like it was in version1: ` getAccount()`.

1. Why I need to care about homeId, localId or something else? v1.2 make it internally whereas v2 delegates it responsibility to me. 
2. Okay. I would can solve this problem like this:

```
    this.msalBroadcastService.msalSubject$
    .pipe(
        filter((msg: EventMessage) => msg.eventType === EventType.ACQUIRE_TOKEN_SUCCESS)
    )
    .subscribe((result) => {
        console.log(result.payload?.account);
    });
```

But I need to use explicit  Type Assertions: `result.payload as SomeType` that is considered as bad practices in some projects. Anyway simple `.getAccount()` was nice feature in my opinion.

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @anton-marchenko . The main difference is that MSAL v1 didn't support multiple accounts, so there was no need to filter through them because there would always only be one account in the cache. Since MSAL v2 supports multiple cached accounts, you need to specify a way to identify the account you need to get.

Having said that, MSAL v2 has a `getAllAccounts` API that will return all of the accounts in the cache. If you're confident that there's only one account in the cache, you can call `getAllAccounts()[0]` and it will mimic the same behavior of MSAL v1's `getAccount()`.

Please let us know if this helps resolve your issue, thanks!

**Comment by anton-marchenko** [comment]
> Hi @anton-marchenko . The main difference is that MSAL v1 didn't support multiple accounts, so there was no need to filter through them because there would always only be one account in the cache. Since MSAL v2 supports multiple cached accounts, you need to specify a way to identify the account you need to get.
> 
> Having said that, MSAL v2 has a `getAllAccounts` API that will return all of the accounts in the cache. If you're confident that there's only one account in the cache, you can call `getAllAccounts()[0]` and it will mimic the same behavior of MSAL v1's `getAccount()`.
> 
> Please let us know if this helps resolve your issue, thanks!

Okay. It helps. Thanks!
