### ISSUE TITLE
.default scope can't be combined with resource-specific scopes

### ISSUE THREAD

**Issue by rhalaly** [AzureAD/microsoft-authentication-library-for-js#4071]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

^2.16.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

^1.0.1

### Description

Started to receive this error recently: `.default scope can't be combined with resource-specific scopes`

### Error Message

> .default scope can't be combined with resource-specific scopes

### MSAL Configuration

```javascript
{
  auth: {
    clientId: 'XXXX-XXXX-XXXX-XXXX',
    redirectUri: '/',
    postLogoutRedirectUri: '/',
  },
  cache: {
    cacheLocation: 'localStorage',
  },
};
```

### Relevant Code Snippets

```javascript
const tokenRequestGraph = {
  scopes: ['People.Read', 'User.Read', 'User.ReadBasic.All'],
};

const tokenRequestService = {
  scopes: ['XXXX-XXXX-XXXX-XXXX/.default'],
};

export const loginRequest = {
  scopes: ['User.Read'],
  extraScopesToConsent: [...tokenRequestService.scopes, ...tokenRequestGraph.scopes],
} as msal.RedirectRequest;
```

### Reproduction Steps

1. Trigger a redirect login.
2. Getting
![image](https://user-images.githubusercontent.com/8597700/133753595-aa489c3f-dc70-4611-8eef-deebca859501.png)

### Expected Behavior

Loggin will work. As it used to work

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Edge

### Source

Internal (Microsoft)

**Comment by derisen** [comment]
@rhalaly I think the issue here is that you're mixing scopes for different resources (Microsoft Graph and your own web API). See [our documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md#resources-and-scopes) on this. 

Also, can you double check the code snippet you shared? I'm assuming you renamed `tokenRequestService` to `tokenRequestCts` later.

**Comment by rhalaly** [comment]
Yes, I was rename it for simplicity. Fixed... When I used a specific resources instead of `.default` it works. Any idea why?

**Comment by derisen** [comment]
@rhalaly you can put all the MS Graph scopes into the `scopes` array, and use the `extraScopesToConsent` array for your web API's scope. Would that help?

**Comment by rhalaly** [comment]
Maybe I missed something. For my understanding, the `scope` field is foe the login respone and the "extra" are for consent only (for getToken). If I move the Graph scopes to the `scopes` it can work? I just need them for consent. The actual Graph request is used later

**Comment by derisen** [comment]
@rhalaly true, your understanding is correct.

Interesting, this does look like a recent change, which you actually mentioned.. Ok, so you won't be able to use the `.default` scope but you should be fine if you replace it with the actual scope (e.g. 'XXXX-XXXX-XXXX-XXXX/my_scope'). This for instance should work: 

```javascript
const loginRequest = {
  scopes: ["User.Read", "Mail.Read", "Calendars.Read"],
  extraScopesToConsent: ["Chat.Read", "https://management.azure.com/user_impersonation"],
};
```

**Comment by rhalaly** [comment]
Thank you for the comments. If this is a new thing, I don't understand why it isn't introduced in a major version of the package. It is a breaking change that broke our system. 

I will try to use the system scopes explicitly and update if it works

**Comment by jasonnutter** [comment]
> Thank you for the comments. If this is a new thing, I don't understand why it isn't introduced in a major version of the package. It is a breaking change that broke our system.

This condition is being enforced by AAD, as opposed to MSAL. @hpsin Do you have any insight into why this behavior may have changed recently?

**Comment by rhalaly** [comment]
@derisen I use the default scope for the on-behalf-of flow. I read that this is the only way to do that. Any alternative how to solve this in this case?

**Comment by derisen** [comment]
@rhalaly it's a convenient way, but there are other alternatives. The main issue is to grant consent to the permissions required by the middle-tier web API, as it has no way of directly prompting the user (who is facing the client app). One alternative is to use a single app registration for both the client and the middle-tier app, which makes sense for OBO scenarios as they are often logically "one app". Another alternative is to grant admin consent to the permissions required by the middle-tier app, so that user consent is not required. If using msal libraries with the web API, yet another alternative is to handle the **www-authenticate** response sent by the middle-tier web API when it requires consent to its own permissions (if not using msal on the backend, you can construct a similar response and propagate it to the client app). This response looks like:

`Bearer consentUri="https://login.microsoftonline.com/<tenantId>/oauth2/v2.0/authorize?client_id=<middle-tier-client-id>&response_type=code&redirect_uri=<redirect-uri>&response_mode=query&scope=offline_access%20User.Read", claims="", scopes="User.Read", proposedAction="consent"`
