### ISSUE TITLE
How do I renew idToken and accessToken after one hour so the user doesn't have to login all the time?

### ISSUE THREAD

**Issue by chetanku** [AzureAD/microsoft-authentication-library-for-js#409]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ X] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: Latest

## Current behavior

Once I am initially logged in how do I maintain the user session after the token expires?
Do I have to manually call the acquireTokenSilent method so the token is renewed or does it automatically handle it?  
Currently I am calling acquireTokenSilent method right before the idToken and accessToken.
I see I get new idToken and accesstoken but  I don't see getUser() response getting updated . I get user object with old expiry time.
Is there any documentation around on how to implement this?
The goal is to automatically renew the user session so the user is logged in.
Any help will be greatly appreciated.

```
this.app.acquireTokenSilent([Config.AppID]).then(      // Passing clientId to get a new idToken
       idToken => {
       // renew IdToken
         console.log(idToken);
      this.app.acquireTokenSilent(Config.Scopes)
        .then(accessToken => {
        // renew accessToken
          console.log(accessToken);
        // getting user info after tokens are renewed expecting that the user.IdToken.exp will have a new //expiry time.
          const user = this.app.getUser() ;
        }
```

</code></pre>

**Comment by fabiodrg666** [comment]
I am also having some trouble to understand the documentation (however, my biggest problem is how to implement this logically in a browser extension, because of redirect URI). 

I think once you call login function, you can use `acquireTokenSilent()`. However, you should set a fallback, because, if the user account uses two step authentication, the user must enter the credentials again. Therefore, if `acquireTokenSilent()` results in an error, call the `acquireTokenRedirect` or `acquireTokenPopUp` for user interactivity (sorry if I am misspelling the function names, typing by memory).

Once the `access_token` is retrieved, from my understanding, you can stick to `acquireTokenSilent()` before any API call. The library handles the expiration. If the access_token is valid, it's retrieved from the cache/storage, if not it will renew it silently. Not sure if it is always possible to renew silently.

**Comment by yanamandrac** [comment]
@fabiodrg666  Thanks for your reply.  My question is more related to getUser(), the user object I get in response by calling getUser() is not updated when we get a new token with acquireTokenSilent(). So, is it a good practice to use getUser() to check if the user is still authenticated or not? or is there any other recommended way?

**Comment by chetanku** [comment]
@fabiodrg666 Thanks for your reply. My question is more related to getUser(), the user object I get in response by calling getUser() is not updated when we get a new token with acquireTokenSilent(). So, is it a good practice to use getUser() to check if the user is still authenticated or not? or is there any other recommended way?

**Comment by fabiodrg666** [comment]
From my understanding, you can't rely on getUser(). When the access_token expires, the getUser() will return the basic user information, the id_token, etc, anyway. **It won't return null, unless the data on storage is deleted.** 

As I said previously, when you call acquireTokenSilent(), you get the stored/cached access_token if still valid (thus, the return from getUser() should be the same), otherwise it's made an attempt to renew the token. Based on the REST API documentation, when you renew an access_token you get a new access_token and a new id_token (besides other parameters, not relevant here). Thus, I would suspect that when the access_token expires, the id_token value is updated internally, resulting in a different return from getUser(). Did you tried a successful login and acquireToken and waited more than 1 hour to let the token expire and see if the return has changed?

On the other hand, id_token is only required for OpenID protocol, which might not be your case. In this scenario, the id_token probably isn't updated, thus getUser() never changes the returned object.

Anyway, my conclusion, and to directly address your question, is that **getUser() is not a good way for check if a user is authenticated**. And, as far as I know, there's isn't a direct way to check if session expired or not. If you really need it, it should be fairly easy to manually store  a date and time from the last time access_token was refreshed. There's a callback function invoked everytime you call login or acquireToken. Use that callback to ensure an access_token was successfully acquired.

If you don't know which callback I am talking about, it is set when you create new `Msal.UserAgentApplication(clientId, authority, tokenReceivedCallBack, ...)`.  `tokenReceivedCallBack` is the function you want to be called upon logins and acquireTokens. The function definition is `tokenReceivedCallBack(errorDesc, token, error, tokenType, state)`.

Sorry if my answer is quite verbose, just wanted to explain how I concluded that `getUser()` is not the way to checking if a user is authenticated, and why it might return the same value everytime.

**Comment by navyasric** [comment]
@chetanku Please call the acquireTokenSilent method which handles token renewals. This is explained now [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/FAQs#q3-how-to-renew-tokens-with-msaljs) 
If the user is inactive and the idtoken lifetime is 1 hour, it is expected that the user is logged out. 
The user session and id tokens lifetime can be configured here or the user can stay logged in by choosing Keep me signed in as documented here: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#single-sign-on-session-tokens

**Comment by chetanku** [comment]
@navyasric The issue I was facing is, even if the user is active for an hour, and I am calling acquiretokensilent method to renew, msal logged him out. I will try again and let you know if I am still facing the issue.

**Comment by AbhaysinghBhosale** [comment]
Did the same implementation. But have to issue with calling aquireTokenSilent() method. Documentation says call this method each time i call REST API (backend in c#). This is not feasible for me.

So want to renew token only if it is near expiry. do i have to write own logic to track expiry time and call the method ?
