### ISSUE TITLE
ChromiumExtensionSample not work

### ISSUE THREAD

**Issue by dacapoday** [AzureAD/microsoft-authentication-library-for-js#4091]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

raise
Uncaught (in promise) BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API. For more visit: aka.ms/msaljs/browser-errors.
in
msal-browser.min.js:547

msal-browser.min.js is include in ChromiumExtensionSample

### MSAL Configuration

```javascript
auth: {
    authority: "https://login.microsoftonline.com/consumers/",
    clientId: "",
    redirectUri,
    postLogoutRedirectUri: redirectUri,
  },
  cache: {
    cacheLocation: "localStorage",
  },
```

### Relevant Code Snippets

```javascript
async function acquireToken(request) {
  return msalInstance.acquireTokenSilent(request).catch(async (error) => {
    console.log(error);
    const acquireTokenUrl = await getAcquireTokenUrl(request);

    return launchWebAuthFlow(acquireTokenUrl);
  });
}
```

### Reproduction Steps

just follow sample readme, and reproducted

### Expected Behavior

no error log like readme discription.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by samuelkubai** [comment]
Hi @dacapoday, 

This is an error caused by calling an interaction API; which in this case is `loginRedirect` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/ba041e8c2d8c393896e5f3bb3b8b83c522ec2910/samples/msal-browser-samples/ChromiumExtensionSample/auth.js#L85); whilst another interaction API has not been resolved, you can find more information on this error [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md#interaction_in_progress).

The sample does not prevent this from happening and we will need to design the code flow to prevent that. In any case, you should design your own application to prevent a scenario where multiple interaction API calls can be executed simultaneously.
