### ISSUE TITLE
AcquireTokenSilent Does not create any iframe.

### ISSUE THREAD

**Issue by Shivam60** [AzureAD/microsoft-authentication-library-for-js#4111]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

Prior to upgrading to V2 we were logging users who already have logged in some other Microsoft website silently by creating an iframe and triggering a signin by redirect flow in the iframe. This helped us in getting users silently sign in.

As per the docs the `acquuireTokenSilently` is supposed to do exactly this however once we upgraded to v2 we see a massive drop in users who are signed in. 

What are we missing here that we are not seeing silent sign on?

### MSAL Configuration

```javascript
auth: {
                clientId: // client id,
                authority: "https://login.microsoftonline.com/common/",
                redirectUri: // our homepage,
            },
            cache: {
                cacheLocation: "localStorage",
            },
```

### Relevant Code Snippets

```javascript
if (this.props.msalContext.instance.getAllAccounts()[0]) {
            this.props.msalContext.instance
                .acquireTokenSilent({
                    account: this.props.msalContext.instance.getAllAccounts()[0],
                    ...loginRequest,
                })
                .then(token => //use token)
                .catch(err => {
log telemetry 
                });
        }
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
> As per the docs the acquuireTokenSilently is supposed to do exactly this however once we upgraded to v2 we see a massive drop in users who are signed in.

`acquireTokenSilent` in MSAL.js v2 does not use hidden iframes to acquire access tokens most of the time. The `ssoSilent` API will create a hidden iframe to attempt to silently authenticate the user, and is likely more appropriate for your scenario (at least to silently authenticate the user when your app first loads. You should use acquireTokenSilent to silently acquire tokens after that). Note, today `ssoSilent` requires you to pass `sid`, `loginHint`, or `account` for the user, otherwise it will throw an error. We will be removing this restriction in a future version of MSAL.js.

**Comment by Shivam60** [comment]
I don't have any value in account array. How else can i access `sid` or `loginHint`

**Comment by jasonnutter** [comment]
> I don't have any value in account array. How else can i access `sid` or `loginHint`

You may not be able to get those values, unfortunately. You are not the only customer who has this scenario and needs to be able to call `ssoSilent` without `sid` or `loginHint`, which is why we will be removing this restriction soon.

For now, you should invoke an interactive method (e.g. loginRedirect, loginPopup) to allow the user to authentication. Note, if the user is already signed in (and they just have one account), they should not need to reenter their credentials, and the interactive request should complete immediately.

@pkanher617 please follow up here when we have completed the work to remove the restriction on `ssoSilent`.

**Comment by Shivam60** [comment]
Is there eta/workitem for this ?

Asking users to login interactively would break the current experience. What other alternative would you suggest us in that case ?
Should we go back to the iframe then?

**Comment by jasonnutter** [comment]
> Is there eta/workitem for this ?

Please connect with @pkanher617 internally and he can provide this for you.

> Asking users to login interactively would break the current experience. What other alternative would you suggest us in that case ?
> Should we go back to the iframe then?

When loginredirect is called and the user has one active session, they should not need to interactively login, and AAD will redirect them back to your application immediately. If they aren't logged in, or if they have multiple accounts, then they will need to perform interaction. This isn't any different than what would happen with a silent request in an iframe (without loginhint/sid), as AAD would return an error in the iframe if the user isnt logged or there are multiple accounts.

**Comment by Shivam60** [comment]
It appears majority of our users are logged in via single account only. Thus using redirect within an iframe has worked for us ensuring a higher signed users and an experience where users doesnt navigate away from the site for login if there exisits an active session.

I ll wait for @pkanher617 's thoughts and ETA on the above. It looks we ll have to revert back to our iframe code :(

**Comment by Shivam60** [comment]
![image](https://user-images.githubusercontent.com/13963817/135972398-079d4e43-575c-45c2-abf0-95f0f97a879c.png)
