### ISSUE TITLE
Too many branches with no commit ahead

### ISSUE THREAD

**Issue by ghost** [AzureAD/microsoft-authentication-library-for-js#4139]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

5.0.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.4

### Description

While searching through the branches for indication of RxJS 7 update I noticed, that there are over 100 branches with not a single commit ahead and many with just 1 or 2 commits ahead which were done over a year ago and are a few thousand commits behind.

This makes it difficult to see what is currently being worked on, escpecially as the roadmap is not updated for the current quarter.

Suggestion: Delete most of the stale branches.

### Source

External (Customer)

**Comment by tnorling** [comment]
Thanks for the suggestion. This is a reasonable ask and we'll see what we can do. Regarding the roadmap, the quarter just started and commitments are still being finalized, it will be updated as soon as we have something to share. 

I'm not aware of any formal plans to update RxJS but we always welcome PRs if you know what needs to be done, otherwise please open a feature request for that and we'll get it added to our backlog. Thanks!
