### ISSUE TITLE
`aadApp.acquireTokenSilent(...)` sometimes fails due to lack of MFA request

### ISSUE THREAD

**Issue by chriskuech** [AzureAD/microsoft-authentication-library-for-js#415]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [X] Firefox version 61
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.0

</code></pre>

## Current behavior

Authentication requests *inconsistently* fail, as AAD does not request MFA from the user
```
AADSTS50079: The user is required to use multi-factor authentication.
Trace ID: 447f0da4-d992-4c92-aafe-34febfb52400
Correlation ID: 6ec2db49-0caa-4d5d-a1fb-a08fb6c3ccfd
Timestamp: 2018-08-30 20:23:08Z|interaction_required
```

## Expected behavior

msal exposes a method to force a multi-factor authentication request

## Minimal reproduction of the problem with instructions

Transient and hard to reproduce.  Message me on Teams for repro steps if you work at Microsoft.

</code></pre>

**Comment by navyasric** [comment]
@chriskuech The above error happens when a [conditional access claims challenge](https://docs.microsoft.com/en-us/azure/active-directory/develop/conditional-access-dev-guide#scenario-single-page-app-spa-using-adaljs) such as MFA policy is required.
The pattern to handle this error is to make an interactive acquireToken call in MSAL.js such as acquireTokenPopup or acquireTokenRedirect.
We are working on documenting this better in our Wiki, but hopefully this will resolve the issue for you. Let us know.

**Comment by nehaagrawal** [comment]
@chriskuech This error must be coming from AcquireTokenSilent. Please call acquireTokenRedirect/AcquireTokenPopup in the error block of AcquireTokenSilent. Something like this.

this.acquireTokenSilent(applicationConfig.graphScopes).then(function (accessToken) {
    // Change button to Sign Out
    updateUI();
}, function (error) {
    console.log(error);
    this.acquireTokenPopup(applicationConfig.graphScopes).then(function (accessToken) {
        updateUI();
    }, function (error) {
        console.log(error);
    });
});

**Comment by chriskuech** [comment]
thanks this worked
