### ISSUE TITLE
OBO flow credentials improvement

### ISSUE THREAD

**Issue by diberry** [AzureAD/microsoft-authentication-library-for-js#4177]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Description

If the Azure Function needs to do so much work to validate the token in this [sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/on-behalf-of/web-api/index.js), shouldn't the MSAL SDK wrap that for me?  

I want to take the function token and get a credential to use with the Azure SDKs. Why doesn't the sample use the Azure SDKs instead of an REST API?

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
We are currently working on a new token validation library, which will do much of the logic you see in that sample (e.g. validating the token signature, validating claims, etc.). cc @pkanher617 @jo-arroyo 

The sample is intended to show how you can use MSAL Node to perform the OBO flow (and I believe the sample was written before the Azure SDK supported the OBO flow as a credential provider), which is why we show how to do the steps manually (as opposed another library which may abstract certain steps away).

**Comment by diberry** [comment]
@jasonnutter Are you saying @azure/identity sdk supports obo - meaning given a token, I can get a credential, then use any of the Azure SDKs? If yes, do you happen to have a link?

**Comment by jasonnutter** [comment]
@diberry Yep, check the comment left here: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4168#issuecomment-946211026

**Comment by sameerag** [comment]
Tagging this with node validation library, cc @jo-arroyo.

**Comment by jasonnutter** [comment]
Closing, as this will be handled in teh new Token Validation library, let us know if there are still questions.
