### ISSUE TITLE
Remove Default OIDC Parameter from Authority URL

### ISSUE THREAD

**Issue by GeekyDiya** [AzureAD/microsoft-authentication-library-for-js#4196]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

Hi,
We have a requirement for our multi-tenant B2C SPA where I want to redirect to the authority URL with the below structure:
https://mytenant.b2clogin.com/as/authorization.oauth2?client_id=myClientID&response_type=code&scope=openid&redirect_uri=https://applicationlogin.com

Here we are facing an issue since the package is appending OIDC default configurations to the URL (v2.0/.well-known/openid-configuration) due to which we get 400 error.

![image](https://user-images.githubusercontent.com/25152588/139071178-066f9460-3c22-4b5a-a2ca-ab699813ebcc.png)

Is there a way to restrict or configure the auth in a way that we can directly hit the authority URL?

Below is the current MSAL configuration

### MSAL Configuration

```javascript
let auth = {
      clientId: <client id>,
      authority: https://mytenant.b2clogin.com/as/authorization.oauth2?client_id=myClientID&response_type=code&scope=openid&redirect_uri=https://applicationlogin.com,
      redirectUri: <login redirect url>,
      postLogoutRedirectUri: <logout redirect url>,
    };

    const externalAuth = {
      validateAuthority: false,
      knownAuthorities: ["tenant.b2clogin.com", https://mytenant.b2clogin.com/as/authorization.oauth2?client_id=myClientID&response_type=code&scope=openid&redirect_uri=https://applicationlogin.com],
    };

    auth = isExternalLogin? { ...auth, ...externalAuth} : { ...auth };

    const ssoConfig = {
      auth,
      cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: false,
        secureCookies: false,
      },
    };
```

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@GeekyDiya It appears that you are constructing your authority before passing it into MSAL, whereas MSAL is able to do that for you. Please see [this sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-react-samples/b2c-sample/src/authConfig.js) for an example of what the `authority` and `knownAuthorities` should look like when configuring MSAL (e.g. authority:  "tenant.b2clogin.com/policyName", knownAuthorities: ["tenant.b2clogin.com"]).

**Comment by GeekyDiya** [comment]
I have now provided the values in the respective parameters and yet the URL is not being constructed. Also, I wish to understand how I can pass extra parameters (scope and response_type) in the parameters. If someone could guide me in the same, would really appreciate it.

```
 const ssoConfig = {
      auth: {
        clientId: "myClientID",
        authority: "https://mytenant.b2clogin.com/as/authorization.oauth2",
        redirectUri: "${window.location.origin}/app/callback", 
        postLogoutRedirectUri: `${window.location.origin}/logout}`,
        validateAuthority: false,
        knownAuthorities: [
          "https://mytenant.b2clogin.com/as/authorization.oauth2",
        ],
      },
      cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: false,
        secureCookies: false,
      },
    };
```



I also need to add the below 2 parameters to be constructed in the URL but not able to figure out where I need to add and how it'll be inserted in the url.

```
scope:["opened"]
response_type:["code"]
```


Even after giving the parameters, the final constructed URL is coming out to be : `https://mytenant.b2clogin.com/as/authorization.oauth2/v2.0/.well-known/openid-configuration`
where as my client is expecting the URL as : `https://mytenant.b2clogin.com/as/authorization.oauth2?client_id=myClientID&response_type=code&scope=openid&redirect_uri=applicationURL`


Is there a way to restrict the package from appending the URL with "_/v2.0/.well-known/openid-configuration_"

**Comment by hectormmg** [comment]
@GeekyDiya may I ask why you want to add these query parameters to the authority string? The scopes and response_type attributes are meant for authorization/token requests, during which MSAL will correctly append the values to the URI when making a request to the authentication endpoint.

The "/v2.0/.well-known/openid-configuration" path is appended to the authority during endpoint discovery, which MSAL does to know where to send authorization requests afterwards. You probably don't need to worry about the endpoint resolution request.

As long as your token request object includes the correct scopes, you should see the "client_id=myClientID&response_type=code&scope=openid&redirect_uri=applicationURL" parameters in the authorization and token requests when you use `acquireTokenX` APIs to acquire tokens. You actually don't need to set response_type since MSAL uses the Authorization Code flow by default.

**Comment by GeekyDiya** [comment]
@hectormmg Since this is a client SSO we are configuring, this URL is not part of Microsoft and they are using Ping federate as their IDP due to which they require the authority URL to be exactly like the one I posted (with the additional query parameters in the authority string) - `https://mytenant.b2clogin.com/as/authorization.oauth2?client_id=myClientID&response_type=code&scope=openid&redirect_uri=applicationURL`


When the package is appending "/v2.0/.well-known/openid-configuration" the URL fails and gives us 404 error. Hence wanted to check if there is a way to remove that from the authority endpoint. As also if there is a way to add the additional parameters (scope, response_type & client_id)

**Comment by hectormmg** [comment]
@GeekyDiya is Ping being used through Azure AD B2C in this scenario?

**Comment by GeekyDiya** [comment]
@hectormmg  Im not sure how I can check it but in the knownAuthorities I am passing the authority URL provided to us

**Comment by GeekyDiya** [comment]
any updates @hectormmg or could you help?

**Comment by hectormmg** [comment]
@GeekyDiya could you explain why you're trying to redirect to the authority URL yourself? As mentioned before, the parameters you are trying to add to the authority URL are Auth Code request parameters, which, if configured in the MSAL token request, MSAL will append automatically when the token request happens.

The well-known URL path is added to the authority before MSAL requests the tokens from the network in order to do endpoint discovery. You shouldn't need to modify the authority URL for that.
