### ISSUE TITLE
Msal with Angular 13

### ISSUE THREAD

**Issue by AnaflaviaDiaz** [AzureAD/microsoft-authentication-library-for-js#4257]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Description

 I updated to Angular 13 but I have an error with MsalService

![image](https://user-images.githubusercontent.com/15807118/141498798-43a6f25f-5403-4513-b4c1-76b6149d7848.png)

### Source

External (Customer)

**Comment by janpereira-dev** [comment]
I got this error installing msal on angular v13

![image](https://user-images.githubusercontent.com/6440548/142018750-cc2b9988-a724-462f-a6db-3c03e21a6f0a.png)

Do you have any date for the package update?

**Comment by slubowsky** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4154#issuecomment-974183734

**Comment by fayeBabacar78** [comment]
The issue is still present when trying to install @azure/msal-angular in an Angular v13 project. The current version of RXJS when generating a new Angular v13 project is not compatible to the one used within the MSAL library. My fix was to downgrade RXJS version from **7.5.0** to **6.6.7** (the latest before v7).

**Comment by jasonnutter** [comment]
Closing as duplicate of #4154, which includes some potential short-term workarounds. Apologies for the delay in addressing this!
