### ISSUE TITLE
Cache location for Access token 

### ISSUE THREAD

**Issue by rahulmotwani1996** [AzureAD/microsoft-authentication-library-for-js#4271]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.1

### Description

I checked msal documentation regarding SSO. 
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso

Since my client requested for SSO in our react app , i tried different ways to use session storage for SSO but didn't get the required output. Is there any way we can Session storage for SSO

if not do we have any security vulnerability when using local storage.

It would be really helpful if someone can provide their inputs.

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by rahulmotwani1996** [comment]
Hi @samuelkubai  any update on this?

**Comment by samuelkubai** [comment]
Hi @rahulmotwani1996, thank you for raising the question with us.

Could expound more on this?
>  I tried different ways to use session storage for SSO but didn't get the required output

By sharing more on what you have configured, what you expected and what is happening now.

**Comment by rahulmotwani1996** [comment]
Hi @samuelkubai  
I configured azure in my react application by setting the cache location to session storage, but when i opening the same application in new tab it is asking for login again. I tried sharing the session between multiple tabs it worked but idk if that is valid approach sharing session data between multiple tabs.

With using localStorage i was able to achieve the required Single sign on behaviour , but i am concerned if there is any security vulnerability that could arise.

**Comment by sameerag** [comment]
@rahulmotwani1996 `Session Storage` setting here is behaving exactly as intended, the browser limits the memory access to a session which is unique per tab. Our caching strategy is listed [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/926f1c2ba0598575e23dfd8cdd8b79fa3a3d19ff/lib/msal-browser/docs/caching.md)

We cannot support SSO with `session storage` since the memory is partitioned across tabs and we cannot access context of the account created. 

>  I tried sharing the session between multiple tabs it worked but idk if that is valid approach sharing session data between multiple tabs.

This is probably dependent on what data is shared across those sessions. The trade off between `local storage` and `sharing sessions` mostly depends on your data model.

**Comment by rahulmotwani1996** [comment]
@sameerag  If we are going with the localStorage cache strategy is there any security concern with it ?

**Comment by tnorling** [comment]
@rahulmotwani1996 We do not have specific concerns about using local storage, however, it is your responsibility to ensure your application is not vulnerable to XSS and other attacks that may compromise the tokens held in browser storage whether you are using local or session storage.
