### ISSUE TITLE
MSAL in Storybook

### ISSUE THREAD

**Issue by PetterRuud** [AzureAD/microsoft-authentication-library-for-js#4282]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.1

### Description

I'm Trying to set up MSAL in Storybook using a decorator, https://storybook.js.org/docs/react/writing-stories/decorators

It works fine on pageload and if refresh the page, but if i click between the stories I can see that "inProgress" is "startup" and nothing else happens.

I have tried with different configurations for cache, but to no avail.

Anyone got any tips or have done this themself?

I reckon it is something on Storybooks side and how they handle routing as it the same configration i use for the other apps and they work fine.

I dont want to add MSALProvider for each story

### MSAL Configuration

```javascript
auth: {
    clientId: xxx,
    authority: xxx,
    redirectUri: '/',
  },
  cache: {
    secureCookies: true,
    cacheLocation: 'localStorage', // This configures where your cache will be stored
    storeAuthStateInCookie: true, // Set this to "true" if you are having issues on IE11 or Edge
  },
```

### Relevant Code Snippets

```javascript
./storybook/preview.js

const withMSALProvider = (Story) => {
  return (
    <MsalProvider instance={publicClientApplication}>
      <MsalAuthenticationTemplate
        interactionType={InteractionType.Popup}
        loadingComponent={InProgressComponent}
        errorComponent={ErrorComponent}
      >
        <Story />
      </MsalAuthenticationTemplate>

      <UnauthenticatedTemplate>
        <LoggInn />
      </UnauthenticatedTemplate>
    </MsalProvider>
  );
};

export const decorators = [withMSALProvider];
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by igorovic** [comment]
I have a similar issue in a Next.js app when using router.push(). 

Msal inProgress property is set to `startup` then nothing else happens. Nothing is rendered and inPorgress remains at `startup`. 

Here are the my msal trace logs: 

```
inProgress startup
authConfig.ts?849f:25 3 '[Sun, 28 Nov 2021 16:48:48 GMT] : @azure/msal-browser@2.19.0 : Verbose - Event callback registered with id: b376237c-a3d3-4dfa-bc80-5a77bec5b2a3'
authConfig.ts?849f:25 3 '[Sun, 28 Nov 2021 16:48:48 GMT] : @azure/msal-react@1.1.1 : Verbose - MsalProvider - Registered event callback with id: b376237c-a3d3-4dfa-bc80-5a77bec5b2a3'
authConfig.ts?849f:25 3 '[Sun, 28 Nov 2021 16:48:48 GMT] : @azure/msal-browser@2.19.0 : Verbose - Event callback registered with id: 54217728-d3d5-495b-8178-b0b866eacbb6'
authConfig.ts?849f:25 3 '[Sun, 28 Nov 2021 16:48:48 GMT] : @azure/msal-react@1.1.1 : Verbose - MsalProvider - Registered event callback with id: 54217728-d3d5-495b-8178-b0b866eacbb6'
authConfig.ts?849f:25 3 '[Sun, 28 Nov 2021 16:48:48 GMT] : @azure/msal-browser@2.19.0 : Verbose - handleRedirectPromise called'
authConfig.ts?849f:25 3 '[Sun, 28 Nov 2021 16:48:48 GMT] : @azure/msal-browser@2.19.0 : Verbose - getAllAccounts called'
authConfig.ts?849f:25 4 '[Sun, 28 Nov 2021 16:48:48 GMT] : @azure/msal-browser@2.19.0 : Trace - BrowserCacheManager.getIdTokenCredential: cache hit'
authConfig.ts?849f:25 4 '[Sun, 28 Nov 2021 16:48:48 GMT] : @azure/msal-browser@2.19.0 : Trace - BrowserCacheManager.getRefreshTokenCredential: cache hit'
authConfig.ts?849f:25 4 '[Sun, 28 Nov 2021 16:48:48 GMT] : @azure/msal-browser@2.19.0 : Trace - BrowserCacheManager.getIdTokenCredential: cache hit'
authConfig.ts?849f:25 4 '[Sun, 28 Nov 2021 16:48:48 GMT] : @azure/msal-browser@2.19.0 : Trace - BrowserCacheManager.getRefreshTokenCredential: cache hit'
authConfig.ts?849f:25 3 '[Sun, 28 Nov 2021 16:48:48 GMT] : @azure/msal-browser@2.19.0 : Verbose - handleRedirectPromise has been called previously, returning the result from the first call'
```

And the react components explorer: 

![image](https://user-images.githubusercontent.com/758832/143777903-cfc31e17-d2d6-441c-b692-7df0a5bd1bf6.png)

**Comment by sameerag** [comment]
>I dont want to add MSALProvider for each story

@PetterRuud What happens if you add an MSAL provider for each story? Does the refresh work? Also can you please MSAL logs which can help us determine if the events are triggered in the right order. 

@igorovic Can you please check the Next.js sample we published for your issue? You can access the sample [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/nextjs-sample)

**Comment by igorovic** [comment]
I actually used the sample you mentioned.
The issue only happens when I try to change the locale of the project. According to Next.js documentation we can use a link like this one.

`<Link href="/" locale="fr">FR<Link>`

All the links without `locale` work properly. But using `locale` attribute somehow blocks msal client.


> @igorovic Can you please check the Next.js sample we published for your issue? You can access the sample [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/nextjs-sample)

**Comment by tnorling** [comment]
@igorovic On the route change is `MsalProvider` being unmounted/re-mounted? What's happening is that `MsalProvider` expects certain events to be fired to advance through the `inProgress` states and these events are not being fired on the route/locale change because the `PublicClientApplication` hasn't been reinitialized. Essentially there's a misunderstanding between `MsalProvider` and `PublicClientApplication` about whether or not "startup" tasks need to be performed.

We can look into whether or not this can be improved from the library side but regardless the best solution in your case is to do one of 2 things: 

1. Render `MsalProvider` above your routes so that it is not re-rendered on route/locale changes (preferred)
2. Re-initialize `PublicClientApplication` on each route/locale change (this is trickier to implement because we don't suggest initializing `PublicClientApplication` inside your component tree)

I suspect the original issue is suffering from the same root problem and the 2 solutions mentioned may be relevant there as well.

**Comment by igorovic** [comment]
@tnorling Thanks for the quick response. 

I think that `MsalProvider` is above all routes since it's declared in `_app.tsx`.  Here is what my code looks like. 

```_app.tsx
function MyApp({ Component, pageProps }: AppProps) {
  const router = useRouter();
  const navigationClient = new CustomNavigationClient(router);
  msalInstance.setNavigationClient(navigationClient);
  return (
      <MsalProvider instance={msalInstance}>
        <Component {...pageProps} />
      </MsalProvider>
  );
}

export default appWithTranslation(MyApp);
```

I suspect that the culprit is `appWithTranslation` from [next-i18next](https://www.npmjs.com/package/next-i18next). But I couldn't isolate the problem.

**Comment by tnorling** [comment]
@igorovic Ah, I'm guessing since `appWithTranslation` wraps your `MyApp` component that locale changes are causing a re-render of both your page contents and `MsalProvider`. Instead can you try wrapping `Component` with `appWithTranslation` instead so that the translation also sits underneath `MsalProvider`?

Alternatively, you can initialize `PublicClientApplication` before `MyApp` mounts, however, this is less preferred because it means you'll take a performance hit.

I think there's also a slight change we can make in the library to fix this scenario. I'll put an item in our backlog to take a closer look and update this issue if and when I have more.

**Comment by igorovic** [comment]
I was able to workaround this issue with this code. 

```_app.tsx
function MyApp({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />;
}

const App2 = appWithTranslation(MyApp);

function MsalApp(props: AppProps) {
  const router = useRouter();
  const navigationClient = new CustomNavigationClient(router);
  msalInstance.setNavigationClient(navigationClient);
  return (
    <MsalProvider instance={msalInstance}>
      <App2 {...props} />
    </MsalProvider>
  );
}

export default MsalApp;
```

@tnorling  Thanks for your help.

**Comment by tnorling** [comment]
This issue will be fixed by the linked PR. Thanks for bringing this to our attention!
