### ISSUE TITLE
Azure AD B2C Endpoint for checking active session

### ISSUE THREAD

**Issue by JJHakiLe** [AzureAD/microsoft-authentication-library-for-js#4294]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.11.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Hi there, i'm using MSAL browser for authentication on multiple websites with different domains under a single application under one Azure AD B2C Tenant. I am exploring options for cross-tab, cross-domain single sign off. I was wondering if there was a dedicated endpoint that I can make a silent AJAX call to determine if there's an active session?

Thanks in advance!

### Source

External (Customer)

**Comment by sameerag** [comment]
@nickgmicrosoft Can you help here?

**Comment by JasSuri** [comment]
This is not an entirely an MSAL issue, but how AAD B2C performs single logout against your applications, and latest browser protections.

When you hit the AAD B2C /logout endpoint, AAD B2C spawns hidden iframes to every website with a registered logout url that the user is currently tracked to be logged into.
These iframes attempt to clear the MSAL local storage state from the application.

This operation fails when the domain name of the application differs from the domain name used at AAD B2C, as many browsers now enforce protections against 3rd party cookies (includes local storage), and 3rd party tracking. Since the domain name differs, the MSAL local storage is not cleaned, and therefore the user remains logged in until their tokens expire in that app.

The user is only logged out of the website they initiated the logout request from, and Azure AD B2C (session cookies are destroyed).

If you want to check if there is an active session with AAD B2C in the other apps, call MSAL method `ssoSilent()`, which will try do a cookie based authentication to AAD B2C. Those cookies will have been destroyed. If you can do that on some sort of user initiated activity, it would be a workaround. When an error is thrown, call MSAL logout() method. But, be careful, if the Refresh token lifetime exceeds the B2C session lifetime, this approach will start logging out legitimate users.

**Comment by JJHakiLe** [comment]
I see, so AAD B2C endpoint will spawn a hidden iframe with the registered logout URL for each client application that the user is signed into. So the registered logout URL will only work if the application is only used with a single domain. Hence, why local storage works for single sign out in these cases.

Got it, does the method `ssoSilent()` make a request to AAD B2C endpoint to see if cookies are present on that AAD B2C endpoint? And does `ssoSilent()` work for all browsers? I believe I read somewhere that `ssoSilent()` will always fail when third party cookies are disabled (https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas) 

Thank you very much in advance!

**Comment by JasSuri** [comment]
Actually yes, you are right there, even `ssoSilent()` will fail in the case where the app is on a different domain to AAD B2C. So right now, there is no real (nice) workaround here.

**Comment by JJHakiLe** [comment]
Gotcha, so `ssoSilent()` will fail on apps with multiple different domains. Okay, I think this answers my questions. Thank you very much for your insight and help @JasSuri !
