### ISSUE TITLE
Question about Password Reset & MsalAuthenticationTemplate

### ISSUE THREAD

**Issue by Hopp3r** [AzureAD/microsoft-authentication-library-for-js#4382]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.1

### Description

I've recently begun to implement a forgot password (redirect) flow into my React application.
I've elected to use MsalAuthenticationTemplate and have some questions about implementation.

Forgot password is handled as an error event & thus the fallback is to render the component passed as a prop to MsalAuthenticationTemplate like so:

```js
<MsalAuthenticationTemplate
      interactionType={InteractionType.Redirect}
      authenticationRequest={{
        scopes: ["openid", "profile"],
        prompt: 'login',
      }}
      loadingComponent={MyLoadingComponent}
      errorComponent={MyErrorComponent}
>
  <p>At least one account is signed in!</p>
</MsalAuthenticationTemplate>
```

This makes sense, but some behavior I've noticed is that MyErrorComponent will display briefly while InteractionStatus is not "none".  Therefore a page that indicates an error will briefly display while my application is proceeding through the various InteractionStatus(es) before finally being redirected to my forgot password authority.

I've solved this by putting a guard like:
```js
errorComponent={ InteractionStatus.None ? MyErrorComponent : MyLoadingComponent }
```
so that the component that briefly displays is a loading one. However, should the onus of this be on the developer or on the library? It seems like we'd only want to display an errorComponent once the InteractionStatus is no longer in flux.

Let me know if you have any questions or if I'm doing something incorrectly.

Thanks!

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
@Hopp3r Rendering the error component should already be gated by interaction status on [this line](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/2f0c4095993f54056acc1b30b52628a9a308cd9e/lib/msal-react/src/components/MsalAuthenticationTemplate.tsx#L47)

Is it possible that the brief visibility here is due to `InteractionStatus` briefly being `None` between your 2 interactions (coming back from the signin policy and leaving for the forgot password policy)?

Would you be able to provide a reproduction, preferably using one of our [samples](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples)?

**Comment by syed-ahmad** [comment]
I'm facing the same issue, will put together a sample to reproduce that.
