### ISSUE TITLE
BrowserAuthError: hash_empty_error: Hash value cannot be processed because it is empty. Please verify that your redirectUri is not clearing the hash. 

### ISSUE THREAD

**Issue by RuchiShah2021** [AzureAD/microsoft-authentication-library-for-js#4456]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

when using B2C UserFlow login, we are getting below error.  can someone please help ? 

### Error Message

BrowserAuthError: hash_empty_error: Hash value cannot be processed because it is empty. Please verify that your redirectUri is not clearing the hash. Given Url: https://ourSite.com/login
at t [as constructor] (main.7fe9d3ff.js:2:48435)
at new t (main.7fe9d3ff.js:2:63089)
at Function.t.createEmptyHashError (main.7fe9d3ff.js:2:63588)
at main.7fe9d3ff.js:2:193588

### MSAL Configuration

```javascript
export const msalConfig = {
    auth: {
        clientId: "id", // This is the ONLY mandatory field that you need to supply.
        authority: b2cPolicies.authorities.signUpSignIn.authority, // Use a sign-up/sign-in user-flow as a default authority
        knownAuthorities: [b2cPolicies.authorityDomain], // Mark your B2C tenant's domain as trusted.
        redirectUri: `${window.location.origin}/login`,
        postLogoutRedirectUri: "/", // Indicates the page to navigate after logout.
        navigateToLoginRequestUrl: false, // If "true", will navigate back to the original request location before processing the auth code response.
    },
    cache: {
        cacheLocation: "sessionStorage", // Configures cache location. "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    },
    system: {	
        loggerOptions: {	
            loggerCallback: (level, message, containsPii) => {	
                if (containsPii) {		
                    return;		
                }		
                switch (level) {		
                    case LogLevel.Error:		
                        console.error(message);		
                        return;		
                    case LogLevel.Info:		
                        console.info(message);		
                        return;		
                    case LogLevel.Verbose:		
                        console.debug(message);		
                        return;		
                    case LogLevel.Warning:		
                        console.warn(message);		
                        return;		
                }	
            }	
        }	
    }
};
```

### Relevant Code Snippets

```javascript
// simple login function

const userAgentApplication = new PublicClientApplication(msalConfig);
  async login(event) {
    event.preventDefault();
    var that = this;
    this.userAgentApplication.loginPopup(loginRequest).then(
      function (result) {
        if (result.accessToken.length > 10) {
          that.setState({ email: result.account.username });
          that.setState({ username: result.account.username });
          that.setState({ isLoading: true }, () => {
            that.props.login(that.state.email, that.state.password);
          });
        }
      }).catch(function (error) {
        console.log(error);
      });
  }
```

### Reproduction Steps

just run the function specified above in code snippet
you will see the error. 

### Expected Behavior

Expecting login to work. 

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@RuchiShah2021 When using `loginPopup`, the popup opened by MSAL will be redirected back to your redirect uri with the response in the hash (fragment) of the url. As noted in the error message, this error means that MSAL attempted to read the hash response, however, the hash was empty. This likely because your application is clearing the hash when the redirect uri (`https://ourSite.com/login`) is loaded. You need to make sure when this route is loaded in your app (with a url like `https://ourSite.com/login#code=...`) that it isn't cleared, as this will allow MSAL to parse it and complete login.

**Comment by HichamBenjelloun** [comment]
To complement @jasonnutter's answer, [the official documentation recommends setting the `redirectUri` to a blank page when using popup and silent APIs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#redirecturi-considerations).

I had the same issue recently because my application router was intermittently redirecting based on the authentication state (maybe related to #4477) before the hash had a chance to be processed.
