### ISSUE TITLE
I am calling the /token end point after every 10 mins. to check the token validity , is there any cap on the number of token calls we can make on the network.

### ISSUE THREAD

**Issue by rahulmotwani1996** [AzureAD/microsoft-authentication-library-for-js#4457]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.2.0

### Description

For handling password change , or any change in the account for which i need to invalidate any current session of the user, i am calling the token api from my application after every 10 mins. with { forceRefresh: true } is there any cap or can microsoft reject the calls if they are too frequent ?

### Relevant Code Snippets

```javascript
setInterval(() => { fetchAccessToken({ forceRefresh: true }) }, 1000 * 60 * 10)
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@rahulmotwani1996 We do not recommend doing this, as it will likely result in your application getting throttled, as there is a limit on how often you can invoke the token endpoint. Instead of doing this, we recommend implementing [Continuous Access Evaluation](https://docs.microsoft.com/azure/active-directory/conditional-access/concept-continuous-access-evaluation). cc @salman90 for documentation

**Comment by rahulmotwani1996** [comment]
@salman90 Can you please provide the link for the documentation on how to integrate CAE with web application.

**Comment by jasonnutter** [comment]
@rahulmotwani1996 https://docs.microsoft.com/azure/active-directory/conditional-access/concept-continuous-access-evaluation
