### ISSUE TITLE
handleRedirectPromise after signing in with scopes of multiple resources

### ISSUE THREAD

**Issue by ukaaa** [AzureAD/microsoft-authentication-library-for-js#4479]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

When signing in a user with multiple scopes from multiple resources, e.g. ```[`api://${client_id_1}/access_as_user`, `api://${client_id_2}/access_as_user`]``` and redirecting back to our web page, we have issues using `handleRedirectPromise`.

`handleRedirectPromise` is triggering a token request, but it uses the same multiple scopes from multiple resources to do so, resulting in the following error:

```
AADSTS28000 Provided value for the input parameter scope is not valid because it contains more than one resource
```

I understand that you cannot request a token for multiple scopes from multiple resources. I don't know why `handleRedirectPromise` tries that. Instead, I suppose it should do multiple token requests for the individual resources.

- Can we prevent using `handleRedirectPromise` in our code and handle the URL hash ourselves?
- Can we configure the behaviour of `handleRedirectPromise` to not request a token for all resources at the same time?

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@ukaaa 

> Can we configure the behaviour of handleRedirectPromise to not request a token for all resources at the same time?

Unfortunately, MSAL.js by design makes no attempt to understand the semantics of the scopes array, i.e. whether or not two scopes are for different resources. 

For scenarios like this, an application should provide scopes for one resource in the `scopes` array, and provide the scopes for other resources in the `extraScopesToConsent` array. These scopes will be sent to the `authorize` endpoint so that the user can consent to them, however, will not be included in the request to the `token` endpoint. And then after invoking `handleRedirectPromise` (which will return you an access token for the first resource), the application should invoke `acquireTokenSilent` for each additional resource to get an access token for those resources.

```js
// Initiate login
await msalInstance.loginRedirect({
  // ...
  scopes: [ `api://${client_id_1}/access_as_user` ],
  extraScopesToConsent: [ `api://${client_id_2}/access_as_user` ] 
})

// Process login
const {
  accessToken: accessTokenForResource1
} = await msalInstance.handleRedirectPromise();

const {
  accessToken: accessTokenForResource2
} = await msalInstance.acquireTokenSilent({
  scopes: [ `api://${client_id_2}/access_as_user` ] 
})
```

> Can we prevent using handleRedirectPromise in our code and handle the URL hash ourselves?

We do not recommend doing this, given the complexity involved in processing authorization codes which is handled by `handleRedirectPromise` (and it would still require your application to hit the `token` endpoint twice).

Let us know if you have further questions.

**Comment by ukaaa** [comment]
Thanks @jasonnutter, this is exactly what I was looking for. I just tested it and it works. Thanks for explaining in detail 👍
