### ISSUE TITLE
How to send id_token instead of access_token?

### ISSUE THREAD

**Issue by alexander-e-andrews** [AzureAD/microsoft-authentication-library-for-js#4521]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.17.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.3

### Description

How can I send the id_token instead of the access_token for my Authorization header? I would like to check the user's roles on my API server. I can see the id_token using this.authService.instance.getActiveAccount()?.idTokenClaims. 

### MSAL Configuration

```javascript
auth: {
    clientId: environment.clientId,
    authority: environment.authority,
    redirectUri: '/',
    postLogoutRedirectUri: '/',
  },
  cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage,
    storeAuthStateInCookie: isIE,
  },
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @alexander-e-andrews . The Interceptor doesn't allow that behavior since ID tokens aren't interchangeable with access tokens and serve different purposes. Which specific claim are you looking to inspect? It is likely this ID token claim in question may also be in the access token. If that's not the case, using a custom scope for specific user roles could be a good solution here.

**Comment by alexander-e-andrews** [comment]
@hectormmg I am trying to send custom app roles. I have added them under the API Permissions tab on my ad instance, but I do not see them on the access token. Is there something basic I could be missing?

**Comment by jo-arroyo** [comment]
@alexander-e-andrews Have you followed the steps listed in [this document](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps) about adding app roles?
