### ISSUE TITLE
Store Id Token in session cookie

### ISSUE THREAD

**Issue by tejaswibm** [AzureAD/microsoft-authentication-library-for-js#4525]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.0

### Description

I have an SPA that has links to multiple portals hosted in different domains. Each of these portals in turn have integrated SSO using flask-appbuilder. When logged-in to my SPA, I want the links of other portals to open without asking for login again.

I checked `Flask` code and it checks if JWT token is present in session cookie.

In my SPA, I have integrated msal, but it does not allow me to store idToken in session cookie. 

Can this be achieved with msal library or whats the best way to store idToken in session cookie ?

### MSAL Configuration

```javascript
import { Configuration } from "@azure/msal-browser";


export const MSAL_CONFIG: Configuration = {
  auth: {
    clientId: '<CLIENT_ID>',
    authority: 'https://login.microsoftonline.com/<TENANT_ID>',
    redirectUri: 'http://localhost:9000/',
    postLogoutRedirectUri: 'http://localhost:9000/'
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: true,
    secureCookies: false,
  },
};

/**
 * Scopes you add here will be prompted for user consent during sign-in.
 * By default, MSAL.js will add OIDC scopes (openid, profile, email) to any login request.
 * For more information about OIDC scopes, visit:
 * https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#openid-connect-scopes
 */
 export const loginRequest = {
  scopes: ["User.Read"]
};

/**
* Add here the scopes to request when obtaining an access token for MS Graph API. For more information, see:
* https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md
*/
export const graphConfig = {
  graphMeEndpoint: "https://graph.microsoft.com/v1.0/me"
};

export default MSAL_CONFIG;
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
Hi @tejaswibm , thanks for raising the issue!

Setting the ID Token in the session cookie is only useful for the app on a specific domain maintaining its own access while the session is active, since cookies are partitioned by domain. This means even if you did set it, it would not be accessible from the other portals/apps on different domains.

As far as how to achieve SSO across domains, each app still has to make a token request through MSAL by either using our interactive APIs (loginRedirect/loginPopup) or by leveraging [ssoSilent](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#silent-login-with-ssosilent). I hope this helps.

**Comment by tejaswibm** [comment]
@hectormmg - Thanks for providing your insights. 
1. All portals in our eco-system are hosted on the same domain (only sub-domains are different).
2. Flask-AppBuilder lib uses session cookie to check if JWT is already present; if not then makes token request call.

Given above 2 points, do you still suggest not to set session cookie with JWT manually ? Is there any security risks in doing so manually ?

**Comment by jo-arroyo** [comment]
@tejaswibm Since the cache is not shared between sub-domains, each app would have to go to the network to request tokens. Our recommendation would still be to leverage [ssoSilent](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#silent-login-with-ssosilent) instead of setting the cookies manually.
