### ISSUE TITLE
Redirect user to custom error page when AADSTS50105 error occurs

### ISSUE THREAD

**Issue by ranikatta** [AzureAD/microsoft-authentication-library-for-js#4529]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.20.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.6

### Description

Hi, is there a way that I can redirect the user to a custom error page instead of showing the below screen.
There are users that are using our app and who have multiple MS accounts. When they access our app and was signed in with another account already which do not have access to our app this page shows up. There is no link such that user can logout of existing session and login with another account. 

![image](https://user-images.githubusercontent.com/11966035/154345467-7ede4569-7185-49ee-826c-370aeaf255cd.png)

Thanks for any help.

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
@ranikatta that error screen as well as the navigation are handled on the service side, so MSAL has no control over redirection after an error like this. The user needs to hit the back button or manually go back to your application. You can leverage MSAL's logout APIs in order to remove the tokens from their other accounts from the MSAL cache so the next time they will be prompted for the account during login.

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md

**Comment by ranikatta** [comment]
@hectormmg thanks for your reply and suggestion.
