### ISSUE TITLE
MsalGuard and consent scopes fail when scopes from multiple resources are specified

### ISSUE THREAD

**Issue by rellis-of-rhindleton** [AzureAD/microsoft-authentication-library-for-js#4532]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.2

### Description

We've been using MSAL Angular for a long time now, and I thought I knew how to configure it. We had to spend a few hours troubleshooting an error yesterday and although we got it working I'm confused. Was hoping you could provide some clarification.

In the MsalGuard config factory I've been including the full list of scopes to which the user needs to consent. This worked fine with scopes from two resources (Graph and our own API). When we added a third resource (another of our own APIs) we started getting this error:

`AADSTS28000: Provided value for the input parameter scope is not valid because it contains more than one resource.`

This error happens during authentication, not during an attempt to obtain access tokens for APIs (it doesn't get that far).

Removing the scopes from the guard config fixed the problem. Removing the new API from protected resource map also fixed it, but then we couldn't call that API, so that wasn't an option.

I'm just wondering what we're supposed to be doing with authRequest.scopes. The scopes are already consented by admins in Azure, so we don't actually need it, but if we did then would we be able to use it?

### MSAL Configuration

```javascript
const protectedResourceMap = new Map<string, Array<string>>();
protectedResourceMap.set('https://graph.microsoft.com/v1.0', ['User.Read']);
protectedResourceMap.set('https://api-number-one', ['api://api-number-one-id/access_as_user']);
protectedResourceMap.set('https://api-number-two', ['api://api-number-two-id/access_as_user']);

export function msalInterceptorConfigFactory(): MsalInterceptorConfiguration {
    return {
      interactionType: InteractionType.Redirect,
      protectedResourceMap
    };
  }
  
export function msalGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
      // This fails. If I comment out authRequest, it works fine.
      authRequest: {
      scopes: [
        'openid',
        'profile',
        'User.Read',
        'api://api-number-one-id/access_as_user',
        'api://api-number-two-id/access_as_user',
      ]
    },
    loginFailedRoute: loginFailedUri
  };
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @rellis-of-rhindleton , thanks for opening this issue, happy to help.

AAD doesn't support scopes for multiple resources in the `scopes` parameter, but there is a query parameter that MSAL and AAD support called `extraScopesToConsent`. Putting scopes for other resources in `extraScopesToConsent` should allow the server to prompt the user for consent on those scopes while they're logging in and although they won't receive an access token for those scopes immediately, the app can later request those access tokens silently. 

```typescript
export function msalGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
      authRequest: {
      scopes: [
        'openid',
        'profile',
        'User.Read',
        'api://api-number-one-id/access_as_user',
      ], 
     extraScopesToConsent: [
        'api://api-number-two-id/access_as_user',
      ]
    },
    loginFailedRoute: loginFailedUri
  };
}
```

Check out our docs on [Resources and Scopes](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md#dynamic-scopes-and-incremental-consent) for more info on `extraScopesToConsent` and some usage examples.

Let us know if your issue is resolved with this suggestion so we can close the issue, thanks!

**Comment by rellis-of-rhindleton** [comment]
I see - apparently the [documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-guard.md) for msalGuardConfigFactory needs to be updated. There’s nothing in  about that. 

I believe that answers my question, thanks.
