### ISSUE TITLE
Consistency track: please provide consistent APIs to disable authority validation and instance discovery

### ISSUE THREAD

**Issue by xiangyan99** [AzureAD/microsoft-authentication-library-for-js#4625]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular), MSAL React (@azure/msal-react), MSAL Node Extensions (@azure/msal-node-extensions)

### Description

Now we have different API/behaviors for customers to disable authority validation and instance discovery.

Please sync across languages to provide consistent ones.

This is important because JEDI scenarios are blocked by current behavior.

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@xiangyan99 Thanks for filing. Can you please work with @EmLauber to have this tracked in ADO? Thanks!

**Comment by jasonnutter** [comment]
@xiangyan99 Also, please confirm the version of MSAL.js impacted. We are no longer adding new feature to MSAL.js v1, and instead are only focusing on MSAL.js v2 (`@azure/msal-browser`).

**Comment by xiangyan99** [comment]
This is for latest msal. :)

**Comment by sameerag** [comment]
@jasonnutter I am in discussion with AzureSDK on this topic. We do not intend to change MSAL JS's API, we are already compliant with JEDI/Airgapped support with "KnownAuthorities". I have tagged @EmLauber to follow up with the PM leads to standardize this across MSALs.

@xiangyan99 We prefer ADO tracking instead of github in this use case since there is no action needed from the MSAL JS dev team at this point.  I will have @EmLauber handle it and close this ticket.

**Comment by sameerag** [comment]
Update: MSAL JS already has all the code changes needed regarding this change. Azure SDK dev is currently adding tests to confirm the consistency of the authority behavior.

@KarishmaGhiya please close this once you are able to test all the use cases.

**Comment by sameerag** [comment]
@KarishmaGhiya Closing this as you merged your change. Thanks.
cc @EmLauber in case we have an ADO open, we can link this and close it. Please let me know.
