### ISSUE TITLE
Outdated and incorrect documentation on distributed caching in `@azure/msal-node`

### ISSUE THREAD

**Issue by rudfoss** [AzureAD/microsoft-authentication-library-for-js#4632]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable (edit: removed angular, not applicable).

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/ExpressTestApp/TestApp/App/utils/cachePlugin.js

### Description

The example provided here doesn't seem to be correct anymore. 

[This line](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/f2ee16ca90914edf61ac4f5ee098d235079d52b3/samples/msal-node-samples/ExpressTestApp/TestApp/App/utils/cachePlugin.js#L48) in the `cachePlugin.js` file refers to the method `getKVStore()` that no longer exists on the object. What would be the appropriate alternative for `@azure/msal-node` v1.7.0?

I've been looking for good documentation on how to implement an express application (or any web application really) that supports multi-user authentication while protecting each users cached credentials correctly. Many different MS specific sites such as [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/caching.md#performance-and-security) and [this](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-node-migration) eventually lead back the above example. And since the example no longer works it is hard to know the correct way to implement this.

Authentication is already pretty hard to get right so I feel it is critical to have good documentation on how to distribute cached credentials correctly using `msal`. Especially when the library is recommended by Microsoft.

**Comment by sameerag** [comment]
@rudfoss Thank you for bringing this to our attention. @salman90 can you please work with @samuelkubai to update this sample?

**Comment by jon-a-nygaard** [comment]
@sameerag @salman90 @samuelkubai Has there been made any recent updates or progress related to this issue topic? :slightly_smiling_face:
I feel the documentation and example on distributed caching is a bit lacking, and could benefit from some updates and elaboration to boost the confidence about maturity and security of the implementation.

So far I have encountered the following issues when trying to implement persistent caching based on the [Securing an Express MVC web app with MSAL Node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/51a79f565227de3734824fbdffeeb315d0d029a3/samples/msal-node-samples/ExpressTestApp#securing-an-express-mvc-web-app-with-msal-node) example:

## `ClientApplication.tokenCache.persistence` is a private member in TypeScript
In the example the partition key is provided by [creating a new instance implementing `ICachePlugin` and override `ConfidentialClient.tokenCache.persistence` with the new instance](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/ExpressTestApp/TestApp/App/app.js#L63-L64) which contains a reference to the provided partition key (session id).
- First problem here is that `ConfidentialClient.tokenCache` is a private member, but this can be solved by using `ConfidentialClient.getTokenCache()`.
- Then the second problem arises when trying to set `TokenCache.persistence` since this is a private readonly member. The TypeScript compiler is not happy with this, and a `ConfidentialClient.setCachePlugin` or similar solution would be helpful.

## Overriding `ClientApplication.tokenCache.persistence` is not sufficient
For instance [`ConfidentialClient.acquireTokenByCode` is creating an instance of `AuthorizationCodeClient`](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/51a79f565227de3734824fbdffeeb315d0d029a3/lib/msal-node/src/client/ClientApplication.ts#L150) which is passed the cache plugin instance that is located in `ConfidentialClient.config.cache.cachePlugin`.
Therefore it is not enough to just override `ClientApplication.tokenCache.persistence`, but it is also necessary to override `ConfidentialClient.config.cache.cachePlugin` to make sure the correct partition key is used.
Again a helper function such as `ConfidentialClient.setCachePlugin` or similarly would be helpful to take care of the required internal logic.

**Comment by derisen** [comment]
@jon-a-nygaard apologies for the confusion. This sample was demoing an initial approach to distributed caching, but since then msal-node was updated and a more mature pattern has been implemented [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/RedisTestApp) -can you please refer to that sample instead? I'll keep this open to update the **ExpressTestApp** sample and the distributed caching doc to clarify things.

**Comment by jon-a-nygaard** [comment]
Thanks for the quick reply and help @derisen, I will look to the `RedisTestApp` sample. Glad to see that you're updating the docs as well 🙂
