### ISSUE TITLE
Login flow in electron chromium browser popups is it secure??

### ISSUE THREAD

**Issue by ashu8912** [AzureAD/microsoft-authentication-library-for-js#4737]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0

### Description

I wan to use msal for my electron app authentication flow and i am not sure if it is secure to do the entire authentication process inside the chromium runtime based window that electron provides, I was in an impression that msal redirect option would open an external browser window to authenticate but that is actually not the case, both popup and redirect open the same electron provided window. 

My security concern arises from here https://stackoverflow.com/a/69332071/8527880

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
@ashu8912 thanks for the question. Since MSAL Node doesn't officially support Electron, the security considerations from the OAuth 2.0 perspective haven't been fully investigated. I will look into using the default browser and will update the sample accordingly, but please remember that this is a usage sample for a scenario that isn't officially supported.
