### ISSUE TITLE
Magic link documentation is missing (connection for id_token or access_token)

### ISSUE THREAD

**Issue by akarray** [AzureAD/microsoft-authentication-library-for-js#4890]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/working-with-b2c.md

### Description

Hi,

I don't find any documentation about using magic link scenario.
The goal is to login with a link like this exemple : https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-magic-link

I have a link generator that work perfectly. But I don't find any way to login with this link.

Is there a sample to share please ?
Thank you 
Best

**Comment by derisen** [comment]
@akarray Our documentation aims to cover general usage, but it might not be able to discuss every use case. It's best if you could raise an issue with the [azure-ad-b2c/samples](https://github.com/azure-ad-b2c/samples) repo and ask for a JavaScript example. Regardless, it seems the scenario requires your client app to grab the signed JWT which contains the `id_token_hint` claim from the query parameters when the user clicks the magic link that will redirect to your client app, and then pass this JWT to a login request to Azure AD B2C where the magic link policy is the `authority`. This might look like:

```JavaScript
// grab the 'id-token-hint-value' from query params

const loginRequest = {
     authority: 'https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/my_magic_link_policy',
     extraQueryParameters: { id_token_hint: 'id-token-hint-value' }
};

msalInstance.loginPopup(loginRequest);
```

**Comment by akarray** [comment]
@derisen Thank you for explanation. I understand better now. 
It still not working for us this flow. Authority link look mysterious for us.

We tested format of your example : https://xxxx.b2clogin.com/mytenant.onmicrosoft.com/b2c_1a_signin_with_magic_links
_We get this error: ServerError: invalid_request: AADB2C90233: The provided id_token_hint parameter failed signature validation._
We are sure that signature and issuer are both good

We tested also link format for endpoint : https://xxx.b2clogin.com/xxx.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1a_signin_with_magic_links
We get cors and then 404 error


We don't need to see a popup in our passwordless signin case. Is there a better user friendly method  than msalInstance.loginPopup  ?

Thanks for your help

**Comment by derisen** [comment]
@akarray it seems your first case actually hit the correct B2C policy (the second case i.e. policy name in query parameters is not supported) -it's just that the service couldn't validate the signature. It's not really possible for us to determine the reason here. If possible, consider [opening a support ticket](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#what-should-i-do-if-i-believe-my-issue-is-with-the-b2c-service-itself-rather-than-with-the-library) with the B2C service. It's also a good idea to ask around the [azure-ad-b2c/samples](https://github.com/azure-ad-b2c/samples) repo.

Regarding the popup, you could use the [redirect flow](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/initialization.md#redirect-apis) instead (`loginRedirect`). You might also attempt to [silently log in the user](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#silent-login-with-ssosilent) via `ssoSilent` API , though you should make sure to catch if it throws `interaction_required` error and handle it with either `loginRedirect` or `loginPopup`.

**Comment by akarray** [comment]
Thank you.
