### ISSUE TITLE
Add method to logout user directly

### ISSUE THREAD

**Issue by Ralms** [AzureAD/microsoft-authentication-library-for-js#490]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently we only have available the method logout() which receives no parameters.
Meaning that in a multi-user login portal, when a user wants to login a specific account, he will be prompted with the Microsoft account selector to logout. 

## Request
Would be great to add a method like logoutUser(user) where we can provide the user object to logout directly, avoiding that extra step to the user to reselect the account he wishes to logout.

</code></pre>

**Comment by daniel-seitz** [comment]
Would be great to have that feature. Please let us know if and when this is planned.

**Comment by sameerag** [comment]
@Ralms @daniel-seitz Logout screen is not controlled by MSAL JS but the service. We are tracking this with the service team who are in control of the logout screen if there is a query parameter that can help achieve this behavior. 

We will update this issue once we hear back from them.

**Comment by Ralms** [comment]
@sameerag Thank you for the update.

**Comment by daniel-seitz** [comment]
Great, thank you.
One important thing to consider is that the user might use other ms apps in other tabs as well. Here we should likely not log out the user from all apps. Or at least thats something to think about.

**Comment by Apollinaire** [comment]
>  We are tracking this with the service team who are in control of the logout screen if there is a query parameter that can help achieve this behavior.

Any update on this @sameerag ?

**Comment by sameerag** [comment]
@Ralms @daniel-seitz @Apollinaire The service team confirmed that this behavior in v2 is by design even if it is an extra prompt for the user to select for the below reasons (for cases without a hint) :

**In the security considerations of the OpenId Session Mgmt spec:**
The id_token_hint parameter to a logout request can be used to determine which RP initiated the logout request. Logout requests without a valid id_token_hint value are a potential means of denial of service; therefore, OPs may want to require explicit user confirmation before acting upon them.

There are two follow-ups we can do in this regard:

1) Currently, even if a hint is passed, we do not have the v2 endpoint supporting this out of the box. It needs further discussion and a potential feature if the service team decides to implement it.

2) I am pursuing if there is an option for a single user AAD (first party) use case to bypass this and will update this PR when I hear back. 

But for a generic use case, this prompt during logout for v2 may stay for a while.

**Comment by sameerag** [comment]
Looks like this is something the service plans to revisit but only after a quarter. Tagging @negoe to track this as a feature we want to work on later. 

@negoe once we have this feature in ADO, please close this ticket or tag it with a milestone that is appropriate to revisit later.

**Comment by jmprieur** [comment]
@negoe, @sameerag : please keep me in the loop. We have the same questions for Web app that sign-out users

**Comment by PraveenVerma17** [comment]
@sameerag
I think we should priorities this issue because its a huge security whole in process.

Step 1: Click on log out
Step 2: Does not select any account to logout
Step 3: leave system if someone else uses same session window or same browser and refreshes the page
Step 4: MSAL does not remove this from server because token did not expire yet
Step 5: Another user get the access of previous user data even though we are explicitly clearing cache and storage

**Comment by DarylThayil** [comment]
#735  Unfortunately the protocol does not support this yet. We have filed a ticket with them to get this work done so it is supported

**Comment by daniel-seitz** [comment]
A "half-baked" workaround could be:

- User clicks logout
- Remove all items in localstorage which start with msal
- Call the logout method

That way upon reload of the app (even without clicking the final AD-logout) the msal-logged-in state for this particular app (and also this user) is logged-out. No token no login.

Only thing is of course that the user is still logged into AD and can easily log in again, however it is an additional step for an "attacker" since the login screen is displayed and .. two clicks are needed to sign in.
This might break if msal chooses to change the prefix or introduce additional items with different names in localstorage.

Thank you all for looking into this!

**Comment by PraveenVerma17** [comment]
Use the session storage instead of local storage. So you can clear directly without choosing MSAL once. If you are not looking for SSO.
