### ISSUE TITLE
Redirect url with state parameter

### ISSUE THREAD

**Issue by chandveri** [AzureAD/microsoft-authentication-library-for-js#4908]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

2.3.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.3.1

### Description

Hello,

We have created a new  app in azure app registration to integrate microsoft teams with our application. Currently we are  stuck on below two points. Any help will be highly appreciated.

1- Redirect Url issue
A. We are authenticating from an azure app from our application.
B. In the azure app we have provided a redirect url  http://localhost:4203/profile-verification
C. But when authentication happens from Microsoft azure app it redirects the page to http://localhost:4203/ instead of specific url http://localhost:4203/profile-verification that we gave in step 2.

2- State parameter
There is one more issue that we want to make this url dynamic by appending some parameters to the redirect URL like http://localhost:4203/candidate-detail/9123?type=video&title=Screen
According to our discussions with the azure team they have given us the solution to use state parameters that we can append after authentication from the azure app. We tried but it did not work. Can you please help by providing sample code for state parameters so that we can get this feature to work?

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: 'e192d3dc-0e6e-48e2-bdb0-429d05fa6a11',
      authority: 'https://login.microsoftonline.com/410c01dc-5cc4-4719-a1f1-886c158029ss',
      redirectUri: 'http://localhost:4203/profile-verification',
      postLogoutRedirectUri: 'http://localhost:4203/profile-verification'
    }
  });
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @chandveri . 

For the first issue, it is possible that Angular is redirecting the user to the base route because the redirectUri isn't registered as a route in your app's routing module even when the server is redirecting to your redirect URI. Can you confirm if this is the case?

For the dynamic parameters in the URL, we could may need some clarification.

If the user is already in the location that they should be redirected to, then setting `navigateToLoginRequestUrl` in the auth config object should take care of redirecting them to the same page after the entire auth flow is done.

If you want to dynamically route your user to a different page after they are redirected to `/profile-verification` by the server, you can add whatever information you need as a string in the `state` request parameter, but you will have to extract this state from the `authResponse`, parse it and handle the redirect logic in your own application.
