### ISSUE TITLE
Add Subscription Check

### ISSUE THREAD

**Issue by Toso82** [AzureAD/microsoft-authentication-library-for-js#4933]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.23.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.2.0

### Description

My problem i want to add extra check on login for subscription user state. It is possible to add check on refresh token? And how? I have api to check state of subscription.  Or there is other best solution i don't know?

Any suggestion?

Many Thanks

### MSAL Configuration

```javascript
{ // MSAL Configuration
      auth: {
        clientId: '',
        authority: '',
        redirectUri: '/',
      },
      cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
        storeAuthStateInCookie: true, 
      },
      system: {
        loggerOptions: {
          loggerCallback: (logLevel: LogLevel, message: string ) =>{
            //console.log(message);
          },
          // logLevel: LogLevel.Verbose,
          piiLoggingEnabled: false
        }
      }
    }), {
      interactionType: InteractionType.Redirect, // MSAL Guard Configuration      
    }, {
        interactionType: InteractionType.Redirect, // MSAL Interceptor Configuration
        protectedResourceMap: new Map()
    })
  ],
  
  exports: [MsalModule],
}
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by bmahall** [comment]
@Toso82 I am currently looking into this , thanks for your patience!

**Comment by Toso82** [comment]
I'm waiting the solution :-) thanks @bmahall

**Comment by bmahall** [comment]
@Toso82 Thanks for your question.  For adding a Rest API call during Azure AD B2C Custom policy- Sign In, the process should be similar to:-
[https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-api-connector-token-enrichment?pivots=b2c-user-flow](url)
[https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-api-connector?pivots=b2c-user-flow](url)

For more information on Technical Profile, you can refer to:-
[https://docs.microsoft.com/en-us/azure/active-directory-b2c/restful-technical-profile](url)


After creating the Technical Profile for the API endpoint, you can add it as an orchestration profile step.

Is there any particular step you are facing issue with? 

For B2C specific queries, you can raise an issue [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#what-should-i-do-if-i-believe-my-issue-is-with-the-b2c-service-itself-rather-than-with-the-library).

**Comment by Toso82** [comment]
Hi I try to understand how to put your suggestion but I'm not so clear I understand I could add a custom workflow but how it is not so easy. I mean if I understand correct I must to add something return claim or role to check in client?

**Comment by bmahall** [comment]
@Toso82 Apologies for the delay, I have relayed your follow-up query for exact implementation details regarding B2C Custom policy to the relevant team. 

Meanwhile, a broad-level overview of the implementation level changes that are involved in your scenario are as follows:-
Assuming you have your RestAPI registered in Azure, the following steps are required:-
1. **Cut UserJourneys section from Base file and paste in Extensions file**** (recommended). Paste it after the ClaimsProvider section ends.  

2. **Create ClaimsProvider Technical Profile**:- This technical profile contains configuration details for your rest API and provides a connection between Azure AD B2C and the API. For convenience, you can consider using the B2c Visual studio extension, using this you can automatically search for "B2c add rest API Technical Profile" and it will load it for you. 
For example of Technical Profile, refer to [https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-api-connector-token-enrichment?pivots=b2c-custom-policy#add-the-restful-api-technical-profile](url) . 
       2.1) Under the OutputClaim, replace PartnerClaimType value with the variable name returned from the Api. Example:- state 

      2.2) _Under TechnicalProfile, input claims represent the set of information you are sending to the Api._ For sending complex Json payloads to the Api, you can also attach SendClaimsin option as referenced here:- [https://docs.microsoft.com/en-us/azure/active-directory-b2c/restful-technical-profile#send-a-json-payload](url). Again, this is very implementation specific and depends on the data you want to send to your api. 

_Output claims should reflect the information that the rest API is sending back_ , hence replace the PartnerClaimType value to reflect the data field name sent back by your Api. 
It should look like:-
`<InputClaim ClaimTypeReferenceId="userLanguage" **PartnerClaimType**="lang" DefaultValue="{Culture:LCID}" AlwaysUseDefaultValue="true" />`

2.3) You can set the authentication to Basic or any other that you prefer to be used with your api. For metadata details, refer to [https://docs.microsoft.com/en-us/azure/active-directory-b2c/restful-technical-profile#metadata](url)

4. **Insert the claim in the claims schema:**-
Insert the claim under <BuildingBlocks> element. An example of Claim body to be inserted is:- 

```
`<ClaimType Id="**surname**">
  <DisplayName>Surname</DisplayName>
  <DataType>string</DataType>
  <DefaultPartnerClaimTypes>
    <Protocol Name="OAuth2" PartnerClaimType="family_name" />
    <Protocol Name="OpenIdConnect" PartnerClaimType="family_name" />
    <Protocol Name="SAML2" PartnerClaimType="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname" />
  </DefaultPartnerClaimTypes>
</ClaimType>`
```

Here "surname" denotes the claim you are mapping. You will need to modify it to match claim name you are using on the B2c side. 

5. **Add Orchestration step to call the Rest API:**-
 Insert this under UserJourney element in the Extension file. 
Example:-
Locate the `<UserJourney Id="SignUpOrSignIn">` (this order is important, insert it under this in order to use the information provided to the application AFTER the user sign-up or sign-in ) , and add the following orchestration step before the last one.
```
`<OrchestrationStep Order="7" Type="ClaimsExchange">
  <ClaimsExchanges>
    <ClaimsExchange Id="RESTGetProfile" TechnicalProfileReferenceId="REST-GetProfile" />
  </ClaimsExchanges>
</OrchestrationStep>`
```
You might need to refactor the Order field for steps that follow your newly inserted step. 

6. **Inside SignUporSignIn.xml, add the output claim**:- 
The OutputClaims element of the [RESTful technical profile](https://docs.microsoft.com/en-us/azure/active-directory-b2c/restful-technical-profile) contains a list of claims returned by the REST API.
Example: 
```
`<OutputClaims>
  <OutputClaim ClaimTypeReferenceId="displayName" PartnerClaimType="name" />
  <OutputClaim ClaimTypeReferenceId="email" />
  <OutputClaim ClaimTypeReferenceId="loyaltyNumber" />
</OutputClaims>`
```

For further queries, you can also reach out to me through my email in my Git account. 
Most of the steps above are detailed in :- [https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-api-connector-token-enrichment?pivots=b2c-custom-policy#add-the-restful-api-technical-profile](url)

Hope this helps and thanks for your patience!
