### ISSUE TITLE
Add configuration to let the pop-ups not be blocked on Safari iOS

### ISSUE THREAD

**Issue by minggangw** [AzureAD/microsoft-authentication-library-for-js#4996]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Description

Platform: iPhone/iPad
OS: iOS 15.5
Browser: Safari
Description: When using MSAL.js to execute login, the pop-up will be blocked by Safari without any hint, and after disabling the Block Pop-ups from Settings=>Safari, it will show as below
![image](https://user-images.githubusercontent.com/6469275/177920351-d74ed1a0-99ce-439d-8de6-2bff5ee97ab4.png)
Compare with Google and Facebook, their pop-ups don't get blocked, so can MSAL.js have kind of configuration to achieve that?

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
@minggangw I assume you mean `Google` and `Facebook` pages in Safari. This is interesting as we do not control the pop-up blocking behavior of the browser. Let me check with my UX team and reach out.

**Comment by minggangw** [comment]
Yes, the pop-ups of Google & Facebook, which will navigate to the login page, don't get blocked by Safari.

**Comment by sameerag** [comment]
@minggangw  can you please provide me the below info:
- What is the `msal-browser` version in use?
- Did you explicitly allow popups for the websites above or are you testing all the scenarios on default settings of safari?

We expect `msal-browser` to work if the popup method is triggered as a result of user interaction and popups were previously blocked. Please also share the logs (enable msal logging) to further help us narrow the root cause here.

**Comment by minggangw** [comment]
> What is the msal-browser version in use?

We are using @azure/msal-browser v2.22.0 2022-02-08

> Did you explicitly allow popups for the websites above or are you testing all the scenarios on default settings of safari?

The pop-up blocker is enabled as default on Safari iOS and we tested using the default setting (enable the pop-up blocker)

Meanwhile, I did more investigation to identify the root cause and found that

- Calling `msalObj.loginPopup()` only can trigger the popup
- Our case is calling `msalObj.loginPopup()` inside `ssoSilent()`, which fails, e.g.,
```js
   msalObj.ssoSilent(silentRequest).then(responseHandler).catch(err => {
      msalObj.loginPopup(silentRequest).then(responseHandler).catch(error => {
      });
    });
```

**Comment by tnorling** [comment]
@minggangw This makes sense. Popup blockers require that the popup be opened as a direct result of user interaction (clicking a button for example) in order to not be blocked. By wrapping the call in ssoSilent first, the popup is now opened in an async context, rather than from the button click. Is there a reason you need to call ssoSilent on button click?

**Comment by minggangw** [comment]
I see, we call the ssoSilent because we want to sso directly for Edge browser where some Edge-only functions are available to achieve that. I think we can call `loginPopup` on Safari directly in this case, so close this issue and thanks for your help!
