### ISSUE TITLE
<AuthenticatedTemplate> is rendering children when session is expired

### ISSUE THREAD

**Issue by remojansen** [AzureAD/microsoft-authentication-library-for-js#5028]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.27.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.3

### Description

I'm trying to use `<AuthenticatedTemplate>` and `<UnauthenticatedTemplate>`. They work as expected with one exception: When the session is expired. When the session expired, I could not use `acquireTokenSilent` I was getting an error. Now that is solved. However, I have noticed that `<AuthenticatedTemplate>` still renders as if the user session is active.

Is this a bug? If not, how do you recommend fixing this?

### Relevant Code Snippets

```javascript
<AuthenticatedTemplate>
    <button
      type="button"
      onClick={() => {
        (async () => signOut())();
      }}
    >
      Logout
    </button>
  </li>
</AuthenticatedTemplate>
<UnauthenticatedTemplate>
    <button
      type="button"
      onClick={() => {
        (async () => signInOrSignUp())();
      }}
    >
      Login
    </button>
</UnauthenticatedTemplate>
```
```


### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
@remojansen This behavior is expected and as designed. MSAL.js is stateless in that it doesn't have any knowledge of the validity of the user's session, it only has some static information about the user, including tokens. You should never assume that acquireTokenSilent will work, nor should you use the `AuthenticatedTemplate` or `UnauthenticatedTemplate` components as a security boundary, they are merely there to conveniently render content based on whether or not an account is available.

If you would like a more heavy handed approach, you can use the `MsalAuthenticationTemplate` or `useMsalAuthentication` hook which will attempt to acquire an access token (silently, then interactively if needed) on the first render and only render child components if that was successful. However, since this is only done on the first render, you may run into the same problem if the component lives for a long time.

The more general advice is, no matter which approach you take, you should call `acquireTokenSilent` each time you need a token and that call should have fallback logic to `acquireTokenRedirect` or `acquireTokenPopup` if the silent call fails.

**Comment by remojansen** [comment]
Thanks for the answer, I'm doing what you suggested but I wanted an official confirmation :)
