### ISSUE TITLE
broken link for initializing application object

### ISSUE THREAD

**Issue by PeterArriaza** [AzureAD/microsoft-authentication-library-for-js#5251]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/public-apis.md

### Description

The first link for how to initialize the application object is broken.  It seems like there are multiple ways of doing this, so I'd like to make sure that I'm doing the right thing.
I'm using Angular 11 and the v11 docs show one way: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v2-samples/angular11-sample-app/src/app/app.module.ts  whereas the general v2 docs I have linked shows another way.

**Comment by hectormmg** [comment]
@PeterArriaza thanks for raising this issue. I've made a PR with updates to fix the broken angular doc references. As for how to initialize an MSAL Angular instance, I suggest you follow the v2 docs since those are updated more regularly than the dev samples for older versions of Angular. Please let us know if you have any other questions!
