### ISSUE TITLE
SPA + Web API - no custom scopes

### ISSUE THREAD

**Issue by AlexanderOpran** [AzureAD/microsoft-authentication-library-for-js#5381]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Documentation Location

https://learn.microsoft.com/en-us/azure/active-directory-b2c/configure-authentication-sample-spa-app

### Description

Hey,

I recently started a project in which we are using Azure AD B2C and there are a couple of things that I don't fully understand and are not in the documentation.

I believe our scenario and use-case is one of the most common ones for Single Page Applications. We have a SPA (Angular) that uses our APIs. Token signature validation and authorization (based on roles) is handled by the API Management Gateway and the APIs themselves. 

**In this case the only thing the API / backend needs is an access token sent with each request.** 

I am again, new at this, so perhaps I am a bit naive in my approach, but I do have the following questions to which I couldn't necessarily find any answers:
1. I do not want custom scopes / permissions in AD B2C at all, I just want a simple token (the same one) sent to all of my endpoints. In this simple scenario I do not understand what benefits there are in requesting a different token with a different scope for every endpoint that you have. This only adds more complexity and another place where you have to update things when you are doing changes the APIs. What benefit is there when the frontend is constantly asking "Hey, do I have permission to actually call that API endpoint?" and requesting a new token with each request?  I have to add hundreds of permissions and scopes in AD B2C for all the endpoints ("protected") that my application already has. Why would I even want to do that if I just want a simple token?

2. Is there some kind of default scope that I can use without being forced to define ani API permissions and custom scopes? I saw that for the normal AD there is the ./default scope but this seems to not work at all for AD B2C. What I did found instead is the fact that I can use my application client id as the scope and it seems to work again. **This is not documented anywhere.** What does this actually do (using the clientID as the scope) and are there any other elegant ways to achieve this?

Thanks!

**Comment by derisen** [comment]
Hi @AlexanderOpran , regarding your questions:

> 1. I do not want custom scopes / permissions in AD B2C at all, I just want a simple token (the same one) sent to all of my endpoints. In this simple scenario I do not understand what benefits there are in requesting a different token with a different scope for every endpoint that you have. This only adds more complexity and another place where you have to update things when you are doing changes the APIs. What benefit is there when the frontend is constantly asking "Hey, do I have permission to actually call that API endpoint?" and requesting a new token with each request?  I have to add hundreds of permissions and scopes in AD B2C for all the endpoints ("protected") that my application already has. Why would I even want to do that if I just want a simple token?

[Every access token is meant for a certain resource](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md) (API), so there's no single token that would work across all APIs (assuming each API has its own app registration). That being said, within the same API you can just define one scope (e.g. `https://<my-tenant>.onmicrosoft.com/<my-client-id>/access_as_user`) and use that across all endpoints (e.g. `https://<my-api-domain>/api/books`, `https://<my-api-domain>/api/movies`  -that's really about how those API endpoints are configured to validate the incoming access token). Since you are doing role based authorization, this is fine (basically you answer the question "does this user have access to the `/books` endpoint"? by checking the role `Books.Reader` as opposed to checking the scope `Books.Read`)

> 2. Is there some kind of default scope that I can use without being forced to define ani API permissions and custom scopes? I saw that for the normal AD there is the ./default scope but this seems to not work at all for AD B2C. What I did found instead is the fact that I can use my application client id as the scope and it seems to work again. **This is not documented anywhere.** What does this actually do (using the clientID as the scope) and are there any other elegant ways to achieve this?

This is actually documented [here](https://learn.microsoft.com/en-us/azure/active-directory-b2c/access-tokens#openid-connect-scopes) and it would work if your frontend and API is sharing the same app registration (because the audience of the access token would be the same then). However I don't think it's a good way going forward. This approach is a legacy from a time when the scope concept didn't exist. Azure AD (as opposed to B2C) does not accept using the clientId as scope anymore, and there could be changes to B2C in the future that would require you to go back and update this. I would personally try to follow the current paradigm unless I have a very good reason not to.

Hope this helps. Couple of samples that you might find useful:

[Angular SPA calling B2C protected web API](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/3-Authorization-II/2-call-api-b2c)
[Angular SPA calling protected web API using roles](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/5-AccessControl/1-call-api-roles)

**Comment by AlexanderOpran** [comment]
@derisen Than you for the explanation! In this case as I can understand the most elegant way would be to create one API and one scope for my whole backend and then use that in the client application, correct? Although you mention the custom scope approach is the recommended way going forward, I don't think this covers the most common approaches and architectures out there. It doesn't work for simple scenarios, nor does it work for more complex ones when you need a lot of granularities on your permission-based authorization system. Nevertheless, we will work with what we have.

As for the second point, I am not a native English speaker so that is perhaps one of the issues, but I do not find the current AD B2C integration documentation (for Angular or anything else) intuitive at all. I don't think it easily answers what custom scopes are, why they are used and recommended, what benefit do they provide, how do the fit in the overall picture and what are the alternatives?

Anyway, this can be closed if needed but I do think the documentation can be improved a lot. I may try to do a PR in the future when I would have more experience with AD B2C. Thank you again!

**Comment by derisen** [comment]
@AlexanderOpran no worries! The Microsoft identity platform is OAuth 2.0 and OpenID Connect compliant, so it's following the industry standards for authentication and authorization. Scope is a mechanism in OAuth 2.0 to limit an application's access to a user's data, and the reason it exists is exactly to provide granularity (roles perform a similar function, and you can combine scopes and roles for even more granularity). I understand the confusion around OAuth but going into why it should be used  is beyond our scope here (you might find [this article](https://learn.microsoft.com/azure/active-directory/develop/scopes-oidc) useful). As I said you can use the client ID as scope in B2C if your client and API shares the same app registration. I will go ahead and close this, but feel free to raise an issue if you have another quesiton or use our [discussion board](https://github.com/AzureAD/microsoft-authentication-library-for-js/discussions). Thanks!
