### ISSUE TITLE
CAE is broken when token is served from the cache (claims should bypass the token cache)

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-js#5494]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

9.0.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

1.14.5

### Public or Confidential Client?

Confidential

## Context

MSAL handle claims as follows: 

1. User is expected to add claims in json format (MSALs don't need validate this)
2. If claims are added, MSAL **must not serve an access token from the cache**
3. Point 2 above does not apply to client capabilities

## Actual behavior: 

MSAL's client_credential, OBO and refres_token (shared between PCA and CCA) do not respect point 2 above. 

#### Ref designs: 

https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview?path=/ClientCapabilities/overview.md&_a=contents&version=GBdev

https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview?path=/ClaimsParameters/overview.md&version=GBdev&line=180&lineEnd=181&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

### MSAL Configuration

```javascript
with claims
```

### Relevant Code Snippets

```javascript
n/a
```

### Reproduction Steps

see desc

### Expected Behavior

bypass the cache

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

Internal (Microsoft)

**Comment by bgavrilMS** [comment]
CC @sameerag for public client implication.

**Comment by tnorling** [comment]
You may want to chat with @hectormmg. He added the requested claims to our cache lookups in #4296

**Comment by bgavrilMS** [comment]
Ah ok, so MSAL Js went on the route of indexing access tokens by claims hash? @hectormmg - would this apply automatically to `AcquireTokenByCredential` and `AcquireTokenOnBehalfOf`, both of which looks in the cache by themselves?

Also, please confirm that the `claimsRequestHash` part of the cache key. I.e. will 2 AT, one with claims and one without claims co-exist?

**Comment by Robbie-Microsoft** [comment]
ping @hectormmg

**Comment by bgavrilMS** [comment]
@Robbie-Microsoft - sorry, I forgot to update this. MSAL JS uses the claims as part of the AT cache key. This is fine.

**Comment by bgavrilMS** [comment]
@Robbie-Microsoft - we can assume this works, but it should be easy to write a unit test that demonstrates that it works. Something like; 

AcquireTokenForCredenatial() -> goes to ESTS
AcquireTokenForCredentails(claims1) -> goes to ESTS
AcquireTokenForCredentails(claims2) -> goes to ESTS
AcquireTokenForCredentails(claims1) -> from cache
AcquireTokenForCredentails(claims2) -> from cache

**Comment by hectormmg** [comment]
@bgavrilMS  @Robbie-Microsoft Sorry I didn't see this earlier.

Here's the original cached requested claims PR: https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/4296

And here's the Node follow-up: https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/4296

From what I can tell/remember:

A) OBO and Client Credential lookup should not have this logic if they have their own lookup logic (it was added to the cache manager for silent lookup)
B) the requested claims hash is present in the cache key if claims where present in the request that resulted in a cached token.

We make a point of calling them requested claims since there is no guarantee the claims are present in the token (which is the original reason MSALs are supposed to go to the network every time claims are requested).
