### ISSUE TITLE
What version of msal azure I should use to angular 4? Can you send me a doc samples pls!!

### ISSUE THREAD

**Issue by GustavoGatti** [AzureAD/microsoft-authentication-library-for-js#5498]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

0.1.4

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

0.1.4

### Public or Confidential Client?

Public

### Description

I need to integrate msal in a project that is using angular 4, according with doc of azure msal, i should use the version o msal angular v0 that the last version is 0.1.4, but i dont find any doc, someone can send my the doc of samples with this version? Am i wrong of the version i should use? if yes, whats version i can use to integrate?

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
Unfortunately msal-angular v0.x was a pre-release version which we no longer support and do not have documentation for. Our officially supported/documented libraries are msal-angular v1 which supports Angular 6-9 and msal-angular v2 which supports Angular 9-14+

**Comment by GustavoGatti** [comment]
In this case, msal-angular dont have compatibility with angular 4 version? or less that angular 6? I cant apply in this case, right?

**Comment by tnorling** [comment]
That is correct. You will need to upgrade to at least Angular 6 to use MSAL. If you do consider upgrading we actually further recommend that you upgrade to a version of Angular which is [currently supported ](https://angular.io/guide/releases#actively-supported-versions) by Angular itself so that you may use the latest MSAL and take advantage of the higher level of security and support it provides.
