### ISSUE TITLE
calling msal.PublicClientApplication when already authenticated on web server

### ISSUE THREAD

**Issue by cbrandsma-cs** [AzureAD/microsoft-authentication-library-for-js#5558]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Current Setup:
* Asp.net MVC Core 6 web application
* multiple apis written using WebApi.
* all the calls to the WebApi happen via javascript on the browser.
* Authentication is configured on the web server.

Issue: we really want the web server to handle authentication, how to we call the secured endpoints in the WebApi service?

It seems I have to use MSAL and load up 

         const config = { 
             auth: {
                clientId: '[client id guid]', 
             }, 
             cache: { 
                 cacheLocation: "localStorage", 
                 storeAuthStateInCookie: false 
             } 
         }; 
     
         const msalInstance = new msal.PublicClientApplication(config);

that looks like it works. But when I call `msalInstance.acquireTokenSilent(request)` I get this error: 

    no_account_error: No account object provided to acquireTokenSilent and no active account has been set. Please call setActiveAccount or provide an account on the request.

So how do I wire up msal.PublicClientApplication when the login already happened.  Shouldn't it be able to grab something out of the authentication cookie?

### Relevant Code Snippets

```javascript
const config = { 
             auth: {
                clientId: '[client id guid]', 
             }, 
             cache: { 
                 cacheLocation: "localStorage", 
                 storeAuthStateInCookie: false 
             } 
         }; 
     
         const msalInstance = new msal.PublicClientApplication(config);
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by cbrandsma-cs** [comment]
this might be the sample I need: https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/6-AdvancedScenarios/4-sign-in-hybrid/README.md

**Comment by derisen** [comment]
@cbrandsma-cs the error you are getting is because you haven't passed an `account` object as param to `acquireTokenSilent` -please refer to usage [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/accounts.md). If you have signed in via the ASP.NET web app, that doesn't mean msal.js on the frontend knows this. You'll need to fire a login from the frontend as well (though you'll likely not required to enter credentials, via the active session cookie).

For this kind of scenario, you can make use of the [hybrid SPA authorization code](https://github.com/AzureAD/microsoft-identity-web/wiki/Hybrid-SPA) -the sample you've found illustrates this, though I think [this ASP.NET + React sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-5-HybridFlow) would be more close.
