### ISSUE TITLE
Emulate login in debug

### ISSUE THREAD

**Issue by NimbleHive** [AzureAD/microsoft-authentication-library-for-js#557]
Hi,
IS there an easy way to emulate logging in when running in debug - so that we bypass the actual login and can just specify a token.

Is that easy to do within the library, or can you think of a way its best implemented?

I want to keep using MSAL library when debugging so that it adds the token to API requests, so bypassing completely MSAL wouldn't be ideal.

Thanks for any help,

Andrew

**Comment by navyasric** [comment]
@NimbleHive If you obtain an Azure AD id_token for an authenticated user, you can get the preferred_username claim and pass it as a login_hint in MSAL.js. Then you can skip calling login and just call acquireTokenSilent to get the access token. This is described here: https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Sso#sso-to-an-app-without-msaljs-login

**Comment by NimbleHive** [comment]
Thanks  @navyasric ! That looks like what I need - let me try that out and let you know.  Sorry for not seeing that - I did have a look but couldn't find the info.

**Comment by NimbleHive** [comment]
Hi @navyasric just processing this now - not sure if it will work (but that could be my lack of knowledge in this area).  The ID Token only lasts a short period of time - 1 hour or so.

What I want to do is create a Token that expires a long time in the future - say 5 years, and has all the claims for testing in it.  Then have this token passed too all APIs called whilst debugging. 
Effectively I don't want to call Azure B2C at all, but I want to use the MSAL.js framework that  auto adds the token to outbound calls.

**Comment by NimbleHive** [comment]
I wonder if all I need to do is change MsalInterceptor and this line of code:
    var tokenStored = this.auth.getCachedTokenInternal(scopes);
So that it gets the stored token from the config?

Do you see any issues with that, will the app still try and login?  Perhaps I need to change MsalGuard to also ignore trying login if token specified?

**Comment by navyasric** [comment]
@NimbleHive MSAL.js provides you the acquireTokenSilent method to renew tokens. If there is a valid cached token, it will return it. Otherwise it will make a silent call to the Identity provider to renew it. Please note that you will be able to renew tokens as long as you have a valid user session with the identity provider. 
You can take a look at this article about [token lifetimes](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#token-types) and how you can configure the lifetime which I think is a maximum 1 day. Id tokens are meant to authenticate the user and get some user information, please use access tokens to pass to APIs. It is not recommended to have long living access tokens in the browser. 
If your scenario is to have a running test app, you should consider having a secured server side flow using [auth code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code#oauth-20-authorization-flow) where you can have long lived refresh tokens and you can look at the libraries we offer [here](https://docs.microsoft.com/dotnet/api/microsoft.identity.client?view=azure-dotnet-preview).

**Comment by navyasric** [comment]
Closing this issue given the above information. Please reopen if necessary
