### ISSUE TITLE
Changing AAD B2C User Flow

### ISSUE THREAD

**Issue by eluchsinger** [AzureAD/microsoft-authentication-library-for-js#5590]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.2

### Public or Confidential Client?

Public

### Description

Assume, your application is using an Azure AD B2C User Flow `SignIn & SignUp` called `LoginAndRegistrationFlow`, but then you want to migrate to use a new flow `LoginOnlyFlow`.

The way to go currently would be to change the MSAL Settings `authority` to use the new flow. This works, and if deployed like this, the users will start seeing the new flow. 

But the problem starts here. The existing users that are logged in will start having issues, because their token was issued for the old policy.

How should I proceed if I want to migrate from one flow to a different one? I can not add multiple authorities for example.

### Relevant Code Snippets

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: environment.msalConfig.auth.clientId,
      authority: environment.b2cPolicies.authorities.signUpSignIn.authority, // <-- This is the one we want to migrate
      redirectUri: '/',
      postLogoutRedirectUri: '/',
      knownAuthorities: [environment.b2cPolicies.authorityDomain]
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Verbose,
        piiLoggingEnabled: false
      }
    }
  });
}
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by derisen** [comment]
@eluchsinger one thing you can try is to set the new authority/policy in msal configuration and use it by default, but keep the old authority/policy somewhere (e.g. in your config files etc.) If the app detects a signed-in user, check the user's account to see with which policy it was acquired (you can check the issuer, tfp/acr claims in the ID token and etc.). If it was acquired with the old authority/policy, you can override the default authority (since it was set to the new one) in acquireTokenSilent calls by setting it to old the authority in the [request API](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html#silentrequest). When an interaction is required for that user (say, tokens are expired), just continue using the default authority, so the new tokens will be acquired with the new policy. 

But keep in mind tokens issued to a SPA are short-lived (see [token lifetimes](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md)) anyways, so you might find avoiding this complexity and asking user's to sign-in again acceptable.
