### ISSUE TITLE
Webpack 5 compatibility and crypto dependency

### ISSUE THREAD

**Issue by rsudworth** [AzureAD/microsoft-authentication-library-for-js#5598]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.6

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

I'm using msal to manage authentication for embedded PowerBI reports in an MS Dynamics ecommerce solution (https://github.com/microsoft/Msdyn365.Commerce.Online). A recent upgrade to the dynamics code included a requirement for webpack 5, which has led to the build now failing as follows:

` "message": "Module not found: Error: Can't resolve 'crypto' in 'E:\\source\\repos\\xxx-xxx-xxx\\node_modules\\@azure\\msal-node\\dist'\n\nBREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.\nThis is no longer the case. Verify if you need this module and configure a polyfill for it.\n\nIf you want to include a polyfill, you need to:\n\t- add a fallback 'resolve.fallback: { \"crypto\": require.resolve(\"crypto-browserify\") }'\n\t- install 'crypto-browserify'\nIf you don't want to include a polyfill, you can use an empty module like this:\n\tresolve.fallback: { \"crypto\": false }"`

As I understand it, webpack 5 stopped including some common Node libraries liike crypto and the recommended solution is to add a polyfill, as described by the error message. Unfortunately, the webpack build and config for the solution is wrapped in custom build scripts that aren't available to the developer. Is there any other work around available? Or perhaps an update is due soon that moves away from relying on the crypto library?

Thanks.

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@bgavrilMS for visibility

**Comment by bgavrilMS** [comment]
Possible duplicate: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5602

**Comment by DxDen1004** [comment]
I do not understand why this issue is marked as "completed". Completed what? Where is the answer to the author's question (and many more people's question)? Where is the fix? 

Three years later and still, creating a React Solution in Visual Studio 2022 Enterprise edition (and not just running create-react-app from the cli), will present you with a project that won't even start as soon as you install @azure/msal-node because of this "Module not found" error (which appears to me as quite different from the No Matching Export issue). How are we supposed to use msal with node? Is msal-node deprecated? Why it is not working as expected when installed on a freshly created project?

` "message": "Module not found: Error: Can't resolve 'crypto' in 'E:\source\repos\project_folder\node_modules\@azure\msal-node\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
    - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
    - install 'crypto-browserify'

If you don't want to include a polyfill, you can use an empty module like this:
    resolve.fallback: { "crypto": false }"`

If you try to follow the suggestion in the error message and edit the webpack config file to add the fallback, you will get tons and tons more "can't resolve" errors.

Should we just stop using this package?

**Comment by crysiscore** [comment]
im having the same issue @DxDen1004 .  installing @azure/msal-node results in a compile error:
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
- install 'crypto-browserify'

If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "crypto": false }"`

If you try to follow the suggestion in the error message and edit the webpack config file to add the fallback, you will get tons and tons more "can't resolve" errors.

**Comment by SaraRavasio** [comment]
i'm having a similar experience! 

i first get an error for `http` and `https`.

<img width="1490" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/33936661/934ba2e3-3022-4b1d-b181-d18d074487da">


after they're added in the resolve.fallback, i get this new error

<img width="1495" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/33936661/7ecb37b4-95f7-43bf-9cb1-8d50e269c687">

**Comment by nayodahl** [comment]
Hello,
I'm having the same issue.
Adding fallback to webpack config just help with the build to pass, but then the js code breaks elsewhere because the module/class is actually not found.
Webpack 5 up to date, node 18.

Any solution found ?
