### ISSUE TITLE
Need to find a method to authenticate users on the iPhone/iPad

### ISSUE THREAD

**Issue by malvina-kochkina** [AzureAD/microsoft-authentication-library-for-js#5670]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.31.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.10

### Public or Confidential Client?

Public

### Description

Using MSAL in our Office Add-in.
Upgrading to MSAL v2 has led to some login issues.
For mobile app: sso for ios fails, Add-in doesn't work on mobile.
For desktop app: If the silent login fails, the Add-In tries a popup login instead, but instead of login popup user gets "Look for an app in the Microsoft Store". It appears that the consent popup also fails, so it might be that Outlook blocks all popups.
For web app: The popup login works as expected in OWA.

What is the recommended way to authenticate our users in our Office Add-in. We need it to work in Office on the web, Office on Windows, and Office on iPhone/iPad.
To our knowledge, the @Azure-DevOps-Alerts/msal-browser library does not support interactive login in Office Add-Ins. We have tried both the popup and the redirect interaction method. Silent login works as expected.
Using the SSO functionality in the OfficeRuntime works as expected for Office on the web and Office on Windows, but is not supported on Office on iPhone/iPad.
We have yet to find a method to authenticate our users on the iPhone/iPad, is this not supported at all?

### MSAL Configuration

```javascript
{
  auth: {
    authority,
    clientId,
    navigateToLoginRequestUrl: false,
    postLogoutRedirectUri: baseUri,
    redirectUri: baseUri
  },
  system: {
    loadFrameTimeout: 10000,
    loggerOptions: {
      loggerCallback,
      piiLoggingEnabled: false,
      logLevel: LogLevel.Verbose,
      correlationId: '1234'
    },
  },
  cache: {
    cacheLocation: 'localStorage', 
    storeAuthStateInCookie: true,
  },
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment]
@malvina-kochkina Can you please share the MSAL JS logs? The instructions are [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md).

Also is this in iOS browser and if so, which browser? OrIs it a native add-in in iOS which is integrated with MSAL JS?

**Comment by malvina-kochkina** [comment]
This is the logs from Outlook Desktop when the required consent popup is blocked. 

[localhost-1676024094451.log](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/10707041/localhost-1676024094451.log)

We think the crucial part here is: Error - error opening popup empty_window_error: window.open returned null or undefined window object.

When is comes to mobile app: It's the native iOS Outlook app running an Office Add-In with MSAL.

**Comment by sameerag** [comment]
@malvina-kochkina can you confirm any `window.open()` call works at all in native iOS office add-in? That could be the issue here.

**Comment by hectormmg** [comment]
@malvina-kochkina Office Add-ins do not support interactive token acquisition directly. You have to open a popup dialog through the Office API and then invoke loginRedirect inside that dialog. Please take a look at [this sample](https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/auth/Office-Add-in-Microsoft-Graph-React/utilities/office-apis-helpers.ts).

On the iOS/mobile case in general (without Office Add-in context), we discourage the use of the popup interaction since mobile browsers have a very different and often restricted implementation of popups. The same redirect approach described above should work on mobile browsers if Office Add-ins can open a new tab like it's a popup as the login dialog.

**Comment by oleksandr-slys** [comment]
@sameerag `window.open()` works but open a tab in system browser and fail to redirect back to the outlook app. thank you for the suggestion.

@hectormmg we will try it and get back to you. thank you for the suggestion.

**Comment by oleksandr-slys** [comment]
It is still an issue. We will try an approach with `Office.context.ui.displayDialogAsync` and get back with the results.

**Comment by oleksandr-slys** [comment]
Status so far. I was able to check that it is possible to open dialog window via `window.Office.context.ui.displayDialogAsync(dialogLoginUrl, { height: 40, width: 30 }, (result) => { console.log('msg received'); })` function in iPhone. I will try to implement auth redirect flow inside that dialog window and get back with the results.

**Comment by oleksandr-slys** [comment]
Hi!
I was finally able to get access token via `Office.context.ui.displayDialogAsync`, but we have to disable quite a lot of security policies.
Is it possible to use that access token with `@azure/msal-XXX` libraries somehow or I need to have my custom authentication logic?
Because after I got token from `Office.context.ui.displayDialogAsync` and called `const { result, error } = useMsalAuthentication(InteractionType.Silent, authenticationRequest);` I got error again
```
*** useAuthentication [false,false,[],null,{"errorCode":"login_required","errorMessage":"AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com). Trace ID: a3959b2a-ae73-41d0-8d44-81d4e8714a00 Correlation ID: 6943291e-6274-49d7-b715-4e940d3e966a Timestamp: 2024-03-08 08:02:08Z","subError":"","name":"InteractionRequiredAuthError","timestamp":"","traceId":"","correlationId":"6943291e-6274-49d7-b715-4e940d3e966a","claims":""}]
```
What makes me think that I can't rely on `@azure/msal-xxx` libraries when I get token via `Office.context.ui.displayDialogAsync`. Is it true?
