### ISSUE TITLE
acquireTokenSilent No access token found in cache for the given properties.

### ISSUE THREAD

**Issue by Rutakamekiar** [AzureAD/microsoft-authentication-library-for-js#5708]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.1

### Public or Confidential Client?

Public

### Description

acquireTokenSilent always executes because 'No access token found in cache for the given properties', and this is true because I'm only using an id_token. Is it possible for acceptTokenSilent to read the id_token from cache?

### Msal Logs

[Wed, 22 Feb 2023 11:46:20 GMT] : @azure/msal-browser@2.32.1 : Info - Emitting event: msal:acquireTokenStart
authConfig.ts?b8bb:42 [Wed, 22 Feb 2023 11:46:20 GMT] : [beccdd56-680f-40b9-a22e-b4d4b7059401] : @azure/msal-common@9.1.0 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
authConfig.ts?b8bb:42 [Wed, 22 Feb 2023 11:46:20 GMT] : @azure/msal-browser@2.32.1 : Info - Emitting event: msal:acquireTokenFromNetworkStart
authConfig.ts?b8bb:42 [Wed, 22 Feb 2023 11:46:20 GMT] : @azure/msal-browser@2.32.1 : Info - Emitting event: msal:acquireTokenSuccess
authConfig.ts?b8bb:42 [Wed, 22 Feb 2023 11:46:22 GMT] : @azure/msal-browser@2.32.1 : Info - Emitting event: msal:acquireTokenStart
authConfig.ts?b8bb:42 [Wed, 22 Feb 2023 11:46:22 GMT] : [7c4368ee-ff48-490c-93f6-c5a43b5d4c6b] : @azure/msal-common@9.1.0 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
authConfig.ts?b8bb:42 [Wed, 22 Feb 2023 11:46:22 GMT] : @azure/msal-browser@2.32.1 : Info - Emitting event: msal:acquireTokenFromNetworkStart
authConfig.ts?b8bb:42 [Wed, 22 Feb 2023 11:46:22 GMT] : @azure/msal-browser@2.32.1 : Info - Emitting event: msal:acquireTokenSuccess

### MSAL Configuration

```javascript
{
  auth: {
    clientId: 'afe97106-8c7f-4b47-855d-1f78b3458715',
    authority: b2cPolicies.authorities.signUpSignIn.authority,
    knownAuthorities: [b2cPolicies.authorityDomain],
    redirectUri: '/',
    postLogoutRedirectUri: '/',
  },
  cache: {
    cacheLocation: 'localStorage',
  }
}
```

### Relevant Code Snippets

```javascript
const res = await msalInstance
        .acquireTokenSilent({
          scopes: ['openid'],
          account: account,
        })
```

### Reproduction Steps

1. login to the app
2. make a call acquireTokenSilent to get id token
3. call API with the id token 
4. repeat step 2 

### Expected Behavior

acceptTokenSilent method will find the id_token in the cache and not execute the /token endpoint

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@Rutakamekiar While `acquireTokenSilent` is likely reading id token from the cache, it is currently set up to retrieve access tokens when they are not found in the cache, which is why you are seeing this behavior. Please see [this doc](https://learn.microsoft.com/en-us/azure/active-directory/develop/id-tokens) for more information about id tokens and why we do not suggest using them on their own.

However, our library is considering improvements in the future where you may be able to retrieve only id tokens, which may fit your use case better. While this work has not been prioritized, please keep an eye on [this issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4206#issuecomment-1439068407), where the work will be tracked.

**Comment by Rutakamekiar** [comment]
Thank you for your answer, if anyone is interested in how to quickly get access token in response, you can add clientId to the scope
