### ISSUE TITLE
Add ability to call acquireTokenSilent() from within iframe

### ISSUE THREAD

**Issue by benjaminmillhouse** [AzureAD/microsoft-authentication-library-for-js#593]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] IE version XX
- [x] Edge version XX
- [x] Safari version XX

## Library version

<pre><code>
Library version: 0.2.4

</code></pre>

## Current behavior

acquireTokenSilent() will not work when called from inside of an iframe.

## Expected behavior

It would be nice to be able to call this while inside of an iframe (if embedding the application).  After digging through the code it looks like there is a decorator (resolveTokenOnlyIfOutOfIframe) that blocks the acquireTokenSilent() method from being called if it happens inside of an iframe.  Instead of calling through, it returns a never-ending promise. I'm assuming that this is being done to prevent loops within the hidden iframe, but it would be nice if there were some kind of method to call this legitimately from an app running inside of an iframe. (for example, MS Teams application)

## Minimal reproduction of the problem with instructions

Load application from inside of an iframe.  Observe the acquireTokenSilent() request never resolves.

Might be a duplicate of #504

**Comment by josephd9** [comment]
I have the same need for this as well. When a user loads my app in an iframe I am forced to open a new tab for them to log in and then assign the token to a cookie so the calling page can get the token. This has led to poor user experience when the token is refreshed because a new tab will open up suddenly and close just so I can retrieve that fresh token. Being able to acquire the token while inside an iframe would resolve this.

**Comment by sameerag** [comment]
Tracking this with #504 as a new feature.
