### ISSUE TITLE
Access token for resource URL

### ISSUE THREAD

**Issue by captainR0bbo** [AzureAD/microsoft-authentication-library-for-js#6147]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.37.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

na

### Public or Confidential Client?

Public

### Description

I am currently able to get a working access token using a client secret directly from the "https://login.microsoftonline.com/{tenantId}/oauth2/token" endpoint by specifying the URL of my resource in the body of the request:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/56075984/1b04f659-f60a-48e5-ae8d-bfdfdc3f50be)

When I inspect the access token, the aud is the resource URL that I requested. And I am able to use that access token successfully. 

I would like to avoid creating a separate web API that my client application (SPA) needs to call to access this resource (because we obviously don't want the secret on the client), but I cannot get MSAL working for user authentication. From what I understand, resources are scopes in MSAL, but it does not seem I can put the URL of my resource in as a scope. When I do I get this error:

`"AADSTS650057: Invalid resource. 
The client has requested access to a resource which is not listed in the requested permissions in the client's application registration."`

And I don't see anywhere that I can add the resource URL in Azure AD.

In the included code sample, I have "/.default" added to my scope because if I don't, I get a different error message:
`"AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://resourceURL.com openid profile offline_access is not valid. The scope format is invalid. Scope must be in a valid URI form <https://example/scope> or a valid Guid <guid/scope>."`

I don't know where the other scope values in there came from.

### MSAL Configuration

```javascript
{
  auth: {
    authority: "https://login.microsoftonline.com/{tenantId}",
    clientId: clientId,
    redirectUri: "https://localhost:3000/login.html",
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: true,
  },
};
```

### Relevant Code Snippets

```javascript
const loginRequest: RedirectRequest = {
  scopes: ["https://resourceURL.com/.default"],
};
const msalInstance = new PublicClientApplication(msalConfig);

  msalInstance
    .handleRedirectPromise()
    .then((response) => {
      // If response is non-null, it means page is returning from AAD with a successful response
      if (response) {
        Office.context.ui.messageParent(
          JSON.stringify({ status: "success", result: response.accessToken, scopes: response.code })
        );
      } else {
        // Otherwise, invoke login
        msalInstance.loginRedirect(loginRequest);
      }
    })
    .catch((error) => {
      const errorData: string = `errorMessage: ${error.errorCode}
                                   message: ${error.errorMessage}
                                   errorCode: ${error.stack}`;
      Office.context.ui.messageParent(JSON.stringify({ status: "failure", result: errorData }));
    });
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @captainR0bbo , thanks for raising this issue. You need to register scopes in the Azure portal by going to "Expose an API" in your client app registration and using the "Add a scope" button.

From your token endpoint it seems like you're using the Client Credential flow with the OAuth2.0 v1 endpoint. MSAL Browser uses the Authorization Code flow with the OAuth2.0 v2 endpoints, which is a bit different and why you are being asked for scopes rather than resource URLs.

You can read more about scopes [here](https://learn.microsoft.com/EN-US/azure/active-directory/develop/scopes-oidc).

**Comment by captainR0bbo** [comment]
Thank you for the response. So if all I have is the resource URL (Dynamics 365 Finance and Operations environment url), then I cannot use the Authorization code flow as there is no registered app to add a scope for? thanks!

**Comment by hectormmg** [comment]
Since you have a client ID you must have a client app registration that it was issued for. Dynamics has its own scopes that should be available to your client app registration in the Azure Portal. You can go to the "API permissions" blade in the portal and click "Add permission". You can then search for the specific Dynamics scope you need in the search tool and add it if it isn't already added to your app registration. The resource URL should map to one of the available Dynamics scopes.

Sorry for the misunderstanding, the "Expose an API" section is for custom scopes and custom APIs.

**Comment by captainR0bbo** [comment]
Yes, I have registered an app so I have a client Id. And you are right there are scopes out there for Dynamics, but I guess I am confusing myself and thinking there needed to be a specific resource/scope for my instance of Dynamics. I guess not.
The problem, which is why I running  in this circle here, is that when I use the Dynamics scopes in Azure AD and request them, it tells me they don't exist.

Permissions added to my app registration:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/56075984/92e94ea6-069e-4e64-943f-ba86a9b74eee)

But when I request the scope in my auth config, I get this message back:
`"AADSTS650053: The application 'D365 Outlook addin' asked for scope 'AX.FullAccess' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'."`

Resource '00000003-0000-0000-c000-000000000000' is the Graph API, right?

Any idea what I could be doing wrong here?

**Comment by hectormmg** [comment]
@captainR0bbo can I see the full request? If you could collect a fiddler network trace and send it to the e-mail address in my profile it may help me identify the problem better.

**Comment by captainR0bbo** [comment]
Thank you! I just sent the trace.

**Comment by captainR0bbo** [comment]
Hector, I figured it out. I found and tried this [github exampe ](https://github.com/microsoft/PowerApps-Samples/tree/master/dataverse/webapi/C%23/QuickStart/QuickStartMSAL) and it worked as expected. So I ran the trace and found that the authority needs to be "https://login.microsoftonline.com/organizations" instead of "https://login.microsoftonline.com/{tenantId}. And then I was able to pass my "https//environmentUrl/.default" as my scope and it worked.

Did I miss this being documented somewhere? Obviously not specific to this library, but in general I don't think I ever saw an example of using "/organizations", only "/common" or "/{tenantId}"

Thanks for taking the time to assist!

**Comment by hectormmg** [comment]
@captainR0bbo I realize this doc is actually under MSAL.NET but the authorities explanation is the same since we're dealing with AAD.

https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-client-application-configuration#authority

The authority type/value has to match what's configured in your azure portal.
