### ISSUE TITLE
@azure/msal-node-extensions breaks the app if hosted on Azure App Service

### ISSUE THREAD

**Issue by arvilmena** [AzureAD/microsoft-authentication-library-for-js#6160]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.15.0

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Wrapper Library Version

1.0.0-alpha.30

### Public or Confidential Client?

Confidential

### Description

Hello!

I am using your `@azure/msal-node-extensions` for my NestJS app. Unfortunately, it is breaking up when I am deploying it to an [Azure App Service](https://azure.microsoft.com/en-au/products/app-service) with the error:

```Error: libsecret-1.so.0: cannot open shared object file: No such file or directory```

Which I learned is one of the OS dependency of this packaged. Unfortunately, I cannot run apt-get install nor build these libraries inside Azure App Service.

I am wondering if there's a workaround on this without needing to rely on that library.

My app only has to use the `FilePersistence` and `PersistenceCachePlugin` from `@azure/msal-node-extensions` so I wonder if we can decouple these 2 functions?

I would appreciate any suggestion or help here.

Thank you!

### Error Message

```
2023-06-26T18:58:25.915758249Z node:internal/modules/cjs/loader:1338
2023-06-26T18:58:25.915790251Z   return process.dlopen(module, path.toNamespacedPath(filename));
2023-06-26T18:58:25.915798251Z                  ^
2023-06-26T18:58:25.915803951Z
2023-06-26T18:58:25.915809452Z Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
2023-06-26T18:58:25.915814852Z     at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
2023-06-26T18:58:25.915820252Z     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-06-26T18:58:25.915825653Z     at Module._load (node:internal/modules/cjs/loader:958:12)
2023-06-26T18:58:25.915830753Z     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-06-26T18:58:25.915835953Z     at require (node:internal/modules/cjs/helpers:110:18)
2023-06-26T18:58:25.915841053Z     at Object.<anonymous> (/node_modules/keytar/lib/keytar.js:1:14)
2023-06-26T18:58:25.915846654Z     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-06-26T18:58:25.915851754Z     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-06-26T18:58:25.915857054Z     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-06-26T18:58:25.915872255Z     at Module._load (node:internal/modules/cjs/loader:958:12) {
2023-06-26T18:58:25.915877655Z   code: 'ERR_DLOPEN_FAILED'
2023-06-26T18:58:25.915882756Z }
2023-06-26T18:58:25.917253831Z
2023-06-26T18:58:25.917275232Z Node.js v18.16.0
```

### Msal Logs

nothing, it breaks on startup

### MSAL Configuration

```javascript
const cachePath = path.join(__dirname, './../../mso365-token-cache.json');

const filePersistence = await FilePersistence.create(
  cachePath,
  loggerOptions,
);
const clientConfig: Configuration = {
  auth: {
    clientId: this.mso365Config.azureAdClientId,
    authority: `https://login.microsoftonline.com/${this.mso365Config.azureAdTenantId}`,
    clientSecret: this.mso365Config.azureAdClientSecret,
  },
  system: {
    loggerOptions,
  },
  cache: {
    cachePlugin: new PersistenceCachePlugin(filePersistence),
  },
};
this.client = new ConfidentialClientApplication(clientConfig);
```

### Relevant Code Snippets

```javascript
import {
  ConfidentialClientApplication,
  Configuration,
  LogLevel,
} from '@azure/msal-node';
import {
  FilePersistence,
  PersistenceCachePlugin,
} from '@azure/msal-node-extensions';
import { Injectable } from '@nestjs/common';
import { Microsoft365ConfigService } from './microsoft365-config.service';
import path = require('path');

export interface IMicrosoft365ClientProviderService {
  getClient(): Promise<ConfidentialClientApplication>;
}

@Injectable()
export class Microsoft365ClientProviderService
  implements IMicrosoft365ClientProviderService
{
  client: ConfidentialClientApplication;
  constructor(private readonly mso365Config: Microsoft365ConfigService) {}

  async getClient(): Promise<ConfidentialClientApplication> {
    if (!this.client) {
      const loggerOptions = {
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        loggerCallback(loglevel, message) {
          console.log(message);
        },
        piiLoggingEnabled: true,
        logLevel: LogLevel.Verbose,
      };
      const cachePath = path.join(__dirname, './../../mso365-token-cache.json');

      const filePersistence = await FilePersistence.create(
        cachePath,
        loggerOptions,
      );
      const clientConfig: Configuration = {
        auth: {
          clientId: this.mso365Config.azureAdClientId,
          authority: `https://login.microsoftonline.com/${this.mso365Config.azureAdTenantId}`,
          clientSecret: this.mso365Config.azureAdClientSecret,
        },
        system: {
          loggerOptions,
        },
        cache: {
          cachePlugin: new PersistenceCachePlugin(filePersistence),
        },
        // Uncomment or comment the code below to enable or disable the MSAL logger respectively
      };
      this.client = new ConfidentialClientApplication(clientConfig);
    }
    return this.client;
  }
}
```

### Reproduction Steps

1. Import {
  FilePersistence,
  PersistenceCachePlugin,
} from '@azure/msal-node-extensions';

2. Use them

3. Deploy to Azure App Service

### Expected Behavior

Should work smoothly

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
Tagging @bgavrilMS @Robbie-Microsoft for msal-node-extensions help.

**Comment by bgavrilMS** [comment]
Hi @jo-arroyo - @Robbie-Microsoft and myself only own the confidential client part of MSAL Node, whereas the msal-node-extension is purely public client. Web sites / web api would never store token caches in encrypted files / KeyChain / KeyRing (which is what this extension lib does). Instead they would store them in memory, in session or in Redis / SQL, for which we have samples but no extra library.

**Comment by arvilmena** [comment]
@bgavrilMS I am using the confidential client on my code (see my OP code):

```
this.client = new ConfidentialClientApplication(clientConfig);
```

The `FilePersistence ` library is used in the server-side, not in the public web.

**Comment by tnorling** [comment]
@arvilmena Is this being thrown on import or when invoking one or both of the functions?

I'll let @bgavrilMS further comment on whether using file persistence with confidential clients is even supported.

**Comment by bgavrilMS** [comment]
No, we do not recommend using msal-node-extensions with confidential client and won't be investigating this type of issue. Server side apps do not use files for storage - they use caches like Redis or Sql Server etc. `msal-node-extensions` is for public clienta apps.

@arvilmena - what is your scenario here? Are you using AcquireTokenByCredential, i.e. acquiring a token on based on a certificate or a secret for a service principal (not for a user) ?  Is your app a single or a multi-tenant app, i.e. do you need tokens for many tenants or a for single one? Looking at your code I think a single one? `${this.mso365Config.azureAdTenantId}`

If so, I recommend the following: 

1. For single tenant apps, consider using Managed Identity instead of certificate / secret based auth. Managed Identity gives you a token without having to prove you have a secret. It relies on the fact that your app is deployed to Azure. 

You'll need to use Azure SDK for that, MSAL JS doesn't implement Managed Identity yet. https://github.com/Azure/azure-sdk-for-js/blob/main/documentation/using-azure-identity.md

2. If you can't use Azure SDK or if you have a multi-tenant app, use MSAL Js. Start with in-memory caching only and monitor the cache hit ratio (there's a `fromCache` property on `AuthenticationResult` you can use). A cache entry is for 1 tenant for 1 resource / scope and is about 2KB. If you need tokens for 1 resource (e.g. Graph) for 1M tenants you'll need around 2KB * 10^6 = 2GB of RAM. 

If you really are very high scale and require persistent caching, checkout this sample that shows how to use Redis:

https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/client-credentials-distributed-cache
