### ISSUE TITLE
Is it normal for getUser() to return user information even when the jwt id token has expired?

### ISSUE THREAD

**Issue by hiraldesai** [AzureAD/microsoft-authentication-library-for-js#62]
I'm seeing a weird behavior in my app where id token for my `Msal.UserAgentApplication` has expired but it still returns the user information when `getUser()` is called. Am I missing something here?

If this is intended behavior then what's the best way to check if user is authenticated? Something like `app.isUserAuthenticated()`?

**Comment by FredrikOhrn** [comment]
I have the same experience.

**Comment by hiraldesai** [comment]
I have done the following as a temporary workaround if anyone is interested. It's a snippet from my auth.service typescript file for one of my angular2 projects. Honestly - I don't know why `MSAL` doesn't expose a method for `getIdToken()` and `isAuthenticated()` as a part of library itself. I'd like to know the reason behind that.

```
import '../../../node_modules/msal/out/msal';
/// <reference path="../../../node_modules/msal/out/msal.d.ts" />
import { Injectable } from '@angular/core';
import { ResourceService } from 'app/services/resource.service';
import { environment } from 'environments/environment';
import { Observable } from 'rxjs/Rx';
import { JwtHelper } from 'angular2-jwt/angular2-jwt';

@Injectable()
export class AuthService {
    private app: Msal.UserAgentApplication;
    private clientId: string = environment.aadSettings.clientId;
    private graphScopes: string[] = environment.aadSettings.graphScopes;
    private jwtHelper: JwtHelper = new JwtHelper();

    /// Removed code for brevity
    constructor() {
        this.app = new Msal.UserAgentApplication(this.clientId, null,
            (errorDes, token, error, tokenType) => {
                if (error || errorDes) {
                    console.error('Error receiving token.', error, errorDes);
                }
            });
    }

    public getIdToken() {
        const storage = new Msal.Storage(this.app.cacheLocation);
        const idToken = storage.getItem(Msal.Constants.idTokenKey);
        return idToken;
    }

    public isAuthenticated() {
        const idToken = this.getIdToken();
        const loggedIn = idToken !== null && !this.jwtHelper.isTokenExpired(idToken);
        if (!loggedIn) {
            console.error('id token has expired, redirecting to login...');
            return false;
        }
        const user = this.app.getUser();
        return user !== null;
    }


    /// Removed code for brevity
}
```

**Comment by rohitnarula7176** [comment]
@hiraldesai An ID token is meant for proving to a client that the user has authenticated and who they are as a result. When a client receives an ID token, it just converts it to a ClaimsIdentity and persist it. The ID token has to be unexpired at this point of use (which it should be, since it has just been issued). But after this it is not used again, so it does not matter if it expires while the user still has an active session. The client has the authentication information it needs, and in turn can choose its own policy for how long the session lasts before the user has to log in again. The workaround you suggested will link the getUser information with the expiration of the idtoken but it does not tell you whether your session has expired or not.

**Comment by hiraldesai** [comment]
Thank you for your explanation @rohitnarula7176 . I thought that would be the case, just wanted to check it anyway.
