### ISSUE TITLE
Login always prompts for user interaction in this version of angular wrapper

### ISSUE THREAD

**Issue by pnaika** [AzureAD/microsoft-authentication-library-for-js#629]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.1.2

## Current behavior

We recently updated our auth to use @azure/msal-angular from adal-angular but we have an issue to bypass login prompt and auto login which used to happen in adal.

We did some research and we think msal-angular uses an older version of msal-js library.
Is there a plan or Can we update the msal version to newer 0.2.4 version? https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/package.json#L27

https://github.com/AzureAD/microsoft-authentication-library-for-js/releases , this release has the fix for the issue I guess.

## Expected behavior

do not show the login pop up

## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by Highspeed7** [comment]
Are you referring to SSO not working? Because if so, I've noticed this as well. Another problem I'm having (Probably for another discussion is that after loginPopup, and acquireTokenSilent, the login popup shows up again, but not always.

**Comment by amigup** [comment]
I'm experiencing the same issue due to which in SSO flow, the user is always asked to select an available account (due to hardcoded prompt=select_account in older version msal.js lib). Since, msal.js 0.2.4 already incorporated the required behavior, so can this @azure/msal-angular package use the latest msal version i.e. 0.2.4.

**Comment by sameerag** [comment]
@amigup We are pushing a fix in #785 which also lets the user pick an angular version from a local repo instead of npm. Can you upgrade to msal 2.4 in your environment, build it and see if angular wrapper works as is?

Ideally, we would want everyone on msal 1.0.x (which is breaking changes from msal 0.2.4) but angular wrapper work is not yet updated with the same. Meanwhile, all angular wrapper issues are tracked with #786. 

I want to check if the above option is feasible to you as an intermittent solution. For angular updates, please check for announcements in our [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap)

**Comment by sameerag** [comment]
Linking this to #786 for traction and closing this.
