### ISSUE TITLE
Using MSAL based on TypeScript 3.4.3 

### ISSUE THREAD

**Issue by lzhang-advent** [AzureAD/microsoft-authentication-library-for-js#6426]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.38.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0

### Public or Confidential Client?

Public

### Description

Hi
I'm using TypeScript 3.4.3 which is a lower version. But MSAL.js is based on a new version of TypeScript. I upgrade MSAL.js to 2.38.0. In my testing it works well. Do you know if there is any potential issue?

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
@lzhang-advent We recommend to update the dependencies as feasible to what MSAL JS supports. However if you have specific reasons to stick to a specific version, I would expect you to handle any issues that come with it. We cannot anticipate any issues that would happen as it depends on an external library and not completely in our control.

Please let us know if you have a specific issue with MSAL JS due to this (recommend raising a new one) and we will try to help as much as we can.
