### ISSUE TITLE
MsalInterceptor

### ISSUE THREAD

**Issue by hm-00** [AzureAD/microsoft-authentication-library-for-js#6427]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.2

### Public or Confidential Client?

Public

### Description

MSAL interceptor doesnt function correctly when used in conjuction with an app route data resolver AND the browser is subsequently refreshed 

### Error Message

No errors shows anywhere

### MSAL Configuration

```javascript
{
      clientId: environment.msalConfig.auth.clientId,
      authority: environment.msalConfig.auth.authority,
      knownAuthorities: environment.msalConfig.auth.knownAuthorities,
      redirectUri: '/',
      postLogoutRedirectUri: '/auth/logout',
    },
    cache: {
      cacheLocation: BrowserCacheLocation.SessionStorage,
    },
    system: {
      allowNativeBroker: false, // Disables WAM Broker
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Error,
        piiLoggingEnabled: false,
      },
    },
  });
```

### Relevant Code Snippets

```javascript
{
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true,
    },


together with

{
    path: 'app',
    component: AdminLayoutComponent,
    resolve: {
      initialData: InitialDataResolver,
    },


with the data resolver going to  


  resolve(): Observable<any> {
    return this._appConfigService.getAppConfig();
  }

with app config a service
```

### Reproduction Steps

Add data resolver to app routes

### Expected Behavior

browser refresh should function as expected

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by tnorling** [comment]
Can you please expand on "MSAL interceptor doesnt function correctly "? What is the behavior you see versus the behavior you expect to see?

**Comment by Almamu** [comment]
@tnorling I'm under a similar situation. I have an app that depending on user permissions loads a different amount of remote modules (we're using NX in this case). The way we achieve this is by calling a remote endpoint that lists all the loadable modules under APP_INITIALIZER, and then pass that to the angular router so it knows what urls it has available.

That request requires of authentication, and if it fails, the route should be handled as if it didn't exist. To add the token I'm using the MsalInterceptor (in my case through the configuration provider), but when the http request should happen, the request never completes and a message of 
```
 [] : @azure/msal-angular@3.0.4 : Error - Interceptor - acquireTokenSilent rejected with error. Invoking interaction to resolve.
```
appears in the console.

The issue seems to be gone if the url that the app loads by default has the MsalGuard as canActivate (the expected behavior of following interactionType happens) and the navigation is initiated before the call (which shows an error page momentarily until the request completes, which is not ideal, ideally the navigation should be blocked and not handled until the request is completed), but shouldn't the interceptor also invoke the interaction? Even better would be a way of making the request fail so my loading code can handle that situation gracefully... I'm guessing that writing a custom interceptor is the only option?

This is for a confidential client, but I should be able to provide a small, minimal example of the issue on a normal angular project if required.
