### ISSUE TITLE
Is locking necessary ?

### ISSUE THREAD

**Issue by NicoAdrian** [AzureAD/microsoft-authentication-library-for-js#6566]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.18.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

I have an express application that needs for each request to fetch an access token using the method 
`acquireTokenByClientCredential`.

I know the MSAL client uses an internal cache to prevent getting a new token if the previous I got isn't experied yet.
Consider the following scenario:
1) My token is expired, so the MSAL client fetches a new one.
2) During the fetch (which is non blocking I/O operation), my Express server receives another request, hence needs an access token
3) Since the token was expired because I didn't receive the response during step 1) yet, I fetch another token.

Repeat until step 1) is done so new token in cache.

So, my questions are:

1) Does the MSAL client implements some kind of locking mechanism to prevent 2 or more requests to be made at the same time
2) If not, should I do it to prevent multiple fetch at the same time ?

### Identity Provider

None

### Source

External (Customer)

**Comment by bgavrilMS** [comment]
As far as I know, no, there is no locking mechanism in NodeJS? Happy to be educated on this.

Indeed we do not lock.

- Request 1 would make an HTTP request for a token, which I presume will put the request thread to sleep. 
- Request 2 would then also make an HTTP request. Etc.
- Request 1 would put the token in the cache. 
- Request 2 would overrrite the token in the cache. 
- All other requests would hit the cache.

In my experience with MSAL.NET, which also doesn't lock the cache, this is fine - the chances of HTTP contention are not as high. When we implement managed identity, we may have to revisit this, because Managed Identity endpoints are heavily throttled. 

Are you writing a single-tenanted application @NicoAdrian  or a multi-tenanted one?

**Comment by NicoAdrian** [comment]
Ok so I do need to lock. There is no locking mechanism in nodeJS but something like this should work for anyone interested.

```js
class AsyncLock {
  constructor() {
    this.locked = false;
    this.queue = [];
  }

  acquire() {
    return new Promise((r) => {
      if (!this.locked) {
        this.locked = true;
        r();
      } else {
        this.queue.push(r);
      }
    });
  }

  release() {
    if (this.queue.length > 0) {
      this.queue.shift()();
    } else {
      this.locked = false;
    }
  }
}

// and then use it like this:

const myLock = new AsyncLock();

await myLock.acquire();
const acessToken = await getMyAccessToken();
myLock.release();
```

Thank for your answer.
