### ISSUE TITLE
A way to enforce MFA when using oauth2/v2.0/authorize or change authorize endpoint

### ISSUE THREAD

**Issue by stefanolsenn** [AzureAD/microsoft-authentication-library-for-js#6746]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.2

### Public or Confidential Client?

Public

### Description

I'm trying to enforce MFA during the /authorize request using `amr_values=ngcmfa`, but I get the following error, since it's not supported in the v2.0 of Microsoft Identity Platform.

> AADSTS901002: The 'amr_values' request parameter is not supported.

Is there a way to enforce my user to have performed MFA, or is there a way to use the v1.0 endpoints in this library?

### MSAL Configuration

```javascript
auth: {
    clientId: '<client-id>',
    authority: 'https://login.microsoftonline.com/common',
    redirectUri: `${location.origin}`,
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: false
  },
  system: {
    allowNativeBroker: false
  }
```

### Identity Provider

None

### Source

External (Customer)

**Comment by tnorling** [comment]
MFA enforcement should be done with [Conditional Access policies](https://learn.microsoft.com/en-us/entra/identity/conditional-access/overview) rather than request parameters. We are unfortunately not experts on this so I would recommend [opening a support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) if you need assistance.
