### ISSUE TITLE
MSAL Authentication not working in Angular 17.0.5

### ISSUE THREAD

**Issue by Sauravchandra755** [AzureAD/microsoft-authentication-library-for-js#6764]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

^3.6.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

NA

### Public or Confidential Client?

Confidential

### Description

I am implementing MSAL authentication in Angular 17.0.5 and unable to authenticate using AD credentials and its giving 401 Un-authorized error. Same code was working in Angular 11.2.12.

These are the dependencies of the application

Node: 18.16.0
Package Manager: npm 9.5.1
"@angular/animations": "^17.0.0",
"@angular/cdk": "^17.0.2",
"@angular/common": "^17.0.0",
"@angular/compiler": "^17.0.0",
"@angular/core": "^17.0.0",
"@angular/forms": "^17.0.0",
"@angular/material": "^17.0.2",
"@angular/platform-browser": "^17.0.0",
"@angular/platform-browser-dynamic": "^17.0.0",
"@angular/router": "^17.0.0",
"@azure/msal-browser": "^3.0.0-alpha.2",
"minimatch": "^9.0.3",
"rxjs": "~7.8.0",
"tslib": "^2.3.0",
"zone.js": "~0.14.2"

### MSAL Configuration

```javascript
auth: {
      clientId: environment.clientID,
      redirectUri: environment.redirectUri,
      authority: environment.authority,
      navigateToLoginRequestUrl: true
    },
    cache: {
      cacheLocation: "localStorage",
    },
    system: {
      allowNativeBroker: false,
  }
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
MSAL is not a service and thus does not return HTTP status codes. Can you please elaborate on _what_ is returning a 401? Is it your application or login.microsoftonline.com?

**Comment by Viltersten** [comment]
The user reports the issue unclearly. The problem is that Angular v17 introduces a new strategy for service provision as they're no longer registered in a common module file but in per-service way using a decorator in the service. It means that each service now governs autonomously where it's avaiable.

The most common provision by `forRoot()` is required in majority of cases and, as the guide for MSAL v3 explains, an alteration of the module file is required. The provlem springs from the fact that Angular v17 hasn't such a module file since the app is built as standalone. (At least that's the recommended and most spread way which also is the default when scaffolding a new Angular app using the CLI tools).

I suppose, we should see MSAL v4 that embraces the new paradigm. However, the impression I've got is that the team responsible for the development of MSAL library isn't even aware of the problem, let alone has a roadmap for addressing it.
