### ISSUE TITLE
Integration with file picker and file sync leads to user going through consent form three times?

### ISSUE THREAD

**Issue by Diggsey** [AzureAD/microsoft-authentication-library-for-js#6779]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

I am attempting to implement a very simple integration with OneDrive/SharePoint, where a user can select a folder from their OneDrive/SharePoint, and then the contents of that folder are periodically synced into the application without further interaction.

I cannot figure out how to do this without a ridiculous user experience where they have to login three separate times:

1) I initiate a login flow to get an access token to post to the OneDrive/SharePoint file picker.
2) The file picker requests an access token for the specific SharePoint site (eg. `https://<tenant>-my.sharepoint.com`) which triggers a second login popup.
3) The user picks a folder and I trigger a third login flow to obtain offline access to the folder.

Furthermore, step (2) needs to use the "Spa" client type, whereas step (3) needs to use the "Web Application" client type, so I need to configure two different client types for my application. And worse yet, I can't set the same redirect URL for both client types, so I then need to set up two different redirect URLs?

Is there a way to cut this down to two or even one login flow? Is there a way I can use only the "Web Application" flow instead of both "Web Application" and "Spa"? Is there a way I can make this agnostic to whether I'm dealing with a "consumer/OneDrive" or "tenant/SharePoint" instance?

### MSAL Configuration

```javascript
N/A
```

### Relevant Code Snippets

```javascript
N/A
```

### Reproduction Steps

N/A

### Expected Behavior

I expect to be able to use the Web Application login flow to get a token with all the required permisssions, and then use that token for all further operations without the user having to login multiple times.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer, None (Server)

### Source

External (Customer)

**Comment by hectormmg** [comment]
@Diggsey can you provide sample code of your MSAL usage? Following our documented usage pattern recommendations, you most likely should be able to acquire these tokens for the same user without re-authenticating every time. How are you using `acquireTokenSilent`?

**Comment by Diggsey** [comment]
Just following the example here for the first part:
https://learn.microsoft.com/en-us/onedrive/developer/controls/file-pickers/?view=odsp-graph-online

> Currently the control relies on SharePoint tokens and not Graph, so you will need to ensure your resource is correct and you cannot reuse tokens for Graph calls.

For the second part I couldn't figure out how to use MSAL with the "Web Application" client type, so I'm using a generic OAuth implementation which exchanges the code for a refresh token server-side.

It would be helpful if you could give an overview of how you would expect the authentication flow to work (at a protocol level) for an application like this where I need to exchange the code server-side in order to obtain offline access to the file, but I also need the user to be able to use the file picker in the browser.

For other integrations it is simple: I do the server-side `code => [refresh & access token]` exchange, and then only expose the access token to the client for selecting the files. Meanwhile the server retains the refresh token and uses it to obtain access tokens in the future during file sync. With microsoft this seems impossible.

**Comment by hectormmg** [comment]
For the first part:

Please check our msal-browser docs and update your getToken logic to match our suggested usage pattern. While the sample you shared does indeed use MSAL, it was made for a very specific scenario and doesn't make full use of MSAL Browser's recommended usage patterns.

For the second part:

MSAL Browser is optimized and only officially supports SPAs. This is because MSAL browser runs on public clients and cannot make use of confidential client auth flows. Why do you need to use MSAL with a "Web Application" client type? Why can't you just use auth code on the client side?

MSAL Browser also acquires and caches refresh tokens that are used to refresh expired access tokens and acquire new tokens without interaction. MSAL takes care of the refreshing for you so you don't have to worry about refresh tokens.

As an added comment, you should not be exposing access tokens obtained server-side to your public client (front-end) application.

**Comment by Diggsey** [comment]
> Please check our msal-browser docs and update your getToken logic to match our suggested usage pattern. While the sample you shared does indeed use MSAL, it was made for a very specific scenario and doesn't make full use of MSAL Browser's recommended usage patterns.

I'm assuming you're referring to the specific method calls (eg. using acquireTokenPopup instead of loginPopup)? How exactly does this help? It will still require multiple access grants, since there are different scopes being requested?

> MSAL Browser also acquires and caches refresh tokens that are used to refresh expired access tokens and acquire new tokens without interaction. MSAL takes care of the refreshing for you so you don't have to worry about refresh tokens.

The refresh token is used for offline access - when there is no client/browser present in order to sync the files on a regular schedule (eg. daily). There's no way MSAL can manage the refresh token in this case.

> As an added comment, you should not be exposing access tokens obtained server-side to your public client (front-end) application.

What are the security implications of exposing an access token to the resource owner? ie. What capabilities does an access token obtained server-side have beyond an access token generated client side with the same scopes?

**Comment by Diggsey** [comment]
FWIW I updated to use `acquireTokenPopup` as suggested and it still requires multiple logins.

**Comment by Diggsey** [comment]
> As an added comment, you should not be exposing access tokens obtained server-side to your public client (front-end) application.

It appears to be fairly common to send the access token to the client, even when it was obtained via the server-side process, eg.
https://stackoverflow.blog/2022/04/14/the-authorization-code-grant-in-excruciating-detail/

> Send the token down to the client to be stored securely. If on a native app, use the iOS keychain or Android secure storage. If in a browser, then store the token in an in-memory variable or as a secure, HTTP only cookie.

And there isn't really an alternative as far as I can tell.

**Comment by tnorling** [comment]
Access tokens should only be handled by the Identity Provider, the application that requested them and the resource they are intended for. Passing them back and forth between frontend and backend is not recommended despite what others have decided to do.

If your app architecture includes both a confidential backend and a SPA frontend you should pick which will make the API calls (both is also a valid option).

> The refresh token is used for offline access - when there is no client/browser present in order to sync the files on a regular schedule (eg. daily). There's no way MSAL can manage the refresh token in this case. 

That is one use case for refresh tokens but not the only one. More generally refresh tokens are used to acquire fresh id and access tokens via POST request, offline or not. SPA refresh tokens are valid for 24 hours after which a new auth code must be obtained, MSAL manages all of this under the hood.

Refresh tokens can be redeemed for an access token representing any scopes the user has previously consented to. It sounds like your issue is with a new user scenario in which the user has not yet consented to all the permissions needed for your application. If that's true you can stack the consent screens into the first "interactive" sign in prompt (acquireTokenPopup/acquireTokenRedirect) by using the `extraScopesToConsent` request parameter. What that would look like for a fully client-side app is like so:

```javascript
// Popup will ask user to consent to all 3 scopes before closing
const result1 = await acquireTokenPopup({ scopes: ["scope-for-resource1"], extraScopesToConsent: ["scope-for-resource2", "scope-for-resource3"]});

const result2 = await acquireTokenSilent({scopes: ["scope-for-resource2"], account: result1.account});
const result3 = await acquireTokenSilent({scopes: ["scope-for-resource3"], account: result1.account});
```

Since you're also using a confidential backend your token requests executed on the backend will use the "Web" redirect type and token requests executed on the front end will use the "SPA" redirect type. If both the backend and frontend share an appId you can use the "Hybrid SPA flow" to show a single interactive prompt on the backend to acquire your backend tokens then redeem the "spa code" on your frontend to acquire your frontend tokens. Implementations will vary depending on what language you're using on your backend. We have a sample [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/HybridSample) for Node based backends.

**Comment by Diggsey** [comment]
@tnorling Thanks, the hybrid flow (specifically the `enableSpaAuthorizationCode` option) seems to be what I was missing.

> Passing them back and forth between frontend and backend is not recommended despite what others have decided to do.

Such recommendations are worthless unless an alternative exists (which you have now provided, thanks!) and/or the justification for the recommendation is explained (I would still like to understand what the security implications of the original approach are).

Having worked with several other OAuth implementations I've not encountered any others which offer something like the `enableSpaAuthorizationCode` option, and without opening this issue I would never have discovered it from the microsoft documentation.

**Comment by tnorling** [comment]
> I would still like to understand what the security implications of the original approach are

Tokens acquired on your backend may be different from tokens acquired on your frontend (roles, lifetime, conditional access, and more). SPA tokens are typically a bit more restrictive as they are stored client-side and thus "public". Also depending on how you communicate the token from the backend to your frontend you may increase your attack surface. As a general rule acquire the tokens from the entity which will use them.
