### ISSUE TITLE
How does knownAuthorities work

### ISSUE THREAD

**Issue by programm-ingovals** [AzureAD/microsoft-authentication-library-for-js#6799]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.6.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.8

### Public or Confidential Client?

Public

### Description

The config has the property `knownAuthorities` but I'm not sure how that is supposed to work.

Lets say I have two tenants, A and B, and a client app registered at tenant A.

Do I gain something by adding them both to knownAuthorities.

What is the implacation of a single tenant app vs multi tenant app in regards to `knownAuthorities` 

I'm asking is because I want a multi-tenant app, but not open to all accounts, but open to limited set of tenants.

### MSAL Configuration

```javascript
{
  auth: {
    clientId: "e46f3b1d-b0f4-47bb-a593-b9c9ff8c2cac",
    authority:
      "https://login.microsoftonline.com/2e211aa5-00d0-47b0-9100-94c6888248a4",
    redirectUri: "/",
    knownAuthorities: [
      "login.microsoftonline.com/2e211aa5-00d0-47b0-9100-94c6888248a4",
      "login.microsoftonline.com/7cf9cd89-a17a-4480-b4c3-ae1335c49ee4",
    ],
  },
};
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
knownAuthorities is specifically for B2C and other non-Microsoft IdentityProviders. You should not be using it for `login.microsoftonline.com` or other AAD aliases as discovery is done for those authorities by default.

Restricting access to your app to select tenants should be done via Conditional Access rather than client-side validation as client-side checks are very easy to workaround.
