### ISSUE TITLE
acquireTokenSilent always bypasses the cache when no scope is passed

### ISSUE THREAD

**Issue by jnizet** [AzureAD/microsoft-authentication-library-for-js#6887]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.7.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.11

### Public or Confidential Client?

Public

### Description

When trying to acquire a token silently (with acquireTokenSilent), passing an empty aray of scopes, the token is obtained successfully, but the cache is bypassed: a request to the token endpoint is sent every time before returning the token.
Adding a useless scope ('User.Read') fixes the issue.

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
    auth: {
      clientId: 'ad42dfc7-d1df-450e-aab5-2f1c34c4741d',
      authority: 'https://login.microsoftonline.com/6981636a-c14f-494e-8722-38ba9f8aabab/',
      redirectUri: '/',
      postLogoutRedirectUri: '/',
      navigateToLoginRequestUrl: false,

    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage
    },
    system: {
      allowNativeBroker: false, // Disables WAM Broker
      loggerOptions: {
        loggerCallback,
        piiLoggingEnabled: false
      }
    }
  }
```

### Relevant Code Snippets

```javascript
import { HttpInterceptorFn } from '@angular/common/http';
import { inject } from '@angular/core';
import { MsalService } from '@azure/msal-angular';
import { switchMap } from 'rxjs';

export const authInterceptor: HttpInterceptorFn = (req, next) => {
  const msalService = inject(MsalService);
  let activeAccount = msalService.instance.getActiveAccount();
  if (activeAccount) {
    return msalService.acquireTokenSilent({
      account: activeAccount,
      scopes: []
    }).pipe(
      switchMap(authenticationResult =>
        next(req.clone({ setHeaders: { Authorization: `Bearer ${authenticationResult.accessToken}` }}))
      )
    );
  } else {
    return next(req);
  }
};
```

### Reproduction Steps

Use the above HTTP interceptor and, after being logged in, send requests every N seconds. Each request causes a POST request to https://login.microsoftonline.com/6981636a-c14f-494e-8722-38ba9f8aabab/oauth2/v2.0/token to be sent before the actual request.

### Expected Behavior

acquireTokenSilent should return the token from the cache.

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by konstantin-msft** [comment]
Hi @jnizet,

This is expected behavior. If you enable [MSAL trace logging](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md) you will see the following error message in the logs: `Scopes cannot be passed as null, undefined or empty array because they are required to obtain an access token`. This makes MSAL.js bypass cache lookup and make a network call to acquire a new token. Please refer to the [error message source](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/ae92c9a9fefcdc98b3bff206d66c9bc4db1db76c/lib/msal-common/src/request/ScopeSet.ts#L79) and the [corresponding unit test](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/71d9e45ad28410a0e2f9e5d02aef05338a5331f1/lib/msal-common/test/client/SilentFlowClient.spec.ts#L489). Also, please keep in mind that MSAL.js adds `openid`, `profile` and `offline_access` scopes to every network request by default. Please refer [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/a34066e55fdcb8633c175e4afc11a3fbc2e1abdd/lib/msal-browser/docs/resources-and-scopes.md#default-scopes) for more details.

**Comment by jnizet** [comment]
Hi @konstantin-msft 

Thanks for responding.

I'd argue that  

1. the error message is wrong since, as you said, if we pass no additional scope, a network request is done and *successfully* acquires an access token. It's thus perfectly possible to get one without passing additional scopes. It's just that MSAL won't let you get it from the cache.
2. if the intention is really for MSAL to forbid getting a token without passing additional scopes even though the server allows it, then it should fail immediately and throw rather than swallow the error and make a network request every time.

**Comment by konstantin-msft** [comment]
I tend to agree. That's not the best user experience. Let me create an item for tracking. Appending default scopes for the cache lookup looks like a good solution to me.
Meanwhile, please use a workaround by passing one of the default scopes.
