### ISSUE TITLE
Support multiple clientId dynamically with MSAL V3

### ISSUE THREAD

**Issue by edwardDev89** [AzureAD/microsoft-authentication-library-for-js#7048]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Description

Hi MSAL team,

We are currently upgrading from V2 to V3 by following the upgrade guidelines outlined here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/v2-migration.md

In our current project structure, we need to support different client IDs. We assume that users will need to re-login (reinitialize MSAL config) every time they select a different client ID. However, after upgrading to V3, we are encountering an issue where we can't get the msal:loginSuccess event by subscribing to msalBroadcast after reinitialization and calling loginRedirect as below:

```
 this.msalBroadcastService.msalSubject$.subscribe((result: EventMessage) => {
    console.log(result) // not able to get msal:loginSuccess event, only handleRedirectStart / End or other event...
  })

  // this function call from user select dropdown list clientId value
  async setApplicationAndRedirect(clientId: string) {
    await this.initializeMsalService(clientId)
    this.msalInstance.loginRedirect()
  }

  initializeMsalService(clientId: string): void {
    var msalConfiguration = this.configService.getSettings("msal")
    msalConfiguration.auth["clientId"] = clientId // to replace new clientId from user input selected clientId
    this.msalInstance = new PublicClientApplication(msalConfiguration)

    // Await initialization
    await this.msalInstance.initialize()
   }
```

May I know is there any possible that MSAL V3 support multiple client Id? Are we missing something in the upgrade process or in our implementation? Any guidance on resolving this issue would be greatly appreciated.

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
We do not offer explicit support for dynamic clientIds. It should be possible but this is not a scenario we have any samples or documentation for. You may need to fork msal-angular and make custom changes or skip msal-angular altogether and simply use msal-browser directly. Keep in mind that doing either limits the support we'll be able to offer you. The best way forward would be to find a way to converge into a single clientId. If you can help us understand why you need multiple we may be able to suggest some alternative approaches.

**Comment by edwardDev89** [comment]
In our project we have huge user and AD group under one app registration, so we split it to different app registration in order to be more organize and easy to manage. 
Since the client Id is based on app registration Id, we somehow need to find a way to dynamically set/inject the new selected client Id into msal config once user selected from angular UI.

In V2 we injected the new selected client Id into the config and initialize it, then using loginredirect user to login again. But once upgraded to V3 it no longer works. We follow the v2-v3 upgrade guide by adding the await and async for the initialize but no luck as the msalBroadcast can't get loginSuccess event.

Any advice or alternative approaches is highly appreciated! Thank you 🙏

**Comment by tnorling** [comment]
I'm not sure I understand the requirement for multiple clientIds. App registrations and AD groups are largely separate things, I don't understand the relationship here. Can you please expand on this aspect?

**Comment by edwardDev89** [comment]
As our project design requirement, we registered different user and AD groups and assigned them into different app registration, so when user choose different clientId from angular UI, we need redirectlogin user to check whether he/she is assigned to the app registration. 

In this case, we assume that msal configuration need to be reinitialize dynamically once there's different clientId has been selected. I hope it clarifies.

**Comment by tnorling** [comment]
Why do different users need to use a different app registrations? This does not make sense to me. The app is the app, this doesn't have anything to do with users or AD groups. 

The answer is that this isn't a scenario we have ever considered and I'm doubtful this is even needed. Best practice is to use a single app registration for each app and I would highly suggest decommissioning your extra app registrations and converge down to a single one. If there are specific blockers to doing so I would very much like to understand what they are so we can suggest a better approach.

**Comment by bryan-ch** [comment]
Hi @edwardDev89 

At the end Did you find a solution to your problem ? I'm facing a similar issue, basically I have 2 client Ids 2 tenant, scope, etc... basically two organizations in the same angular app, lets say for login A and login B however I don't know how to change them dynamically, I have 2 buttons one for login A and the other for login B  and both redirect to its corresponding Microsoft login, I have tried different ways but I face different problems. 

for example if I initialize MsalModule with the config of login A and then try to click on login B, the button redirect to the microsoft login with the credentials of client A. then only way I managed to successfully have the two logins was creating a module for them, one for login A credentials and the other for Login B. It was working good however after a success login,  if I refresh or create a new browser tab the msal instance get lost, returning undefined or null, not sure if its because msal is designed to handle only 1 client id and it fail reading the authentication from the local storage. I don't know what to do, I don't know if it is possible or not

I hope you can understand my problem, but as you can see is similar to yours,
