### ISSUE TITLE
Wrong decode with UTF-8 Characteres

### ISSUE THREAD

**Issue by dluque92** [AzureAD/microsoft-authentication-library-for-js#730]
Using this to decode a token:

Utils.base64DecodeStringUrlSafe = function (base64IdToken) {
        // html5 should support atob function for decoding
        base64IdToken = base64IdToken.replace(/-/g, "+").replace(/_/g, "/");
        if (window.atob) {
            return decodeURIComponent(encodeURIComponent(window.atob(base64IdToken))); // jshint ignore:line
        }
        else {
            return decodeURIComponent(encodeURIComponent(this.decode(base64IdToken)));
        }
    };

Using **window.atob** the UTF-8 characteres are not supported.

**Comment by sameerag** [comment]
@dluque92 Can you please elaborate what your issue is? We purposely moved away from window.atob as we had developers reporting encoding/decoding issues. There is also a stack overflow that elaborates the same issue: [atob issue with decode](https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings)

Also can you please follow the template: 


## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: X.Y.Z



## Current behavior



## Expected behavior



## Minimal reproduction of the problem with instructions



</code></pre>

Before you report an issue? It will be helpful for us to follow up better.

**Comment by dluque92** [comment]
After update to 1.0.1
I was using 0.2.3 
Thanks!
