### ISSUE TITLE
`prompt` ignored with a NAA token request

### ISSUE THREAD

**Issue by adriencohen** [AzureAD/microsoft-authentication-library-for-js#7356]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.24.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

`prompt` param given to `acquireTokenSilent` when using `createNestablePublicClientApplication` client is ignored.

This can be an issue in Outlook add-in. I have 2 logged in accounts but the token acquired is not related to the current user of the mailbox. In this case I tried to force `prompt` to `select_account` to get a correct token but it's ignored.

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
    auth: {
      clientId: appId,
      authority: 'https://login.microsoftonline.com/common',
    },
  }
```

### Relevant Code Snippets

```javascript
const mfClient = await createNestablePublicClientApplication({
    auth: {
      clientId: appId,
      authority: 'https://login.microsoftonline.com/common',
      redirectUri: '/',
      postLogoutRedirectUri: '/',
    },
  });

  const tokenRequest = {
    scopes: [`myappuri/access_as_user`],
    prompt: 'select_account',
  };

  // Acquire token silent failure. Send an interactive request via popup.
  try {
    console.log('Trying to acquire token interactively...');
    const userAccount = await mfClient.acquireTokenPopup(tokenRequest);
    console.log('Acquired token interactively.');

    return userAccount.accessToken;
  } catch (popupError) {
    // Acquire token interactive failure.
    console.log(`Unable to acquire token interactively: `, popupError);
    throw popupError;
  }
```

### Reproduction Steps

1. Execute `acquireTokenPopup` with a prompt which should force user interaction will not enforce it

### Expected Behavior

`prompt` should be taken into consideration

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Other

### Source

External (Customer)

**Comment by sameerag** [comment]
@adriencohen Which platform are you running the NAA app on?

**Comment by adriencohen** [comment]
Most of my tests about this was on Outlook Web

**Comment by sameerag** [comment]
@adriencohen NAA apps ideally should not have UX control. Since the brokering is done at the host, and since the host prefers to fetch the tokens as less disruptive as possible (since any interaction disrupts all applications and not just yours), it is expected that the interaction is never controlled by the NAA app. This is by design.

I will check with the outlook team in case they have a different opinion and reach out as needed.

**Comment by salaman** [comment]
NAA doesn't let you select an account--you'll be using whatever account the host is currently providing, but if you're not getting the mailbox for the currently selected mail message that you would otherwise expect in an addin in Outlook Web, that's unexpected.

Do you use ssoSilent? It's possible NAA is not actually working for whatever reason, and MSAL is falling back to standard web logic for ssoSilent and picking an account. MSAL logging should tell you what flows are being used: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md, or looking at network inspector to see if you're getting an account or token through iframe-based auth instead of through NAA. (If web-based ssoSilent is used as a fallback, then you should pass a `loginHint` as part of your token request which I believe you can get through OfficeJS with `Office.auth.getAuthContext()`).

If you manage to confirm which flow is being used, please let me know here and we can troubleshoot a bit more. A preliminary first step is to ensure MSAL is being initialised _after_ OfficeJS: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/enable-nested-app-authentication-in-your-add-in#initialize-the-public-client-application, and you can also sanity check if `window.nestedAppAuthBridge` is present in your addin at the time of calling `createNestablePublicClientApplication`.

**Comment by adriencohen** [comment]
I was not able to reproduce, I'll reopen with more information and more logs if I'm able to do it again at somepoint
