### ISSUE TITLE
getLoginInProgress() return false when redirected back to the redirect_uri

### ISSUE THREAD

**Issue by bryanchen-d** [AzureAD/microsoft-authentication-library-for-js#740]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 74
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

Library version: 1.0.1

I am migrating from version 0.2.4.

## Current behavior

After user signed in, and redirected back to the redirect_uri with the id_token, calling `getLoginInProgress` returns false

## Expected behavior

It should be same as the `loginInProgress()` method from version 0.2.4, in which it returns true.

I did some investigation, it return false since it failed to detect the 'msal.urlhash' from the cache storage, and actually that has been removed in the `processCallBack` function which is called before calling `getLoginInProgress()`

**Comment by sameerag** [comment]
@pkanher617 Can you check this?

**Comment by pkanher617** [comment]
@bryanchen-d Thanks for reporting this issue and looking into it. I will take a look and resolve this ASAP.

**Comment by pkanher617** [comment]
@bryanchen-d this is working as expected. The loginInProgress method will not return true once the id_token has been returned to the application. This behavior has not changed since 0.2.4. 

If you check line 322 of UserAgentApplication.ts in msal 0.2.4 you will see that we remove the hash in processCallback as well. 

There is an acquireTokenInProgress method as well if you need a state variable for acquireToken calls.

Closing for now, please re-open if you have further questions.
