### ISSUE TITLE
Get Access Token Issue -loginRedreict

### ISSUE THREAD

**Issue by arunprasathv** [AzureAD/microsoft-authentication-library-for-js#754]
@dhanyahk 

Hi, How do i get the access token to call graph API?   I'm trying something like this but doesn't return the token.  I'm doing it in Angular 7. 

this.broadcastService.subscribe("msal:acquireTokenSuccess", (payload) => {
      // do something here

      console.log('token success'  + JSON.stringify(payload));
 });

public getToken(): Promise<string> {
    return this.msalService.acquireTokenSilent(this.scopes)
      .then(token => {
        return token.accessToken;
      }).catch(error => {
        return this.msalService.acquireTokenPopup(this.scopes)
          .then(token => {
            return Promise.resolve(token.accessToken);
          }).catch(innererror => {
            return Promise.resolve('');
          });
      });
  }

**Comment by DarylThayil** [comment]
@pkanher617  do you have direction to add on this?

**Comment by arunprasathv** [comment]
@DarylThayil @pkanher617 
Is it possible to get the accesstoken using this library ? I think we it should work in order to make a call to graph API.

**Comment by sameerag** [comment]
@anuprasathv yes, you can get an accessToken with this library. If you are using loginRedirect(), you need to register a callback for your calls. We have the details on how our library is structured  [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-basics) and [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL.js-1.0.0-api-release). 

Especially this:

For authentication methods with redirect flows (loginRedirect and acquireTokenRedirect), you will need to explicitly register a callback through the handleRedirectCallback() method. This is needed since redirect flows do not return promises as the popup methods do.

We also have our [QuickStart](https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2) which has a sample that demonstrates both popup/silent and redirect flows. 

Please check these out and reach out if you are still facing issues.

**Comment by arunprasathv** [comment]
@sameerag could you please point me to angular examples , im using  @azure/msal-angular": "^0.1.2" library.

**Comment by sameerag** [comment]
@arunprasathv  we do not have Angular working for Core libraries yet, please check our roadmap for more updates: [Angular Roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap).

**Comment by DarylThayil** [comment]
@sameerag  msal angular was working for redirect though in that version, correct?

**Comment by sameerag** [comment]
Yes! It is. Unless they are using msal-core latest with their Angular App it should be functional.

**Comment by arunprasathv** [comment]
I will use logingPopup until login redirect works.

**Comment by DarylThayil** [comment]
closing this issue as it will be addressed with angular 1.0.0
