### ISSUE TITLE
Unable to get  AccessToken after using loginRedirect Method

### ISSUE THREAD

**Issue by Ankita22** [AzureAD/microsoft-authentication-library-for-js#755]
Hi,
I am trying to use MSAL.js with Angular 7 for login. In which i am using loginRedirect method instead of loginPopup method but i am not able to get the access token. I tried using sample code provided by MS for loginPopup method which returns callback, it is returning Accesstoken successfully but unable to get it with loginRedirect method.

I am pasting the code sample which i am using for loginRedirect method  : 
 

  initB2C() {
    this.authority =
      'https://login.microsoftonline.com/tfp/' +
      this.tenantConfig.tenant +
      '/' +
      this.tenantConfig.signUpSignInPolicy ;
       this.clientApplication = new Msal.UserAgentApplication(
      this.tenantConfig.clientID,
      this.authority,
      function(errorDesc: any, token: any, error: any, tokenType: any) {
      
      }
    );
  } 

 public login() {
        this.clientApplication.loginRedirect(this.tenantConfig.b2cScopes);
         getAccessToken();
}

  getAccessToken() {
           this.clientApplication.acquireTokenSilent(this.tenantConfig.b2cScopes, this.authority)
            .then(function(acctoken: any) {
              console.log('ACCESS TOKEN : ', acctoken);
            })
            .catch(accerror => {
            });
  }

**Comment by arunprasathv** [comment]
I do have similar issue with loginRedirect() - I tried to set response_type still not getting it.

extraQueryParameters: 'response_type=id_token token'

**Comment by sameerag** [comment]
@Ankita22 I have added some information on how to use our library in #754, please check the same. Having said that we also have an Angular Wrapper for our core planned in the next few months as @DarylThayil suggested in a different ticket #750.

@arunprasathv The developer cannot set 'response_type=id_token token' as it is determined by the MSAL JS library based on your cache status and session status. I think your issue could be because of the callback not registered, I have added the docs in your ticket.

**Comment by sameerag** [comment]
Linking this to #754 and closing this ticket.
