### ISSUE TITLE
this.msalService.acquireTokenSilent returns idtoken instead of accessToken

### ISSUE THREAD

**Issue by arunprasathv** [AzureAD/microsoft-authentication-library-for-js#760]
@DarylThayil @sameerag 

Hi,

Getting id token instead of the access token from acquireTokenSilent, I'm using loginPopup method.

Yesterday it was working fine, was getting access token. anything changed ?

What am I missing more here? It should be consistent I guess. 

 Thanks
Arun

**Comment by DarylThayil** [comment]
I believe if you don't pass in scopes to consent but pass in client id instead, you will get the id token instead .

Can you share your msal lib and version?

**Comment by arunprasathv** [comment]
It works now, not sure what has caused it to stop working. I did pass scopes.

**Comment by sameerag** [comment]
Closing this as it seems to work now. If you have clear steps of repro, please reopen this. As @DarylThayil  mentioned, if you pass client_id instead of scopes we get an id_token for an acquireTokenSilent call. It is also possible to get both id_token and token in a single call if there is no session found (expired or otherwise).
