### ISSUE TITLE
Dynamic configuration

### ISSUE THREAD

**Issue by hrschoch** [AzureAD/microsoft-authentication-library-for-js#764]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The only option to set a configuration is when defining the MsalModule.forRoot(...).
If the configuration is loaded dynamically (e.g. from an API), it is not possible to set it at a later stage.

## Expected behavior
Add an option to set the configuration dynamically, similar to adal-angular4 where the adal service provides an init function:
`adalService.init(adalConfig);`
#

**Comment by DarylThayil** [comment]
I am assuming that this is in regards to msal-angular? 

Currently core can only be configured on instantiation, however requests can take overriding params like authority.

We will begin angular work soon, to bring it to parity with 1.0.0 msal-core and will keep this in mind as a feature request.

Closing for now since this is not an issue , but an improvement

@negoe  to track for feature requests
