### ISSUE TITLE
Username 

### ISSUE THREAD

**Issue by sberube** [AzureAD/microsoft-authentication-library-for-js#770]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version 75.0
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version
Library version: 0.1.2

___I know that a fix has already been reported (https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/596) but a new Angular version of the package has not been released since then.___

## Current behavior
___Using Angular 8.0___

When calling MsalService.getUser(). User.name property is having an issue with accent characters like é. Like the issue described here 

https://stackoverflow.com/questions/48170828/msal-issue-with-spanish-characters-getting-name-from-social-provider

## Expected behavior
Accents (and that kind of characters) should be correctly displayed.

## Potential fix
When using jwt.io the idToken returned by Azure B2C correctly display the user name with the accents.

So, I found that the JWT IdToken is not correctly deserialized (Utils.js file). I solved this issue by using this code to correctly convert the accent characters

https://stackoverflow.com/questions/38552003/how-to-decode-jwt-token-in-javascript

Thanks!

**Comment by sameerag** [comment]
@sberube Thanks for reporting this issue. This issue is indeed fixed with #596 and it is integrated with msal core. 

We have Angular work in planning right now, as mentioned in our [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap). This and all other issues w.r.t angular compatibility with msal 1.0.x will be addressed as a part of that effort.

I am closing this right now as this is linked to a major effort that we are actively working on. We are welcome for mode feedback if you have specific issues addressed in angular and can reach us here.
