### ISSUE TITLE
loginRedirect goes in loop , it works fine after deleting cookies 

### ISSUE THREAD

**Issue by arunprasathv** [AzureAD/microsoft-authentication-library-for-js#771]
@DarylThayil @jasonnutter @sameerag 
Using Angular Wrapper, after sometime when accessing the application, loginRedirect goes into loop then I have to delete cookies to make it work. What's the trick to make it work. it works fine for the first time.   Appreciate your help.

**Comment by sameerag** [comment]
@arunprasathv Can you please share the sample code you are using for loginRedirect?

**Comment by arunprasathv** [comment]
Code :
public scopes: string[] = ['User.Read', 'openid', 'profile', 'email', 'Directory.Read.All'];
this.msalService.loginRedirect(this.scopes);

In AppModule,

 MsalModule.forRoot({
      clientID:  clientid
      authority: 'https://login.microsoftonline.com/tenant-id/',
      validateAuthority: true,
      cacheLocation : 'localStorage',
      navigateToLoginRequestUrl: true,
      popUp: true,
      isAngular: true,
      level: LogLevel.Verbose,
      consentScopes: ['openid profile email User.Read Directory.Read.All'],
      extraQueryParameters: 'response_type=id_token',
      piiLoggingEnabled: true
    }
  ),

**Comment by arunprasathv** [comment]
@sameerag  any update on this?

**Comment by sameerag** [comment]
@arunprasathv I would need the sample code that handles the callback.

A Couple things that stood out to me in the configuration:
- why is *popUp: true* set when this is loginRedirect() call?
- extraQueryParameters: 'response_type=id_token' - This is not supposed to be a user set parameter, 'response_type' is always dynamically determined by the msal js application depending on the session status.

For loginRedirect() since we need a callback, I was wondering if the code pattern at that point may be incomplete causing loops. We have seen some issues in this regard in the past with older MSALs.

**Comment by arunprasathv** [comment]
@sameerag 

I don't see a callback for loginRedirect(), the return type is void not a promise like loginPopup. 

If i don't pass extraQueryParameters: 'response_type=id_token' , it doesn't work , says the user is not authorized and takes reponse_type=token. it doesn't take id_toke unless I pass it. 

is popUp: true set to true since I was using loginpopup before, I forgot to remove that. This is not the cause of the problem. 

Why is it working if I delete a cookie ? 

I'm using angular wrapper. 

All the code that involved in SSO:

loginRedirect then call getUser passing accesstoken to call graph api. 

 async signIn(): Promise<void> {
        console.log('Sign In');
        this.msalService.loginRedirect(this.scopes);
        this.getUser().then((user) => {this.user = user; } );
}

private  async getUser(): Promise<User> {
    const user = new User();
    // if (!this.authenticated) { return null; }
    if ( this.msalService.getUser() != null ) {

        const graphClient = Client.init({
      // Initialize the Graph client with an auth
      // provider that requests the token from the
      // auth service
      authProvider: async(done) => {
        const token = await this.getAccessToken()
          .catch((reason) => {
            done(reason, null);
            console.log ('access token error' + token );
          });

        if (token) {
          done(null, token);
          console.log('ACCESS token   ' + token);
        } else {
          done('Could not get an access token', null);
          console.log('Could not get an access token');
        }
      }
    });

    // Get the user from Graph (GET /me) - https://graph.microsoft.com/v1.0/me/  - Pass Bearer Access Token in the header
    const graphUser = await graphClient.api('/me').get();
}


  async getAccessToken(): Promise<string> {
    const result = await this.msalService.acquireTokenSilent(this.scopes)
      .catch((reason) => {
        //this.msalService.loginPopup(this.scopes);
        console.log('error token   ');
        this.alertsService.error('Get token failed  ' +  JSON.stringify(reason, null, 2), false);
      });
      console.log("access token  " + result);

    return result;
  }

**Comment by hadaromash** [comment]
Same for me in my React client. I'm using version 1.0.1

**Comment by arunprasathv** [comment]
@sameerag Could you please provide an update on this?

**Comment by sameerag** [comment]
@arunprasathv For redirect calls (both loginRedirect and acquireTokenRedirect) it is mandatory to handle the token in the callback: handleRedirectCallback(authCallback); The usage is mentioned in the [ReadMe](https://github.com/AzureAD/microsoft-authentication-library-for-js).

I do not see that in the above sample code.

Also since you mentioned you are using Angular Wrapper,  Can you please give us which version of msal js is under the hood? The call back signature is different in older versions and I can give you the correct syntax based on the same.

**Comment by arunprasathv** [comment]
The example your provided is for msal.js, I'm looking for the angular wrapper and i see that broadcast service methods are callback as below, and i did have this call back.. let me take another look. will update you once i have the fix.  

this.broadcastService.subscribe("msal:loginFailure", (payload) => {
// do something here
});

this.broadcastService.subscribe("msal:loginSuccess", (payload) => {
// do something here
});

**MSAL.JS version**

"@azure/msal-angular": {
      "version": "0.1.2",
      "resolved": "https://registry.npmjs.org/@azure/msal-angular/-/msal-angular-0.1.2.tgz",
      "integrity": "sha512-J8vfgx0cKQg6g709YVa2aKZYx1yaFrlemVUqhEFRPS6jAk5SiVi5GK0nqbKkL0wdLiNEMOkolOJpBG0yjERG5g==",
      "requires": {
        "msal": "0.2.1",
        "tslib": "1.7.1"
      },

**Comment by sameerag** [comment]
@arunprasathv, Long term solution to your problem would be to move to the latest msal js 1.0.x - we have internal customers who have seen this issue in their implementations (Mostly React) but did not in the latest version of msal. This is because we simplified some of our redirect code in the API release.

But since moving to the latest msal js is not a viable option for folks using the angular wrapper (we have plans to get this out soon and tracking this with #786, and keeping our [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap) updated with the announcements), I have couple of suggestions that may help resolve this sooner for you.

1) #785 solves an issue with angular wrapper but also allows a user to pick up a msal version locally. This would mean you can move up to msal 0.2.4 which is compatible with the wrapper you are working with. You seem to be still on msal 0.2.1 which is a little older version that may not have all the improvements in the newer code version.

2) The first party developer I talked to who faced this issue mentioned to me is that setting the options: loadFrameTimeout to a suitable value/ introducing a sleep basically between the instantiation of msal and a token response helped their loop issue to go away. I am trying to gather the exact details regarding the sleep - will post as I get them. You can try that approach.

Hope this helps with the progress.

**Comment by arunprasathv** [comment]
@sameerag Appreciate your Help!.  

Option 1.

I just did npm install , how can i pick the msal version 0.2.4. ? 

Option 2
Sure, will wait for your update.

**Comment by arunprasathv** [comment]
@sameerag Could you please provide an update on this ? Need help with Option 1 to upgrade MSAL version to 0.2.4.

**Comment by sameerag** [comment]
@arunprasathv Unfortunately for Option 1, we had to rollback the fix as it is breaking AOT builds for angular. We may need to wait for a while until we figure out a comprehensive fix for the same.

Option 2, what I heard from the dev who had a workaround before moving to latest MSAL is this: "We had a sleep in the constructor pre GA; there are  flags that you can adjust to set the sleep time under the covers, we are using the 500ms default that is in the library"; Their general guidance is that latest MSAL 1.0.x works right out of the box.

**Comment by rayterrill** [comment]
I actually ran into the same issue - I had to change my logic to only call msalInstance.loginRedirect if we don't find the user via getAccount - otherwise it loops trying to log the user in because of the redirect (this was not clear to me from the documentation):
```
if (msalInstance.getAccount() && !msalInstance.isCallback(window.location.hash)) {
    //do something with the logged in user
} else {
    //force the user to sign in
    msalInstance.loginRedirect(loginRequest);
}
```

**Comment by DarylThayil** [comment]
#786  will resolve this, closing as duplicate, expect release by end of December cc @jasonnutter
