### ISSUE TITLE
Cookie length should be less then or equal to 4096 characters

### ISSUE THREAD

**Issue by nmiddendorff** [AzureAD/microsoft-authentication-library-for-js#78]
I am using the userAgentApplication.loginRedirect(config.b2cScopes) function to authenticate the users for my app.  

Occasionally when I login, I receive the following message:
`Set-Cookie header is ignored in response from url: https://login.microsoftonline.com/xxxxxxx.onmicrosoft.com/login. Cookie length should be less then or equal to 4096 characters.`

This prevents msal.js from authenticating the user until the browser is closed or the cookies are cleared.

**Comment by RobARichardson** [comment]
My organization and our clients are regularly seeing this issue (or something similar).  Error message is "Bad Request - Request Too Long.  HTTP Error 400. The size of the request headers is too long."  A number of posts across the web (GitHub and Stack Overflow) all suggest that cookies need to be cleared because too many MSFT websites are causing a "cookie overflow".  While this may be true, asking our customers to clear their cookies isn't a realistic expectation to impose on them long term just because we decided to use AAD B2C for our apps.

**Comment by jmprieur** [comment]
@RobARichardson : thanks for the feedback. Do you think it's a cookie issue? or is it because the query parameters on the URL is too long (which also happens with B2C) ?

For the moment proposing to close this issue as this is not an issue with msal.js, but with the B2C requests (I added [Feedback] to the title, BTW). Have communicated the feedback to the B2C team.

**Comment by CamiloTerevinto** [comment]
@jmprieur  We are developing an app that lives in Azure and uses AAD for authentication. All five of us (developers) see the exact same error message that cookies exceed 4096.

We cannot just clear all cookies all the time, as we don't only work in this project (think about Google account, Microsoft, Stack Overflow, any app that uses cookies really).

Isn't there anything we can do?

**Comment by jmprieur** [comment]
@navyasric can you please check with the MSAL.JS team what @CamiloTerevinto can do?
