### ISSUE TITLE
Can this be used in react-native applications?

### ISSUE THREAD

**Issue by frags51** [AzureAD/microsoft-authentication-library-for-js#825]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[] Feature request
[x ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

**Comment by tatelang** [comment]
Can this be used within React Native based Mobile Applications (Android and iOS) ?

**Comment by jasonnutter** [comment]
It sounds like MSAL.js will not work with React Native [due to the inability to use LocalStorage or SessionStorage](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/827). It is certainly something we can consider moving forward.

In the mean time, we have native client libraries for both [Android](https://github.com/AzureAD/microsoft-authentication-library-for-android) and [Objective C](https://github.com/AzureAD/microsoft-authentication-library-for-objc), I would recommend giving those a try (although I'm not sure if they official support React Native or not).

**Comment by askpatrickw** [comment]
This should be revisited now that App Center Auth has been deprecated for core Auth services (and their libraries).

**Comment by jasonnutter** [comment]
@askpatrickw Have you tried our native mobile MSAL libraries?

**Comment by askpatrickw** [comment]
@jasonnutter Are you asking, have I tried building my authentication screens in Objective-C\Swift for iOS and Java for Android instead of using React Native?  If so, No.

For comparison: You should look at how easy it is to use expo and AWS Amplify.

**Comment by jasonnutter** [comment]
@askpatrickw That's fair, I agree they definitely do a good job. We are going to be looking at React sometime this year (likely focusing first on the browser), and React Native is certainly something we will consider.

@DarylThayil
