### ISSUE TITLE
Scopes not populated in authentication response.

### ISSUE THREAD

**Issue by Ralms** [AzureAD/microsoft-authentication-library-for-js#853]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX
- [x] Opera 62.0.3331.72

## Library version

<pre><code>
Library version: 1.0.2
</code></pre>

## Current behavior
loginPopup() AuthResponse returning an empty array Scopes property.

## Expected behavior
loginPopup() AuthResponse Scopes property to contain all scopes the user has access to, both granted by an Admin or the user. 

## Minimal reproduction of the problem with instructions
Have an App and a user that has granted some scopes.
Login with loginPopup() with the following properties:
{
     scopes: ['user.read'],
     prompt: 'select_account'
}
Check response.

**Comment by pkanher617** [comment]
@Ralms The login call only returns an idToken. Scopes are tied to access tokens, so you will receive the user.read scope when you make an acquireToken call for a graph access token. 

Scopes passed during the login call are pre-consent scopes, which allows the user to consent to these scopes at login time, rather than when acquiring the token. These scopes must all be from the same resource. Any scopes for additional resources must be consented in a separate call. 

Please let me know if this doesn't make sense. We will update our docs to be more clear on this.

**Comment by Ralms** [comment]
@pkanher617 I'm confused, in the issue #854 you say that "The granted scopes are returned in the AuthResponse object that is returned when an acquireToken or login call has been completed." and this is a login call.
Now here you say it's not returned. 

Can you please confirm that this is the actual intended behavior? 
Because I have someone saying that in .NET version of the library it works fine, although I didn't validate it myself.

**Comment by pkanher617** [comment]
@Ralms In the future please combine related issues into a single submission to make it easier to mitigate. I am going to merge #854 into this issue to make it easier to manage.

Javascript works a little differently than other libraries, since we are the only ones with the login API.

I misspoke when I was responding in #854, which I have updated. This is intended behavior. Scopes are tied to tokens, not the specific calls. Login calls do not return access tokens, so you will never have a populated scopes object in the response for login calls.

To answer your question in #854, MSAL does not track scopes for the user. We do return the consented scopes in the response object, so you will need to keep track of these consented scopes as you make requests.

**Comment by Ralms** [comment]
@pkanher617 The reason I've opened 2 issues was because although it's the same topic, it was 2 diferent scenarios. This one was something that I though it could be a bug on login, while the other was a question on getting the scopes but not by getting it from the accessToken. 

It's clear. Thanks.

**Comment by pkanher617** [comment]
@Ralms Gotcha, glad we were able to resolve your issues!
