### ISSUE TITLE
Automate CDN Publish

### ISSUE THREAD

**Issue by DarylThayil** [AzureAD/microsoft-authentication-library-for-js#893]
Publishing msal js versions to the cdn is automated and can be extended for other packages

**Comment by jmckennon** [comment]
Update: This ended up evolving into something totally different. We had to completely rework the way we use and make uploads to our CDN in order to facilitate keeping the same domain that we were on previously. Today, we are able to make manual uploads again with our new method by directly accessing Azure storage with a CDN connected to it. I'll be closing this ticket in reference to that untracked task and be making a new one for the automation of our new method of using the CDN.
