### ISSUE TITLE
No safe solution for partial JS applications

### ISSUE THREAD

**Issue by CodeMonkeyAlpha** [AzureAD/microsoft-authentication-library-for-js#940]
We provide a plugin JS application to our clients and some of them would like Microsoft Account login capabilities to be enabled. We neither control the page (or page state), meaning redirecting is unlikely to return the page in the same condition, and in our corporate clients popups may well be blocked completely by group policy.

So right now we seemingly have no solution? With the direction applications and corporate security are going this would seem to be a massive limitation.

I appreciate this is 'by design' but I could just bypass all this and provide a server side relay solution. So it seems to be security by 'annoyance' only. Likely only to keep out honest vendors who would feel uncomfortable doing this. Illicit actors are unlikely to be deterred.

Can we get a third option of an inline login or at least one that runs in an iframe? The alternative is a bypass, and I'd really rather not.

**Comment by DarylThayil** [comment]
@CodeMonkeyAlpha  thanks for sharing your use case. There are a couple things we are working on here, and a couple security constraints we cant bend on.

Any credential entry in an iframe is strictly banned, because of the threat of clickjacking. 
We are working to relax the constraint on iframe constrained apps from requesting tokens, but are doing so with the requirement that the top frame app is using msal and that it can delegate request on behalf of the child app (this is still in design and implementation may not look the same as I just described). 

In terms of the parent apps state, if popups are blocked, and interaction is required from the user, there is no way to prevent a refresh of the app. 

The end goal is to enable the iframe scenario, while preserving security for the user. 

Does this provide clarity on our position / plans? 

If not please let me know what I can clarify, if so I will close this ticket and you can expect a release in the next 1-2 months with this enhanced iframe functionality.

**Comment by CodeMonkeyAlpha** [comment]
Hi,

Good to hear something is coming. I guess my point was also that the security is pretty ineffective, so it seems a little pointless. I have a reasonable bypass rigged now and I could use it to set up click jacking if I was so inclined (obviously I wouldn't). I don't think this is stopping any illicit behavior, but I guess it does make it a little more work. I've only been at it for 5 hours, and while I still have a couple of niggles, it does seem pretty easy to work around.

How likely is that delivery date? Not going to hold you to anything but I'd like to manage expectations in the business realistically if I can. As much as this bypass with a little polish would work its a bit brittle to changes and so I'd rather not.

Thanks for getting back.

**Comment by DarylThayil** [comment]
@CodeMonkeyAlpha  the release is planned, but I would say that the unexpected can always happen and we should treat it as a date that we can find out if it meets your needs instead of a date that we have a battle hardened solution.  Would you be willing to do a call with us to talk through your use case, workaround, and what a great solution would look like?
@negoe  cc

**Comment by CodeMonkeyAlpha** [comment]
Hmm sure I could do that I guess, I haven't really thought about how I would want it to be. You know how these things go you tend to focus more on what you can make of whats available. You can probably find me on Skype by my user name if you want...

**Comment by DarylThayil** [comment]
Makes sense, I will close this issue for now and @negoe  can you reach out and give @CodeMonkeyAlpha  and contact he can share any feedback he has when he has it?
