### ISSUE TITLE
error trying to login 

### ISSUE THREAD

**Issue by lucamorelli** [AzureAD/microsoft-authentication-library-for-js#962]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X ] Other... Please describe:
</code>unable to use the sample to login using azure ad</pre>

## Browser:
- [ X] Chrome version 76
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.1.2

</code>project just created</pre>

## Current behavior

I took the angular sample from [Sample,]((https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular/samples/MSALAngularDemoApp)) recreated a new project using the angular cli v.8, and copied all the files, updating where needed.
 I changed the tenantId with a my Own (seems to me I had the same problem with sample params), but when I try to login I obtain this error

`login failure {"_error":"The provided value for the input parameter 'scope' is not valid. One or more scopes in 'user.read api://[my id]/basic openid profile' are not compatible with each other.","_errorDesc":"invalid_scope","_scopes":""}`

## Expected behavior

to be able to login

## Minimal reproduction of the problem with instructions

created a new project using angular cli 8
copy all the source files
update use of rxjs and other differencies
changed the tenant params of the client app
run the app
try to login

**Comment by Nasicus** [comment]
Pretty sure this was broken server from Microsoft and not in this library!

Authentication for personal Microsoft account's is not working anymore (using `https://login.microsoftonline.com/common`) if you provide some extra scopes to consent (in our case: ` https://graph.microsoft.com/User.Read` and `https://graph.microsoft.com/User.ReadBasic.All`)!

This used to work until ~ a few days back, cannot say the exact day.
Since this suddenly stopped working on our **production environment** (where we didn't do any deployement recently) I'm pretty sure that no the MSAL javascript library did break, but instead the changed something on the server side (thanks for that).

Our current workaround is, to catch the error, and if it's the error (see below) we do ANOTHER login request, without the extra scopes.

@repo-owners
Would be nice if someone could confirm this or reach out to ones responsible for this to let them know. I have no idea who this might be or how to contact them.

Error for us:

```
The provided value for the input parameter 'scope' is not valid. One or more scopes in 'api://<clientId>/access_as_user openid profile offline_access https://graph.microsoft.com/User.Read https://graph.microsoft.com/User.ReadBasic.All' are not compatible with each other.","msalErrorCode":"invalid_scope"
```

**Comment by DarylThayil** [comment]
I have reached out to our server team for reason why this may have happened

**Comment by pkanher617** [comment]
@hpsin Could you please take a look at this?

**Comment by hpsin** [comment]
You can't make a token request to multiple resources.  This has always been true.  It's possible that the code you updated went from collecting consent + id_token (where this would be a valid scope request) to consent + id_token + token, where this request is invalid.  If you can capture the request (URL it sends you to in the browser), that will help identify the issue.

**Comment by tnorling** [comment]
Closing as this was answered. Please let us know if you are still having issues
