### ISSUE TITLE
msal vs. @azure/msal

### ISSUE THREAD

**Issue by scale-tone** [AzureAD/microsoft-authentication-library-for-js#993]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

The [main page](https://github.com/AzureAD/microsoft-authentication-library-for-js) says:

> npm install msal

While the [main wiki page](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-Installation) says:

> npm install msal
> or
> npm install @azure/msal

What's the difference? How do we choose?

We've just finished a hard work of figuring out the difference between *msal* and *adal*. Are we back to having yet another confusing ambiguity?!

**Comment by jasonnutter** [comment]
@scale-tone Apologies for the confusion. They are the same library, but you should use `msal` for now, as it looks like we are behind on publishing new versions to `@azure/msal`.

**Comment by jasonnutter** [comment]
FYI @pkanher617

**Comment by pkanher617** [comment]
@jasonnutter Thanks for the update, I will publish to @azure/msal for the missing versions.

**Comment by scale-tone** [comment]
Can anyone still explain why we have the same library published twice?

**Comment by jasonnutter** [comment]
I have updated `@azure/msal` to be up to date with `msal`.

@scale-tone `msal` is the original name, and then `@azure/msal` was published to be consistent with `@azure/msal-angular`, which was published under the `@azure` scope to differentiate it from third-party libraries. Going forward we'll make sure this is documented, and we'll look at how we can make this less confusing in the future.

Closing as no further actionable items.

**Comment by PaybackMan** [comment]
To be clear, which one should we be using?

**Comment by jasonnutter** [comment]
@Paybackman They are the same library, but if you need to pick one, choose `msal`. As I said, we're aware this is confusing and will try to make this less confusing in the future.

**Comment by thrixton** [comment]
This is confusing, especially since @azure/msal-angular is org scoped only (there is msal-angular but it's not owned by azuread).
Could you maybe mark msal deprecated and / or put a notice on the readme directing users to @azure/msal?
And make sure to publish @azure/msal first (note, it's currently behind, again :)).

Thanks 👍

**Comment by jasonnutter** [comment]
@thrixton Sorry about that, `@azure/msal` has been updated with 1.2.2 (1.3.0 will be released soon so we'll just do the stable release for that).

Due to the much larger amount of users on `msal` vs `@azure/msal` (107k vs 4k weekly downloads), we are inclined to stay with `msal` as the primary package. We haven't decided yet about `@azure/msal` once `@azure/msal-browser` is GA.

**Comment by thrixton** [comment]
Thanks @jasonnutter , looks like 1.3.0 is released now to msal but not @azure/msal.

**Comment by jasonnutter** [comment]
@thrixton Unfortunately publishing to `@azure/msal` takes a little longer due to permissions, I should have it up shortly, apologies for the delay.

**Comment by jasonnutter** [comment]
@thrixton `@azure/msal@1.3.0` has been published.
