### ISSUE TITLE
Msal.js has telemetry dashboards to show  usage and reliability

### ISSUE THREAD

**Issue by DarylThayil** [AzureAD/microsoft-authentication-library-for-js#998]
@sameerag  to fill out requirements and goals for this work item

**Comment by PraveenVerma17** [comment]
We are looking for this feature... currently we are managing the telemetry using appinsights js and user login event we are managing using custom event. As they are not that reliable when user logged in correctly because in case of refresh we again log the same event actually in this case we pull the user from cache. We are using login redirect which makes telemetry little incorrect.

**Comment by sameerag** [comment]
@PraveenVerma17 I will be adding more details to this space as we have more clarity on what will be delivered as a part of this activity. Please watch out for the updates.

**Comment by jasonnutter** [comment]
There is an internal ticket for this, closing.
